### ISSUE TITLE
trying to upgrade from 2.7, test failures during post process trying to access the tempfile

### ISSUE THREAD

**Issue by xxx** [thoughtbot/paperclip#1002]
Hello,

I'm attempting to upgrade from 2.7.8 to 3.1.4, but am running into issues in the test environment, because `copy_to_tempfile` is trying to copy the file from a path where it doesn't exist after I assign the file in my test suite.

How to replicate:

1. Create instance

1. `file = File.new('path/to/fixture.jpg')`

1. `instance.avatar = file`

1.  `post_process` is called from [`Paperclip::Attachment#assign`](https://github.com/thoughtbot/paperclip/blob/master/lib/paperclip/attachment.rb#L107)

1. One of our post-processors needs access to the file, but [`Paperclip::AttachmentAdapter#copy_to_tempfile`](https://github.com/thoughtbot/paperclip/blob/master/lib/paperclip/io_adapters/attachment_adapter.rb#L27) looks for the file at the path set via `:path` in the `has_attached_file` call, rather than using the real path of the file I'm actually assigning.

We used `to_file` in the past, but now, moving to `Paperclip.io_adapters`, we see this problem. How do I fix it?

**Comment by maclover7** [comment]
Hi @xxx ! Is this still an issue for you in Paperclip; I know this issue is from approximately 3 years ago. If it is still an issue, can you please provide the code that's causing you the error? Thanks!

**Comment by xxx** [comment]
Oh, no. We've been on 4.x for ages now. I'll close this out.
