### ISSUE TITLE
after_post_process not working as expected

### ISSUE THREAD

**Issue by justinperkins** [thoughtbot/paperclip#1004]
Using Paperclip 3.1.4 with Rails 3.2

I have a simple upload field set up for plain text file uploads. I want to be able to process the text files after paperclip is done, so I'm using after_post_process with a callback. The uploaded file is non-existant when this method is invoked, despite the docs saying "...  you can access the model and the attachment if necessary". I can access the model and all the uploaded file metadata just fine, but the file itself is missing.

``` ruby
class SomeModel < ActiveRecord::Base
  has_attached_file :upload
  after_post_process :process_uploaded_file
  private
  def process_uploaded_file
    # this always evaluates to false, but if I go into the console and load up the newly created record, the file does exist
    puts '================'
    puts File.exists?(self.upload.path)
    puts '================'
  end
end
```

``` bash
> SomeModel.create :upload => File.open('/path/to/file.txt')
===================
false
===================
> u=_
> File.exists? u.upload.path
 => true 
```

**Comment by dwn** [comment]
Can confirm what segfault88 said - made my afternoon!
