### ISSUE TITLE
Same as issue 266

### ISSUE THREAD

**Issue by beekus** [thoughtbot/paperclip#1029]
I am using 3.1.4 and experiencing the same problem listed in issue #266. I'm currently using the workaround described at the bottom of the issue.

**Comment by maclover7** [comment]
Hi @beek and @uberllama ! Is this still an issue for you in Paperclip; I know this issue is from approximately 3 years ago. If it is still an issue, can you please provide the code that's causing you the error? Thanks!

**Comment by uberllama** [comment]
I don't even remember what I had for breakfast today. :)

**Comment by tute** [comment]
If we can't replicate the error, I hope things are working well now for you. I’ll close the issue, happy to continue further discussion if we can find the problem (and potential fix) for it. Thanks for your input!
