### ISSUE TITLE
New Cocaine API Breaks Old Paperclip Gems

### ISSUE THREAD

**Issue by boone** [thoughtbot/paperclip#1038]
The old paperclip.gemspec allowed any version of the Cocaine gem >= 0.0.2. So currently installs of the Paperclip gem will include Cocaine 0.4.0, which did not work for me. I was using an old version in development (2.4.5), but updating to the latest (3.2.0) didn't help.

https://github.com/thoughtbot/paperclip/commit/d15d8d81eecf7b2235214e46dfce5d66ac5e2772

I was getting this error:

```
Command :: identify -format %wx%h :file
[paperclip] An error was received while processing: #<Paperclip::NotIdentifiedByImageMagickError: {path to my image} is not recognized by the 'identify' command.>
```

I solved this by removing Cocaine 0.4.0 and adding this to my Gemfile:

```
gem 'cocaine', '0.3.2'
```

**Comment by johnantoni** [comment]
thanks for posting this.

lifesaver

**Comment by cs102** [comment]
thanks, adding 

> gem 'cocaine', '0.3.2'

 to my gem file fixed the problem :+1:
