### ISSUE TITLE
#reprocess! original images lost

### ISSUE THREAD

**Issue by ScotterC** [thoughtbot/paperclip#1055]
I don't have a specific error narrowed down yet but I thought I should start the discussion.

In the midst of reprocessing several thousand images, I lost about 300-400 of them.  I was using a resque job to iterate through my ActiveRecord objects and spinning off delayed_paperclip jobs to reprocess each one.  

The odd part about this is that when they are 'lost', they still exist as a file in the original style but it's just a 0kb size file without any other styles processed.  I was under the impression that reprocess wouldn't touch the original file.  

Other pertinent information is that this is with the latest version of paperclip (3.3.0) and the images are being stored on S3

**Comment by maclover7** [comment]
@jferris @jyurek Please close issue, problem appears to be solved.

**Comment by zreitano** [comment]
I am currently having this issue where reprocess! deletes the original file (leaving a 0kb file remaining).

**Comment by alexandrz** [comment]
We are having this issue too. Is it possible to reprocess single style only, and don't touch original version at all?

**Comment by md-farhan-memon** [comment]
Hi!
We are on Rails 3.2.22, Ruby 2.2.4 and use paperclip v4.3.7. This includes the fix given in #1354 but still the images on s3 while reprocessing a single style, deletes that image.

`
has_attached_file :photo, :styles => { 
    :thumb => "50x50#", 
    :small => "225x257#",
    :small_m => "225^",
    :small_mo => "151x173#",
    :large => "350x400>", 
    :large_m => "350x400>", 
    :zoom => "800x1100"},

    :convert_options => {
      :thumb => "+profile -strip -quality 70 -interlace Plane -units PixelsPerInch -density 1x1",
      :small => "+profile -strip -quality 70 -interlace Plane -units PixelsPerInch -density 1x1 -background white -flatten +matte -gravity center",
      :small_m => "+profile -strip -quality 30 -interlace Plane -units PixelsPerInch -density 1x1 -background white -flatten +matte -gravity center",
      :small_mo => "+profile -strip -quality 70 -interlace Plane -units PixelsPerInch -density 1x1 -background white -flatten +matte -gravity center",
      :large => "+profile -strip -interlace Plane -units PixelsPerInch -density 1x1",
      :large_m => "+profile -strip -quality 70 -interlace Plane -units PixelsPerInch -density 1x1 -background white -flatten +matte -gravity center",
      :zoom => "+profile -strip -quality 70 -interlace Plane -units PixelsPerInch -density 1x1",
    }
`

And I am running this through console: 
`Image.find(SOME_ID).photo.reprocess!(:small_m)`

Please provide a solution or fix to this.
