### ISSUE TITLE
missing required :bucket option

### ISSUE THREAD

**Issue by rebyn** [thoughtbot/paperclip#1073]
Paperclip runs fine on my production server, but my development machine. This is causing me difficulty in testing new features. When I tried adding the gem to my Rails app, this message often comes up:

```
missing required :bucket option
```

**development.rb**

```
config.paperclip_defaults = {
    :storage => :s3,
    :s3_credentials => {
      :bucket => ENV['AWS_BUCKET'],
      :access_key_id => ENV['AWS_ACCESS_KEY_ID'],
      :secret_access_key => ENV['AWS_SECRET_ACCESS_KEY']
    }
  }

  Paperclip.options[:command_path] = "/usr/local/bin/"
```

This error appears every time I use Paperclip methods, like this one:

```
<%= model_name.avatar.url(:square) %>
```

**Comment by rishabhtayal** [comment]
Any solution yet?

**Comment by maclover7** [comment]
Try setting env variable through something like dotenv or Figaro, that should solve the problem.

**Comment by zmachuca** [comment]
Try 
:bucket => ENV['S3_BUCKET_NAME']

**Comment by jyurek** [comment]
The option is `bucket` on the main level. It's not part of `s3_credentials`. It can be set via environment variable, or it can be a block.

**Comment by pedroviana** [comment]
I realize that my .env vars was not been loaded when config.paperclip_defaults was set, put a raise of your keys before the set and probably you will see its empty, I've moved to this solution:
http://tammersaleh.com/posts/managing-heroku-environment-variables-for-local-development/
