### ISSUE TITLE
Zero-byte files uploaded to S3

### ISSUE THREAD

**Issue by jasonfb** [thoughtbot/paperclip#1096]
I'm using paperclip 3.3.1, aws-sdk 1.5.8, and Ruby 1.9.3-p194 on a Rails 3.1.8 project

When I upload a file, the file goes up to Amazon S3 in the right place, but it has no contents (zero-bytes) I can tell this because when I download it , it is empty. Also the file size is 0 bytes. 

In the log, I see this:

[paperclip] saving inventory_csv_files/42/HOLfirst.csv
[AWS S3 200 0.579688 0 retries] put_object(:acl=>"public-read",:bucket_name=>"candidev",:cache_control=>"max-age=315576000",:content_type=>"text/csv",:data=>Paperclip::UploadedFileAdapter: HOLfirst.csv,:expires=>"Tue, 29 Nov 2022 17:37:46 GMT",:key=>"inventory_csv_files/42/HOLfirst.csv")  
[paperclip] Saving attachments.

I checked the contents of the tempfile (which in my case happened to be /tmp/RackMultipart20121129-3054-1mfna4c) and they look like the file I put into the interface.

my has_attached_file is defined like so:

  has_attached_file(:attachment,
                    :path => "inventory_csv_files/:id/:basename.:extension",
                    :storage => :s3,
                    :s3_credentials => "#{Rails.root.to_s}/config/s3.yml",
                    :s3_headers => { 'Cache-Control' => 'max-age=315576000', 'Expires' => 10.years.from_now.httpdate })

Not sure where to begin debugging this, anyone seen this kind of a thing before?

**Comment by jameswilliamiii** [comment]
@jasonfb thanks for posting your solution. I just ran into a very similar issue, and was pulling my hair out trying to figure out what was going on. Rewind did the trick!

**Comment by jhogan4288** [comment]
I just ran across this same problem -- thanks again for posting this!
