### ISSUE TITLE
processing styles leaves tempfiles on filesystem

### ISSUE THREAD

**Issue by pmckinnon** [thoughtbot/paperclip#1108]
I think that processing attachments with styles (:thumbnail for example) leaves unused tempfiles on the filessystem. Whenever I run reprocess! on an attachment I end up with tempfiles laying around on the filesystem corresponding to each of the styles.

I believe the offending code is here: https://github.com/thoughtbot/paperclip/blob/master/lib/paperclip/attachment.rb#L431

I think the problem is that a new tempfile is created with Processor.make but never closed/unlinked so they stick around until the objects are garbage collected.

I've run into problems where I fill the entire filesystem with tempfiles on a large batch job that reprocesses all of my attachments. 

This code fixes the issue for a single processor per style, but I suspect it is still broken for chained processors:

```ruby
processed = style.processors.inject(@queued_for_write[:original]) do |file, processor|
  Paperclip.processor(processor).make(file, style.processor_options, self)
end
@queued_for_write[name] = Paperclip.io_adapters.for(processed)
processed.close! if processed.respond_to? :close!
```

**Comment by maclover7** [comment]
Hi @pmckinnon and @magec ! Is this still an issue for you in Paperclip; I know this issue is from approximately 3 years ago. If it is still an issue, can you please provide the code that's causing you the error? Thanks!

**Comment by tute** [comment]
Ping @pmckinnon. How can we replicate your issue?

**Comment by tute** [comment]
If @magec can't point us into solving this, we'll need to close it, as we don't have enough information yet.

**Comment by bheeshmar** [comment]
We have to run a cron job to clean out the temp files on our production box.

**Comment by tute** [comment]
Closing in favor of duplicate https://github.com/thoughtbot/paperclip/issues/1326.
