### ISSUE TITLE
Using Fog + S3 without specifying fog_public: true breaks

### ISSUE THREAD

**Issue by joshuaclayton** [thoughtbot/paperclip#1109]
Within `config/initializers/paperclip.rb`:

```ruby
if Rails.env.production?
  Paperclip::Attachment.default_options.update(
    path: ':class/:id/:attachment/:style/:filename',
    storage: :fog,
    fog_credentials: {
      provider: 'AWS',
      aws_access_key_id: ENV['S3_ACCESS_KEY'],
      aws_secret_access_key: ENV['S3_SECRET_KEY']
    },
    fog_directory: 'bucket-name'
  )
end
```

Not specifying `fog_public: true` breaks (Amazon returns a 400 Bad Request); adding that config fixes image uploading. The documentation outlines that it defaults to true (https://github.com/thoughtbot/paperclip/blob/master/lib/paperclip/storage/fog.rb#L29-L30), which is (as of 3.3.1) not the case.

**Comment by maclover7** [comment]
Hi @joshuaclayton ! Is this still an issue for you in Paperclip; I know this issue is from approximately 3 years ago. If it is still an issue, can you please provide the code that's causing you the error? Thanks!

**Comment by joshuaclayton** [comment]
@maclover7 thanks for reaching out - I'll close this for now and reopen if I run into it again. Thanks!
