### ISSUE TITLE
Inconsistencies and improvements to expiring_url

### ISSUE THREAD

**Issue by nathany** [thoughtbot/paperclip#1112]
We recently switched from the aws-s3 backend to fog, removing a gem dependency from our app. I ran into some issues:

### Different definition of time:

* `expiring_url` for s3 takes the number of seconds from now
* for fog `expiring_url` takes a Time, which defaults to `(Time.now + 3600)`

These should be consistent. Since people may be relying on the Fog behavior or the S3 behavior, I think we'll need to introduce a new method altogether and deprecate `expiring_url`.

### HTTPS

* We were using the `s3_protocol` setting for private urls. I don't see an equivalent option with fog.
* An expiring url should most likely default to https, as it is intended to be private. (maybe not https with a custom `fog_host` if that doesn't support it?)
* While looking for a solution, I saw inconsistencies in the documentation on whether or not `fog_host` should  include the protocol. It ended up generating urls starting with `http://https://`. I noticed that the regular expressions for some tests aren't anchored to the beginning of the url string.

### Style first

* In the projects I've worked on, the 1-hour default expiry is usually fine, as what we're really after is a private url.
* It's more common that we want to change the style. In fact, we have helpers to wrap expiring_url. So I would suggest swapping the argument order.

Perhaps something like this, to complement `public_url`:

```ruby
private_url(style = default_style, expires_in_seconds = 3600)
```

or perhaps:

```ruby
private_url(style = default_style, time = Time.current + 3600)
```

As people can always use ActiveSupport, eg. `2.hours.from_now`.

I would be happy to help contribute code/tests to improve this. Just wanted to get your opinions on the issue and API before diving in. Thanks!

**Comment by maclover7** [comment]
Hi @nathany ! Is this still an issue for you in Paperclip; I know this issue is from approximately 3 years ago. If it is still an issue, can you please provide the code that's causing you the error? Thanks!

**Comment by nathany** [comment]
I'm no longer using Paperclip on any projects, so I guess it's not an issue.

**Comment by maclover7** [comment]
@jferris @jyurek Please close issue, problem appears to be solved.
