### ISSUE TITLE
"can't dump file"  issue never been resolved [Rails 3.2.9, Paperclip 3.3.1]

### ISSUE THREAD

**Issue by ghost** [thoughtbot/paperclip#1114]
a lot of posts with this issue .. but no clear solution , only one hack I am using for months
upon non valid save ( create/update) I get this message .. I tried many of the 'solutions' given
( see http://stackoverflow.com/questions/7087969/paperclip-validations-causing-error-in-rails-3 ) but

only hack I know working well is to clear the tempfile  whenever existing ( this doesn't happen in test mode)

params[:mymodel][:picture].tempfile = nil unless Rails.env == "test" || params[:mymodel][:picture].tempfile.nil? 

I thought it was an issue with the session store ( cookies) and moved to ActiveRecord session store , same issue...  so I only stick to this hack but it's very difficult to understand why this happen ...

**Comment by ctpelnar1988** [comment]
If you are using Active Record Session Store:

"The serializer may be one of marshal, json, or hybrid. marshal is the default and uses the built-in Marshal methods coupled with Base64 encoding. json does what it says on the tin, using the parse() and generate() methods of the JSON module. hybrid will read either type but write as JSON."

Adding: `ActiveRecord::SessionStore::Session.serializer = :json` to config/application.rb solved the issue for me.
