### ISSUE TITLE
s3 writes fail if attachment :styles is a Proc

### ISSUE THREAD

**Issue by BradRubenstein** [thoughtbot/paperclip#1136]
lib/paperclip/attachment.rb is coded to allow :styles option to be a Proc, called with self as an argument.

lib/paperclip/storage/s3.rb assumes it is a hash, and doesn't call the Proc with self as an argument.  (where it is trying to get style_specific_options in #flush_writes )

Thus, this code fails when trying to evaluate attachment.instance:

    has_attached_file :attachment, 
        :styles => Proc.new { |attachment| attachment.instance.styles }

    def styles
       ...
    end

workaround (assumes I'm not ever using s3_options, s3_metadata etc with styles):
  
    :styles => Proc.new { |attachment| attachment.instance.styles rescue {} }

**Comment by maclover7** [comment]
Hi @BradRubenstein ! Is this still an issue for you in Paperclip; I know this issue is from approximately 2 years ago. If it is still an issue, can you please provide the code that's causing you the error? Thanks!

**Comment by BradRubenstein** [comment]
I'm no longer using it.  Regards, - Brad

**Comment by maclover7** [comment]
@jferris @jyurek Please close issue, problem appears to be solved.
