### ISSUE TITLE
Paperclip whines in log about 'Duplicate path'

### ISSUE THREAD

**Issue by johnnyshields** [thoughtbot/paperclip#1143]
Paperclip whines unnecessarily the following based on default 'url' and 'path' settings in the log output.

```
[paperclip] Duplicate path for image with :rails_root/public:url. This will clash with attachment defined in MyModel class
```

I think the problem is that helpers.rb `check_for_path_clash` method doesn't evaluate the `:url` interpolation, which by default will yield different paths for different models. Not critical, but would be nice to remove this error if possible.

**Comment by maclover7** [comment]
@jferris @jyurek Please close issue, problem appears to be solved.

**Comment by johnnyshields** [comment]
I'm closing this, I believe it's resolved.
