### ISSUE TITLE
Cannot specify s3_options in s3.yml config file

### ISSUE THREAD

**Issue by yemartin** [thoughtbot/paperclip#1146]
Hi,

While configuring Paperclip to work with a Eucalyptus/Walrus installation, i tried the following in my s3.yml config:

    production:
      access_key_id: XXXXXXXXXXXXXXXXXXXXX
      secret_access_key: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      bucket: "my-private-bucket"
      s3_host_name: walrus.example.com
      s3_options:
        use_ssl: false
        s3_port: 8773

Everything worked fine (*), except for the `s3_options` being ignored by Paperclip.
Specifying `s3_options` in the `has_attached_file` options works, but, yuck...

Can we fix Paperclip to allow the `s3_options` to be read from the `s3_credentials` ?

(*): not entirely fine, I had to patch one method in aws-sdk to allow for a path prefix.

Thank you,
Yves-Eric

**Comment by maclover7** [comment]
Hi @yemartin ! Is this still an issue for you in Paperclip; I know this issue is from approximately 2 years ago. If it is still an issue, can you please provide the code that's causing you the error? Thanks!

**Comment by tute** [comment]
ping @yemartin. Is this still an issue?

**Comment by yemartin** [comment]
Hi,

It is not an issue for me anymore in the sense that the project involved has been shipped using the workaround, and we are not involved with it anymore. I still think it would be nice to see `s3_options` handled properly from the yaml config, but I do not have access to a Walrus instance currently and would not be able to test it.

**Comment by tute** [comment]
Will close for now as we can't reproduce it, if we find it is an issue I'll reopen. Thanks for your input!
