### ISSUE TITLE
rake paperclip:refresh:missing_styles i.c.w. hash interpolation "hides" already existing (and processed) styles

### ISSUE THREAD

**Issue by niels** [thoughtbot/paperclip#1153]
While #966 is marked as closed, the described, or a similar, issue still exists:

When refreshing missing styles, updated_at is set to the current time (the rake task ultimately calls out to Paperclip#reprocess! which in turn calls #assign which does `instance_write(:updated_at, Time.now)`) and the new styles are processed and saved. Existing styles are not touched.

The hash path interpolation by default uses updated_at as part of the string to hash. Updating that timestamp thus changes the calculation of all hashes, including those for existing styles. Since they don't get touched (i.e. renamed) alongside the updated_at change however, they are now effectively unreachable. Only the paths to the new styles are correctly calculated.

A workaround is to manually remove :updated_at from :hash_data. To make this safe out of the box however, either the default configuration should be changed to ship w/o the timestamp included, the reprocessing should be changed to either keep the original timestamp or rename existing files as necessary, or style-specific timestamps (or simple integer versioning!) should be introduced, or all hashes or full paths to the files should be stored in the database. (Btw, the latter would also make it easier to clean up physical files whose originating objects no longer exist.)

**Comment by maclover7** [comment]
Hi @Nielsomat ! Is this still an issue for you in Paperclip; I know this issue is from approximately 2 years ago. If it is still an issue, can you please provide the code that's causing you the error? Thanks!

**Comment by JoshSmith** [comment]
@maclover7 I'm not sure what code you want provided? Just running a rake task to refresh the missing styles is all you'll need. I suffered maybe 5 hours of perceived downtime from this issue back in December. I'd tried to just refresh the missing styles but ended up with broken references to all of my existing styles, exactly as @Nielsomat said.

**Comment by maclover7** [comment]
@JoshSmith So the issue here is that when you are running the rake task it is breaking all the existing styles you are trying not to refresh? Would you be willing to send in a PR to try and solve the problem?

**Comment by Nielsomat** [comment]
@maclover7, I don't actively use paperclip at the moment and thus can't confirm whether the issue is still present or not. However @JoshSmith description of the symptoms is spot-on – so if you can reproduce that with the current version, it hasn't been fixed :)

**Comment by dmitry** [comment]
Still not fixed. https://github.com/thoughtbot/paperclip/issues/913 and https://github.com/thoughtbot/paperclip/pull/914 related to this issue. Also related gem is also affected by this issue: https://github.com/jstorimer/delayed_paperclip/issues/35 I've seen more issues like that, but I haven't saved them. Issue is here: https://github.com/thoughtbot/paperclip/blob/v4.2.1/lib/paperclip/attachment.rb#L451

**Comment by tute** [comment]
> the default configuration should be changed to ship w/o the timestamp included

I think this is a good solution. Would you send a PR doing this? Thanks!

**Comment by toao** [comment]
Seems that this issue is till present, even in the latest version:
https://github.com/thoughtbot/paperclip/blob/v5.0.0/lib/paperclip/attachment.rb#L20
https://github.com/thoughtbot/paperclip/blob/v5.0.0/lib/paperclip/attachment.rb#L452

Are there any updates, is somebody taking care?

Changing the default config is one thing, but for already exiting apps/images this is a huge problem.

**Comment by mike-burns** [comment]
Thank you for reporting this. Unfortunately, we will be deprecating Paperclip and therefore will not have the bandwidth to address this issue.
