### ISSUE TITLE
Filename special character issues on windows

### ISSUE THREAD

**Issue by djcp** [thoughtbot/paperclip#1162]
From @brstp 

See: https://gist.github.com/brstp/4951517

Apparently there are still problems with special characters in filenames on windows.

**Comment by maclover7** [comment]
Hi everybody! Is this still an issue for you in Paperclip; I know this issue is from approximately 2 years ago. If it is still an issue, can you please provide the code that's causing you the error? Thanks!

**Comment by tute** [comment]
This seems to be fixed for newer versions of cocaine and paperclip. Thank you all!
