### ISSUE TITLE
Content_length returns 0 when uploading to S3 with aws-sdk > 1.5.0.

### ISSUE THREAD

**Issue by lmckenzie** [thoughtbot/paperclip#1184]
I am not super familiar with contributing to projects but to the best of my knowledge the latest version of paperclip when used with aws-sdk > v1.5.0 throws an error related to the content_length returning as zero. I rolled back to paperclip 3.0.4 and it works well with the latest version on aws-sdk. I am using ruby 1.9.3p0 and rails 3.2.11. Let me know how I can help.

**Comment by maclover7** [comment]
Hi @lmckenzie ! Is this still an issue for you in Paperclip; I know this issue is from approximately 2 years ago. If it is still an issue, can you please provide the code that's causing you the error? Thanks!

**Comment by lmckenzie** [comment]
@maclover7 I am not sure, I have not had a reason to update and I have not spent much time on the project.

**Comment by maclover7** [comment]
@lmckenzie Is it okay if the issue is closed then?

**Comment by lmckenzie** [comment]
You can close it if you'd like.

**Comment by tute** [comment]
Thank you all!
