### ISSUE TITLE
Paperclip validates the model before an actual validation (save/update/create) is called

### ISSUE THREAD

**Issue by michiels** [thoughtbot/paperclip#1186]
I have a piece of code that basically does this:

``` ruby
def create
  @contribution = @phase.contributions.new(params[:contribution])
  @contribution.save
end
```

In the form that creates this model users can upload a photo using params[:contribution][:photo].

I also have another validation that depends on the @contribution.phase relation to be existent on validation.

However, apparently the `Contribution.new(params[:contribution])` call causes Paperclip to validate the model in https://github.com/thoughtbot/paperclip/blob/master/lib/paperclip/attachment.rb#L108

This means that all other validations will be run as well and this fails because the @contribution.phase relation is not set by Rails yet. Causing me to do a workaround of:

``` ruby
@contribution = @phase.contribution.new
@contribution.attributes = params[:contribution]
@contribution.save
```

This doesn't seem right at all. Shouldn't Paperclip only validate when actually creating or saving the model with `@contribution.save`? Validating the model on `.new` makes no sense.

Am I missing some behavior here?

Thanks!

**Comment by fregas** [comment]
I seem to be experiencing this issue in paperclip 4.3.4.  I set the check_validity_before_processing: false like so:

```

  has_attached_file :primary_creative,
    :path => "#{SifiConfig['system_assets_path']}/uploaded_assets/:campaign_id/:id/:hashed_primary_filename",
    :url  => "#{SifiConfig['system_assets_url']}/uploaded_assets/:campaign_id/:id/:hashed_primary_filename", check_validity_before_processing: false
```

But its still firing all model validation.

**Comment by fregas** [comment]
This seemed to fix the issue for me, but I'm not familiar with paperclip source code to be sure this will take care of it.  

```
   def post_process(*style_args) #:nodoc:
      return if @queued_for_write[:original].nil?

     # added this line:
      return unless @options[:check_validity_before_processing]

      instance.run_paperclip_callbacks(:post_process) do
        instance.run_paperclip_callbacks(:"#{name}_post_process") do
          unless @options[:check_validity_before_processing] && instance.errors.any?
            post_process_styles(*style_args)
          end
        end
      end
    end
```

**Comment by fregas** [comment]
Pulled that out as I didn't want to fork Paperclip.  Instead, I overrode assign_attributes in my model, so that I could sort the hash so that certain fields that were required got set before the attachment fields did.  Its a bit of a hack though.  Ideally, Paperclip would not fire validation without being told to.  

```
  # paperclip calls validation on model.new before load_strategy gets a chance

  def assign_attributes(new_attributes, options = {})
    if new_attributes.has_key? :ad_file_type_id
      ordered = {ad_file_type_id: new_attributes[:ad_file_type_id] }
      new_attributes.each do |key, value|
        ordered[key] = value unless key == :ad_file_type_id
      end

      return super ordered, options
    end
    super new_attributes, options
  end

```
