### ISSUE TITLE
Shoulda matcher for validate_attachment_presence failing

### ISSUE THREAD

**Issue by christoomey** [thoughtbot/paperclip#1194]
I have the following class and spec in a rails app. The specs pass if I just use `has_attached_file :document`, but the validation spec fails if I provide the `:styles` arg as shown below.

``` ruby
# app/models/attachment.rb
class Attachment < ActiveRecord::Base
  attr_accessible :document
  # passing in the styles option causes validation spec to fail
  has_attached_file :document, styles: { :thumb => ["32x32#", :png] } 
  validates :document, :attachment_presence => true
end

---
# spec/models/attachment.rb
require 'spec_helper'

describe Attachment do
  it { should have_attached_file(:document) }
  it { should validate_attachment_presence(:document) }
end
```

**Comment by maclover7** [comment]
Hi everybody! Is this still an issue for you in Paperclip; I know this issue is from approximately 2 years ago. If it is still an issue, can you please provide the code that's causing you the error? Thanks!

**Comment by tute** [comment]
@christoomey @jyurek is this still an issue with Paperclip?

**Comment by jyurek** [comment]
I think, given that this hasn't been mentioned in two years in a serious manner, that it's probably not an issue anymore.
