### ISSUE TITLE
 Paperclip::Errors::NotIdentifiedByImageMagickError

### ISSUE THREAD

**Issue by justmyhead** [thoughtbot/paperclip#1205]
I just did a 'bundle update'. Now I'm seeing this error. I have read that some have luck using an older version of cocaine. Thanks in advance...

**Comment by Jatapiaro** [comment]
Hi to everyone, I just solved this issue.
brew makes a directory call Cellar, /usr/local/Cellar
Verify if you don`t have two ImageMagick, i had one named ImageMagick-Ruby182, so, if you have it run brew uninstall ImageMagick-Ruby182, and also the normal imagemagick, and reinstall image magic.
