### ISSUE TITLE
invalid file path

### ISSUE THREAD

**Issue by illnino** [thoughtbot/paperclip#1210]
Hi, there

I am customizing spree, which uses paperclip for uploading images. 

It did successfully upload images to a third party storage, but not s3. However, the path isnt valid. It will always comes with localhost:3000/assests/ as prefix.

I have create a spree.rb in config/initializers/spree.rb

<pre lang="ruby"><code>

Spree.config do |config|
  config.attachment_url = ":my_url"
end

Paperclip.interpolates(:my_url) do |attachment, style|
  "http://path/to/third/party/storage/test/:attachment/:id/:style/:filename"
end
</code>
</pre>

I have aslo specified path and url in model/image_decorator.rb
<pre lang="ruby"><code>
      :path => "test/:attachment/:id/:style/:filename",
      :url => "test/:attachment/:id/:style/:filename",
</code>
</pre>

Is there anyone could give me some help?

**Comment by maclover7** [comment]
Hi @illnino ! Is this still an issue for you in Paperclip; I know this issue is from approximately 2 years ago. If it is still an issue, can you please provide the code that's causing you the error? Thanks!

**Comment by illnino** [comment]
hi Jon




it has been a long time. I am not using paperclip now. cant let you know.




nino



—

**Comment by maclover7** [comment]
@jferris @jyurek Please close issue, problem appears to be solved.
