### ISSUE TITLE
Question: file_name in DB column does not change with hash

### ISSUE THREAD

**Issue by wakproductions** [thoughtbot/paperclip#1221]
I'm using the hash feature to encrypt the names of files I am storing. However, I noticed that the file_name field in the database retains the original name of the uploaded file, not the hashed filename.  Why is this?

I am also thinking about removing the :updated_at property from the :hash_data.  Given that the hashed filename is not stored anywhere, I am concerned about one of the DB fields getting corrupted, which would cause me to lose track of where each file belongs.  The updated_at I think is particularly vulnerable because I'm worried about that changing if I add a new style or whatnot.  Is there a disadvantage to removing :updated_at?

**Comment by maclover7** [comment]
Hi @wakproductions and @juankuquintana ! Is this still an issue for you in Paperclip; I know this issue is from approximately 2 years ago. If it is still an issue, can you please provide the code that's causing you the error? Thanks!

**Comment by juankuquintana** [comment]
Not currently, i did a workaround.

**Comment by maclover7** [comment]
@jferris @jyurek Please close issue, problem appears to be solved.
