### ISSUE TITLE
Issue with s3_headers

### ISSUE THREAD

**Issue by premanandh** [thoughtbot/paperclip#1230]
Hi,
 I am trying to set the name of the file using content disposition dynamically. I am using the command,
{:s3_headers => lambda { |attachment| { "Content-Disposition" => "attachment; filename=\"#{attachment.invention_document_file_name}\"" } }}.merge( PAPERCLIP_OPTIONS)

I am getting cannot convert Proc into Hash Error.

When i checked the s3.rb in paperclip folder. I found that the code assumes that s3_headers is a Hash. Can anyone please tell me how to set the name dynamically in this case ?

Thanks in advance.

**Comment by maclover7** [comment]
@jferris @jyurek Please close issue, problem appears to be solved.
