### ISSUE TITLE
Could not run the `identify` command

### ISSUE THREAD

**Issue by jordanmichaelrushing** [thoughtbot/paperclip#1273]
I'm getting this error running on Heroku whether its for uploading a picture, video, anything.. It was working fine before but not all of a sudden is giving me this error:

`2013-07-04T21:48:53.647151+00:00 app[web.1]: [paperclip] An error was received while processing:` `<Paperclip::Errors::CommandNotFoundError: Could not run the 'identify' command. Please install ImageMagick.>`

What kind of info do you need from me to help diagnose?

**Comment by GoodWorkLabs** [comment]
Yeah, this helped ^
