### ISSUE TITLE
Paperclip::Errors::NotIdentifiedByImageMagickError

### ISSUE THREAD

**Issue by pratz3** [thoughtbot/paperclip#1289]
I have read all similar threads and nothing has solved my problem. In development everything seems to be working just fine. I am able to upload and crop images, but on Heroku, it's not working. I have Paperclip 3.4.2 and I tried Cocaine 0.5.0 and 0.5.1, but it simply doesn't work. I don't have any Paperclip :command_path set in my production environment. In development, I have: 

Paperclip.options[:command_path] = "/usr/local/bin/"

**Comment by ztsuperman** [comment]
Thanks bro!

**Comment by melsatar** [comment]
Hi,

It was working fine in heroku and S3 and suddenly something wrong happened without any change in the code, I got this error

ActionView::Template::Error (Paperclip::Errors::NotIdentifiedByImageMagickError):

It is working find in development Any help?

**Comment by tute** [comment]
> It was working fine in heroku and S3 and suddenly something wrong happened without any change in the code, I got this error

Could it be related with https://devcenter.heroku.com/changelog-items/891?

**Comment by melsatar** [comment]
I think yes, I tested it in my development env with S3 credentials and it works fine, what is the solution for this?

**Comment by melsatar** [comment]
Okay, I solved this issue, but i do not know what is wrong in https connection, i just changed from https to http and it is working fine, but it is producing warning for all images for mixed content using https and http

config.paperclip_defaults = {
  :storage => :s3,
  :s3_protocol => 'http',
  :s3_host_name => 's3-eu-west-1.amazonaws.com',
  :s3_credentials => {
    :bucket => ENV['S3_BUCKET_NAME'],
    :access_key_id => ENV['AWS_ACCESS_KEY_ID'],
    :secret_access_key => ENV['AWS_SECRET_ACCESS_KEY']
  }
}

if anyone has better solution please post, or how i can get only crop images over http and rest images over https

**Comment by melsatar** [comment]
I made this final change, it could help someone

`	def image_geometry(style = :original)
	@geometry ||= {}
	image_path = (image.options[:storage] == :s3) ? image.url(style) : image.path(style)
	@geometry[style] ||= Paperclip::Geometry.from_file(image_path.gsub("https","http"))
	end  `

**Comment by simonfranzen** [comment]
@melsatar But just turning off HTTPS for the cropper cant be the finally solution, can it?? No security risks here ??

**Comment by bilalbash** [comment]
thanks @pratz3  i deployed my app the amazon EC2 and now it is working fine due to ure fix!

**Comment by bilalbash** [comment]
@simonfranzen sorry i couldn't understand why it is a security risk because u are just changing image url not the url of the website or web application!
