### ISSUE TITLE
Errno::EPERM (Operation not permitted - /var/www/vastra/public/system/vastromen/avatars/....

### ISSUE THREAD

**Issue by mladjan** [thoughtbot/paperclip#1295]
I'm getting on create following error in error log:
Errno::EPERM (Operation not permitted - /var/www/vastra/public/system/vastromen/avatars/000/000/003/original/mladjan.png):
  app/controllers/vastromen_controller.rb:29:in `create'

Ubuntu 12.04

which convert
/usr/bin/convert

convert -version
Version: ImageMagick 6.6.9-7 2012-08-17 Q16 http://www.imagemagick.org
Copyright: Copyright (C) 1999-2011 ImageMagick Studio LLC
Features: OpenMP

ruby -v
ruby 1.9.3p448 (2013-06-27 revision 41675) [x86_64-linux]

rails -v
Rails 3.2.13

paperclip (3.4.2)

Tried to fix permissions by setting even 777 for system dir and subdirs, but without result :|

**Comment by jsanders67** [comment]
I am also receiving this issue. This is my error specifically: 

Errno::EPERM (Operation not permitted @ unlink_internal - /Users/James/Desktop/appname/public):
  app/controllers/products_controller.rb:150:in `block in create'
  app/controllers/products_controller.rb:65:in `create'

I am curious as to how one goes about changing the permissions of a folder

**Comment by k10blogger** [comment]
I had the same problem. This happened as my files directory was mapped to a server location which had a user x. The redmine was running as user x on the server. Now the file directory access was changed to user y. User x was removed. Whereas the passenger was still running as a user x service so hence the conflict was there. 
Hope this helps to anyone reading. 
So this was indeed a permission issue.
