### ISSUE TITLE
"Paperclip::Errors::NotIdentifiedByImageMagickError" as a validation message for corrupted image

### ISSUE THREAD

**Issue by Webovani** [thoughtbot/paperclip#1299]
I wanted to validate uploaded image according to file contents (not mime headers) before saving and ended up with unexpected behaviour when I uploaded intentionally corrupted image file.

When I upload corrupted image (image/jpeg, random data), `post_process` method is called before validation takes place, `Paperclip::GeometryDetector#make` raises `Paperclip::Errors::NotIdentifiedByImageMagickError.new` and it's message is stored as a validation error. This results in showing string `"Paperclip::Errors::NotIdentifiedByImageMagickError"` as a validation error to user and inability to show proper error for user as I wanted to do in code below with `validate_file_type_by_contents` method.

```ruby
class Image < ActiveRecord::Base
  has_attached_file :file, :styles => { :thumb => '100x100' }

  validates_attachment_presence :file
  validate :validate_file_type_by_contents

  def validate_file_type_by_contents
    file_path = file.queued_for_write[:original].path

    output = Cocaine::CommandLine.new('identify', '-format %m :file').run(:file => file_path)
    errors.add(:file, 'only jpeg, png or gif files are allowed') unless %w(PNG JPEG GIF).include? output.strip
  rescue Cocaine::ExitStatusError => e
    errors.add(:file, 'unsupported file format or file corrupted')
  end
end
```

I am able to circumvent this by calling 

```ruby
    if errors.include?(:file)
      errors.get(:file).each {|msg| msg.sub!('Paperclip::Errors::NotIdentifiedByImageMagickError', 'unsupported file format or file corrupted')}
      return
    end
```
but that is not very nice.

**Comment by maclover7** [comment]
Hi @Webovani ! Is this still an issue for you in Paperclip; I know this issue is from approximately 2 years ago. If it is still an issue, can you please provide the code that's causing you the error? Thanks!

**Comment by tute** [comment]
Closing in favor of duplicate https://github.com/thoughtbot/paperclip/issues/1313.
