### ISSUE TITLE
Emit more useful errors when a file cannot be identified as an image

### ISSUE THREAD

**Issue by djcp** [thoughtbot/paperclip#1313]
See #1299 

When a file has passed validations but cannot correctly have its geometry read, it will cause paperclip to add a `Paperclip::Errors::NotIdentifiedByImageMagickError` error message. This is not a great error message - it should read something like "could not be identified as an image", which might be totally valid for PDFs, word docs, or other files that can't be processed through the default thumbnail processor.

Hook into rails i18n() and ensure that we keep the default "whiny" behavior, which silences certain imagemagick-related errors when encountered.

**Comment by maclover7** [comment]
Hi @djcp ! Is this still an issue for you in Paperclip; I know this issue is from approximately 2 years ago. If it is still an issue, would you be willing to send in a PR to solve the problem? Thanks!

**Comment by tute** [comment]
@jyurek do you think we'd need the PR described in @djcp's comment, or is this issue stale now?

**Comment by tute** [comment]
If we need more information, there's a lengthy discussion in https://github.com/thoughtbot/paperclip/issues/1223.

**Comment by jyurek** [comment]
@tute I don't believe this has been acted on, so we probably do still need it.

**Comment by tute** [comment]
> @tute I don't believe this has been acted on, so we probably do still need it.

It hasn't been acted on, and we very much need it indeed!

**Comment by lifeiscontent** [comment]
@tute @jyurek any updates on this?

**Comment by tute** [comment]
Not that I'm aware of.

**Comment by mike-burns** [comment]
Thank you for reporting this. Unfortunately, we will be deprecating Paperclip and therefore will not have the bandwidth to address this issue.

(Hi @djcp !)

**Comment by jomz** [comment]
I believe that this is the culprit: https://github.com/ImageMagick/ImageMagick/commit/90ee513#commitcomment-24758911
