### ISSUE TITLE
Check for exists? of S3 attachment causes Net::HTTP[s3.amazonaws.com]: HEAD calls

### ISSUE THREAD

**Issue by masonoise** [thoughtbot/paperclip#1314]
I'm attaching user avatar images via Paperclip and storing them in S3, and in order to determine whether a user has uploaded an avatar or not, I'm using exists?, such as "current_user.avatar.exists?". I noticed looking at some requests in NewRelic, that every call to exists? is causing a call out via Net::HTTP, which is having a terrible impact on page performance when showing information about a large number of users. The NewRelic details show it as:

    Net::HTTP[s3.amazonaws.com]: HEAD

Every single time. I double-checked by adding a single exists? call to a controller, and sure enough, saw the HEAD call appear.

Is there a better way to check for the existence of an avatar that won't cause this? I'm considering taking advantage of the default behavior and checking if user.avatar.url != "/headshots/original/missing.png" but that seems like a pretty weak hack.

Any suggestions would be great. Thanks.

**Comment by kevinjalbert** [comment]
`.present?` will also work as it simply is an alias to `.file?`.

https://github.com/thoughtbot/paperclip/blob/master/lib/paperclip/attachment.rb#L352

**Comment by jamescmartinez** [comment]
+1, using `.file?` for now which does not ping Amazon. Here's the details of the time it takes to perform the request:

```
irb(main):001:0> Benchmark.ms { User.last.avatar.exists? }
  User Load (2.9ms)  SELECT  "users".* FROM "users"  ORDER BY created_at DESC LIMIT 1
  User Load (2.9ms)  SELECT  "users".* FROM "users"  ORDER BY created_at DESC LIMIT 1
[AWS S3 200 0.35031 0 retries] head_object(:bucket_name=>"redacted-staging",:key=>"users/avatars/945c8bac-19b8-48a0-a6a8-7e7f79952418/original/image.png")

[AWS S3 200 0.35031 0 retries] head_object(:bucket_name=>"redacted-staging",:key=>"users/avatars/945c8bac-19b8-48a0-a6a8-7e7f79952418/original/image.png")

=> 547.155637992546


irb(main):002:0> Benchmark.ms { User.last.avatar.present? }
  User Load (1.6ms)  SELECT  "users".* FROM "users"  ORDER BY created_at DESC LIMIT 1
  User Load (1.6ms)  SELECT  "users".* FROM "users"  ORDER BY created_at DESC LIMIT 1
=> 3.352894971612841
```

**Comment by maclover7** [comment]
Hi @masonoise ! Is this still an issue for you in Paperclip; I know this issue is from approximately 2 years ago. If it is still an issue, can you please provide the code that's causing you the error? Thanks!

**Comment by tute** [comment]
Can this be fixed in paperclip or should it be part of the documentation?

**Comment by masonoise** [comment]
I haven't worked with this for a long time now so unfortunately I can't say whether it stills acts the same way. At the very least I'd say documentation advising people to use `.present?` would be a good thing to do.

**Comment by tute** [comment]
@maclover7 would you like to take this, as part of https://github.com/thoughtbot/paperclip/issues/1854?

**Comment by jyurek** [comment]
`exists?` will check Amazon because that's the only way to know if the file actually exists. `file?` and `present?` will let you know if the `_file_name` field has been populated and that's it. I would entertain a PR that added an `exists_in_db?` or similar method as well as documentation explaining the difference, but I'm probably not going to change how the `exists?` method currently works without assurance that it won't really affect people currently using Paperclip.
