### ISSUE TITLE
NoMethodError in v 3.5.1 breaks existing code

### ISSUE THREAD

**Issue by betesh** [thoughtbot/paperclip#1319]
I upgraded paperclip from 3.4.1 to 3.5.1 and a line of code which used to behave now raises an NoMethodError.  Downgrading back to 3.4.2 fixed this.

Here's a stack trace from my Rails application -- it starts in an ActiveRecord model on the line "u.valid?"

    class Member < ActiveRecord::Base
      # ...
      has_attached_file :member_data # No validation -- I don't care if it exists or not
      # ...
      def self.some_other_attribute_can_be?(some_value)
        u = self.new(:some_other_attribute => some_value)
        u.valid? # <--- This raises the error
        return !u.errors.to_hash.has_key?(:some_other_attribute) # Returns whether errors were found on :some_other_attribute
      end
    end

A NoMethodError occurred in ControllerName#ControllerAction:
  undefined method `flush_errors' for nil:NilClass
  paperclip (3.5.1) lib/paperclip/has_attached_file.rb:28:in `block in define_flush_errors'
  paperclip (3.5.1) lib/paperclip/has_attached_file.rb:28:in `block in define_flush_errors'
  activemodel (3.2.12) lib/active_model/validator.rb:181:in `call'
  activemodel (3.2.12) lib/active_model/validator.rb:181:in `validate_each'
  activemodel (3.2.12) lib/active_model/validator.rb:153:in `block in validate'
  activemodel (3.2.12) lib/active_model/validator.rb:150:in `each'
  activemodel (3.2.12) lib/active_model/validator.rb:150:in `validate'
  activesupport (3.2.12) lib/active_support/callbacks.rb:310:in `_callback_before_113'
  activesupport (3.2.12) lib/active_support/callbacks.rb:517:in `_run__4461855193761339832__validate__728062533282226168__callbacks'
  activesupport (3.2.12) lib/active_support/callbacks.rb:405:in `__run_callback'
  activesupport (3.2.12) lib/active_support/callbacks.rb:385:in `_run_validate_callbacks'
  activesupport (3.2.12) lib/active_support/callbacks.rb:81:in `run_callbacks'
  activemodel (3.2.12) lib/active_model/validations.rb:228:in `run_validations!'
  activemodel (3.2.12) lib/active_model/validations/callbacks.rb:53:in `block in run_validations!'
  activesupport (3.2.12) lib/active_support/callbacks.rb:403:in `_run__4461855193761339832__validation__728062533282226168__callbacks'
  activesupport (3.2.12) lib/active_support/callbacks.rb:405:in `__run_callback'
  activesupport (3.2.12) lib/active_support/callbacks.rb:385:in `_run_validation_callbacks'
  activesupport (3.2.12) lib/active_support/callbacks.rb:81:in `run_callbacks'
  activemodel (3.2.12) lib/active_model/validations/callbacks.rb:53:in `run_validations!'
  activemodel (3.2.12) lib/active_model/validations.rb:195:in `valid?'
  activerecord (3.2.12) lib/active_record/validations.rb:69:in `valid?'

**Comment by maclover7** [comment]
Hi everybody! Is this still an issue for you in Paperclip; I know this issue is from approximately 2 years ago. If it is still an issue, can you please provide the code that's causing you the error? Thanks!

**Comment by gerard-leijdekkers** [comment]
I still had the issue, but it turns out it was generated by some stubbing on the attachment in the specs. So I have updated to 4.2.1 :)

**Comment by betesh** [comment]
The code that was raising the error no longer exists, so I'm not sure if this is still an issue.

**Comment by maclover7** [comment]
@jferris @jyurek Please close issue, problem appears to be solved.

**Comment by gerard-leijdekkers** [comment]
The code still exists, it just wasn't paperclips fault the error got raised.

**Comment by rmagnum2002** [comment]
This problem is still here, tried versions 4.0, 3.5.4, 3.5
The one that works is 3.4.2

rails 4.1.8 
ruby 2.2.1
