### ISSUE TITLE
URL escaping is broken

### ISSUE THREAD

**Issue by toupeira** [thoughtbot/paperclip#1324]
The current code uses `URI.escape`, which is [deprecated in Ruby 1.9.2](http://blade.nagaokaut.ac.jp/cgi-bin/vframe.rb/ruby/ruby-core/29293?29179-31097) and doesn't escape some characters such as brackets and parentheses. This leads to an `URI::InvalidURIError` when trying to parse the generated URL.

Example:
```ruby
URI.parse(URI.escape("http://www.example.org/()[]"))
```

As a workaround I monkey-patched `Paperclip::UrlGenerator` to disable escaping and just do it manually in the one interpolation where I need it, using `ERB::Util.url_encode`.

**Comment by maclover7** [comment]
Hi @toupeira ! Is this still an issue for you in Paperclip; I know this issue is from approximately 2 years ago. If it is still an issue, can you please provide the code that's causing you the error? Thanks!

**Comment by toupeira** [comment]
Hey @maclover7, haven't been using Paperclip in a while :) I assume the fix in 27a02c3 resolved it. IIRC I noticed the issue when using URL components with parentheses in them (e.g. the original filename).

**Comment by maclover7** [comment]
@jferris @jyurek Please close issue, problem appears to be solved.

**Comment by toupeira** [comment]
Ah sorry I thought the issue was already closed (confused the label from another issue above) and you were asking for some other reason ;-)
