### ISSUE TITLE
AWS::S3::Errors::RequestTimeTooSkewed when upload file

### ISSUE THREAD

**Issue by jackbit** [thoughtbot/paperclip#1336]
No information for server time, could you add more information about it? because it's not easy to get S3 amazon server time.

**Comment by maclover7** [comment]
Hi @jackbit ! Is this still an issue for you in Paperclip; I know this issue is from approximately 2 years ago. If it is still an issue, can you please provide the code that's causing you the error? Thanks!

**Comment by jackbit** [comment]
It is not from paperclip but server time has gap with S3 timezone. problem solved.

**Comment by maclover7** [comment]
@jferris @jyurek Please close issue, problem appears to be solved.
