### ISSUE TITLE
Looking for elegant way to force attachment's content_type

### ISSUE THREAD

**Issue by Capncavedan** [thoughtbot/paperclip#1338]
We fetch some binary PDF data and store it as an S3 attachment.  The file name Paperclip assigns is "stringio.txt" and the content_type in Rails is nil; on S3 the metadata indicates the content_type is "text/plain".  This causes a problem in Chrome as it doesn't deal with the download properly.

We're looking for a way to force the attachment's `content_type`.  Below is what we've found but it seems uglier than necessary.  Note that `pdf_data` is a method on the model that returns binary PDF data.

````

  has_attached_file :pdf,
    storage:          :s3,
    # etc


  # before, getting text/plain as content_type set on S3
  def render_pdf
    self.pdf = StringIO.new(pdf_data)
    save
  end


  # after, getting application/pdf as content_type on S3
  def render_pdf
    io = StringIO.new(pdf_data)
    def io.content_type; 'application/pdf'; end
    self.pdf = io
    save
  end
````

Any suggestions appreciated.

**Comment by maclover7** [comment]
Hi @Capncavedan ! Is this still an issue for you in Paperclip; I know this issue is from approximately 2 years ago. If it is still an issue, can you please provide the code that's causing you the error? Thanks!

**Comment by Capncavedan** [comment]
Unsure if still an issue with current Paperclip.  Our workaround shown above continues to work with Paperclip 3.5.4.  Feel free to close this issue.

**Comment by maclover7** [comment]
@jferris @jyurek Please close issue, problem appears to be solved.
