### ISSUE TITLE
undefined method `add_attachment'

### ISSUE THREAD

**Issue by marionzumbado** [thoughtbot/paperclip#1351]
Hi, I run my migrations and give me this error:   undefined method `add_attachment'

**Comment by pasierb** [comment]
Little bit late, but i ran into this when developing Rails engine with paperclip 5.1.0.
It looks like Paperclip::Schema was not being included. Easy solution is to do this explicitely in your migration class

`include Paperclip::Schema`

**Comment by awortham** [comment]
I had the same issue while developing an engine with the same version. Thanks for the heads up on including the Paperclip::Schema.
