### ISSUE TITLE
Can't save images with all formats

### ISSUE THREAD

**Issue by itdxer** [thoughtbot/paperclip#1355]
I have model wtih this field

    has_attached_file :path, :styles => { :medium => "300x300>", :thumb => "100x100>" }

I try save many photos in loop like this

    for photo in params[:file][:path]
        current_photo = Photo.create(:description => 'test')
        current_photo.path = photo
        current_photo.save
    end

It save but only in one format (original). How I can save medium and thumb formats?

I use Ruby 1.9.3, Rails 3.2.13 and Paperclip 3.5.1

**Comment by maclover7** [comment]
Hi @itdxer ! Is this still an issue for you in Paperclip; I know this issue is from approximately 2 years ago. If it is still an issue, can you please provide the code that's causing you the error? Thanks!

**Comment by tute** [comment]
Ping @itdxer. Is this still an issue with paperclip for you?

**Comment by itdxer** [comment]
Sorry, that was old project and I didn't remember fix for it. Probably now it isn't an issue.
