### ISSUE TITLE
Copy amongst S3 instead of download & reupload

### ISSUE THREAD

**Issue by sidraval** [thoughtbot/paperclip#1361]
Hello all,

I wrote some code to fix issues #1234 & #647 -- when assigning a model an attachment through another model (e.g. `User.create(avatar: User.last.avatar`), paperclip should use S3's `copy_to` method to copy amongst s3, rather than downloading the file and reuploading it.

See my latest post below for my solution.

**Comment by jahrichie** [comment]
need this bad +1

**Comment by maclover7** [comment]
Hi everybody! Is this still an issue for you in Paperclip; I know this issue is from approximately 2 years ago. If it is still an issue, would you be willing to send in a PR to solve the problem? Thanks!

**Comment by johnnyshields** [comment]
This is still an issue, please do not close.

**Comment by stereoscott** [comment]
For what it's worth, we've been using the gist I created above in our production environment and it works very well for us, but it's fog-specific. Maybe someone who uses the s3 gem directly could take a look and suggest how to abstract it? Then we can top it off w/ some specs and submit the PR.

**Comment by ksin** [comment]
Thanks @stereoscott ! Here's how we quickly implemented it with s3:
https://gist.github.com/ksin/7747334d60b1947f14e9

**Comment by builtinnya** [comment]
Thanks @stereoscott and @ksin.
Here's my working version for S3:
https://gist.github.com/builtinnya/24c2ca12969fc79a0d69
It works with aws-sdk 1.33.0 or higher (not tested). Obviously, it does not work with 2.0.0 or higher.

**Comment by airblade** [comment]
It would be great to see this in Paperclip.

**Comment by airblade** [comment]
Here is an alternative implementation: [gist](https://gist.github.com/airblade/a6c9ea0f6888d4ce1bcd).

I think the code is simpler.

**Comment by airblade** [comment]
I'm happy to write a pull request with tests.  Before I do, I'd like to know:

- Should this functionality be available for S3 storage only, or for all the storages?
  - For example, all the storages implement `copy_to_local_file(style, local_dest_path)`.  Do we want something similar, e.g. `copy_to(destination)` on all storages or just S3?
- Should we copy to an AR instance or an attachment instance?
- Should we copy to or copy from?

**Comment by SirRawlins** [comment]
@airblade good stuff! My thoughts would be that all storages should support this, as Paperclip is built to be somewhat agnostic. However if this makes initial implementation a headache then maybe it's not worth worrying about, additional stores can always be dealt with later.

**Comment by lucascaton** [comment]
Hope is the last to die: this issue was opened in 2013 :laughing:

Is anyone up for implementing it?

**Comment by aledalgrande** [comment]
👍 @airblade's solution is good.

**Comment by corwinstephen** [comment]
@airblade And then it was two years later :(

**Comment by emilkarl** [comment]
Using @airblade's version workouts but I've got an issue I wonder if people got?

I've a got a Upload AR with an `attachment` paperclip field. When duplicating this multiple times it fails to duplicate the Paperclip::Attachment object and this causes the duplication to fail as well as the `destination_attachment` references the same attachment object as the original which generates equal urls.

Why is it that the first time it is duplicated and `@instance` of the attachment is change to the new duplicate but on the second time around it is the same as the original?


## upload.rb
```
class Upload < ActiveRecord::Base
  has_attached_file :attachment, s3_permissions: :private
 end
```

## Iterating uploads and duplicating
```
@original.uploads.map do |upload|
  @ids.map do |id|
    new_upload = upload.dup
    
    Rails.logger.debug "Duplicate #{upload.id} to: #{id}"
    
    new_upload.save(validate: false)
  
    Rails.logger.debug "New upload id: #{new_upload.id}"
    Rails.logger.debug "Attachment AID: #{upload.attachment.object_id}"
    Rails.logger.debug "Duplicate AID: #{new_upload.attachment.object_id}"
    
    # Copy attachment on the S3 side instead of Peppster server, done after record save
    new_upload.copy_attachments_from(upload) if Paperclip::Attachment.default_options[:storage].eql? :s3
    
    Rails.logger.debug ">>>>>>>> next item"
  end
end
```


## output

```
Duplicate 375 to: 14602
Attachment AID: 70122011106260
Duplicate AID: 70122011104940
New upload id: 376

[paperclip] S3 copy: uploads/attachments/000/000/375/original/app_icon_base.jpg -> uploads/attachments/000/000/376/original/app_icon_base.jpg

>>>>>>>> next item

Duplicate 375 to: 14603
New upload id: 377
Attachment AID: 70122011106260
Duplicate AID: 70122011106260

[paperclip] S3 copy: uploads/attachments/000/000/375/original/app_icon_base.jpg -> uploads/attachments/000/000/375/original/app_icon_base.jpg
```

**Comment by jurezove** [comment]
@emilkarl what is `@ids` in your example?

**Comment by mike-burns** [comment]
Hi @sidraval you're sitting next to me. Thanks for helping me deprecate Paperclip.
