### ISSUE TITLE
When I try to upload an image with special chars I give Paperclip::Errors::NotIdentifiedByImageMagickError

### ISSUE THREAD

**Issue by lisotton** [thoughtbot/paperclip#1363]
When I try to upload some image with special chars, like "Café.jpg" it's raise and error:
Paperclip::Errors::NotIdentifiedByImageMagickError

I'm using paperclip 3.5 with rails 3.2.13

**Comment by maclover7** [comment]
Hi @lisotton ! Is this still an issue for you in Paperclip; I know this issue is from approximately 2 years ago. If it is still an issue, can you please provide the code that's causing you the error? Thanks!

**Comment by tute** [comment]
Closing as duplicate of https://github.com/thoughtbot/paperclip/issues/1223.
