### ISSUE TITLE
Paperclip will delete current image even though it's not changed on update

### ISSUE THREAD

**Issue by scaryguy** [thoughtbot/paperclip#1369]
I'm using Paperclip to let my users upload images. 

It works pretty well with separated single resources. I can add, edit, and delete all images without any extra effort using a RESTFUL structure.

But I have some difficulties while working with nested attributes.

I have 2 models called `Article` and `Headline`.

I'm using an `Article` form in my view to create an associated instance of `Headline`. So I'm using `accepts_nested_attributes_for` with ActiveRecord. I've set up everything related to this. I'm using `fields_for` in my form view. Strong parameters settings are all done. Everything works great with adding a NEW article with its headline. I also have a `title` field which updates appropriately.

```
<%= f.fields_for :headline do |r| %>
  <%= r.label :title  %>
  <%= r.text_field :title %>
  <%= r.label :image, "Headline image" %>
  <%= r.file_field :image %>
<% end %>
```

But **when I UPDATE an article without any change of the `Headline`'s image, the `Headline`'s image disappears.**

As I know and experience, Paperclip doesn't update image files unless they are changed. That's the expected behavior. But in this case, it overwrites the nested model's attribute even though it shouldn't.

I think there must be a workaround for this?

`Article.rb`:

```
class Article < ActiveRecord::Base

  after_commit :expire_caches

  scope :desc, ->{ order(created_at: :desc)}

  scope :with_images, -> {where.not(image_file_name: nil)}

  before_validation :set_default_category

  acts_as_taggable

  attr_accessor :is_headline

  has_attached_file :image, default_url: "default_:style.png",
    :styles => { :large=>"700", :medium => "296", :thumb => "150", mini_thumb: "50x50>", :absolute_thumb=>"150x150#" },
    :s3_host_name => 's3-eu-west-1.amazonaws.com',
    :path => "articles_images/:id/:style/:basename.:extension"
  #validates :title, presence: true
  belongs_to :category
  belongs_to :user
  validates :title, :content, presence: true
  validates :content, length: {minimum: 10}
  validates :category_id, presence: true
  validates :cihan_url, uniqueness: true, allow_nil: true
  has_many :galleries, dependent: :destroy
  has_one :headline, dependent: :destroy
  has_one :ad, dependent: :destroy

  has_many :videos

  accepts_nested_attributes_for :headline


  def self.main_page
    where(main_page: true).with_images.desc
  end

  def to_param
    "#{self.id}-#{self.title.parameterize}"
  end

  private

  def set_default_category
    self.category = Category.uncategorized if self.category.blank?
  end

  def expire_caches
    Rails.cache.clear
  end


end
```

`Headline.rb`:

```
class Headline < ActiveRecord::Base
  after_commit :expire_caches
  has_attached_file :image, default_url: "default_:style.png",
    :styles => {  :large=>"600", :medium => "300x300>", :thumb => "150x150>", :absolute_thumb=>"150x150#" },
    :s3_host_name => 's3-eu-west-1.amazonaws.com',
    :path => "headline_images/:id/:style/:basename.:extension"
  belongs_to :article

  private

  def expire_caches
    Rails.cache.clear
  end
end
```

From `articles_controller`:

```
def set_article
  @article = Article.find(params[:id])
end


def update
  if @article.update(article_params)
    redirect_to [:admin, @article], flash: {success: "<i class=\"icon-ok\"></i> Haber başarıyla düzenlendi.".html_safe}
  else
    render action: 'edit'
  end
end


def article_params
  params.require(:article).permit(:title, :content, :publish_date, :category_id, :active, :tag_list, :main_page, :extra_title, :image, :is_headline, headline_attributes: [:title, :counter, :order, :image])
end
```

**Comment by maclover7** [comment]
Hi @scaryguy and @krevels ! Is this still an issue for you in Paperclip; I know this issue is from approximately 2 years ago. If it is still an issue, can you please provide the code that's causing you the error? Thanks!

**Comment by tute** [comment]
@krevels what could we update in paperclip to avoid this?

**Comment by tute** [comment]
> It appears that when you don't specify :id as one of the strong parameters for your nested attributes, Paperclip will remove whatever is currently attached there. This almost certainly seems like a bug.

@jyurek is this a bug? That's the most concise description of this one issue.

**Comment by jyurek** [comment]
I'm not sure it's a bug in Paperclip or how nested attributes work, but it's certainly unexpected and breaking things, and so we should handle it, whoever's fault it is.

**Comment by lpsBetty** [comment]
thanks @krevels for the workaround!

**Comment by MulleOne** [comment]
@krevels That worked! Thanks a lot!

**Comment by tute** [comment]
Anyone would be willing to send a PR to the README explaining this potential pitfall? A wiki page helps as well. Thank you!

**Comment by brobertsaz** [comment]
OMG! I just spent a couple of hours struggling with this! Thanks @krevels for the work around

**Comment by mike-burns** [comment]
Looks like we found workarounds, closing.
