### ISSUE TITLE
validates_attachment and if: lambda. Rails 4, ruby 2

### ISSUE THREAD

**Issue by Curter29** [thoughtbot/paperclip#1375]
Rails 4, Ruby 2, RVM

validates_attachment_presence :name, if: lambda { will work }
validates_attachment :name, presence: true, if: lambda { will NOT work }

**Comment by maclover7** [comment]
Hi @Curter29 ! Is this still an issue for you in Paperclip; I know this issue is from approximately 2 years ago. If it is still an issue, can you please provide the code that's causing you the error? Thanks!

**Comment by tute** [comment]
Ping @Curter29: do you know if this is still an issue with Paperclip? Can we get a failing spec?

**Comment by reshleman** [comment]
FWIW, I'm unable to reproduce this issue in Paperclip `4.2.1` (w/ Rails `4.2.1` / Ruby `2.2.1`).

Using the following model:

```
class Widget < ActiveRecord::Base
  has_attached_file :image
  do_not_validate_attachment_file_type :image

  validates_attachment :image, presence: true, if: lambda { true }
end
```

And attempting to create a `Widget` without an `image` in Rails console:

```
Widget.create!
```

Raises the expected validation error:

```
ActiveRecord::RecordInvalid: Validation failed: Image can't be blank
```

Doesn't `ActiveModel` -- not the validator itself -- handle [conditional validations](http://guides.rubyonrails.org/active_record_validations.html#conditional-validation) anyway?

**Comment by tute** [comment]
Thanks for trying to reproduce @reshleman! That's useful. Will close for now, if it's continue to be an issue please send reproducing steps @Curter29. Thanks!
