### ISSUE TITLE
paperclip for responsive websites

### ISSUE THREAD

**Issue by arjunmenon** [thoughtbot/paperclip#1377]
hey
can this be utilized to serve up images for responsive websites?

**Comment by urbanvikingr** [comment]
This may help: http://demosthenes.info/blog/586/CSS-Fluid-Image-Techniques-for-Responsive-Site-Design.

**Comment by cks2pks** [comment]
Hi,
You try 
<%= image_tag @collect.image.url,**class: 'img-responsive' ** %>
