### ISSUE TITLE
Support for I18n

### ISSUE THREAD

**Issue by qrush** [thoughtbot/paperclip#14]
**Reported by Peter Suschlik**

I've added I18n support for error messages:
http://github.com/splattael/paperclip/tree/translate_error_message

Now you can define translations for the errors messages in e.g. your YAML locale file:

<pre>
en:
  paperclip:
    errors:
      attachment:
        size: "Invalid file size"
        content_type: "Unsupported content type"
        presence: "Cant' be blank"
</pre>

I fear my tests are a bit messy... I'm new to shoulda :/

Nevertheless, I hope you like the patch :)

**Comment by yordis** [comment]
@jyurek @joshk is this support? I only see support for :blank and :spoofed_media_type :cry:
