### ISSUE TITLE
rake paperclip:refresh on AWS::S3 timed out

### ISSUE THREAD

**Issue by Theminijohn** [thoughtbot/paperclip#1414]
I had a problem with my attachments upon changing some configurations for Paperclip -> http://stackoverflow.com/questions/21048735/paperclip-configurations-old-attachments

The Answer was : `rake paperclip:refresh CLASS=Screen`

On Localhost it worked just fine. But upon deploying to Heroku and S3 i got a warning and the rake was aborted!

    rake aborted!
    Your socket connection to the server was not read from or written to within the 
    timeout  period. Idle connections will be closed.

    AWS::S3::Errors::RequestTimeout Your socket connection to the server was 
    not  read from or written to within the timeout period. Idle connections will be closed.

I have no idea how to fix this, anyone an idea ?

**Comment by maclover7** [comment]
Hi @Theminijohn ! Is this still an issue for you in Paperclip; I know this issue is from approximately 2 years ago. If it is still an issue, can you please provide the code that's causing you the error? Thanks!

**Comment by Theminijohn** [comment]
Haha, hey @maclover7!
No, fortunately NOT an issue after a year, a lot learned.

You can close it.

**Comment by maclover7** [comment]
@jferris @jyurek Please close issue, problem appears to be solved.
