### ISSUE TITLE
AWS::S3::Errors::NoSuchKey

### ISSUE THREAD

**Issue by LucasCioffi** [thoughtbot/paperclip#1416]
When validates_attachment is turned on, I'm seeing AWS::S3::Errors::NoSuchKey error in the log and the record won't save.  I'm using aws-sdk-1.32.0 gem, Rails 3.2.5, Ruby 1.9.3p194, on OS-X 10.7.4.  I used Homebrew to install ImageMagick v.6.8.6-3.

```
[AWS S3 404 0.05249 0 retries] head_object(:bucket_name=>"bucketname_xyz",:key=>"users/photos/000/000/009/original/IMG00033-20120521-1036.jpg") AWS::S3::Errors::NoSuchKey No Such Key
[AWS S3 404 0.010744 0 retries] head_object(:bucket_name=>"bucketname_xyz",:key=>"users/photos/000/000/009/small_square/IMG00033-20120521-1036.jpg") AWS::S3::Errors::NoSuchKey No Such Key
[AWS S3 404 0.008954 0 retries] head_object(:bucket_name=>"bucketname_xyz",:key=>"users/photos/000/000/009/square/IMG00033-20120521-1036.jpg") AWS::S3::Errors::NoSuchKey No Such Key
```

This only happens when I am using validates_attachment (shown below) and only on Heroku.  It does not happen when I run the server in production mode locally.  When the error does happen in production on Heroku, it always happens for certain images and never for others.  The images range from 20kb-500kb so they are not unreasonably large.

```ruby
has_attached_file :photo,
    :storage => :s3,
    :bucket => (Rails.env.development? ? S3_CONFIG["AWS_BUCKET_NAME"] : ENV['S3_BUCKET_NAME']),
    :s3_protocol => "https",
    :s3_credentials => {
      :access_key_id => (Rails.env.development? ? S3_CONFIG['AWS_ACCESS_KEY_ID'] : ENV['AWS_ACCESS_KEY_ID']),
      :secret_access_key => (Rails.env.development? ? S3_CONFIG['AWS_SECRET_ACCESS_KEY'] : ENV['AWS_SECRET_ACCESS_KEY'])
    },
    :styles => {
      :small_square => '30x30#',
      :square => '100x100#' # The > and # symbols will tell ImageMagick how the image will be resized (the > will proportionally reduce the size of the image).
    },
    :hash_secret => "xyz",
    :default_url => "/profile.png"

validates_attachment :photo
   :content_type => { :content_type => ["image/jpg", "image/jpeg", "image/gif", "image/png", "image/bmp"] }
```

In case it's helpful, here's the link from the aws-sdk gem explaining the NoSuchKey error: http://docs.aws.amazon.com/AWSRubySDK/latest/AWS/S3/Errors/NoSuchKey.html

Any advice?  Many thanks!

**Comment by jonn** [comment]
I ran into this problem as well, with older photos, but not newer ones. Turned out the older photos were created before <code>{attachment_name}_file_type</code> was a required db field. When that field had been added, null was allowed and the old rows' fields were left null. This caused validation to fail when reprocessing styles. Old photos that were reprocessed had styles removed but not regenerated, which may have been why I was seeing <code>AWS::S3::Errors::NoSuchKey</code> errors. I replaced my <code>validates_attachment :photo</code> declaration with <code>do_not_validate_attachment_file_type :photo</code> so I could reprocess the old photos that had lost their styles. Then I updated the <code>photo_content_type</code> field with a sensible default, restored my photo validations and all is working well again.

**Comment by maclover7** [comment]
Hi everybody! Is this still an issue for you in Paperclip; I know this issue is from approximately 1 year ago. If it is still an issue, can you please provide the code that's causing you the error? Thanks!

**Comment by danieljacobarcher** [comment]
@maclover7 I'm not seeing this issue any more.

**Comment by maclover7** [comment]
@jferris @jyurek Please close issue, problem appears to be solved.

**Comment by MrHubble** [comment]
I have this issue when I upload a file that doesn't require post processing. For example if a user uploads an image I will perform processing, but if an excel file is uploaded then no processing is needed. I will then see the error in my logs for the excel file:

````rb
head_object(:bucket_name=>"my-buckey",:key=>"documents/1/thumb/data.xlsx") AWS::S3::Errors::NoSuchKey No Such Key

head_object(:bucket_name=>"my-buckey",:key=>"documents/1/small/data.xlsx") AWS::S3::Errors::NoSuchKey No Such Key

head_object(:bucket_name=>"my-buckey",:key=>"documents/1/medium/data.xlsx") AWS::S3::Errors::NoSuchKey No Such Key
````

**Comment by tute** [comment]
https://github.com/thoughtbot/paperclip/issues/1473 and https://github.com/thoughtbot/paperclip/issues/1570 report similar issues, and they say it's problems in their code. Closing for now, if it's an issue with paperclip please tell us how to reproduce or fix. Thanks!

**Comment by danielbonnell** [comment]
Hello,

I'm having this same problem with my Rails 4 app on Heroku. I tried @jonn's suggestion as well as running `paperclip:refresh:missing_styles`, but to no avail. In my model I have the following:

    has_attached_file :logo, :styles => { :medium => "300x300>", :thumb => "100x100>" }
    do_not_validate_attachment_file_type :logo
    # validates_attachment_content_type :logo, :content_type => /\Aimage\/.*\Z/
    has_attached_file :profile_photo, :styles => { :medium => "300x300>", :thumb => "100x100>" }
    # validates_attachment_content_type :logo, :content_type => /\Aimage\/.*\Z/
    do_not_validate_attachment_file_type :profile_photo

I haven't found many resources on this other than the few issue reports on GitHub. Thanks!
