### ISSUE TITLE
Issues with Spoof File Checks

### ISSUE THREAD

**Issue by ericchernuka** [thoughtbot/paperclip#1429]
Hi,
I just upgraded to Paperclip 4.0 and now I'm getting an error about spoofed_media_type. I found the helper for:

``` ruby
do_not_validate_attachment_file_type :push_certificate
```

But I still receive error the error message.  Does Paperclip::MediaTypeSpoofDetector.using(adapter, value.original_filename).spoofed? not take into account the do_not_validate?

**Comment by Marthyn** [comment]
require 'paperclip/media_type_spoof_detector'         
```ruby
Paperclip::MediaTypeSpoofDetector.class_eval do
    def spoofed?
      false
    end
    def type_from_file_command      
        begin       
          Paperclip.run("file", "-b --mime :file", :file => @file.path)
        rescue
          ""
        end       
    end      
end
```
seems to work when file is uploaded on windows

**Comment by mjodko** [comment]
As an improvement to @glebtv's workaround you might want to try this:

```ruby
require 'paperclip/media_type_spoof_detector'

module Paperclip
  class MediaTypeSpoofDetector
    old_spoofed = instance_method(:spoofed?)

    define_method(:spoofed?) do
      if supplied_file_content_types.count > 0
        old_spoofed.bind(self).()
      else
        false
      end
    end
  end
end
```

**Comment by rpbaltazar** [comment]
@mjodko, how would the
```
supplied_file_content_types
```
have something in it? I'm a bit confused with the purpose of the override as you suggest.

**Comment by mach-kernel** [comment]
@glebtv  @mjodko thank you for this. Giggling that this is in production on our servers right now.

**Comment by chrisdpeters** [comment]
For my fellow Googlers who also wish to step into the dark side, @mjodko's [monkey patch above](https://github.com/thoughtbot/paperclip/issues/1429#issuecomment-76622619) should now reference the `content_types_from_name` method instead of `supplied_file_content_types`.

```ruby
# config/initializers/paperclip.rb
require 'paperclip/media_type_spoof_detector'

module Paperclip
  class MediaTypeSpoofDetector
    old_spoofed = instance_method(:spoofed?)

    define_method(:spoofed?) do
      if content_types_from_name.count > 0
        old_spoofed.bind(self).()
      else
        false
      end
    end
  end
end
```

**Comment by rystraum** [comment]
Hopefully this replaces the monkey patching: https://github.com/thoughtbot/paperclip/pull/2378

**Comment by kirushanth-sakthivetpillai** [comment]
No need for monkey patch.

Paperclip has content-type checking and media-type checking. Both seem to do the same thing using `file -b --mime`.

Media-type checking uses the global config of `content_type_mappings`. However, sometimes you want per-model exceptions. Paperclip provides the option for it but not well documented. I got it from the source here:
https://github.com/thoughtbot/paperclip/blob/v4.3/lib/paperclip/has_attached_file.rb#L83

You can do the following to control media-type and content-type checking:

```
class PaperclipModel < ActiveRecord::Base

   has_attached_file :attachment, { validate_media_type: false }

  validates_attachment :attachment, {
     # tweak as desired
     content_type: { content_type: ["text/csv", "text/plain", Paperclip::ContentTypeDetector::SENSIBLE_DEFAULT] }
  }
end
```

**Comment by tomfast** [comment]
Using the latest version of Paperclip (5.1.0) resolved the issue for me. I'm suspecting the 

> * Add default `content_type_detector` to `UploadedFileAdapter` (#2270)

did the trick for me.

Source: https://github.com/thoughtbot/paperclip/blob/master/NEWS for 5.1.0:

**Comment by dradux** [comment]
Standard Alpine Linux (in docker) does not come with the 'file' command so you may want to verify you have it to start with.

- hope its of use to others

**Comment by kennabila** [comment]
> Standard Alpine Linux (in docker) does not come with the 'file' command so you may want to verify you have it to start with.
> 
> * hope its of use to others

I got the same problem on Alpine (Docker), the problem solved by adding this on my Dockerfile:
`RUN apk add file`

Thanks!

**Comment by sunil-smartbear** [comment]
> Workaround:
> 
> ```ruby
> require 'paperclip/media_type_spoof_detector'
> module Paperclip
>   class MediaTypeSpoofDetector
>     def spoofed?
>       false
>     end
>   end
> end
> ```

This is the perfect solution!!!
Thanks
