### ISSUE TITLE
Readme missing info on how to configure for testing

### ISSUE THREAD

**Issue by steakchaser** [thoughtbot/paperclip#1432]
I've seen a lot of different approaches being recommended for how one should work with Paperclip during testing, but there's nothing official being recommended in the Readme.  This would be very useful.

For example, prior to 4.0, I could essentially disable Paperclip from processing any attachments by doing this in my factory:

```ruby
factory :attachment do
  supporting_documentation_file_name { 'test.pdf' }
  supporting_documentation_content_type { 'application/pdf' }
  supporting_documentation_file_size { 1024 }
  # ...
end
```

This no longer works, and instead I get a validation error:
> ActiveRecord::RecordInvalid: Validation failed: Image translation missing: en.activerecord.errors.models.attachment.attributes.supporting_documentation.spoofed_media_type

There are quite a few options being recommended for 3.x (i.e. http://stackoverflow.com/questions/3294824/how-do-i-use-factory-girl-to-generate-a-paperclip-attachment).  There's almost nothing on this topic yet for 4.0.

If I come to a reasonable approach, I'll write it up, but would like feedback from others too.

**Comment by maclover7** [comment]
Hi everybody! Is this still an issue for you in Paperclip; I know this issue is from approximately 1 year ago. If it is still an issue, can you please provide the code that's causing you the error? Thanks!

**Comment by christophe-dufour** [comment]
As far as I'm concerned, I still can't see on the readme a recommended why to configure FactoryGirl with paperclip.

Should I use fixture_file_upload or not ??

**Comment by blackjackcf** [comment]
@christophe-dufour - I've been using fixture_file_upload and then configuring my spec_helper to just clear out the contents of the folder that Paperclip uploads into. It's not pretty, but it works.

**Comment by kulte** [comment]
@maclover7 like @ColinTheRobot says, it's impossible to figure out the configuration to get `#stub_paperclip_s3` and `#paperclip_fixture` to work. What context should these be called in? Have these worked for anyone ever?

**Comment by kulte** [comment]
It would appear by the lack of dog-fooding here that perhaps these methods are dead code? Or am I way off base? https://github.com/thoughtbot/paperclip/blob/master/features/step_definitions/s3_steps.rb

**Comment by dgilperez** [comment]
@blackjackcf could you please share some code about your approach? I keep banging my head against the wall trying to figure this out ...

**Comment by blackjackcf** [comment]
@dgilperez - Here's my setup for my paperclip defaults:

    paperclip: &defaults
      storage: s3
      s3_protocol: <%= ENV['S3_BUCKET_PROTOCOL'] %>
      s3_host_name: <%= ENV['S3_BUCKET_HOST'] %>
      bucket: <%= ENV['S3_BUCKET_NAME] %>
      url: <%= ENV['S3_BUCKET_NAME %>
      path: ':class/:atttachment:id.:style.:extension'
      s3_credentials: ...

     development:
       <<: *defaults

     test:
       <<: *defaults
       paperclip:
         storage: Filesystem

My FactoryGirl setup for the model that's getting the Paperclip attachment:
    FactoryGirl.define do
      factory :asset do
        attachment { Rack::Test::UploadedFile.new("#path_to_attachment", "attachment_file_type (e.g. image/png)") }
      end
    end

spec_helper.rb - I'm using the DatabaseCleaner gem to help clean up after my tests:
    
    RSpec.configure do |config|
      # ...
      config.after(:suite) do
         FileUtils.rm_rf(Dir["#path_where_attachments_are_saved"])
      end
      #...

**Comment by dgilperez** [comment]
@blackjackcf thanks a lot for that! Got it working :clap:

**Comment by asaganda** [comment]
@vinvasir
Updated the README.md file by adding a Configuring Tests (FactoryGirl) section to Testing with @catherinetcai's suggestion

**Comment by tute** [comment]
> Should I use `fixture_file_upload` or not?

cc @joshuaclayton for context. I believe not, but he might have more context on this.

**Comment by tute** [comment]
For now, fixed in merged PR #2183. Still interested in @joshuaclayton's input on `fixture_file_upload`.

**Comment by joshuaclayton** [comment]
@tute I'm not familiar enough with `fixture_file_upload` and the details of file management (how do assets get cleaned up, for example) to know what the best solution is here.

My recommendation is, if at all possible, not to have FG do anything with files unless there's a validation on the model requiring the attachment be present.

@tute for the presence validation in Paperclip, how does it determine if the file is actually present? I might only define those fields on the factory, if that works (e.g. `ATTACHMENT_file_name`, `ATTACHMENT_content_type`).

**Comment by msencenb** [comment]
Has this changed in 5.0.0? 

My specs appear to pass when using the way suggested in the documentation:

```
FactoryGirl.define do
  factory :profile do
    first_name "Austin"
    avatar { File.new("#{Rails.root}/spec/support/fixtures/avatar.jpg") }
  end
end
```

But I get a lot of warnings like this:
```
/Users/msencenb/.rvm/gems/ruby-2.3.1@wrestling/gems/cocaine-0.5.8/lib/cocaine/command_line.rb:9: warning: instance variable @supplemental_path not initialized
/Users/msencenb/.rvm/gems/ruby-2.3.1@wrestling/gems/cocaine-0.5.8/lib/cocaine/command_line.rb:23: warning: instance variable @runner not initialized
/Users/msencenb/.rvm/gems/ruby-2.3.1@wrestling/gems/cocaine-0.5.8/lib/cocaine/command_line/runners/posix_runner.rb:7: warning: instance variable @available not initialized
/Users/msencenb/.rvm/gems/ruby-2.3.1@wrestling/gems/paperclip-5.0.0/lib/paperclip/attachment.rb:199: warning: instance variable @normalized_styles not initialized
/Users/msencenb/.rvm/gems/ruby-2.3.1@wrestling/gems/paperclip-5.0.0/lib/paperclip/style.rb:41: warning: instance variable @processors not initialized
```

The least amount of warnings so far has been by just giving values to the avatar properties like this:

```
FactoryGirl.define do
  factory :wrestler_profile do
    first_name "Austin"
    avatar_file_name { "avatar.jpg" }
    avatar_content_type { 'image/jpg' }
    avatar_file_size { 64000 }
  end
end
```

But that still results in one warning:
```
/Users/msencenb/.rvm/gems/ruby-2.3.1@wrestling/gems/paperclip-5.0.0/lib/paperclip/has_attached_file.rb:44: warning: instance variable @attachment_avatar not initialized
```

**Comment by tute** [comment]
@msencenb interesting, those are Ruby warnings. I'd want for paperclip not to issue any Ruby warnings. But is a big piece of software, and I'm not surprised (albeit not happy about) by those.

Does your Rails 5 app only issue Ruby warnings for paperclip? I'll merge in PRs that diminish/fixes them.

**Comment by msencenb** [comment]
Currently my Rails 5 app only issues warnings for paperclip, at least when running my rspec suite. I'm still building the v1 of my app, but hope to have it deployed to production by the end of the month. I'll try to pin down the warnings before then and update this thread / hopefully send in a PR.
