### ISSUE TITLE
attachment.path() missing :id_partition when referenced in processor.

### ISSUE THREAD

**Issue by SirRawlins** [thoughtbot/paperclip#1435]
Hi Guys,

I've been working on a custom processor today, and during the #make I require the path that the attachment will be saved too. I'm running paperclip 3.5.2 on ruby 2.0.0p247. I have the AWS S3 storage configured too.

Within my custom processor when calling `attachment.path` it returns `/:class/:attachment//:style/:filename` which is missing the numeric id_partition part to the path.

Perhaps this is intentional behaviour and there is a better way for me to access the path during the post processing, or perhaps it isn't available as the ID won't have yet been assigned?

Any comments or suggestions are greatly welcomed.

Robert

**Comment by Julyyq** [comment]
Rails `after_save` hook is better than `after_post_process`.
