### ISSUE TITLE
Issues Trying to Upgrade to 4.1

### ISSUE THREAD

**Issue by noahc** [thoughtbot/paperclip#1448]
We have code that looks like run of the mill paper clip:

```

  has_merchants_attached_file :pdf,
    storage:          :s3, 
    s3_credentials:   Mbc::DataStore.s3_credentials,
    s3_permissions:   :private,
    path:             ":identifier_template.pdf",
    bucket:           Mbc::DataStore.forms_and_templates_bucket_name


  validates_attachment_file_name :pdf, :matches => [/pdf\Z/] #if attribute.to_s.include? "pdf"

```

Which generates an error:

```undefined method `validates_attachment_file_name' for #<Class:0x007fba67d25fe0>```

Interestingly enough, when we down grade back to 3.5, we encounter the same issue.

The controller that is generating this is:

``` 
def index
   @fidelity_templates = FidelityTemplate.order("identifier asc").all
 end
```

Any thoughts on what could be causing this?

**Comment by maclover7** [comment]
Hi @noahc ! Is this still an issue for you in Paperclip; I know this issue is from approximately 1 year ago. If it is still an issue, can you please provide the code that's causing you the error? Thanks!

**Comment by noahc** [comment]
I'm closing this issue, although, it never got resolved. We must have figured out a way to work around it, perhaps by not upgrading.
