### ISSUE TITLE
If call @model.file.url() on a non saved istance get a url instead of nil

### ISSUE THREAD

**Issue by byterussian** [thoughtbot/paperclip#1453]
Hi,

In my action controller call `render 'action'` if model validations fails.

In the `action` view have
```
<div id="preview" data-preview-url="<%= @model.preview.url %>">
```
that return good url if `@model` is saved on db, bad url without :`id` part(obviously) if `@model` is not stored to db. Have to return `nil` in this case or I'm wrong?

**Comment by maclover7** [comment]
Hi @byterussian and @grimmwerks ! Is this still an issue for you in Paperclip; I know this issue is from approximately 1 year ago. If it is still an issue, would you be willing to send in a PR to solve the problem? Thanks!

**Comment by byterussian** [comment]
Hi @maclover7 

I've just sent a pull request to fix this issue https://github.com/thoughtbot/paperclip/pull/1811
