### ISSUE TITLE
How to read the file before model is saved?

### ISSUE THREAD

**Issue by vesse** [thoughtbot/paperclip#1458]
I've been in slow process of upgrading to 3.5.4 from 2.x branch. Back in the day I could easily read the actual file whether it was saved or not using the `to_file` method. Now I can read files from models that have already been saved using `Paperclip.io_adapters.for` but have yet to find a way to read the file without saving.

The model:
```ruby
class FileAttachment < ActiveRecord::Base
  belongs_to :attachable, :polymorphic => true

  has_attached_file :file,
    :url  => "/files/attachments/:attachable_id/:id/:filename",
    :path => ":rails_root/public/files/attachments/:attachable_id/:id/:filename"

  delegate :url, :to => :file

  after_find { @original_path = file.path }
  after_save :relocate_file

  Paperclip.interpolates :attachable_id do |attachment, style|
    attachment.instance.attachable_id || 'unassigned'
  end

  def relocate_file
    return unless @original_path && @original_path != file.path

    Rails.logger.info "[file_attachment] moving #{@original_path} to #{file.path}"
    FileUtils.mkpath File.dirname(file.path)
    FileUtils.mv @original_path, file.path
    FileUtils.rmdir File.dirname(@original_path)
  end
end
```

The controller from related parts:

```ruby
params[:result_files] = params[:result_files].map do |f| FileAttachment.new(:file => f, :attachment_type => :result_file) end
params[:result_files].each do |result_attachment|
  file = Paperclip.io_adapters.for(result_attachment.file)
```

Now for these unsaved model instances the ouput is:

```
ERROR: No such file or directory - /path/to/public/files/attachments/unassigned//sim.xml. Request parameters:
{"result_files"=>[#<FileAttachment id: nil, attachable_id: nil, attachable_type: nil, attachment_type: :result_file, file_file_name: "sim.xml", file_content_type: "application/xml", file_file_size: 16839, file_updated_at: "2014-02-25 04:32:06">], ...}
```

ie. it tries to read a file that probably lies on some tempfile from the path defined in in `has_attached_file`. `io_adapters.for` returns an instance of `Paperclip::AttachmentAdapter` as handler. For models that have been saved things work just fine.

**Comment by maclover7** [comment]
Hi @vesse ! Is this still an issue for you in Paperclip; I know this issue is from approximately 1 year ago. If it is still an issue, would you be willing to send in a PR to solve the problem? Thanks!

**Comment by vesse** [comment]
Were I to continue with the upgrade this probably would still be a problem. However, I have had other things to do than to maintain an old and niche OS project. The 2.x branch worked and the project can live with that. I'll close this now, I had forgotten the whole thing already.
