### ISSUE TITLE
Moving file on S3 upon update

### ISSUE THREAD

**Issue by cbauer10** [thoughtbot/paperclip#1469]
I am using Active Admin in conjunction with Paperclip and S3.  I have a custom interpolation that I am using to determine the :path of the file on S3.  It is based off of a parent that is a select box.  If a user edits the item and changes the parent, I would like the file to move from one parents folder on S3 to the other.  The :path updates properly, but the file does not move on S3.  Can any one please provide a way to move the file on update?

**Comment by maclover7** [comment]
Hi @cbauer10 ! Is this still an issue for you in Paperclip; I know this issue is from approximately 1 year ago. If it is still an issue, can you please provide the code that's causing you the error? Thanks!

**Comment by cbauer10** [comment]
I haven’t seen it in a while.

Thank you,

Christopher Bauer
ChristopherBauer@BauCode.com
BauCode LLC



On Mar 9, 2015, at 5:02 PM, Jon Moss <notifications@github.com> wrote:

Hi @cbauer10 <https://github.com/cbauer10> ! Is this still an issue for you in Paperclip; I know this issue is from approximately 1 year ago. If it is still an issue, can you please provide the code that's causing you the error? Thanks!

**Comment by maclover7** [comment]
@jferris @jyurek Please close issue, problem appears to be solved.
