### ISSUE TITLE
NameError: undefined local variable or method "flush_deletes"

### ISSUE THREAD

**Issue by bry4n** [thoughtbot/paperclip#147]
I encountered this an error on my testing Rails app.

See the error message and sample Model: http://gist.github.com/290270
- Ruby version: 1.8.7
- Gem: 1.3.5
- Installed via script/plugin last night
- added "paperclip" to config.gem
- generated "paperclip" migration
- ran rake db:migrate

Any thought?

**Comment by sidsimac** [comment]
I am facing same issue, under delayed job.
Scenario is, i an object that has paper clip attachment, that will be created after performing certain tasks under delayed job.
