### ISSUE TITLE
validate_attachment_type_content_matcher: Short-curcuiting && means side effects do not happen; confusion around where errors are added

### ISSUE THREAD

**Issue by cofiem** [thoughtbot/paperclip#1476]
Similar, but not exactly the same, as #792 #1158 #1334 #161

Short-curcuiting && means side-effects of methods are not in effect
---------------------------
The return in `matches?` cannot be done as it is on line [38](https://github.com/thoughtbot/paperclip/blob/master/lib/paperclip/matchers/validate_attachment_content_type_matcher.rb#L38). This is because `&&` short-curcuits when a return value is false. 

A failure will call `failure_message`. Due to `failure_message` calling `accepted_types_and_failures` and `rejected_types_and_failures`, `@missing_rejected_types` and `@missing_allowed_types` must have values (`any?` is called on them). These two instance variables are set in the `allowed_types_allowed?` and `rejected_types_rejected?` methods.

The short-curcuit will mean that one or both of `allowed_types_allowed?` and `rejected_types_rejected?` are not called. The end result of all of this is the error discussed in #1334: `undefined method `any?' for nil:NilClass`

One possible fix is to replace line 37 and 38 with:
````ruby
rejected_t = rejected_types_rejected?
allowed_t = allowed_types_allowed?
@allowed_types && @rejected_types && allowed_t && rejected_t
````

Confusion around where errors are added
-----------------------------
Due to #1253, there is confusion about where to look for errors on `@subject` in the `type_allowed?` method.

Currently line [85](https://github.com/thoughtbot/paperclip/blob/master/lib/paperclip/matchers/validate_attachment_content_type_matcher.rb#L85) only checks ` @subject.errors[:"#{@attachment_name}_content_type"]`. It should also check ` @subject.errors[:"#{@attachment_name}"]`.

A possible fix is to replace line 85 with:
````ruby
content_type_any = @subject.errors[:"#{@attachment_name}_content_type"].any? { |item| item == 'is invalid' }
type_any = @subject.errors[:"#{@attachment_name}"].any? { |item| item == 'is invalid' }
!content_type_any && !type_any
````

**Comment by maclover7** [comment]
Hi @cofiem ! Is this still an issue for you in Paperclip; I know this issue is from approximately 1 year ago. If it is still an issue, can you please provide the code that's causing you the error? Thanks!

**Comment by cofiem** [comment]
@maclover7 I haven't looked at this in quite some time. The code this issue refers to has most likely changed in the year since. Please refer to the tests in the fork I linked to in earlier comments.

**Comment by tute** [comment]
I don't think the error message is a problem, as they are always present at that location or the suggested addition one, too.
We'll merge the PR fixing the other bug.
Thanks!
