### ISSUE TITLE
How to skip filename validation

### ISSUE THREAD

**Issue by snoblenet** [thoughtbot/paperclip#1477]
Your read me says:

"Starting at version 4.0.0, all attachments are required to include a content_type validation, a file_name validation, or to explicitly state that they're not going to have either."

How do you skip a file_name validation?

I was looking for a method like `do_not_validate_attachment_file_type`, only for file names.

I ask because I am using Paperclip to attach a file created by the url2png service. The filetype is definitely PNG but the file I am attaching does not have a filename extension when I fetch it from url2png. As a result I'm getting the following error:

````
ActiveRecord::RecordInvalid: Validation failed: Shot has an extension that does not match its contents
````

I have tried the following:

````
validates_attachment_file_name :shot, :matches => [/./]
````

However, that does not solve my problem, as the problem is not that Paperclip is rejecting files without filename extensions but rather than it is rejecting image files that don't have image filename extensions.

**Comment by maclover7** [comment]
Hi @snoblenet ! Is this still an issue for you in Paperclip; I know this issue is from approximately 1 year ago. If it is still an issue, would you be willing to send in a PR to solve the problem? Thanks!

**Comment by snoblenet** [comment]
I @maclover7 -- no I moved to CarrierWave for a number of reasons including this one.

**Comment by snappa** [comment]
@maclover7, I just noticed an email marking issue as closed.  I had a question in my workaround as to whether this was the right approach or if this would cause me problems later on down the road.  Specifically, I'm using the following to get my content_type validation to pass for a json file:

Paperclip.options[:content_type_mappings] = {
  :json => "text/plain"
}

This works because it matches the results of the "file -b --mime" command run by Paperclip on the uploaded file. I will be adding more upload file types to this application over time and want to make sure I'm doing the right thing.

**Comment by mehulkar** [comment]
I'm using a similar strategy. One caveat is that the file utility returns
potentially different mine types at different versions. This made my tests
pass on my machine and fail in Travis, for example.

On Wednesday, March 11, 2015, snappa <notifications@github.com> wrote:

> @maclover7 <https://github.com/maclover7>, I just noticed an email
> marking issue as closed. I had a question in my workaround as to whether
> this was the right approach or if this would cause me problems later on
> down the road. Specifically, I'm using the following to get my content_type
> validation to pass for a json file:
>
> Paperclip.options[:content_type_mappings] = {
> :json => "text/plain"
> }
>
> This works because it matches the results of the "file -b --mime" command
> run by Paperclip on the uploaded file. I will be adding more upload file
> types to this application over time and want to make sure I'm doing the
> right thing.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/thoughtbot/paperclip/issues/1477#issuecomment-78321485>
> .
>


-- 

------
Mehul Kar
@mehulkar

**Comment by snappa** [comment]
@mehulkar that's my concern.  I'm currently working fine on my dev machine, a Heroku instance, and a CI platform running the tests so for now I think I'm safe.  At least I have specs that will catch this if things change so I guess for now that's all I can do.

**Comment by vladimeeer** [comment]
One way to skip considering filename validation in spoofing is using this workaround.. It sets filename extension to the one that was detected from file.

```
module Paperclip
  class MediaTypeSpoofDetector
    def media_types_from_name
      @media_types_from_name = supplied_media_type
    end
  end
end
```
