### ISSUE TITLE
Content spoofing validation error after upgrade from 3.5 to 4.1

### ISSUE THREAD

**Issue by SirRawlins** [thoughtbot/paperclip#1479]
Hello Guys,

I've this morning tried to upgrade paperclip from 3.5 to 4.1 to gain the security benefits however since upgrading I appear to be getting continual validation errors saying that the content of the files does not match the extension.

I'm defining the content type validation as follows:

	validates_attachment_content_type 	:file, :content_type => ['text/css']

This works absolutely fine in 3.5 however when trying to upload .css files after the upgrade I'm getting a spoofing error.

Has something changed under the hood in the way in which the mime type is detected?

Thanks,

Robert

**Comment by maclover7** [comment]
Hi @SirRawlins ! Is this still an issue for you in Paperclip; I know this issue is from approximately 1 year ago. If it is still an issue, would you be willing to send in a PR to solve the problem? Thanks!

**Comment by SirRawlins** [comment]
Hi Jon,

I abandoned the upgrade and stayed with the older version. I will try the
upgrade again soon and see if I have anymore luck.

Robert

**Comment by maclover7** [comment]
@jferris @jyurek Please close issue, problem appears to be solved.

**Comment by tute** [comment]
Will close. Further discussion on this issue should happen https://github.com/thoughtbot/paperclip/issues/1470 it seems.
