### ISSUE TITLE
Dynamic storage option based on user selection

### ISSUE THREAD

**Issue by mengqing** [thoughtbot/paperclip#1483]
Hi all, just wondering if there is any way to dynamically set the storage option based on the User selection?

Eg: the user will be given the option of where their assets will go, S3/File/SFTP etc..

Thanks

**Comment by MattMSumner** [comment]
@sikachu I know this is an old issue, but I'm looking into this know. I'm attempting the `Proc` suggestion as follows:

```rb
  has_attached_file(
    :attachment,
    storage: Proc.new { |this| something here }
  )
```

But it appears that won't work. I guess the best option moving forward would be `STI`?
