### ISSUE TITLE
[4.1.1] undefined method `before_upload_post_process'

### ISSUE THREAD

**Issue by jhaagmans** [thoughtbot/paperclip#1493]
I've just upgraded my live environment from 3.5.1 to 4.1.1 and added the required `validates_attachment_content_type`, but after that my application (running Rails 3.2.13 on Phusion Passenger on nginx) fails to start with the following message:

    undefined method `before_upload_post_process' for #<Class:0x0000000351a088> (NoMethodError)

Stack trace as follows:

      /home/user/.gem/ruby/1.9.1/gems/activerecord-3.2.13/lib/active_record/dynamic_matchers.rb:55:in `method_missing'
      /home/user/.gem/ruby/1.9.1/gems/paperclip-3.5.1/lib/paperclip/validators.rb:58:in `create_validating_before_filter'
      /home/user/.gem/ruby/1.9.1/gems/paperclip-3.5.1/lib/paperclip/validators.rb:51:in `block in validate_before_processing'
      /home/user/.gem/ruby/1.9.1/gems/paperclip-3.5.1/lib/paperclip/validators.rb:49:in `each'
      /home/user/.gem/ruby/1.9.1/gems/paperclip-3.5.1/lib/paperclip/validators.rb:49:in `validate_before_processing'
      /home/user/.gem/ruby/1.9.1/gems/paperclip-3.5.1/lib/paperclip/validators/attachment_content_type_validator.rb:78:in `validates_attachment_content_type'

Removing the validation gets rid of the error (but generates an error for new uploads). What did I miss?

**Comment by maclover7** [comment]
Hi @jhaagmans ! Is this still an issue for you in Paperclip; I know this issue is from approximately 1 year ago. If it is still an issue, can you please provide the code that's causing you the error? Thanks!

**Comment by mhink** [comment]
I was having the same issue, but I was able to fix it by putting the "validates_attachment_*" lines BELOW the "has_attached_file" call.  Which makes sense- I guess the hooks which NoMethodError is complaining about probably don't exist until :has_attached_file creates them.

**Comment by tute** [comment]
That makes sense. If it's not clear in the docs a PR to the README would be good. Thank you!
