### ISSUE TITLE
[4.1.1] Paperclip Gerenator - No Method Error

### ISSUE THREAD

**Issue by brunotiago** [thoughtbot/paperclip#1495]
Hi,

When I run the command "rails g paperclip user photo" I have this message:

/usr/local/Cellar/ruby/2.1.1/lib/ruby/gems/2.1.0/gems/railties-4.0.4/lib/rails/generators/actions/create_migration.rb:13:in `migration_file_name': protected method`migration_file_name' called for #PaperclipGenerator:0x007fb3c6494c20 (NoMethodError)

Can somebody help me ?

**Comment by tosterbuhr** [comment]
Thanks that worked @marcioj

**Comment by aspiringpro-grammar** [comment]
Many thanks @marcioj!

**Comment by joshdance** [comment]
Had same issue, wasn't working, realized I was on old version of the gem. 

`gem 'paperclip', '~> 4.2'` fixed it for me.

**Comment by ladykillington** [comment]
yes, gem 'paperclip', '~> 4.2' fixed it for me.

I wish there's a readme for anticipated errors

**Comment by khaderg** [comment]
I looked up the latest version of paperclip from https://rubygems.org and its 4.3.0 then in my Gemfile i changed it to gem 'paperclip' , '~> 4.3' instead of gem 'paperclip' , '~>3.0' and  then ran bundle install and so i feel Happy i solved the problem,

**Comment by lennartsvanberg** [comment]
It worked for me as well. GREAT!

**Comment by jacurtis** [comment]
Just chiming in -- this worked for me as well, thank you.

**Comment by poidog44** [comment]
Thanks- fixed my issue as well

**Comment by ianfriedel** [comment]
That was the perfect fix! Thank you!

**Comment by afyacy** [comment]
gem 'paperclip', '~> 4.2' was the perfect solution to my problem, thanks.
