### ISSUE TITLE
open-uri is not redirecing http to https

### ISSUE THREAD

**Issue by aug-riedinger** [thoughtbot/paperclip#1501]
I'm facing an issue very well described in this stackoverflow post:
http://stackoverflow.com/questions/10013293/open-uri-is-not-redirecing-http-to-https

Basically, there is a bug in the `open-uri` ruby library.
There is a way around this by using this gem: https://github.com/jaimeiniesta/open_uri_redirections

But since the open-uri library is called inside the paperclip gem, I thought of forking the paperclip gem, but then I have troubles installing my bundle. Here are some short extracts of it to get an idea:

```
bundle install
Fetching gem metadata from https://rubygems.org/......
Fetching gem metadata from https://rubygems.org/..
Resolving dependencies...
You have requested:
  cucumber ~> 1.2.1

The bundle currently has cucumber locked at 1.3.14.
Try running `bundle update cucumber`

bundle update cucumber
Fetching gem metadata from https://rubygems.org/......
Fetching gem metadata from https://rubygems.org/..
Resolving dependencies...
You have requested:
  nokogiri ~> 1.5.0

The bundle currently has nokogiri locked at 1.6.1.
Try running `bundle update nokogiri`

bundle update nokogiri
Fetching gem metadata from https://rubygems.org/......
Fetching gem metadata from https://rubygems.org/..
Resolving dependencies...
You have requested:
  cucumber ~> 1.2.1

The bundle currently has cucumber locked at 1.3.14.
Try running `bundle update cucumber`
```

I'm confused there. Apparently 2 versions of `nokogiri` are required and not compatible.

So my questions are:
- How can I bundle install those?
OR
- Is there a more recent version of paperclip that solved the issue? 

Thanks for support!

**Comment by maclover7** [comment]
Hi @aug-riedinger ! Is this still an issue for you in Paperclip; I know this issue is from approximately 1 year ago. If it is still an issue, can you please provide the code that's causing you the error? Thanks!

**Comment by tute** [comment]
This is not an issue any longer. If it continues to be a problem to you, @aug-riedinger, please tell us how can we reproduce it and let's work on it. Thanks for your report!
