### ISSUE TITLE
Discussion about content type detection

### ISSUE THREAD

**Issue by mmustala** [thoughtbot/paperclip#1506]
I find it a bit confusing how content type validations are handled currently. Current way is to use the operating systems file command to detect the content type, which forces us to write OS dependent code.

For example I have an application that receives email messages and attachments. I have a MailReceiver class that picks some attachments from the emails based on their content type using a code

    message.attachments.each do |attachment|
      if attachment.content_type.match('application/vnd.ms-excel')
        save_attachment(attachment)
      end
    end

save_attachment saves the attachment as a paperclip attachment. Then paperclip does its own content_type validation and originally I had there only:

    validates_attachment_content_type :file, :content_type => %w(application/vnd.ms-excel)

And that worked for a while. Then I deployed my application to a Debian server and surprised that I was getting content_type validation errors. Errors came because my servers file command returns 'application/msword' for an Excel file. So I needed to add that into allowed content types in paperclip validation. 

Notice that I have not needed to adjust the content_type check in the MailReceiver. It still uses 'application/vnd.ms-excel'. I have not studied how Mail gem is determining the content_type but it apparently uses a different strategy for it.

I'm just wondering if I some day change server and I'm again getting weird errors because of a file command returning something else. It looks like it is completely in the hands of the people who write these packages. 

I don't like my application to be so coupled with the server and hope that these content type checks could be done using Ruby code. Even if that means adding another gem dependency. At least then I could be sure that Paperclip behaves the same on every server where I deploy my application.

**Comment by maclover7** [comment]
Is this fixed with #1839 ?

**Comment by tute** [comment]
Ping @mmustala: is this fixed now?

**Comment by jyurek** [comment]
@mmustala Also there is now the option to turn off spoof checks, with the `validate_media_type: false` option.

**Comment by tute** [comment]
> Also there is now the option to turn off spoof checks, with the validate_media_type: false option.

Is that unsafe, or is it sometimes ok? If it is unsafe, we shouldn't provide the option?

**Comment by jyurek** [comment]
The intent is to be "secure by default", but since the option gets in the way of some people using it, as we see here, there's an option to turn it off.

**Comment by tute** [comment]
@mmustala paperclip now uses mimemagick, which might help with the problem you were having.

Since it's been two years since your last activity on this issue, I hope it's working well now for you. If it's not, let us know and we'll continue the discussion. Thanks!

**Comment by mmustala** [comment]
Hi. I have learned to live with it. And I'm using `validates_attachment_content_type :file, content_type: /.*/` in all those cases where I'm handling a file from trusted source. But it is good that paperclip now uses mimemagick. Then we can be sure that the mime type for one file is the same in all platforms and servers. Thanks!
