### ISSUE TITLE
Added :preserve_files option for playing well with soft-delete plugins

### ISSUE THREAD

**Issue by glappen** [thoughtbot/paperclip#152]
I forked and added a :preserve_files option so paperclip can get along with soft-delete plugins like acts_as_paranoid.  When the model is destroyed, the files stay around.  The default is obviously not to preserve files, so it's something non-standard you have to enable. Let me know if you would consider integrating this, or if there's any issues with the implementation.

Here's the changes:  http://github.com/glappen/paperclip/commit/fd622709099feb68e02ba37631221291e9860386
Thanks!

**Comment by jrochkind** [comment]
Anyone know the answer to @djiang 's old question, how does :preserve_files differ from :keep_old_files? I found this googling trying to figure that out, about to dive into the source to see if I can figure it out.
