### ISSUE TITLE
ContentType detector backends

### ISSUE THREAD

**Issue by miyagawa** [thoughtbot/paperclip#1523]
I had a semi-urgent need to run paperclip based Rails apps on a linux CI host without `file` command installed. 

While I could ask the admin to install them, I chose to implement (mostly for a demo purpose) a monkey patch to override the `file` command with [the mimemagic gem](https://rubygems.org/gems/mimemagic) and it turned out to work fine: [paperclip-mimemagic](https://github.com/miyagawa/paperclip-mimemagic)

If there were a proper hook to register a separate backend to detect content types for a file, i could write it as a proper plugin rather than a monkey patch. I wonder if there's any interest in it.

**Comment by maclover7** [comment]
Is this fixed with #1839 ?

**Comment by tute** [comment]
ping @sikachu: is this fixed now?

**Comment by tute** [comment]
The `mimemagic` gem and `file` command are necessary for security purposes. You can disable them if you know what you are doing to get your desired behavior. This doesn't seem to be an issue in paperclip anymore, so I'm closing this issue. Thanks for reporting!
