### ISSUE TITLE
Paperclip::Storage::Fog not requiring fog gem when extended.

### ISSUE THREAD

**Issue by palanglung** [thoughtbot/paperclip#1528]
This set of [Loc] never executed caused Fog always defined as ```Paperclip::Storage::Fog``` . changing to ```defined?(::Fog)``` might be help.

edit: i will send PR soon.

[Loc]:https://github.com/thoughtbot/paperclip/blob/master/lib/paperclip/storage/fog.rb#L38-43

**Comment by maclover7** [comment]
Hi @palanglung ! Is this still an issue for you in Paperclip; I know this issue is from approximately 1 year ago. If it is still an issue, would you be willing to send in a PR to solve the problem? Thanks!

**Comment by palanglung** [comment]
@maclover7 feel sorry about this. i was forgot this issue. because i just mongkey patching and solve the issue so i forgot to create PR. if its not solved yet i will create PR soon nearly this weeks.

**Comment by maclover7** [comment]
All clear then? @mike-burns @jyurek @jferris please close issue, problem appears resolved

**Comment by tute** [comment]
@sikachu do we need the PR that got you excited, or we can close this issue? :)
