### ISSUE TITLE
`file` detects wrong mime type for Open Office XML files

### ISSUE THREAD

**Issue by scpike** [thoughtbot/paperclip#1530]
Paperclip relies on the `file` command to detect the mime type of uploads, rather than the extension, since the extension is provided by the user. Unfortunately `file` reports "application/zip;" for pptx, docx, and xlsx files, so Paperclip thus stores the files with content_type = 'application/zip' rather than the correct mime types.  These files are technically zip files, but that's just an implementation detail that users don't care about - they want the files to open in the right programs. 

These seem like common enough file types that it's worth figuring out a solution. I'm happy to help with the code.

**Comment by maclover7** [comment]
Hi everybody! Is this still an issue for you in Paperclip; I know this issue is from approximately 1 year ago. If it is still an issue, would you be willing to send in a PR to solve the problem? Thanks!

**Comment by scpike** [comment]
@maclover7 this is still an issue for me, and I've been using my fork (https://github.com/scpike/paperclip/tree/ooxml-content-types) for a while. Looks like @jeremywadsack rebased that on top of the latest code and submitted a PR. That code might not pass CI, though, because I'm also using a mimemagic fork.

**Comment by jeremywadsack** [comment]
@scpike I opened a PR from my fork because it was based on newer paperclip (but you are still marked as author). 

Thanks for the reminder about the mimemagic fork. I had forgotten that. I updated the PR to include that in the `Gemfile` which I hope fixes the CI errors in Travis. That said, I wonder is this is really the best solution or if we should use that fork in the `gemspec`.

**Comment by scpike** [comment]
We should get the changes into mimemagic itself, probably, but I haven't submitted a PR there. Mimemagic is based off of the freedesktop.org file type detection, so I tried to get the openxml stuff merged at the source, but they haven't accepted my patch (for reasonable reasons): https://bugs.freedesktop.org/show_bug.cgi?id=78797.

**Comment by jeremywadsack** [comment]
@scpike, yes, better to get the mimemagic changes there rather than in a fork. I'm using your mimemagic fork in production with no other changes, so it seems that would be the best route. It's simpler than the upstream patch which isn't going to fly anyway.

FWIW, though, adding your fork to the Gemfile on #1807  didn't help the Travis builds. Can you take a look at that and see if that's related to mimemagic or something else? I'm not really that familiar with this code.

**Comment by maclover7** [comment]
@jferris @jyurek Please close issue, problem appears to be solved.

**Comment by anykeyh** [comment]
For any interest, as mentionned above, this is a part of my deployment script:

```
exclusion_list_from_docker=$(cat .dockerignore | grep -v '^ *$' | awk -v 's=--exclude=' '{print s $0}' | xargs)
tar --exclude=./bin --exclude=deploy.tar $exclusion_list_from_docker -cf deploy.tar .
```

I exclude all the file ignored in my `.dockerfile` (preventing to pack '.git' and so on), and I've added
some specifics exclusions ( in my case, the bin folder contains packed apps which are not changing a lot but cost 300Mb+ of binary... )

Then in my docker file:

```
# ...
# Bin will be cached and won't be recreated everytime I change one line of code <3
ADD ./bin /bin
#
RUN mkdir -p $APP_HOME
ADD ./deploy.tar $APP_HOME
WORKDIR $APP_HOME
# ...
```

**Comment by johnpaulh** [comment]
I too faced the same issue even with the latest paperclip 5.0.0. gem. My case is i read a docx from paperclip attachment into a Tempfile replace some placeholders in it and create a new attachment from it. After uploading the attachment(with placeholders replaced) when i try to download that in my app I used face the above docx being downloaded as zip issue.On analysis I found that whenever this issue occurs the zip file entries are in the wrong order 
for eg: 

```
word/header1.xml
word/header2.xml
word/footer1.xml
word/numbering.xml
word/settings.xml
word/fontTable.xml
word/_rels/fontTable.xml.rels
word/styles.xml
word/document.xml
word/_rels/document.xml.rels
_rels/.rels
word/fonts/OldStandardTT-regular.ttf
word/fonts/PTSerif-bold.ttf
word/fonts/OldStandardTT-bold.ttf
word/fonts/PTSerif-italic.ttf
word/fonts/PTSerif-boldItalic.ttf
word/fonts/OldStandardTT-italic.ttf
word/media/image01.jpg
word/fonts/PTSerif-regular.ttf
[Content_Types].xml
```

but the correct zip file entries order should be something that starts almost always with
`[Content_Types].xml
`
