### ISSUE TITLE
Can't mass-assign protected attributes: attach

### ISSUE THREAD

**Issue by bigtunacan** [thoughtbot/paperclip#1540]
I'm on Rails 3.2.17, Paperclip 4.1.1 using the strong_parameters gem as we prepare to upgrade to Rails 4.

https://github.com/rails/strong_parameters

I have tried even opening up completely using params.permit!, but still get the mass assignment error when trying to add attachments. I believe this may have something to do with the fact that attach is not actually an attribute on the nested association model?

**Comment by maclover7** [comment]
Hi @bigtunacan ! Is this still an issue for you in Paperclip; I know this issue is from approximately 1 year ago. If it is still an issue, can you please provide the code that's causing you the error? Thanks!
