### ISSUE TITLE
Devkit requirement undocumented

### ISSUE THREAD

**Issue by ezuhaib** [thoughtbot/paperclip#1543]
I on Windows 7 and hadn't added my devkit to system PATH because the path is automagically enhanced when building gems. But lately I discovered that paperclip needs devkit binaries in order to work. Without devkit, I was getting this error while trying to upload an image file:

    has an extension that does not match its contents

this is probably due to:
https://github.com/thoughtbot/paperclip/blob/master/lib/paperclip/media_type_spoof_detector.rb#L63

please do either of these:

1. Document devkit requirement, and it's addition to PATH, in readme.md in the Installation section.
1. Return better error if a required binary from devkit is not found, rather than the above misleading one.

**Comment by maclover7** [comment]
@jferris @jyurek Please close issue, problem appears to be solved.

**Comment by tute** [comment]
Fixed in attached PR. Thank you all!
