### ISSUE TITLE
new version of imagemagick on Mountain Lion causes NilClass bug

### ISSUE THREAD

**Issue by ianks** [thoughtbot/paperclip#1548]
ImageMagick installed with Homebrew on Mountain Lion causes a NoMethodError. 

```
Dyld Error Message:
  Library not loaded: /usr/local/lib/liblzma.5.dylib
  Referenced from: /usr/local/bin/identify
  Reason: image not found
```

Not sure if this is a known issue, if not I will investigate further with better bug report.

**Comment by maclover7** [comment]
Hi @ianks ! Is this still an issue for you in Paperclip; I know this issue is from approximately 1 year ago. If it is still an issue, can you please document this in the wiki? Thanks!

**Comment by ianks** [comment]
I have
