### ISSUE TITLE
Resumable uploads?

### ISSUE THREAD

**Issue by MarkMurphy** [thoughtbot/paperclip#1560]
#### Use Case

[http://tus.io/][tus] does a pretty good job of explaining the problem, everyone reading this should check out that site.

**Excerpts from http://tus.io/:**

> The internet has a problem. Devices are getting better cameras, so user generated files are getting
> bigger and bigger. Unfortunately this makes uploading them reliably much harder as well, especially
> when using the tiny mobile tubes provided by greedy network operators. The problem is that most 
> applications are not up to the challenge, meaning that millions of cat images and videos are lost due 
> to network errors every year!

&bull;

> Users want to share more and more photos and videos. But mobile networks are fragile. 
> Platform APIs are a mess. Every project builds its own file uploader. A thousand one week projects 
> that barely work, when all we need is one real project, done right.

#### User Story
 
In my case, we've built an iOS application that uploads large high definition videos to a server. If an upload fails or is incomplete (maybe because the user's device backgrounded the application, they lose their connection, etc.) we don't want the upload to have to start from scratch. This would allow users to begin uploading a video from say a coffee shop, leave the coffee shop (thereby pausing the upload) and then resume the upload from home at a later time picking up where it left off. 

**Examples of Resumable Uploads**

- [Dropbox API][dropbox]
- [Vimeo API][vimeo]
- [Amazon Web Services][aws]
- [TUS Protocol][tus]

[dropbox]: https://www.dropbox.com/developers/core/docs#chunked-upload
[vimeo]: https://developer.vimeo.com/api/upload#http-put-uploading
[aws]: http://docs.aws.amazon.com/AmazonS3/latest/dev/UsingRESTAPImpUpload.html
[tus]: http://tus.io/

**Comment by maclover7** [comment]
Hi @MarkMurphy ! Is this still an issue for you in Paperclip; I know this issue is from approximately 1 year ago. If it is still an issue, would you be willing to send in a PR to solve the problem? Thanks!

**Comment by tute** [comment]
I believe it does not. @jyurek?

**Comment by tute** [comment]
I don't think this is easily done in the gem. Happy to discuss how can we implement it! Thanks for your question.

**Comment by MarkMurphy** [comment]
I'd love to tell you about how we've implemented this and what role Paperclip has played in it. There's lots of room for improvement. Is this where you'd like to have the conversation?

**Comment by tute** [comment]
A new page in https://github.com/thoughtbot/paperclip/wiki#commonly-needed-functionality seems like a great place to publish that knowledge. Thank you so much!

**Comment by tute** [comment]
If you'd rather discuss, we might reopen and continue here.

**Comment by MarkMurphy** [comment]
@tute I think an open discussion would be more appropriate.

**Comment by MarkMurphy** [comment]
So here's what we use for our api currently:
https://gist.github.com/MarkMurphy/f843566780979174f270

I've also added the documentation for it there.

**Comment by tute** [comment]
That is great, thank you! Do you have tests for that code?

**Comment by MarkMurphy** [comment]
@tute I do not yet, no. It's still very much experimental but that being said we are using it in production :blush: without any issues. Also, as I said above, I think there's lots of room for improvement.

**Comment by tute** [comment]
:+1:

**Comment by MarkMurphy** [comment]
You might also be inspired by this server side implementation of the TUS protocol: https://github.com/picocandy/rubytus

**Comment by MarkMurphy** [comment]
Here's what I don't like about our implementation:

- The file is copied twice: Once the file is uploaded to our server we then hand it off to paperclip to process and upload to Amazon S3. This may be unavoidable but maybe there's a way to make this more efficient in terms of time eg. proxy the upload to S3 right off the bat instead of storing it locally first or upload the chunks to S3 in parallel as they come to the server.
- To commit the upload involves having a model watch for the assignment of an upload id to it (eg. :video_uoload_id) and then call Upload.assign_to_attachment(upload_id (eg. video_upload_id), self (eg. Video Instance), :attchment_name (eg. :attachment)). Not sure how else to accomplish this, maybe it's as simple as turning this functionality into a model concern or maybe there's a totally different cleaner way.

**Comment by MarkMurphy** [comment]
Another improvement that could be made is to checksum each chunk instead of or in addition to the file as it's modified. Keeping a record of each chunk the way AWS does would also be handy.

**Comment by jyurek** [comment]
@MarkMurphy That looks really awesome, but considering we're piggybacking on Rails/ActiveRecord, there's, sadly, really not room in Paperclip for that kind of code. I would absolutely polish it and publish it as its own gem, though. I'm going to close this. If you want our input on this code and perhaps help making it better, make a new github project and drop a link here. That looks really cool.
