### ISSUE TITLE
Deprecation warnings in RSpec 3

### ISSUE THREAD

**Issue by lucascaton** [thoughtbot/paperclip#1568]
Hello there.

I wasn't able to find a similar opened issue, so I'm creating this one.

When I'm running my tests with Paperclip `4.1.1` and RSpec `2.99` or `3.0.0`, I'm getting the following deprecation warning:

```
Paperclip::Shoulda::Matchers::HaveAttachedFileMatcher implements a legacy RSpec matcher
protocol. For the current protocol you should expose the failure messages
via the `failure_message` and `failure_message_when_negated` methods.
```

**Comment by maclover7** [comment]
@jferris @jyurek Please close issue, problem appears to be solved.
