### ISSUE TITLE
Destroy created folders when record gets destroyed

### ISSUE THREAD

**Issue by johannesluedke** [thoughtbot/paperclip#1571]
When Paperclip creates a new folder structure ..:id/:style/ and the record with the attachments gets deleted later on, it deletes the attachments correctly, but it should also delete the :style and :id folder. If one has millions of records, this can be a  problem due to subfolder per folder limitations of *nix tools.

Paperclip 3.5.1

**Comment by maclover7** [comment]
Hi @johannesluedke ! Is this still an issue for you in Paperclip; I know this issue is from approximately 1 year ago. If it is still an issue, can you please provide the code that's causing you the error? Thanks!

**Comment by johannesluedke** [comment]
We switched to using :id_partition to avoid the subfolder per folder limitations.. So in the moment the original issue isn't really a problem for our application any more

**Comment by maclover7** [comment]
@jferris @jyurek Please close issue, problem appears to be solved.

**Comment by tute** [comment]
Should we still address the original issue report, though? cc @jyurek @sikachu

**Comment by hajder** [comment]
I think a note in wiki/Readme should be enough to address this

**Comment by tute** [comment]
Also, this issue needs more info, as it doesn't specify affected versions. If it's still useful, I'll happily merge a note in the README (or you can go ahead and edit the wiki for this project). Thank you all!
