### ISSUE TITLE
Javascript tests can't see my attached images; raising an ActionController::RoutingError

### ISSUE THREAD

**Issue by georgemillo** [thoughtbot/paperclip#1573]
When running RSpec tests with `js:true`, any feature spec which visits a page containing a Paperclip-attached image will fail with a `ActionController::RoutingError`.

Here's a minimal setup I managed to replicate the error with in my app:

    model DataSource
       has_attached_file :icon
       (validations etc)
    end

view:

    # @data_source is set by the controller, obviously
    <% image_tag @data_source.icon.url %>

spec:

    require "spec_helper"

    describe "example failing spec", js: true do
      let(:icon_file) { File.open("spec/support/example_icon.png") }
      let!(:data_source) { create(:data_source, icon: icon_file) } # Uses FactoryGirl

      before { visit data_source_path }

      it "this spec fails!" do
        expect(true).to be_true
      end
    end

when I run this I get the following error:

     Failure/Error: Unable to find matching line from backtrace
     ActionController::RoutingError:
       No route matches [GET] "/system/marketplaces/icons/000/000/001/original/example_icon.png"
     # /Users/george/.rvm/gems/ruby-2.1.1/gems/actionpack-4.1.1/lib/action_dispatch/middleware/debug_exceptions.rb:21:in `call'
     # /Users/george/.rvm/gems/ruby-2.1.1/gems/actionpack-4.1.1/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
     # /Users/george/.rvm/gems/ruby-2.1.1/gems/railties-4.1.1/lib/rails/rack/logger.rb:38:in `call_app'
     # /Users/george/.rvm/gems/ruby-2.1.1/gems/railties-4.1.1/lib/rails/rack/logger.rb:20:in `block in call'
     # /Users/george/.rvm/gems/ruby-2.1.1/gems/activesupport-4.1.1/lib/active_support/tagged_logging.rb:68:in `block in tagged'
     # /Users/george/.rvm/gems/ruby-2.1.1/gems/activesupport-4.1.1/lib/active_support/tagged_logging.rb:26:in `tagged'
     # /Users/george/.rvm/gems/ruby-2.1.1/gems/activesupport-4.1.1/lib/active_support/tagged_logging.rb:68:in `tagged'
     # /Users/george/.rvm/gems/ruby-2.1.1/gems/railties-4.1.1/lib/rails/rack/logger.rb:20:in `call'
     # /Users/george/.rvm/gems/ruby-2.1.1/gems/actionpack-4.1.1/lib/action_dispatch/middleware/request_id.rb:21:in `call'
     # /Users/george/.rvm/gems/ruby-2.1.1/gems/rack-1.5.2/lib/rack/methodoverride.rb:21:in `call'
     # /Users/george/.rvm/gems/ruby-2.1.1/gems/rack-1.5.2/lib/rack/runtime.rb:17:in `call'
     # /Users/george/.rvm/gems/ruby-2.1.1/gems/activesupport-4.1.1/lib/active_support/cache/strategy/local_cache_middleware.rb:26:in `call'
     # /Users/george/.rvm/gems/ruby-2.1.1/gems/actionpack-4.1.1/lib/action_dispatch/middleware/static.rb:64:in `call'
     # /Users/george/.rvm/gems/ruby-2.1.1/gems/rack-1.5.2/lib/rack/sendfile.rb:112:in `call'
     # /Users/george/.rvm/gems/ruby-2.1.1/gems/railties-4.1.1/lib/rails/engine.rb:514:in `call'
     # /Users/george/.rvm/gems/ruby-2.1.1/gems/railties-4.1.1/lib/rails/application.rb:144:in `call'
     # /Users/george/.rvm/gems/ruby-2.1.1/gems/rack-1.5.2/lib/rack/builder.rb:138:in `call'
     # /Users/george/.rvm/gems/ruby-2.1.1/gems/rack-1.5.2/lib/rack/urlmap.rb:65:in `block in call'
     # /Users/george/.rvm/gems/ruby-2.1.1/gems/rack-1.5.2/lib/rack/urlmap.rb:50:in `each'
     # /Users/george/.rvm/gems/ruby-2.1.1/gems/rack-1.5.2/lib/rack/urlmap.rb:50:in `call'
     # /Users/george/.rvm/gems/ruby-2.1.1/gems/capybara-2.1.0/lib/capybara/server.rb:19:in `call'
     # /Users/george/.rvm/gems/ruby-2.1.1/gems/rack-1.5.2/lib/rack/handler/webrick.rb:60:in `service'
     # /Users/george/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/webrick/httpserver.rb:138:in `service'
     # /Users/george/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/webrick/httpserver.rb:94:in `run'
     # /Users/george/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/webrick/server.rb:295:in `block in start_thread'

If I add the block `after { puts "test" }`, I see the word "test" get output before the spec fails (i.e. before the red "F" gets printed), so it looks the spec within the `it` block actually passes (as you'd expect the line `expect(true).to be_true` to do!), but something is happening afterwards causing the above error.

I get this issue using both the Selenium and Capybara::WebkitDrivers, so I don't think the problem is at the RSpec end. (Although if I remove `js: true`, the specs work as you'd expect them to.)

My Gemfile.lock:

    GEM
      remote: https://rubygems.org/
      specs:
        actionmailer (4.1.1)
          actionpack (= 4.1.1)
          actionview (= 4.1.1)
          mail (~> 2.5.4)
        actionpack (4.1.1)
          actionview (= 4.1.1)
          activesupport (= 4.1.1)
          rack (~> 1.5.2)
          rack-test (~> 0.6.2)
        actionview (4.1.1)
          activesupport (= 4.1.1)
          builder (~> 3.1)
          erubis (~> 2.7.0)
        active_model_serializers (0.8.1)
          activemodel (>= 3.0)
        activemodel (4.1.1)
          activesupport (= 4.1.1)
          builder (~> 3.1)
        activerecord (4.1.1)
          activemodel (= 4.1.1)
          activesupport (= 4.1.1)
          arel (~> 5.0.0)
        activesupport (4.1.1)
          i18n (~> 0.6, >= 0.6.9)
          json (~> 1.7, >= 1.7.7)
          minitest (~> 5.1)
          thread_safe (~> 0.1)
          tzinfo (~> 1.1)
        addressable (2.3.5)
        annotate (2.6.1)
          activerecord (>= 2.3.0)
          rake (>= 0.8.7)
        arel (5.0.1.20140414130214)
        attr_encrypted (1.3.2)
          encryptor (>= 1.3.0)
        aws-sdk (1.29.1)
          json (~> 1.4)
          nokogiri (>= 1.4.4)
          uuidtools (~> 2.1)
        bcrypt-ruby (3.1.2)
        builder (3.2.2)
        capybara (2.1.0)
          mime-types (>= 1.16)
          nokogiri (>= 1.3.3)
          rack (>= 1.0.0)
          rack-test (>= 0.5.4)
          xpath (~> 2.0)
        capybara-webkit (1.1.1)
          capybara (>= 2.0.2, < 2.2.0)
          json
        childprocess (0.5.3)
          ffi (~> 1.0, >= 1.0.11)
        climate_control (0.0.3)
          activesupport (>= 3.0)
        cocaine (0.5.4)
          climate_control (>= 0.0.3, < 1.0)
        coffee-rails (4.0.1)
          coffee-script (>= 2.2.0)
          railties (>= 4.0.0, < 5.0)
        coffee-script (2.2.0)
          coffee-script-source
          execjs
        coffee-script-source (1.5.0)
        columnize (0.8.9)
        crack (0.4.2)
          safe_yaml (~> 1.0.0)
        css_parser (1.3.5)
          addressable
        database_cleaner (1.2.0)
        debugger (1.6.6)
          columnize (>= 0.3.1)
          debugger-linecache (~> 1.2.0)
          debugger-ruby_core_source (~> 1.3.2)
        debugger-linecache (1.2.0)
        debugger-ruby_core_source (1.3.2)
        devise (3.2.2)
          bcrypt-ruby (~> 3.0)
          orm_adapter (~> 0.1)
          railties (>= 3.2.6, < 5)
          thread_safe (~> 0.1)
          warden (~> 1.2.3)
        diff-lcs (1.2.5)
        encryptor (1.3.0)
        erubis (2.7.0)
        ethon (0.7.0)
          ffi (>= 1.3.0)
        execjs (2.0.2)
        factory_girl (4.4.0)
          activesupport (>= 3.0.0)
        factory_girl_rails (4.4.1)
          factory_girl (~> 4.4.0)
          railties (>= 3.0.0)
        faker (1.2.0)
          i18n (~> 0.5)
        ffi (1.9.3)
        figaro (0.7.0)
          bundler (~> 1.0)
          rails (>= 3, < 5)
        font-awesome-rails (4.0.3.1)
          railties (>= 3.2, < 5.0)
        friendly_id (5.0.3)
          activerecord (>= 4.0.0)
        hike (1.2.3)
        hirb (0.7.1)
        i18n (0.6.9)
        jasmine-core (2.0.0)
        jasmine-rails (0.6.0)
          jasmine-core (>= 1.3, < 3.0)
          phantomjs
          rails (>= 3.1.0)
          sprockets-rails
        jbuilder (1.5.3)
          activesupport (>= 3.0.0)
          multi_json (>= 1.2.0)
        jquery-rails (3.0.4)
          railties (>= 3.0, < 5.0)
          thor (>= 0.14, < 2.0)
        jquery-turbolinks (2.0.2)
          railties (>= 3.1.0)
          turbolinks
        json (1.8.1)
        json_spec (1.1.1)
          multi_json (~> 1.0)
          rspec (~> 2.0)
        launchy (2.4.2)
          addressable (~> 2.3)
        libv8 (3.16.14.3)
        mail (2.5.4)
          mime-types (~> 1.16)
          treetop (~> 1.4.8)
        mime-types (1.25.1)
        mini_portile (0.5.2)
        minitest (5.3.4)
        multi_json (1.10.1)
        nokogiri (1.6.1)
          mini_portile (~> 0.5.0)
        orm_adapter (0.5.0)
        paint (0.8.6)
        paperclip (4.1.1)
          activemodel (>= 3.0.0)
          activesupport (>= 3.0.0)
          cocaine (~> 0.5.3)
          mime-types
        paypal-sdk-core (0.2.8)
          multi_json (~> 1.0)
          xml-simple
        paypal-sdk-merchant (1.114.0)
          paypal-sdk-core (~> 0.2.7)
        pg (0.17.1)
        phantomjs (1.9.7.0)
        polyglot (0.3.4)
        rack (1.5.2)
        rack-test (0.6.2)
          rack (>= 1.0)
        rack_session_access (0.1.1)
          builder (>= 2.0.0)
          rack (>= 1.0.0)
        railroady (1.1.1)
        rails (4.1.1)
          actionmailer (= 4.1.1)
          actionpack (= 4.1.1)
          actionview (= 4.1.1)
          activemodel (= 4.1.1)
          activerecord (= 4.1.1)
          activesupport (= 4.1.1)
          bundler (>= 1.3.0, < 2.0)
          railties (= 4.1.1)
          sprockets-rails (~> 2.0)
        rails_12factor (0.0.2)
          rails_serve_static_assets
          rails_stdout_logging
        rails_serve_static_assets (0.0.2)
        rails_stdout_logging (0.0.3)
        railties (4.1.1)
          actionpack (= 4.1.1)
          activesupport (= 4.1.1)
          rake (>= 0.8.7)
          thor (>= 0.18.1, < 2.0)
        rake (10.3.2)
        ref (1.0.5)
        roadie (3.0.0.pre1)
          css_parser (~> 1.3.4)
          nokogiri (~> 1.6.0)
        rspec (2.14.1)
          rspec-core (~> 2.14.0)
          rspec-expectations (~> 2.14.0)
          rspec-mocks (~> 2.14.0)
        rspec-core (2.14.7)
        rspec-expectations (2.14.4)
          diff-lcs (>= 1.1.3, < 2.0)
        rspec-mocks (2.14.4)
        rspec-rails (2.14.1)
          actionpack (>= 3.0)
          activemodel (>= 3.0)
          activesupport (>= 3.0)
          railties (>= 3.0)
          rspec-core (~> 2.14.0)
          rspec-expectations (~> 2.14.0)
          rspec-mocks (~> 2.14.0)
        rubyzip (1.1.3)
        safe_yaml (1.0.3)
        sass (3.3.4)
        sass-rails (4.0.1)
          railties (>= 4.0.0, < 5.0)
          sass (>= 3.1.10)
          sprockets-rails (~> 2.0.0)
        selenium-webdriver (2.41.0)
          childprocess (>= 0.5.0)
          multi_json (~> 1.0)
          rubyzip (~> 1.0)
          websocket (~> 1.0.4)
        shoulda-matchers (2.6.1)
          activesupport (>= 3.0.0)
        simplecov (0.7.1)
          multi_json (~> 1.0)
          simplecov-html (~> 0.7.1)
        simplecov-html (0.7.1)
        spring (1.1.2)
        spring-commands-rspec (1.0.2)
          spring (>= 0.9.1)
        sprockets (2.12.1)
          hike (~> 1.2)
          multi_json (~> 1.0)
          rack (~> 1.0)
          tilt (~> 1.1, != 1.3.0)
        sprockets-rails (2.0.1)
          actionpack (>= 3.0)
          activesupport (>= 3.0)
          sprockets (~> 2.8)
        therubyracer (0.12.0)
          libv8 (~> 3.16.14.0)
          ref
        thor (0.19.1)
        thread_safe (0.3.4)
        tilt (1.4.1)
        treetop (1.4.15)
          polyglot
          polyglot (>= 0.3.1)
        turbolinks (2.0.0)
          coffee-rails
        typhoeus (0.6.8)
          ethon (>= 0.7.0)
        tzinfo (1.2.0)
          thread_safe (~> 0.1)
        uglifier (2.4.0)
          execjs (>= 0.3.0)
          json (>= 1.8.0)
        uuidtools (2.1.4)
        vcr (2.9.0)
        warden (1.2.3)
          rack (>= 1.0)
        webmock (1.17.4)
          addressable (>= 2.2.7)
          crack (>= 0.3.2)
        websocket (1.0.7)
        wirb (1.0.2)
          paint
        xml-simple (1.1.3)
        xpath (2.0.0)
          nokogiri (~> 1.3)

    PLATFORMS
      ruby

    DEPENDENCIES
      active_model_serializers
      annotate
      attr_encrypted
      aws-sdk
      capybara (= 2.1.0)
      capybara-webkit (= 1.1.1)
      coffee-rails
      coffee-script-source (= 1.5.0)
      database_cleaner
      debugger (= 1.6.6)
      devise
      execjs
      factory_girl_rails
      faker (~> 1.2.0)
      figaro
      font-awesome-rails
      friendly_id (> 5.0.0)
      hirb
      jasmine-rails
      jbuilder
      jquery-rails
      jquery-turbolinks
      json
      json_spec
      launchy
      minitest
      nokogiri
      paperclip (~> 4.1)
      paypal-sdk-merchant
      pg
      rack_session_access
      railroady
      rails (= 4.1.1)
      rails_12factor
      roadie (= 3.0.0.pre1)
      rspec-mocks
      rspec-rails
      sass-rails
      selenium-webdriver
      shoulda-matchers (~> 2.6.1)
      simplecov (~> 0.7.1)
      spring
      spring-commands-rspec
      therubyracer
      turbolinks
      typhoeus
      uglifier
      vcr
      webmock
      wirb

What's going on?

**Comment by maclover7** [comment]
Hi @georgemillo ! Is this still an issue for you in Paperclip; I know this issue is from approximately 1 year ago. If it is still an issue, can you please provide the code that's causing you the error? Thanks!

**Comment by georgemillo** [comment]
Sorry, this is so long ago I can't even remember what app I was having the problem with! But I don't think I ever fixed it :/

Gonna close this issue as I have nothing left to add, but if anyone else manages to replicate then feel free to reopen.

**Comment by sheck** [comment]
I ran into a similar issue today, getting `ActionController::RoutingError` in my poltergeist tests. I think it was because I followed the Paperclip instructions for storing images during integration testing — and rails could not serve the images from `spec/test_files`. I fixed the issue for my by changing my `environments/test.rb` to to use this:

```
  Paperclip::Attachment.default_options[:path] = "#{Rails.root}/public/test_files/:class/:id_partition/:style.:extension"
  Paperclip::Attachment.default_options[:url] = "/test_files/:class/:id_partition/:style.:extension"
```

And `rails_helper.rb` to use this:

```
  config.after(:suite) do
    FileUtils.rm_rf(Dir["#{Rails.root}/public/test_files/"])
  end
```
