### ISSUE TITLE
update_attributes doesn't affect paperclip field

### ISSUE THREAD

**Issue by mlooney** [thoughtbot/paperclip#158]
This seems like it should pass..

<pre>  
should "bark if you set media to invalid  on update attributes" do
   should_validate_attachment_presence :media
    assert subject.media.present?
    assert !subject.update_attributes(:title=>'fubar', :media=>nil)
    assert_not_nil subject.errors.on(:media)
  end
</pre>

**Comment by javierojeda94** [comment]
I'm facing this problem right now. I'm using update_attributes and a simple asignation but none of them works... I'm using rails 3.2.22.5 and paperclip 4.3.7
