### ISSUE TITLE
Doc: migration methods are instance, not class?

### ISSUE THREAD

**Issue by siruguri** [thoughtbot/paperclip#1585]
Am I right in understanding that since Rails 3.1, migration `up` and `down` methods are instance methods? Would the better convention in the main `README.md` be to recommend using `def up` rather than `def self.up`? 

I can make a PR for this, if someone can confirm that I understand this correctly.

**Comment by tute** [comment]
@siruguri or @maclover7: feel free to send a PR adjusting that. Thank you!

**Comment by tute** [comment]
Closing for now, as migrations with instance method anyway work. Would be nice to polish that though!
