### ISSUE TITLE
-layers "optimize" for gifs render a bad quality image in some cases. Make it optional

### ISSUE THREAD

**Issue by coorasse** [thoughtbot/paperclip#1588]
Converting gifs with -layers "optimize" renders a poor quality image in some cases.
Can we make this option configurable?

![trwp_8711_ws_1 1](https://cloud.githubusercontent.com/assets/1319150/3467867/d7539854-0296-11e4-9111-182640a648d0.gif)

converting to a "240x240>" size executes this:
`convert file.gif -coalesce -auto-orient -resize "240x240>" -layers "optimize" -strip -auto-orient -colorspace sRGB output.gif`

and render this:
![test](https://cloud.githubusercontent.com/assets/1319150/3467884/fc2c961c-0296-11e4-9845-afb1e3239bd5.GIF)

if I remove the option the result is that one:
![test](https://cloud.githubusercontent.com/assets/1319150/3467890/1332ad60-0297-11e4-991c-eca2eae665b0.gif)

**Comment by maclover7** [comment]
Hi @coorasse ! Is this still an issue for you in Paperclip; I know this issue is from approximately 1 year ago. If it is still an issue, can you please provide the code that's causing you the error? Thanks!

**Comment by coorasse** [comment]
Too old, sorry. If I experience the problem again I'll reopen the issue
