### ISSUE TITLE
Default_url in broke at Rails 4.1

### ISSUE THREAD

**Issue by felipelc** [thoughtbot/paperclip#1597]
I'm using Paperclip default_url option with Rails 4.1:
:default_url => ActionController::Base.helpers.asset_path('assets/:style/missing-avatar.png')

This works at development, but not on production environment. At production, it's not adding the fingerprint at the end of the filename (ex: missing-avatar-FINGERPRINT.png) when refer to the file. And all my assets at production have fingerprint (default behavior at Rails 4.1).

**Comment by jacekgrzybowski** [comment]
happens for me as well

**Comment by maclover7** [comment]
Hi everybody! Is this still an issue for you in Paperclip; I know this issue is from approximately 1 year ago. If it is still an issue, can you please provide the code that's causing you the error? Thanks!

**Comment by conradwt** [comment]
Yes, I'm also seeing this issue on Rails 4.2.1 using Paperclip 4.2.1.

**Comment by rkrdo** [comment]
Me too, I'm using Rails 4.1.10 and Paperclip 4.2.1

**Comment by icem** [comment]
I've got this problem with rails 4.2.1, paperclip 4.3.0, sprockets 3.2.0
```
  has_attached_file :logo, styles: {thumb: '200x200#', micro: '35x35#'},
                           default_url: ActionController::Base.helpers.asset_path('no-company-logo.png')
```
Both development and production has ```config.assets.digest = true``` option. I'm using S3 storage.
I need to return logo url in json api (so I can't use image_tag() solution). In development I get correct url
 ``` company.logo.url #=> "/assets/no-company-logo-f48ee1....png" ```
But on production:
``` company.logo.url #=> "/no-company-logo.png"```
What even more strange, when I execute asset_path() in production console separately url is correct!
``` ActionController::Base.helpers.asset_path('no-company-logo.png') # => "/assets/no-company-logo-f48ee1....png" ```

I don't get the reason why during model loading url is incorrect. But I've found simple workaround - use lambda in default_url parameter.
```
  has_attached_file :logo, styles: {thumb: '200x200#', micro: '35x35#'},
                           default_url: ->(attachment) { ActionController::Base.helpers.asset_path('no-company-logo.png') }
```

**Comment by tute** [comment]
Does commit 36095bc0701a65054726af55b2689df9f7e75b9c fix this issue?

**Comment by hiquest** [comment]
I think I'm experiencing the very same problem with paperclip 4.3.1, Rails 4.2.4.

@icem solution worked for me though. Thank you man!

**Comment by zeke** [comment]
@icem solution worked for me as well. Bizarre.

**Comment by nicolasgarnil** [comment]
Does the "lambda solution" works with the `:style` interpolation?

It doesn't works for me and any of the examples above use `:default_url` with interpolation.

E.g:

```ruby
has_attached_file :logo, 
   styles: {
     thumb: '200x200#', 
     micro: '35x35#'
   }, 
   default_url: ->(attachment) {  ActionController::Base.helpers.asset_path('no-company-logo_:style.png') }
```

**Comment by icem** [comment]
@nicolasgarnil Of course your code won't work. `ActionController::Base.helpers.asset_path` has nothing to do with paperclip. It just finds a file in app/assets and returns correct path to it (including file digest etc). 
For me it was acceptable to serve standard sized default image for every style. It only downloaded once so no size problems.

**Comment by bjeanes** [comment]
@nicolasgarnil I'm also having this issue. Lambda doesn't help if you have different defaults for different styles :(

**Comment by bjeanes** [comment]
I'm playing with some changes to Paperclip to make this easier, but in the meantime I worked around this by making my own `UrlGenerator`:

``` ruby
class AssetAwareUrlGenerator < Paperclip::UrlGenerator
  def for(*)
    ActionController::Base.helpers.asset_path(super)
  end
end

class MyModel < ActiveRecord::Base
  has_attached_file :image,
    styles: { small: "48x48#" },
    url_generator: AssetAwareUrlGenerator,
    default_url: 'icons/default-:style.png'
end
```

That seems to do the trick for me, without disrupting attachments with an existing URL:

```
irb(main):013:0> a1.icon.url
=> "/assets/icons/icon-original-b881b02fcfad7247b5e93104cbd64588.png"
irb(main):014:0> a1.icon.url(:small)
=> "/assets/icons/icon-small-263130138614186528191ebf166456d6.png"
irb(main):015:0> a2.icon.url
=> "https://s3.amazonaws.com/[SNIP]/icons/121/original.png"
```

**Comment by heaven** [comment]
And we have:
```yaml
default_url: '//....cloudfront.net/images/missing/:assetable/:kind/:style.jpg'
```
And would like if it was generating a digested url. Now we simply have to put these "missing" images to public/images but that doesn't work well with cloudfront as we now have to invalidate cache manually every time we have to update those images.

**Comment by diazruy** [comment]
FWIW after a lot of struggling with this, and noticing that _some_ images were showing the fingerprint and others weren't, I was able to narrow it down to the use of `image_tag` to generate the images:
```erb
<img src="<%= @user.avatar.url(:large) %>"> <!-- No fingerprint -->
<%= img_tag @user.avatar.url(:large) %> <!-- Fingerprint! -->
```
with a configuration like
```ruby
has_attached_file :avatar,
  styles: { large: "200x200#", small: "60x60#", tiny: "30x30#" },
  default_url: "avatars/user_:style.png",
  #...
```
