### ISSUE TITLE
Lazy load rendering images

### ISSUE THREAD

**Issue by lucianosousa** [thoughtbot/paperclip#1598]
Hi guys, I just uploaded 25 files to S3, deploy on amazon ec2 and stayed 33 seconds waiting to load my page.
The problem I discovered with new relic was:

Before load my page, rails app/excon is going to s3, load all images and just after that render my page.

I never see this before.
Do you guys have some idea to reload these images async? I can imagine it's the regular behavior, but as you can see below:

```
Breakdown table
Category	    Segment	% Time	 Avg calls(per txn)	 Avg time(ms)
External	Excon[brtrax-abmi.s3.amazonaws.com]: HEAD	 96.2	 25.0	 23,300
View	 phonograms/_phonogram.html.erb Partial	 1.4	 25.0	 339
View	 phonograms/index.html.erb Template	 1.0	 1.0	 247
Middleware	 ActionDispatch::Routing::RouteSet#call	 0.4	 1.0	 97.3
View	 phonograms/_filters.html.erb Partial	 0.2	 1.0	 44.8
Database	 SQL - SELECT	 0.2	 38.0	 59.3
Rack App	 Brtrax::Application#call	 0.1	 1.0	 16.3
View	 layouts/application Template	 0.1	 1.0	 18.3
```

Thx

**Comment by maclover7** [comment]
Hi @lucianosousa and @danieljacobarcher ! Is this still an issue for you in Paperclip; I know this issue is from approximately 1 year ago. If it is still an issue, can you please provide the code that's causing you the error? Thanks!

**Comment by lucianosousa** [comment]
@maclover7 sorry man. I haven't this code anymore.

**Comment by maclover7** [comment]
@jferris @jyurek Please close issue, problem appears to be solved.

**Comment by danieljacobarcher** [comment]
@maclover7 I removed the Fog setup from my app, and just using Paperclip directly with AWS.

**Comment by tute** [comment]
Thank you all for your input!
