### ISSUE TITLE
Add custom extension to a file type

### ISSUE THREAD

**Issue by foxpowa** [thoughtbot/paperclip#1601]
I want to attach file with .fasta extension which has a plain/text content type.

Content type validators throws : 
`Content Type Spoof: Filename file.fasta ([]), content type discovered from file command: text/plain. See documentation to allow this combination.`

Validation from my model : 
`validates_attachment :fasta_file, :content_type => { :content_type => 'text/plain' }`

So I would like to associate custom file extension to content type (fasta -> plain/text)

PS : uploading file.txt (with same content) works fine.

**Comment by maclover7** [comment]
Is this fixed with #1839 ?

**Comment by tute** [comment]
ping @foxpowa. Is this now fixed?

**Comment by foxpowa** [comment]
I'm not able to test easily, I'm not using paperclip anymore, sorry guys.
