### ISSUE TITLE
Custom url generation and usage

### ISSUE THREAD

**Issue by JehandadK** [thoughtbot/paperclip#1603]
Paperclip uses fields for uploaded files to S3. Can we customise to do as follows

1) Upload file 
2) Generate a UUID
3) Upload file to the specified bucked using the UUID as name.
4) Save the complete url to a single field. i.e image col

**Comment by maclover7** [comment]
Hi @JehandadK ! Is this still an issue for you in Paperclip; I know this issue is from approximately 1 year ago. If it is still an issue, would you be willing to send in a PR to solve the problem? Thanks!

**Comment by JehandadK** [comment]
I am not sure I posted an issue here. It was something that I wanted to do and coudnt figure out how. Pretty sure anyone with expertise in ROR could do it easily with paperclip. But as a result of this I actually gave up on ROR and shifted to nodejs where there is no hidden magic and I can easily figure out how to use libraries with some customisation. Thanks!

Guess we can close this!

**Comment by maclover7** [comment]
@jferris @jyurek Problem solved, issue is fine to be closed.
