### ISSUE TITLE
Fixed size cropping on a image with height greater than its width

### ISSUE THREAD

**Issue by pacoguzman** [thoughtbot/paperclip#1604]
### Problem

Using the trailing `#` in a Paperclip style is supposed to generate a thumbnail centrally cropped with the specified width and height but it's not.
### Versions
- paperclip 4.2.0
- rails 4.1.4
- imagemagick 6.8.9-1
### Use case

``` ruby
class User < ActiveRecord::Base
  has_attached_file :avatar,
                    :styles => { :thumb => "160x160#" },
                    :default_url => "/images/:style/missing.png"

  validates_attachment :avatar, :presence => true, :content_type => { :content_type => "image/png" }
end
```

Image file

``` sh
$ identify -format '%wx%h,%[exif:orientation]' 'quarted_vertical.png'
537x575,
$ identify -format %m 'quarted_vertical.png'
PNG
```
### Result

``` sh
$ identify -format '%wx%h,%[exif:orientation]' 'thumb/quarted_vertical.png'
84x160,
$ identify -format %m 'thumb/quarted_vertical.png'
PNG
```
### Notes

Paperclip executes the following ImageMagick convert command:

``` sh
-auto-orient -resize "160x" -crop "160x160+0+5" +repage
```

This seems similar to #1028 and #1083 but in the last case they didn't confirm is the issue was solved

**Comment by maclover7** [comment]
Hi everybody! Is this still an issue for you in Paperclip; I know this issue is from approximately 1 year ago. If it is still an issue, can you please provide the code that's causing you the error? Thanks!

**Comment by pacoguzman** [comment]
@maclover7 the code is in the description, and in the following blog post you'll see a better explanation:

http://mrfrosti.com/2015/04/28/dont-use-in-the-paperclip-gem/

**Comment by yob** [comment]
We're seeing this issue as well.

## Versions

* paperclip 4.2.0
* rails 4.1.11
* imagemagick 6.8.9

## Original Image

https://62e528761d0685343e1c-f3d1b99a743ffa4142d9d7f1978d9686.ssl.cf2.rackcdn.com/files/85154/original/image-20150616-5807-144x1bq.jpg

## Model

```ruby
has_attached_file :file,
  path: ":public_path/system/:attachment/:id/:style/:filename",
  url: ":asset_root/:attachment/:id/:style/:filename",
  styles: { width240x240: '240x240#' },
  convert_options: { width240x240: "-quality 80 -strip" }
```
## Result

The cropped image is `240x76` instead of `240x240`:

```bash
$ identify public/system/files/83919/width240x240/image-20150619-14463-1kcu22n.jpg                                                         
public/system/files/83919/width240x240/image-20150619-14463-1kcu22n.jpg JPEG 240x76 240x76+0+0 8-bit sRGB 2.28KB 0.000u 0:00.000
```
