### ISSUE TITLE
after_initialize doesn't allow validations

### ISSUE THREAD

**Issue by rsiddle** [thoughtbot/paperclip#1605]
My model requires the attachment to be initalized afterwards because I need to decide whether the Fog gem is set to public or private. The problem I'm facing is that the validations then fail giving me the following error:

```
undefined method `_attachment_post_process_callbacks' for #<Class:0x007f891b8389b0>
```

The error points to the validates_attachment_content_type. The code for the model is:

```
after_initialize :init_attachment

validates_attachment_content_type :attachment,
 :content_type => ['image/png', 'image/jpeg', 'image/jpg', 'image/gif']

 def init_attachment
   self.class.has_attached_file :attachment,
     :styles => lambda { |attachment|
       !attachment.instance.is_type_of_image? ? {} : {
         thumb: '100x1  ',
         small: '200x2  ',
         medium: '300x300>',
         large: '550x250>'}
     },
     :styles => {
       :medium => { :geometry => "640x480", :format => 'mp4', :convert_options => {:output => {:ar => 44100}} },
       :large => { :geometry => "1024x576", :format => 'mp4', :convert_options => {:output => {:ar => 44100}} },
     }, :processors => [:ffmpeg],
     default_url: "/uploads/:post_type/missing.png",
     url: "/uploads/:style/:permalink/:basename.:extension",
     path: "uploads/:style/:permalink/:basename.:extension",
     fog_public: self.is_public?
  end
```

Any thoughts on a work around for this?

**Comment by ASnow** [comment]
I think exception raised because field :attachment don't exist at moment of validation definition.
Try to put your validation init 'init_attachment' method

**Comment by maclover7** [comment]
Hi @rsiddle and @ASnow ! Is this still an issue for you in Paperclip; I know this issue is from approximately 1 year ago. If it is still an issue, can you please provide the code that's causing you the error? Thanks!

**Comment by ASnow** [comment]
@maclover7, I think it's ok that we get error when has_attached_file don't executed before validates_attachment_content_type 
```
class User < ActiveRecord::Base
  # here must be has_attached_file 
  validates_attachment_content_type :undefined_attachment, :content_type => ['image/png', 'image/jpeg', 'image/jpg', 'image/gif']
end
```
but exception could be more informative e.g. "Attachment `undefined_attachment` was not defined(with has_attached_file) at User"

**Comment by tute** [comment]
Failing early will be an improvement indeed.
