### ISSUE TITLE
S3 security notices

### ISSUE THREAD

**Issue by equivalentideas** [thoughtbot/paperclip#1609]
Paperclip is widely recommended for use with Rails, particularly by Heroku. It could be good to add a sentence in the s3 hosting section of the readme to explain that people should not post their s3 access key credentials to github and should use environment variables. This isn't an obvious issue to newcomers.

Similarly, s3 are now recommending everyone use IAM users instead of using the root user's keys. It would be very helpful to new users (like myself) to have a copy of a secure, basic IAM permissions policy for use with paperclip.

**Comment by maclover7** [comment]
Hi @equivalentideas ! Would you be willing to add some documentation in the wiki about this? Thanks!

**Comment by tute** [comment]
This is outside the scope of this project according to what you describe. If you think that is an incorrect assumption, please do send a PR and we can discuss over the diff.
Thank you!
