### ISSUE TITLE
 Paperclip::AbstractAdapter#rewind delegated to @tempfile.rewind, but @tempfile is nil: Paperclip::NilAdapter:

### ISSUE THREAD

**Issue by gadikotamohan** [thoughtbot/paperclip#1617]
Hi I'm having issue with paperclip
Class Image < ActiveRecord::Base
  has_attached_file :photo,
    styles: lambda { |a| a.instance.styles },
    processors: [:cropper],
    convert_options: {
      thumb: "-quality 75 -strip"
    }

   def styles
     # my code
  end
end

class ProfileImage < Image
  def styles
    {
      thumb: '180x180#',
      square: '210x210#',
      vsmall: '50x50#'
    }
  end
end

If I try to save profle image I get " Paperclip::AbstractAdapter#rewind delegated to @tempfile.rewind, but @tempfile is nil: Paperclip::NilAdapter:" error.

I'm using rails 4.1
paperclip version 3.5.4

**Comment by poussinxt** [comment]
I have about the same problem.... did you find a solution?

**Comment by maclover7** [comment]
Hi @gadikotamohan and @poussinxt ! Is this still an issue for you in Paperclip; I know this issue is from approximately 1 year ago. If it is still an issue, can you please provide the code that's causing you the error? Thanks!

**Comment by tute** [comment]
ping @gadikotamohan: is this still an issue for you?

**Comment by poussinxt** [comment]
I found a work around

2015-05-12 1:35 GMT+02:00 Tute Costa <notifications@github.com>:

**Comment by doutatsu** [comment]
@poussinxt What was the work around you found?
