### ISSUE TITLE
How to delete the original file on save?

### ISSUE THREAD

**Issue by vincentcordel** [thoughtbot/paperclip#1621]
Hello there,

Thanks for your plugin, it's awesome.

I wonder however how I could delete the original file when saving.
Although I understand the use in case of reprocessing, I can see some uses where we don't need it.

Could you please tell me how to do that?

I think the only thing I'm missing is the path to the original file. This is what I have right now in my model:

```
after_post_process :delete_original

def delete_original
     File.delete(self.cover.path)
 end
```

(where 'cover' is the file I'm saving in the DB)

**Comment by asad-nga** [comment]
@jyurek I don't know why but **after_post_process :delete_original** is not getting invoked....
