### ISSUE TITLE
Attachments get uploaded to S3 even though size validation adds error

### ISSUE THREAD

**Issue by neumanrq** [thoughtbot/paperclip#1622]
Context: Rails v4.0.8, Paperclip v4.2

The attachment hosting object validates the attachment size:

```Ruby
validates :photo, attachment_size: { in: 0..1.megabytes }, attachment_content_type: { content_type: /\Aimage/ }
```

When trying to upload bigger sized files the validation is invoked and an appropriate error is added to the attachment hosting instance. But despite this the file gets saved and uploaded to S3, as a consequence the host is invalidated. 

As far as I know this is not intended behavior, isn't it?

Thanks,
Robin

**Comment by maclover7** [comment]
Hi @neumanrq and @cnk ! Is this still an issue for you in Paperclip; I know this issue is from approximately 1 year ago. If it is still an issue, would you be willing to send in a PR to solve the problem? Thanks!

**Comment by neumanrq** [comment]
@maclover7, I'll try to reproduce with latest versions of Paperclip and Rails and try to submit a fix it if the problem holds and I'm able to.

**Comment by neumanrq** [comment]
Having a fresh Rails app with the latest Paperclip version (current master branch), I can't reproduce the problem and everything works as expected. I tested the same controller/model implementation as used in the application where the problem occurs.  

Unfortunately the application where the problem occurs is not 100% ready for upgrading to Rails 4.2.x so I can't be sure if it's caused by an additional side effect of another gem or it is just fixed recently by Rails or Paperclip. If upgrading to Rails 4.2.1 won't fix it for this application, I'll try to figure out what is affecting Paperclip there and reformulate the problem more exactly. 

Anyway, thanks for taking care!
