### ISSUE TITLE
Image rotation

### ISSUE THREAD

**Issue by BrentWheeldon** [thoughtbot/paperclip#1623]
We'd like our users to be able to rotate images, but I can't seem to find an easy way of doing this. It seems like this should be trivial, and there's a `rotator` processor alluded to in the readme, but I can't seem to find it.

I found some implementations after some googling, but they don't seem to rotate the image. An example of what I've got at the moment is:

```
module Paperclip
  class Rotator < Thumbnail
    def initialize(file, options = {}, attachment = nil)
      options[:auto_orient] = false
      super
    end

    def transformation_command
      if rotate_command
        "#{rotate_command} #{super.join(' ')}"
      else
        super
      end
    end

    def rotate_command
      target = @attachment.instance
      if target.rotation.present?
        " -rotate #{target.rotation}"
      end
    end
  end
end

class User < ActiveRecord::Base
  has_attached_file :avatar, {
    styles: {
      small: ['72x72#', :png]
    },
    processors: [:rotator]
  }

  attr_accessor :rotate
end
```

I'm using this code to try and rotate:
```
user.rotate = 90
user.avatar.reprocess!
```

I can see the `-rotate 90` option being passed to `convert`, but it doesn't do anything. Any hints? I'm obviously missing something obvious since I'm sure it's not this difficult to do something so easy.

**Comment by maclover7** [comment]
Hi @BrentWheeldon ! Is this still an issue for you in Paperclip; I know this issue is from approximately 1 year ago. If it is still an issue, can you please provide the code that's causing you the error? Thanks!

**Comment by BrentWheeldon** [comment]
Hi @maclover7. The code is posted above. We've long since moved on from paper clip, feel free to close.

**Comment by maclover7** [comment]
@jferris @jyurek Please close issue, problem appears to be solved.
