### ISSUE TITLE
Setting attachment to Image's S3 URL is changing content_type

### ISSUE THREAD

**Issue by danieljacobarcher** [thoughtbot/paperclip#1631]
I have an app that's uploading first to S3 using s3_direct_upload, and then it later requires post processing, so I have it then save the attachment through Paperclip and upload to S3, but it's losing the content_type on creation..

For example:
```ruby
photo.avatar = URI.parse(URI.escape(photo.direct_upload_url))
```
At this step, it's ignoring the original file's actual MIME type and setting the new content_type to be 'attachment/octet-stream'

Any suggestions?

**Comment by maclover7** [comment]
Hi @danieljacobarcher ! Is this still an issue for you in Paperclip; I know this issue is from approximately 1 year ago. If it is still an issue, can you please provide the code that's causing you the error? Thanks!

**Comment by danieljacobarcher** [comment]
@maclover7 No longer an issue for me.. Don't remember what solved it though!
