### ISSUE TITLE
Passing runner options through to Cocaine (e.g. timeout support)

### ISSUE THREAD

**Issue by maxim** [thoughtbot/paperclip#1638]
If I understand correctly from reading source, currently there is no way to pass runner_options from `has_attached_file` declaration to Cocaine runner. One thing that would really help us is being able to set timeout option in posix-spawn runner.

I would even argue that implementing timeout support for all runners might be a very useful thing, images come in many varieties, and sometimes you get crazy vectors that cause ImageMagick to eat all available CPU/RAM for a long time (especially when encouraging high-quality image uploads).

So I propose either allowing runner_options in Paperclip's processor declaration, or adding consistent support for timeout across Cocaine runners, and natively in Paperclip. Would this be a desirable addition? I will try to find time to work on it if there's a chance of having it merged.

**Update:**

Upon further inspection noticed that Cocaine doesn't create Spawn::Child in posix-spawn, instead it just calls spawn class method, and this method doesn't actually accept timeout. If we go with passing runner_options from paperclip, we should then also modify posix spawn runner to create Child object.

**Update2:**

Here's the code in my rails app that achieves the result I want. Adding it here to give a general idea of how easy it would be to add this functionality to Paperclip. I had to write my own Cocaine runner (a very simple one) and my own processor:

```ruby
# lib/cocaine_runner.rb
require 'posix/spawn'
require 'climate_control'

class CocaineRunner
  def call(command, env = {}, options = {})
    ClimateControl.modify(env) do
      ::POSIX::Spawn::Child.new(env, command, options).out
    end
  end
end


# lib/paperclip_processors/thumbnail_with_timeout.rb
module Paperclip
  class ThumbnailWithTimeout < Thumbnail
    RUNNER_OPTIONS = { runner_options: { timeout: 240 } }.freeze

    def convert(arguments = '', local_options = {})
      Paperclip.run('convert', arguments, local_options, RUNNER_OPTIONS)
    end

    def identify(arguments = '', local_options = {})
      Paperclip.run('identify', arguments, local_options, RUNNER_OPTIONS)
    end
  end
end


# config/initializers/cocaine.rb
require_dependency 'cocaine_runner'
Cocaine::CommandLine.runner = CocaineRunner.new
```

And in has_attached_file specify `:thumbnail_with_timeout` as processor.

**Comment by maclover7** [comment]
Hi @maxim ! Is this still an issue for you in Paperclip; I know this issue is from approximately 1 year ago. If it is still an issue, can you please provide the code that's causing you the error? Thanks!

**Comment by maxim** [comment]
@maclover7 Let's close this, I moved this to cocaine.

**Comment by maxim** [comment]
Here's the discussion of this on cocaine, and in my last comment I describe how ImageMagick's -limit parameter makes this issue somewhat irrelevant: https://github.com/thoughtbot/cocaine/issues/81

**Comment by maclover7** [comment]
@jferris @jyurek Please close issue, problem appears to be solved.
