### ISSUE TITLE
Please bump version to 4.2.1

### ISSUE THREAD

**Issue by MarkMurphy** [thoughtbot/paperclip#1652]
I'm getting the following error:

NoMethodError: undefined method `gsub' for nil:NilClass 
in 
paperclip-4.2.0/lib/paperclip/io_adapters/abstract_adapter.rb:23

```ruby
   def original_filename=(new_filename)
      @original_filename = new_filename.gsub(OS_RESTRICTED_CHARACTERS, "_")
    end
```

But I can see if the master branch of paperclip that there is now a check that will return from this method early if `new_filename` is nil.

**Comment by maclover7** [comment]
Hi @MarkMurphy ! Is this still an issue for you in Paperclip; I know this issue is from approximately 1 year ago. If it is still an issue, can you please provide the code that's causing you the error? Thanks!

**Comment by tute** [comment]
4.2.1 has been released on Dec 09 2014. Thanks!
