### ISSUE TITLE
Getting the URL for a S3-hosted file hits AWS?

### ISSUE THREAD

**Issue by russellquinn** [thoughtbot/paperclip#1658]
My API returns a batch of S3-hosted image URLs, using this:

object.image_attribute.url(:style)

But it seems each one hits AWS to get the head_object to get the full path?

[AWS S3 200 0.088711 0 retries] head_object(:bucket_name=>"bucket",:key=>"path/to/my/image.jpg")  

This causes significant overhead and reduced response times.

Is this expected behavior? Or should Paperclip be calculating the URL locally?

Or am I just doing this in a sub-optimal way?

Thanks!

Russell.

**Comment by gabriprat** [comment]
Did you ever get an answer? I just had the same question.

**Comment by russellquinn** [comment]
Nope! I just ended up caching it locally and invalidating the cache if the image changed.

**Comment by jyurek** [comment]
Paperclip should be calculating the URL locally. Can you paste the definition you have for the attachment's `url` and `path` as well as any interpolations you have?

**Comment by gabriprat** [comment]
I finally discovered my problem. It was my fault. I was calling .exists? first and that hit AWS. Now I changed it for .file? and everything works like a charm. Thank you!

**Comment by jyurek** [comment]
Excellent, glad to hear it!

**Comment by gabriprat** [comment]
I'm sorry not to have found it before posting.
