### ISSUE TITLE
Crash with certain pdf-files

### ISSUE THREAD

**Issue by JanneMantyharju** [thoughtbot/paperclip#1663]
I'm using paperclip 4.2.0 in brimir and I get quite many crashes like these:
Command :: file -b --mime '/tmp/10df2f52f285c3dfdf3dab55c94cf80c20140925-53916-1wdxi0620140925-53916-197wjlr.jpg'
Command :: file -b --mime '/tmp/10df2f52f285c3dfdf3dab55c94cf80c20140925-53916-1bs967.tif'
Command :: file -b --mime '/tmp/c7112990471ba24eabb4db3722db089620140925-53916-1rutoz.PDF'
Command :: file -b --mime '/tmp/c7112990471ba24eabb4db3722db089620140925-53916-1b78ak.PDF'
Command :: identify -format '%wx%h,%[exif:orientation]' '/tmp/c7112990471ba24eabb4db3722db089620140925-53916-1rutoz.PDF[0]' 2>/dev/null

Received mail (5303.2ms)
Completed 500 Internal Server Error in 5378ms

FloatDomainError (NaN):
  app/mailers/ticket_mailer.rb:133:in `block in receive'
  app/mailers/ticket_mailer.rb:121:in `each'
  app/mailers/ticket_mailer.rb:121:in `receive'
  app/controllers/tickets_controller.rb:133:in `block (2 levels) in create'
  app/controllers/tickets_controller.rb:108:in `create'

This seems to happen with some pdf-files which are somehow oddly created, they seem only to open in acrobat reader anyway.

**Comment by tute** [comment]
Thanks for your input @JanneMantyharju! We do keep in mind improving the error handling in the library.
