### ISSUE TITLE
Windows 7 Spoof Fix

### ISSUE THREAD

**Issue by richpeck** [thoughtbot/paperclip#1668]
**Spoofing Fix For Windows 7**

The notorious **`Validation failed: Upload file has an extension that does not match its contents.`** error, caused by the  `content type discovered from file command: .` issue appears on Windows (7) because the `file` command (native in Unix systems) is not present in the OS. 

As mentioned in this [Stackoverflow Answer](http://stackoverflow.com/a/23184171/1143732), and consequently in [this article](http://robots.thoughtbot.com/prevent-spoofing-with-paperclip), you need to install the [`file`](http://gnuwin32.sourceforge.net/packages/file.htm) application for Windows in order to provide the functionality.

The solution is thus:

1. Install "file.exe" (use link above)
2. In `config/environments/development.rb`, use the following:

```
#config/environments/development.rb
Paperclip.options[:command_path] = 'C:\Program Files (x86)\GnuWin32\bin' #-> path to the newly installed `file.exe`
```

Restart your Rails server and it *should* work for you.

--
A simple test will be to do the following:

`run cmd`
`cd C:\Program Files (x86)\GnuWin32\bin`
`file c:\path\to\an\image`

This *should* show you something like the following:

![untitled](https://cloud.githubusercontent.com/assets/1104431/4524452/a1f8cce4-4d44-11e4-872e-17adb96f79c9.png)

**Comment by tute** [comment]
Thank you! Closing for now as this is not an issue with paperclip (happy to reopen if you disagree).
 Can you please add this to the wiki? Thanks again!

**Comment by tute** [comment]
Nevermind about the wiki, it's already in the README. Thanks!
