### ISSUE TITLE
How can I get the expiring url of a private S3 file?

### ISSUE THREAD

**Issue by yosriady** [thoughtbot/paperclip#1675]
In Paperclip, you can do:

```
attachment.expiring_url(EXPIRATION_TIME)
```

But for my Assets created using S3 Direct Upload, there's no such method.
How can I elegantly extract a method to construct an expiring url given a valid private S3 url?

**Comment by maxence33** [comment]
Hi @yosriady 

I have quite asimilar issue. I have uploaded a private paperclip attachment and expiring_url does work well in my views. 

Though expiring_url does not work inside my controller (I try to get the temporary link inside the controller and pass it as Ajax result to my page) 

Is you solution the only possibility to access a private file (and generate link) in the controller ? 
There may be something I am missing ...
