### ISSUE TITLE
data_uri_adapter does not appear to work

### ISSUE THREAD

**Issue by DelvarWorld** [thoughtbot/paperclip#1681]
Based on the existence of this file:

https://github.com/thoughtbot/paperclip/blob/master/lib/paperclip/io_adapters/data_uri_adapter.rb

Here's my class:

    class Thing < ActiveRecord::Base
    
        has_attached_file :image, :default_url => "/thing/missing.png"

    end

Here's my post JSON:

    {
        image: "data:image/png;base64,iVBORw0KGgo..."
    }

It passes the regex ...

    /data:([-\w]+\/[-\w\+\.]+)?;base64,(.*)/.test('data:image/png;base64,iVBORw0KGgo') // true

And it errors with:

    Paperclip::Errors::MissingRequiredValidatorError
      in ThingController#update

**Comment by pjar** [comment]
You need to specify original_filename for Thing. So for controller that would be:

    image = Paperclip.io_adapters.for(params[:image]) 
    image. original_filename = "something.png"
    Thing.create(image: image)

**Comment by tute** [comment]
Paperclip should have more clear error messages whenever possible.

**Comment by jyurek** [comment]
@DelvarWorld That is actually correct. Paperclip requires that you either add a content_type or filename validator, or, as the `do_not_validate_attachment_file_type` method does, explicitly reject that you're going to use one.

But @tute is right, the messaging on this could be much better.

**Comment by tute** [comment]
This is expected behavior, and the README file documents it: https://github.com/thoughtbot/paperclip#validations. Closing the issue. Thanks for reporting!
