### ISSUE TITLE
Paperclip does not propagate errors correctly

### ISSUE THREAD

**Issue by DelvarWorld** [thoughtbot/paperclip#1682]
See https://github.com/thoughtbot/paperclip/issues/1681

When passing in a valid image, the only error given is: Paperclip::Errors::MissingRequiredValidatorError. It does not give any indication as to what is actually missing.

**Comment by tute** [comment]
Thanks! Will close as duplicate of https://github.com/thoughtbot/paperclip/issues/1681, and add a comment there for the error messages that should be improved. Thanks for your input.
