### ISSUE TITLE
Failed object validation and url() method returning invalid asset path due to image not yet being uploaded.

### ISSUE THREAD

**Issue by DrewBe121212** [thoughtbot/paperclip#1687]
Currently when an upload fails validation (either on the image or the form itself) the information about the uploaded file is retained in the temporary object. This is of course expected behavior as it is the normal way any object behaves. The values in the object reflect that which have been recently submitted by the form. The issue I am experiencing is that when an object fails validation, it still thinks that an image has been uploaded even though it hasn't. 

What I have is an avatar image attached to a user object.

```
class User < ActiveRecord::Base
    has_attached_file :avatar, :styles => { :tiny     => ["25x25>", :jpg],
                                                                :thumb    => ["65x65>", :jpg], 
                                                                :small    => ["130x130>", :jpg] }, 
                :default_url => "/assets/missing/:attachment/:style.png",
                :convert_options => { :all => "-strip"},
                :path => ":rails_root/public/assets/users/:id/:attachment/:style.:extension",
                :url  => "/assets/users/:id/:attachment/:style.:extension"

    validates_attachment :avatar, 
                                      :content_type => { :content_type => ["image/jpeg", "image/jpg", "image/png", "image/gif"] },
                                      :file_name => { :matches => [/png\Z/, /jpe?g\Z/, /gif\Z/] },
                                      :size => { :less_than => 100.kilobytes } 
end
```

A user can update their profile at any time. If they have not uploaded an avatar, we fallback on paperclips 'default_url' option. This works great except in an instance when validation fails. When validation fails it seems to be that the url() method should return the default_url option (or the old image if editing) vs the erroneous path to the non-uploaded file. 

Using the following code: 

```
    <%= image_tag @user.avatar.url(:thumb), :class => 'img-thumbnail', :title => 'Avatar', :width => 65, :height => 65 %>
```

We get the following scenario:
- Page loads and either displays the users uploaded avatar / default_url style
- Submitting the form with failed validation, the function @user.avatar.url(:thumb) returns a path to an asset that has yet to be uploaded. 

Is there a way to retrieve the appropriate path derived from default_url? If so, I could do something like this...

```
<% if @user.avatar.exists? %>
    <%= image_tag @user.avatar.url(:thumb), :class => 'img-thumbnail', :title => 'Avatar', :width => 65, :height => 65 %>
<% else %>
    <%= image_tag @user.avatar.default_url(:thumb), :class => 'img-thumbnail', :title => 'Avatar', :width => 65, :height => 65 %>
<% end %>
```

However, to me it seems like url() should return the appropriate information. In this case being a default_url path vs the non-uploaded asset path. 

Thoughts? Am I going about this in a completely bonkers way?

**Comment by tute** [comment]
Is this fixed in https://github.com/thoughtbot/paperclip/commit/36095bc0701a65054726af55b2689df9f7e75b9c?

**Comment by jeffblake** [comment]
No, it's not working in master.

I'm also using

```
  Paperclip::Attachment.default_options.merge!(
    url: ':s3_alias_url',
    s3_host_alias: Proc.new {|attachment| "assets#{attachment.instance.id % 4 + 1}.#{url_host}" }
  )
```
And `attachment.instance.id` is returning as nil when the form is invalid and you are trying to display the image next to the `file_field` , like so:

```
= f.file_field :image
- if f.object.image?
  = image_tag f.object.image.url
```

**Comment by mike-burns** [comment]
Thank you for reporting this. Unfortunately, we will be deprecating Paperclip and therefore will not have the bandwidth to address this issue.
