### ISSUE TITLE
Too many open files on rake paperclip:refresh:thumbnails

### ISSUE THREAD

**Issue by dkhan** [thoughtbot/paperclip#1689]
I have about 5000 images to reprocess thumbnails. When I run rake paperclip:refresh:thumbnails CLASS=Logo it throws the following exception after processing about a hundred files and continues to fail on each following image

> rake paperclip:refresh:thumbnails CLASS=Logo
exception while processing Logo ID 2977f970-24fb-11e2-8804-1231392eb1f5:
 Too many open files - file -b --mime '/tmp/302b0980f656f76188e9b549ac0400b120141105-24397-1kvfhmu20141105-24397-118g331.png'
exception while processing Logo ID 29783bd4-24e7-11e3-89a6-02cc3afa57bd:
 Too many open files - file -b --mime '/tmp/cc7c70a97cb13ece5c35fb969f861d3820141105-24397-1gweprf.png'
exception while processing Logo ID 29822ff6-ec59-11e1-8804-1231392eb1f5:
 Too many open files @ rb_sysopen - /tmp/40bab54902ec314ad9b79b35def7e92320141105-24397-19mcimo.jpg
exception while processing Logo ID 29883a54-af46-11e1-9376-1231392eb1f5:
 Too many open files @ rb_sysopen - /tmp/7b89d5573823f164af2fd3fddd2be0af20141105-24397-y5cfg7.gif
exception while processing Logo ID 299987e7-3b45-11e3-89a6-02cc3afa57bd:
 ......

**Comment by tute** [comment]
Have you tried increasing the `ulimit` for your system? This doesn't seem like an issue with paperclip, closing for now. Please ask too in StackOveflow, and feel free to reopen the issue if you think we can fix it in paperclip. Thanks!

**Comment by tute** [comment]
We can continue discussion in https://github.com/thoughtbot/paperclip/issues/1326.

**Comment by dmitry** [comment]
Original file not closed when it's not selected for reprocessing. Could be closed with `instance_variable_get(:@file).close`
