### ISSUE TITLE
Version 4.2.0 is slow

### ISSUE THREAD

**Issue by scottwillson** [thoughtbot/paperclip#1690]
Our project's test runs became three times slower after upgrading from Paperclip 3.5.2 to 4.2.0.

After digging in with ruby-prof, I found the issue. It appears to have been fixed in August with this commit: https://github.com/thoughtbot/paperclip/commit/6b1f6104152a66248f33b2f62566688f28487d01#diff-a4870b4fe431f88fa95c85e4c819ad4fL393

However, the current gem release (4.2.0) doesn't include this commit. I'm OK with putting a github reference in our Gemfile, but this is a pretty big performance regression + fix. What do you think about cutting a 4.2.1 or 4.3 release?

Thanks,
Scott

**Comment by tute** [comment]
4.2.1 has been released on Dec 09 2014. Thanks!

**Comment by scottwillson** [comment]
Thanks for mentioning it here!
