### ISSUE TITLE
Paerclip shouldn't validate against the content-type reported by a browser

### ISSUE THREAD

**Issue by peterept** [thoughtbot/paperclip#1694]
I've been trying to support attaching Apple's .mobileprovision files.

According MacOS using:
$ file -b --mime-type a.mobileprovision 
"application/octet-stream"

And almost all browsers, Chrome/IE/Safari(pre-Yosemite) report in the POST:
... filename=\"a.mobileprovision\"\r\nContent-Type: application/octet-stream ...

However, Safari on Yosemite browser POST reports a new MIME type:
... filename=\"a.mobileprovision\"\r\nContent-Type: application/x-apple-aspen-mobileprovision ...

Which then paperclip reports the file as invalid (although it does actually save it).

Why is Paperclip listening to what a browser reports when it has file -b --mime-type to interegate? If it is because file doesn't know every type? How can we rely on the browser to be consistant? Apple could change their minds tomorrow correct with a new MIME type?

**Comment by tute** [comment]
Is this fixed by https://github.com/thoughtbot/paperclip/commit/9aee4112f36058cd28d5fe4a006d6981bd1eda57?

**Comment by tute** [comment]
Closing in favor of duscussion in https://github.com/thoughtbot/paperclip/issues/1771. Thanks!
