### ISSUE TITLE
Validations fail for seemingly valid images

### ISSUE THREAD

**Issue by acconrad** [thoughtbot/paperclip#1696]
Upgrading from 2.7 to 4.2 on Rails 3.2.20 (Ruby 2.1.2).

In our model...

```
validates_attachment :profile_photo,
    content_type: { :content_type => ["image/jpeg", "image/jpg", "image/png", "image/gif"] },
    file_name: { :matches => [/png\Z/, /jpe?g\Z/, /gif\Z/] }
```

In our `spec/factories.rb` file...

```
include ActionDispatch::TestProcess
FactoryGirl.define do

  trait :with_profile_photo do
    profile_photo { fixture_file_upload(Rails.root.join('spec', 'support', 'test_image.jpg'), 'image/jpeg') }
  end
end
```

but when creating a factory, such as `create(:user, :with_profile_photo)` we're getting the following error:

> ActiveRecord::RecordInvalid:
>        Validation failed: Profile photo has an extension that does not match its contents

I have verified that our `test_image.jpg` does indeed have the `image/jpeg` content-type and is a valid JPG. Not sure what else we would need to do to get this to pass validations, the validations seem in line with what is being tested.

**Comment by AteqEjaz** [comment]
Hi,

Facing exactly the same issue,

Validation failed: Profile pic has an extension that does not match its contents

Thanks!

**Comment by tute** [comment]
@acconrad is this still an issue for you? How can we replicate it?

**Comment by acconrad** [comment]
@tute this is still an issue for us. I think one mistake I made was that I reported us using `2.7` of Paperclip but we are actually running over version 2.6. 

So in order to replicate you would need to currently have Paperclip 2.6 running with Rails 3.2.21 and Ruby 2.1.5.

We currently have the following set up in a model:

```ruby
  has_attached_file :profile_photo,
    styles: {
      small: ['100x100>', :jpg],
      large: ['300x300>', :jpg],
      profile: ['300x300#', :jpg],
      search: ['90x90#', :jpg],
      very_large: ['500x500>', :jpg]
    },
    hash_secret: '9rleB3FN2qAkjnH0uVhsKozJg1PacDO',
    url: '/profile/:hash.:extension',
    storage: :s3,
    s3_credentials: "#{Rails.root}/config/s3.yml",
    s3_protocol: 'https',
    default_url: 'missing-profile-photo.png'

validates_image :profile_photo
```

and in our `spec/factories.rb` file for the model we have a trait:

```ruby
trait :with_profile_photo do
  profile_photo { File.open(Rails.root.join('spec', 'support', 'sample_photo.jpg')) }
end
```

then create a Feature spec where you `create(:user, :with_profile_photo)` and make sure that works to verify it works for 2.6 in the state I've presented. 

From there you would upgrade to Paperclip 4.2 and change the code to the example I have above - which should be what it takes to upgrade from 2.6 to 4.2 according to the documentation. Then run the feature spec again and it should throw that error.

**Comment by acconrad** [comment]
@tute if it does end up working for you, it would be great to know exactly the code you have that got it working for you, and see if there was something we were missing on our end that perhaps I didn't find in the documentation

**Comment by fxtentacle** [comment]
I have a file which reliably triggers this problem. I don't want to make it public, but I can send it to you for testing. The root cause seems to be the 'file' unix command that is used for file type validation:

# file image7244771971795038491.png
image7244771971795038491.png: x86 boot sector

# file -k -r image7244771971795038491.png
image7244771971795038491.png: x86 boot sector
- PNG image data, 1440 x 863, 8-bit/color RGB, non-interlaced


So by pure chance this PNG file also matches the signature for an x86 boot sector. That's why paperclip rejects it.

**Comment by fxtentacle** [comment]
Further research shows that the underlying libmagic is buggy when trying to get multiple mime types:

```
# file -b --mime image7244771971795038491.png
application/octet-stream; charset=binary

# file -b -k --mime image7244771971795038491.png
image/png; charset=binary
```

The second invocation *should have* returned all mime types.. BTW, this seems to be know for a while:
http://linux.die.net/man/1/mimetype
" The '--all' switch doesn't really show all matches, but only one per mime-typing method. This needs to be implemnted in the modules first. "

So this paperclip problem boils down to:
'file' is broken because 'libmagic' is broken. So does anyone know a suitable replacement for libmagic? or are there fixed branches around?

**Comment by acconrad** [comment]
Hi thoughtbot team,

I'm still having this same problem, except now we're on Rails 4.1.14 and Paperclip 4.3.1 (latest).

This is what our Model code looks like:

```ruby
  has_attached_file :logo,
    styles: { default: '165x165>', large: '330x330>' },
    hash_secret: '9rleB3FN2qAkjnH0uVhsKozJg1PacDO',
    url: '/media/:hash.:extension',
    storage: :s3,
    s3_credentials: "#{Rails.root}/config/s3.yml",
    s3_protocol: 'https'

  validates_attachment :logo,
    presence: true,
    content_type: { content_type: /\Aimage\/.*\Z/ }
```

The factory for this model looks like this:

```ruby
factory :our_object do
    name 'Name'
    logo { File.open('spec/support/sample_photo.png') }
  end
```

And the file mime type looks like this from the console

```bash
% file --mime-type spec/support/sample_photo.png
spec/support/sample_photo.png: image/png
```

I've also included the photo for you to download and try yourself.

![sample_photo](https://cloud.githubusercontent.com/assets/422184/11906359/ce66476c-a599-11e5-9779-b2473eb5428c.png)

**Comment by acconrad** [comment]
@tute are you able to replicate this now?

**Comment by tute** [comment]
This should be enough, thank you!

**Comment by plainlystated** [comment]
Is this still being worked on? It's still broken for me, on 4.3.6.  I'm getting several valid jpgs that come up as "application/vnd.openxmlformats-officedocument.spre..."

**Comment by fxtentacle** [comment]
@plainlystated  if you want a quick fix, just use my patch here: https://github.com/thoughtbot/paperclip/issues/1892

AFAIK, the official repo is still buggy.

**Comment by antonysastre** [comment]
Installing `imagemagick` resolved this for me. Error message confusing though.

**Comment by Yaroslav-F** [comment]
is this still being worked on? Replicated the issue when tried to upload image from twitter url: http://pbs.twimg.com/media/CryI70nWcAQ4EoW.jpg:large :disappointed:

**Comment by Preen** [comment]
still broken for me aswell.

**Comment by cherniv** [comment]
happened to me today, gem version 4.3.7

**Comment by JackWells** [comment]
In my case, this was caused by not having the 'file' package installed on the OS - should be installed by default in most cases, but not necessarily on hosting-servers (why it worked fine on my testing-machine).  Try in a console 'which file' and see if it is found.  Also check for imagemagick being installed, per the post above.

**Comment by cdaloisio** [comment]
Thanks @JackWells :+1: I'm running NixOS, and therefore have to ensure that my environment has all the relevant system packages. Including the `file` package solved this for me.

**Comment by mike-burns** [comment]
Thank you for reporting this. Unfortunately, we will be deprecating Paperclip and therefore will not have the bandwidth to address this issue.

**Comment by yorzi** [comment]
> The spec _still_ breaks reporting `Validation failed: Logo has contents that are not what they are reported to be`. I even tried stopping and starting `spring` in the event that something was cached, and this still does not solve things.

For anyone who is still encountering this kind of issue and it throws the similar error message: this https://github.com/kreeti/kt-paperclip/issues/102#issuecomment-1345693130 works for me. The `file` command might not be included correctly.
