### ISSUE TITLE
De-duplication files on storage

### ISSUE THREAD

**Issue by Hengjie** [thoughtbot/paperclip#1697]
Is it possible to add a layer into Paperclip that allows for du-duplication of stored files? For example, if two records have the same file (based on SHA2 hash), paperclip can point to the same file?

Obv, we must consider how we handle special cases such as deletion, replacing files, etc

**Comment by tute** [comment]
Closing for now for lack of activity, and because it's not an issue with paperclip. Please consider asking in StackOverflow, or reopening if you think that's the way. Thanks!
