### ISSUE TITLE
after_post_process callback called on invalid object

### ISSUE THREAD

**Issue by auswalk** [thoughtbot/paperclip#1698]
I'm creating a attachment , inside the model I call

```ruby
@asset = Asset.new(
  :attachable_id => params[:attachable_id],
  :attachable_type => params[:attachable_type],
  :data => params[:file_upload]
)
```

When I upload a file that's a content spoof, I get:

> [paperclip] Content Type Spoof: Filename libtool.gif (["image/gif"]), content type discovered from file command: text/x-shellscript. See documentation to allow this combination.

but my after_post_process method is still called. When I debugged inside the after_post_process method, self.valid? was false for the content spoofed and was valid for the legitimate attachment.

It should have never called the after_post_process when self.valid? == false according to the documents.

Thanks

**Comment by nhinze** [comment]
Has this been resolved? I'm having the same issue with PaperClip 4.3. I posted this StackOverflow question yesterday:

http://stackoverflow.com/questions/31665588/paperclip-is-not-executing-validates-attachment

**Comment by tute** [comment]
@jyurek do we want to update the documentation to describe this behavior, or change the behavior to what the docs say?

**Comment by auswalk** [comment]
I think the code should reflect what the documentation says. So it's a bug to me.

**Comment by tute** [comment]
What version of Rails are you using? Is this still an issue? We've been editing related code, and need reproduction steps.

**Comment by auswalk** [comment]
At the time, 3.2.16, since moved the 4.2.4 but left the code as is.

**Comment by tute** [comment]
Related with: https://github.com/thoughtbot/paperclip/issues/2178

**Comment by tute** [comment]
Closing in favor of related issue, which has more information. Thank you for reporting.
