### ISSUE TITLE
Lost data image when upload

### ISSUE THREAD

**Issue by HienNguyenAsnet** [thoughtbot/paperclip#1701]
I use paperclip to upload image to s3 through background job (redis) using resque gem. Sometime, some photo is lost data after upload.
Ex: https://50glam-staging.s3.amazonaws.com/products/images/000/024/237/small/8f207f17cce9d845436328fd93df6b28_best.jpg?1415815686

Original: http://bim.shopstyle.com/pim/8f/20/8f207f17cce9d845436328fd93df6b28_best.jpg

Rails version 4.0.4
Ruby version 2.0.0p353 (2013-11-22 revision 43784) [x86_64-linux]
Any help?

**Comment by tute** [comment]
Is this still an issue for you, @HienNguyenAsnet? I'll close it for now as this is not enough information for us to replicate, feel free to reopen if it continues to be a problem. Thanks!
