### ISSUE TITLE
Useless files will be never deleted when using `preserve_files`

### ISSUE THREAD

**Issue by kidlab** [thoughtbot/paperclip#1704]
I am using [Paranoia](https://github.com/radar/paranoia) for soft-delete, and use `preserve_files` to make them work together.

However, there is a problem when I want to perform a real delete (e.g `really_destroy!`) the files are not deleted! It means that useless files will stay there forever. 

Then I looked at the code of [Attachment](https://github.com/thoughtbot/paperclip/blob/master/lib/paperclip/attachment.rb#L555), I understood why it happened:

```ruby
    def queue_all_for_delete #:nodoc:
      return if !file?
      unless @options[:preserve_files]
        @queued_for_delete += [:original, *styles.keys].uniq.map do |style|
          path(style) if exists?(style)
        end.compact
      end
      # ...
    end
```

It's because files are never queued to delete!

**Comment by tute** [comment]
Thanks for your report. Closing in favor of duplicate https://github.com/thoughtbot/paperclip/issues/1326.
