### ISSUE TITLE
Timestamped URLs broken by escaping

### ISSUE THREAD

**Issue by kausters** [thoughtbot/paperclip#1706]
As of commit 804b4ed, attachment paths are no longer unescaped properly upon request (using development environment in this case). More specifically, `?`s (for timestamps) stay encoded as `%3F`s which breaks these attachment paths unless I manually unescape them again.

Temporary fix is is to use the previous commit (17cae0e7) where the issue no longer prevails.

**Comment by sgringwe** [comment]
I am also having this issue still on paperclip 4.2.1 using rails 4.2

**Comment by maxim** [comment]
Found the cause in delayed_paperclip: https://github.com/jrgifford/delayed_paperclip/issues/126

**Comment by MathijsK93** [comment]
Stil not fixed? I'm running rails 4.2.3 with Paperclip 4.2.3 and the question mark before style is still escaped. See:
```
http://localhost:3000/administrations/2/logo%3Fstyle=letter
```

**Comment by robotex82** [comment]
I'm having the same problems on rails 4.2.4 and paperclip 4.3.1 (from gitbhub) in combination with paperclip_database.

**Comment by philipdesmedt** [comment]
I'm also still getting this issue on paperclip 4.3.1...

**Comment by KevinColemanInc** [comment]
:+1:

**Comment by KevinColemanInc** [comment]
for future people, you can set a flag on has_attachments

https://github.com/thoughtbot/paperclip/blob/f94ad973a32c80fcc6993e0098c6b7c192a8a64b/lib/paperclip/attachment.rb#L70

**Comment by jumph4x** [comment]
@KevinColemanInc thank you *very* much, sir.

**Comment by Undistraction** [comment]
It looks like Paperclip is url encoding the url **including** timestamp, so the `?` is turned to `%3F`. Surely it should encode the url **the** add the timestamp.
