### ISSUE TITLE
Thread safety bug: ENV clobbered

### ISSUE THREAD

**Issue by balexand** [thoughtbot/paperclip#1709]
There is a thread safety issue that causes `ENV` to get clobbered periodically. Once this happens, `ENV['PATH']` will be blank so all future calls to command-line commands will fail. This includes all calls to [`Paperclip.run`](https://github.com/thoughtbot/paperclip/blob/v4.2.0/lib/paperclip/helpers.rb#L25). The root of the bug is in the Cocaine gem's unsafe `with_modified_environment` method.

I've produced this bug in Sidekiq, but it should affect any multithreaded environment (like Puma). To reproduce using Sidekiq, create a model and worker like:

```ruby
# app/models/image.rb
class Image < ActiveRecord::Base
  has_attached_file :image

  validates_attachment_content_type :image,
    content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif"]
end

# app/workers/create_image_worker.rb
class CreateImageWorker
  include Sidekiq::Worker
  sidekiq_options retry: false

  def perform
    Rails.logger.info "***PATH before: #{ENV['PATH']}"
    Image.create! image: File.new(Rails.root + 'test/fixtures/example.jpg')
  ensure
    Rails.logger.info"***PATH after: #{ENV['PATH']}"
  end
end

# in console
10000.times { CreateImageWorker.perform_async }
```

Then start the Sidekiq server and let it run. On my iMac with Sidekiq concurrency set to 20, the failure usually happens within 10-20 minutes. I've never seen it process all 10,000 tasks without failing. After the first failure, all subsequent tasks will fail until the Sidekiq server is restarted.

I've created a dummy Rails app that demonstrates this bug. See https://github.com/balexand/paperclip_thread_issue/pull/1

The following backtrace is an example of what can go wrong when calls to `Paperclip.run` fail:

```
{"retry"=>true, "queue"=>"default", "class"=>"CreateImageWorker", "args"=>[], "jid"=>"fe1fe7da77c8d89bf1d3c750", "enqueued_at"=>1416683367.3800461, "error_message"=>"Validation failed: Image Could not run the `identify` command. Please install ImageMagick., Image Could not run the `identify` command. Please install ImageMagick., Image Could not run the `identify` command. Please install ImageMagick., Image has an extension that does not match its contents", "error_class"=>"ActiveRecord::RecordInvalid", "failed_at"=>1416683651.958688, "retry_count"=>1, "retried_at"=>1416684697.969991}
Validation failed: Image Could not run the `identify` command. Please install ImageMagick., Image Could not run the `identify` command. Please install ImageMagick., Image Could not run the `identify` command. Please install ImageMagick., Image has an extension that does not match its contents
/Users/balexand/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activerecord-4.1.8/lib/active_record/validations.rb:57:in `save!'
/Users/balexand/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activerecord-4.1.8/lib/active_record/attribute_methods/dirty.rb:29:in `save!'
/Users/balexand/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activerecord-4.1.8/lib/active_record/transactions.rb:273:in `block in save!'
/Users/balexand/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activerecord-4.1.8/lib/active_record/transactions.rb:329:in `block in with_transaction_returning_status'
/Users/balexand/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activerecord-4.1.8/lib/active_record/connection_adapters/abstract/database_statements.rb:201:in `block in transaction'
/Users/balexand/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activerecord-4.1.8/lib/active_record/connection_adapters/abstract/database_statements.rb:209:in `within_new_transaction'
/Users/balexand/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activerecord-4.1.8/lib/active_record/connection_adapters/abstract/database_statements.rb:201:in `transaction'
/Users/balexand/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activerecord-4.1.8/lib/active_record/transactions.rb:208:in `transaction'
/Users/balexand/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activerecord-4.1.8/lib/active_record/transactions.rb:326:in `with_transaction_returning_status'
/Users/balexand/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activerecord-4.1.8/lib/active_record/transactions.rb:273:in `save!'
/Users/balexand/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activerecord-4.1.8/lib/active_record/validations.rb:41:in `create!'
/Users/balexand/git/paperclip_thread_issue/app/workers/create_image_worker.rb:6:in `perform'
...
```

I've also been able to reproduce this bug on an Ubuntu 14.04 EC2 instance and I originally saw it when using Sidekiq on Heroku.

This monkey patch fixes the issue: https://github.com/balexand/paperclip_thread_issue/pull/2/files. It disables the Cocaine gem's unsafe `with_modified_environment` method. I've verified that this fix works by running 100,000 tasks in the example app above. Also, after deploying the monkey patch to our staging environment, we were finally able to finish processing a large batch of images that kept failing due to this bug.

There is no thread-safe way to modify and revert `ENV`. To fix this properly, the Cocaine gem will need to stop modifying `ENV`, or the Paperclip gem will need to remove Cocaine as a dependency.

Note that in https://github.com/thoughtbot/cocaine/issues/16 the thread-safety issues in Cocaine were addressed. But in https://github.com/thoughtbot/cocaine/commit/ba7630ab83945a4eb11d3e0a30fe3664bd3d9a84 the offending `with_modified_environment` was added back (a regression).

**Comment by calebthompson** [comment]
@jyurek is this resolved? Looks like the commit made it in?
