### ISSUE TITLE
paperclip doesn't seem to accept the "accept" tag

### ISSUE THREAD

**Issue by MartinB83** [thoughtbot/paperclip#1712]
I have this file_field working perfectly and upload my image to my AWS bucket:
<%= f.file_field :picture, :id => "fileToUpload", :onchange => "check_file()" %>

However, this does not work - the picture is not uploaded to my AWS bucket:
<%= f.file_field :picture, :id => "fileToUpload", accept: 'image/png,image/gif,image/jpeg,image/jpg,application/pdf,application/zip', :onchange => "check_file()" %>

**Comment by tute** [comment]
Is this still an issue for you with paperclip, @MartinB83?

**Comment by MartinB83** [comment]
Yes but I do a javascript validation now after file chosen - find that more user friendly anyways.

**Comment by tute** [comment]
Will close this issue for now then. Thank you!
