### ISSUE TITLE
expiring_url and get_http_url method

### ISSUE THREAD

**Issue by nonsense** [thoughtbot/paperclip#1714]
Hello,

I am trying to setup Riak CS with Paperclip and Fog over SSL, which has been working so far. But I kept on getting an "http" expiring_url, when I had specified the schema to be "https" in :fog_credentials. I browsed through the code and noticed the following chunk in `/lib/paperclip/storage/fog.rb`:

```
        if path(style_name) && directory.files.respond_to?(:get_http_url)
          expiring_url = directory.files.get_http_url(path(style_name), time)
```

I can see that this is disregarding the schema and just returning an http url. Is there a way to get an https expiring_url, or this should be fixed with a PR ?

**Comment by tute** [comment]
@nonsense if this is till an issue with paperclip I think it should be addressed in a PR. Thanks for reporting!

**Comment by f1sherman** [comment]
@nonsense I also noticed this issue and the PR to fix it has been merged:
https://github.com/thoughtbot/paperclip/pull/1859

So hopefully a new version of the paperclip gem that fixes this issue will be released shortly!

**Comment by tute** [comment]
Thanks @f1sherman! Meanwhile you can point the Gemfile to current GitHub's master, from which we'll base off a new 4.3.0 version.
