### ISSUE TITLE
Delay deletion files on s3

### ISSUE THREAD

**Issue by albertopriore** [thoughtbot/paperclip#1717]
I'm trying to find a way to delay also the deletion of s3 files.
Do anyone have a solution for that?

Thanks in advance!
Alberto

**Comment by dmitry** [comment]
We are just enabled `preserve_files` option (https://github.com/thoughtbot/paperclip#file-preservation-for-soft-delete). We don't have much deletions...

**Comment by albertopriore** [comment]
Ok @dmitry, but later how can I delete the preserved files definitely?

**Comment by dmitry** [comment]
I guess there are no easy ways to do that. I would do that with paranoia gem (https://github.com/radar/paranoia) and https://github.com/thoughtbot/paperclip/blob/master/lib/paperclip/attachment.rb#L557 embedded in a model callback before real deletion, that can happen in a recurring job (every month or week). Currently we are just storing files and database links (through paranoia like gem). Once we want to destroy all them, we just will need to write some small little modified code taken from `attachment.rb` (code above).

**Comment by tute** [comment]
This issue describes a very specific use case. I suggest that you ask about it in https://stackoverflow.com/questions/tagged/paperclip, which will get attention
from more people than in this issue tracker.

Closing for now, and happy to continue discussion or reopen if we find improvements to make in doorkeeper itself.

Thank you for your input! ❤️
