### ISSUE TITLE
Don't store original filename.

### ISSUE THREAD

**Issue by Exoth** [thoughtbot/paperclip#1718]
Is there any reason why paperclip forces you to store original filename? I don't use `:filename` in paths, so I don't need to keep the original filename at all, so it would be great, if my DB doesn't have to keep any useless data.

**Comment by dmitry** [comment]
It used for checking presence of the attachment:

- https://github.com/thoughtbot/paperclip/blob/c46b40b973a66eb8ac454c1d22e5df15da66d7c3/lib/paperclip/storage/fog.rb#L60
- https://github.com/thoughtbot/paperclip/blob/dca87ec5d8038b2d436a75ad6119c8eb67b73e70/lib/paperclip/storage/filesystem.rb#L29

**Comment by Exoth** [comment]
But there are other fields that can be used to check for presence of attachment like file_size.

**Comment by dmitry** [comment]
As I remember it's working like that from the initial paperclip release. Propose the PR, I think @thoughtbot guys will agree to merge it.

**Comment by tute** [comment]
ping @jyurek

**Comment by jyurek** [comment]
Basically, yeah, it's been the requirement since the beginning that the file name is required to show that an attachment exists. I suppose you could use something else? If you want to submit a PR we'll evaluate it.
