### ISSUE TITLE
Directory not empty @ dir_s_rmdir Paperclip

### ISSUE THREAD

**Issue by btrihatmaja** [thoughtbot/paperclip#1720]
Hi, I got this error when trying to use `disable_with` in my view, paperclip works normally with normal submit button. I don't think it is permission issue since I can upload normally when using normal submit button.

For the details please see [here](http://stackoverflow.com/questions/27409564/directory-not-empty-dir-s-rmdir-paperclip)

Thanks ! :smiley:

**Comment by tute** [comment]
@btrihatmaja is this still an issue for you? How can we fix it in paperclip?

**Comment by tute** [comment]
@jyurek might have some insight on this. Jon, check the StackOverflow question for the detailed explanation.

**Comment by btrihatmaja** [comment]
I lost track on this issue, since it was from a long time ago. I think I found the workaround. :sweat_smile:  I will try to replicate. :smiley:

**Comment by tute** [comment]
Thanks! If you can replicate we'll reopen. :+1:
