### ISSUE TITLE
(4.2.1) `Paperclip::Storage::S3#copy_to_local_file` has size 0

### ISSUE THREAD

**Issue by slepkin** [thoughtbot/paperclip#1729]
This bug appears in 4.2.1, but not 4.2.0.

Context: Our `Asset` object has a `pdf` attachment.

#### 4.2.1
```
2.1.5 :002 > asset = Asset.find(730203)
 => #<Asset id: 730203, created_at: "2014-12-16 19:50:27", updated_at: "2014-12-16 19:50:27", pdf_file_name: "pdf_e0ab3c21-310f-4ee8-811c-6165438ff9e1.pdf", pdf_content_type: "application/pdf", pdf_file_size: 61458, pdf_updated_at: "2014-12-16 19:50:27"> 
2.1.5 :003 > asset.pdf.size
 => 61458 
2.1.5 :004 > asset.pdf.copy_to_local_file(:original, "tmp/test.pdf")
[paperclip] copying assets/pdfs/000/730/203/original/pdf_e0ab3c21-310f-4ee8-811c-6165438ff9e1.pdf to local file tmp/test.pdf
[AWS S3 200 0.777251 0 retries] get_object(:bucket_name=>"assets",:key=>"assets/pdfs/000/730/203/original/pdf_e0ab3c21-310f-4ee8-811c-6165438ff9e1.pdf")  

 => "%PDF-1.4\n1 0 obj\n..." # Long string
2.1.5 :005 > File.open("tmp/test.pdf").size
 => 0 
```

#### 4.2.0
```
2.1.5 :002 > asset = Asset.find(730203)
 => #<Asset id: 730203, created_at: "2014-12-16 19:50:27", updated_at: "2014-12-16 19:50:27", pdf_file_name: "pdf_e0ab3c21-310f-4ee8-811c-6165438ff9e1.pdf", pdf_content_type: "application/pdf", pdf_file_size: 61458, pdf_updated_at: "2014-12-16 19:50:27"> 
2.1.5 :003 > asset.pdf.size
 => 61458 
2.1.5 :004 > asset.pdf.copy_to_local_file(:original, "tmp/test.pdf")
[paperclip] copying assets/pdfs/000/730/203/original/pdf_e0ab3c21-310f-4ee8-811c-6165438ff9e1.pdf to local file tmp/test.pdf
[AWS S3 200 0.777251 0 retries] get_object(:bucket_name=>"assets",:key=>"assets/pdfs/000/730/203/original/pdf_e0ab3c21-310f-4ee8-811c-6165438ff9e1.pdf")  

 => nil 
2.1.5 :005 > File.open("tmp/test.pdf").size
 => 61458 
```

Incidentally, `Paperclip.io_adapters.for(asset.pdf).size` is `0` in 4.2.1, but `61458` in 4.2.0. Is there a chance that c0b7d08c is the culprit?

**Comment by forrestblount** [comment]
I was having an issue copying attachments from one object to another due to imagemagick identify failing and updating the aws-sdk gem corrected the issue so I second your suggestion to update the dependency.

**Comment by ainame** [comment]
@soramugi @slepkin 

I've found the source of this problem.
`aws-sdk` have been merged the changesets of s3_object's chunk based `read` method in `v1.6.3`.
So, it will be empty result by reading data when using sdk's version lower than `v1.6.3`.
(`read` method can receive block object, but don't touch it.)

you can see following this:
https://github.com/aws/aws-sdk-ruby/commit/9877f13179fdffaa31484416ecf690d52597a767#diff-fee108f35c5530990b57dfa537020dc5L713

Then, paperclip must requires aws-sdk's version higher than v1.6.3 in gemspec.
https://github.com/thoughtbot/paperclip/blob/master/paperclip.gemspec#L35

**Comment by slepkin** [comment]
Thanks for digging into this, @ainame! For clarity, do you mean that Paperclip should require _at least_ aws-sdk 1.6.3?

**Comment by ainame** [comment]
@slepkin yes.

**Comment by schrockwell** [comment]
Thank you @slepkin for the detailed findings. I was using the exact problematic combination of Paperclip (4.2.1) and aws-sdk (1.5.8). Upgrading aws-sdk to 1.6.9 has resolved the problem.

**Comment by maclover7** [comment]
Would one of you be willing to send in a PR upgrading the required aws-sdk version? Thanks!

**Comment by schrockwell** [comment]
@maclover7 Done. I think I did it twice. You can accept one PR and trash the other.

**Comment by jyurek** [comment]
Merged in @schrockwell's change. I'm going to close this, but please let us know if there's still an issue. Thanks, all.

**Comment by dmons** [comment]
Guys, thanks a lot this! You saved a lot of time for me!
