### ISSUE TITLE
convert_options does not always get applied (fix suggested)

### ISSUE THREAD

**Issue by harley** [thoughtbot/paperclip#173]
Hello,
# Bug

Say if I have:
<code>has_attached_file :paper, :styles => {:png_version => ["", :png] },
   :convert_options => {:all => "-density 100"}
</code>

This should convert a file to png with density (ppi) as 100, but no, convert only uses the default 72ppi.
# Reason

The problem is with how imagickmagic's "convert" takes the arguments. Perhaps this is a bug with "convert"? It's syntax is <code>convert [input-options] input-file [output-options] output-file</code> but the documentation is not clear what are input-options and what are output-options. Try the following in the command line:
1. convert some_file.pdf -density 100 output.png
   vs
2. convert -density 100 some_file.pdf output.png

Only the 2nd one does what you expects convert to do, the 1st command just ignores "-density 100" altogether.
# Investigation

What paperclip has in thumbnail.rb right now (line 48-53 in thumbnail.rb)
<code>command = <<-end_command
        #{ source_file_options }
        "#{ File.expand_path(src.path) }[0]"
        #{ transformation_command }
        "#{ File.expand_path(dst.path) }"
      end_command
</code>

I tried specifiying :source_file_options instead of convert_options in the has_attached_file function but source_file_options always seem to be empty in "def make" of thumbnail.rb.

My current solution is just writing my own processor and use it instead of thumbnail.rb.

Can somebody help verify if this happens to you too?

Thank you
Harley

**Comment by md-farhan-memon** [comment]
Hi!
I have a similar issue but not during new upload but reprocessing. I had to change convert_options for already existing styles, the options are applied when new images are uploaded, however, when I call Image.last.photo.reprocess! from console the conversion isn't applied. Gem v4.3.7, ruby 2.2.4p230 and Rails 3.2.22. Following are the options I have.

has_attached_file :photo, :styles => { 
:thumb => "50x50#", 
:small => "225x257#",
:small_m => "225x257",
:small_mo => "151x173#",
:large => "350x400>", 
:large_m => "350x400>", 
:zoom => "800x1100"},

:convert_options => {
  :thumb => "+profile -strip -quality 70 -interlace Plane -units PixelsPerInch -density 1x1",
  :small => "+profile -strip -quality 70 -interlace Plane -units PixelsPerInch -density 1x1 -background white -flatten +matte -gravity center",
  :small_m => "+profile -strip -quality 40 -interlace Plane -units PixelsPerInch -density 1x1 -background white -flatten +matte -gravity center",
  :small_mo => "+profile -strip -quality 70 -interlace Plane -units PixelsPerInch -density 1x1 -background white -flatten +matte -gravity center",
  :large => "+profile -strip -interlace Plane -units PixelsPerInch -density 1x1",
  :large_m => "+profile -strip -quality 70 -interlace Plane -units PixelsPerInch -density 1x1 -background white -flatten +matte -gravity center",
  :zoom => "+profile -strip -quality 70 -interlace Plane -units PixelsPerInch -density 1x1",
}

**Comment by zamarshi** [comment]
@md-farhan-memon Did you come up with a solution for this?
