### ISSUE TITLE
Attachments on S3 should not escape '?' in timestamped URLs

### ISSUE THREAD

**Issue by JuanitoFatas** [thoughtbot/paperclip#1732]
Hello paperclip :wave: ,
# Updated

See https://github.com/thoughtbot/paperclip/issues/1732#issuecomment-67282361 for new issue description, ignore below.
## :arrow_down: Ignore :see_no_evil:

Rails 4.1.8, Ruby 2.2.0-preview1, Paperclip 4.2.0.

When using S3 to store an image named `Screenshot 2014-11-24 22.39.21.png`, Paperclip generated URL is `Screenshot+2014-11-24+22.39.21.png`. :cry: The correct url on s3 should be  `Screenshot+2014-11-24%2B22.39.21.png`

``` ruby
> image.file.url
=> "https://bucket.s3.amazonaws.com/images/files/000/000/023/original/Screenshot+2014-11-24+22.39.21.png?1418795063"
```

Apply `gsub('+', '%2B')`

``` ruby
> image.file.url.gsub('+', '%2B')
=> "https://bucket.s3.amazonaws.com/images/files/000/000/023/original/Screenshot%2B2014-11-24%2B22.39.21.png?1418795063"
```

This url works but I need to `gsub` everywhere. :sweat: 

Related issue: https://github.com/thoughtbot/paperclip/issues/563

Thank you in advance! :bow:

**Comment by gmcnaughton** [comment]
I'm seeing this with rails 3.2.21 / paperclip 4.2.2.  Timestamped urls have `%3F` instead of `?`.

Also, `?`s in my custom `:default_url` interpolation get escaped as well (so `default_url: "/public/missing.png?foo=bar"` results in `/public/missing.png%3Ffoo=bar`)

**Comment by ivanoblomov** [comment]
Looks like this was [already fixed!](https://github.com/thoughtbot/paperclip/pull/2396)
