### ISSUE TITLE
rails 4.2 errors

### ISSUE THREAD

**Issue by homanchou** [thoughtbot/paperclip#1736]
Trying to upgrade a rails project to rails 4.2.  Noticed that I was getting an error on saving the model

```
ProductImage.create
NameError: undefined local variable or method `create' for #<ProductImage:0x007f9038eb2bc8>
```

I thought this might be related to some after save hooks, so I removed everything from the model except:

```
class ProductImage < ActiveRecord::Base

  belongs_to :product

  has_attached_file :file

end
```

But from the re-started console:

```
p = ProductImage.create
   (0.2ms)  BEGIN
  SQL (0.5ms)  INSERT INTO "product_images" ("created_at", "updated_at") VALUES ($1, $2) RETURNING "id"  [["created_at", "2014-12-19 21:18:10.145961"], ["updated_at", "2014-12-19 21:18:10.145961"]]
   (0.7ms)  COMMIT
   (0.1ms)  BEGIN
  SQL (0.2ms)  DELETE FROM "product_images" WHERE "product_images"."id" = $1  [["id", 6107]]
   (3.2ms)  COMMIT
   (0.1ms)  BEGIN
   (0.1ms)  COMMIT
   (0.1ms)  BEGIN
   (0.1ms)  COMMIT
   (0.1ms)  BEGIN
   (0.1ms)  COMMIT
   (0.1ms)  BEGIN
   (0.1ms)  COMMIT
   (0.1ms)  BEGIN
   ....  SystemStackError: stack level too deep
```

Get infinite loop happening somewhere.  Any ideas?  I'm using rails 4.2.rc3 and paperclip 4.2.1

In my rails 4.1 branch everything works fine.

**Comment by inspire22** [comment]
Still seems like a bug in paperclip imo, if adding Array#to_s causes a silent infinite loop.  Just spent 6 hours trying to track this down myself as well.
