### ISSUE TITLE
update doc: MIME::Types#index_extensions is deprecated and will be private.

### ISSUE THREAD

**Issue by zhangpy** [thoughtbot/paperclip#1737]
The warning shows up when I copy it from document. 
But I don't find method to avoid it

mime-types (2.4.3)

**Comment by sb89** [comment]
I've come across this too, what should be used instead?

**Comment by mehulkar** [comment]
anyone find a solution to this yet?

**Comment by tute** [comment]
Related ruby-mime-types issue: https://github.com/mime-types/ruby-mime-types/issues/88

It seems there will be no replacement. Should we remove it from the README?

**Comment by tute** [comment]
We need to update the docs, to solve that issue with different calls.

**Comment by mehulkar** [comment]
Wondering if anyone has worked around this or come to a resolution yet?

**Comment by tute** [comment]
@jyurek?

**Comment by moritzschepp** [comment]
Instead of

    text_plain = MIME::Types["text/plain"].first
    text_plain.extensions << "foo"
    MIME::Types.index_extensions text_plain

it seems you can use

    text_plain = MIME::Types["text/plain"].first
    text_plain.add_extensions "foo"

**Comment by bdewater** [comment]
On mime-types 2.99.1 I still need to index_extensions method call but that gives a deprecation warning. The example in https://github.com/thoughtbot/paperclip/issues/1924#issuecomment-182024240 by wrkrb33 seems like the better way of solving this.

**Comment by aCandidMind** [comment]
Isn't the old way of adding extensions but using the current v3.1 API less error-prone than the `content_type_mappings` in that you don't have to specify all (sometimes OS-dependent) MIME types for the desired extensions? Note that in [wrkrb33's solution](https://github.com/thoughtbot/paperclip/issues/1924#issuecomment-182024240) already linked to above, all zip MIME types had to be explicitly mentioned. Or the other [problems](https://github.com/thoughtbot/paperclip/issues/1924#issuecomment-218141097) mentioned in that same thread.

Here's the relevant mime_types changelog entry for 3.0, which indicates there's now an API that suits paperclip's use case.
> When extensions are set or modified with add_extensions, the primary registry will be informed of a need to reindex extensions. Resolves [#84](https://github.com/mime-types/ruby-mime-types/issues/84).

from
https://github.com/mime-types/ruby-mime-types/blob/master/History.rdoc#30--2015-11-21

`add_extensions` now in turn calls `reindex_extensions`
https://github.com/mime-types/ruby-mime-types/blob/v3.1/lib/mime/type.rb#L244
