### ISSUE TITLE
Just because Rails is defined does not mean Rails.env is

### ISSUE THREAD

**Issue by betesh** [thoughtbot/paperclip#1739]
Bug on https://github.com/thoughtbot/paperclip/blob/v4.2.1/lib/paperclip/storage/s3.rb#L291

See https://github.com/rails/rails-html-sanitizer/issues/25 and https://github.com/rails/rails-html-sanitizer/issues/26

**Comment by jyurek** [comment]
Merged a fix for this. Thanks for the report!
