### ISSUE TITLE
Validation Failing even though do_not_validate specified

### ISSUE THREAD

**Issue by DaveCollinsJr** [thoughtbot/paperclip#1740]
Hello,
  Absolutely love paperclip!!

  Having an issue when we are scraping log files from distant embedded Linux machines.  Have upgraded to Paperclip 4.2.1, aws-sdk 1.60.2 while troubleshooting this problem...

  We have a DeviceLogFile model that is setup as follows:

```ruby
  has_attached_file :log,
                    url: 'device_log_file/:id/:basename:extension',
                    path: 'device_log_file/:id/:basename:extension'

  validates :device_id, presence: true

  do_not_validate_attachment_file_type :log
```

Even with the do_not_validate_attachement_file_type it still, sometimes, gives us the error: **has an extension that does not match its contents**.

Details from our logs:

```ruby
» 21:00:32.179  [paperclip] Content Type Spoof: Filename 0FB478_20141230020015_log_1.txt (["text/plain"]), content type discovered from file command: inode/x-empty. See documentation to allow this combination.
» 21:00:32.179  Command :: PATH=/usr/bin:$PATH file -b --mime '/tmp/531a60f01eb1ee0c75a5bd18d9298b4b20141230-25914-3fol8p.txt'
» 21:00:32.179  [paperclip] Content Type Spoof: Filename 0FB478_20141230020015_log_1.txt (["text/plain"]), content type discovered from file command: inode/x-empty. See documentation to allow this combination.
» 21:00:32.179  (0.8ms)  ROLLBACK
» 21:00:32.179  (4.4ms)  BEGIN
» 21:00:32.179  Command :: PATH=/usr/bin:$PATH file -b --mime '/tmp/531a60f01eb1ee0c75a5bd18d9298b4b20141230-25914-c4ln4p.txt'
» 21:00:32.179  [paperclip] Content Type Spoof: Filename 0FB478_20141230020015_log_1.txt (["text/plain"]), content type discovered from file command: inode/x-empty. See documentation to allow this combination.
» 21:00:32.179  (0.9ms)  ROLLBACK
» 21:00:32.179  (DeviceLogShippingWorker.perform) Inner Error Validation failed: Log has an extension that does not match its contents
```

I've tried adding inode/x-empty to the list of approved content-types (when we were validating this attachment type) but that didn't work either.

Suggestions?  

Thanks,
Dave

**Comment by DaveCollinsJr** [comment]
Any help or suggestions on this please?

**Comment by jyurek** [comment]
That validation message is from the media type spoofing. The `do_not_validate_attachment_file_type` call is to turn off the requirement that `content_type` or `file_name` be validated.

You want this setting:

    has_attached_file :log, validate_media_type: false, [...]

This will turn off that validation.
