### ISSUE TITLE
Misleading error `Paperclip::Error` and method name `ensure_required_accessors!`

### ISSUE THREAD

**Issue by jmera** [thoughtbot/paperclip#1745]
The [error](https://github.com/thoughtbot/paperclip/blob/master/lib/paperclip/attachment.rb#L406) raised in `ensure_required_accessors!` can be misleading.  The method checks for response to getters and setters for each field.  That doesn't necessarily mean that the model is missing `attr_accessor` for that method.  As an example: If the user is running Rails, they may have just forgotten to run their migrations.  Instead the error should read something like:

`"#{@instance.class} model does not respond to '#{name}_#{field}' and/or '#{name}_#{field}='"`

The method should also be renamed to something like `ensure_required_responses!`.

Am I missing something here? If not, I can submit a quick PR.

**Comment by tute** [comment]
Please do submit a PR and lets discuss over the concrete changeset. Thank you, @jmera!
