### ISSUE TITLE
Include Simple Form example in Readme

### ISSUE THREAD

**Issue by ResumeNothing** [thoughtbot/paperclip#1746]
It might be nice if there were an example of using Paperclip with Simple Form in the Readme. Maybe something like this:

Edit and New Views

```ruby
<%= form_for @user, :url => users_path, :html => { :multipart => true } do |form| %>
  <%= form.file_field :avatar %>
<% end %>
```

If you're using Simple Form:

```ruby
<%= simple_form_for @user, :html => { :multipart => true } do |form| %>
  <%= form.input :avatar %>
<% end %>
```

This might save someone time as they might not be aware that this syntax is supported out of the box.

**Comment by tute** [comment]
This is done: https://github.com/thoughtbot/paperclip/blob/52543bde7ac24cd8d052ceb5f73fb2b7d1e0851a/README.md#edit-and-new-views-with-simple-form.
Thanks!

**Comment by ResumeNothing** [comment]
Great, thanks!
