### ISSUE TITLE
media_type_spoof_detector and regexp

### ISSUE THREAD

**Issue by pierre-alain-b** [thoughtbot/paperclip#1751]
Hello all,

First of all, thanks for the hard work on Paperclip, this is a very good gem!

Now, here is the situation I'm facing:
- users are uploading (through paperclip) .eml file (email file from Thunderbird)
- sometimes the .eml is mapped as text/html and sometimes as text/plain by the *file* command 
- I've added this to my initializer file:
```
    Paperclip.options[:content_type_mappings] = {
      :eml => "text/plain"
    }
```
And then it works when it is detected as text/plain. But when it is detected as text/html, I have the "spoofing" warning.

I've not found anywhere a way to add two different exceptions for the same extension.

If I am right, this is where the stuff is checked:
https://github.com/thoughtbot/paperclip/blob/dca87ec5d8038b2d436a75ad6119c8eb67b73e70/lib/paperclip/media_type_spoof_detector.rb#L33
Wouldn't it be a good idea to check with a regexp?

This line:
```
    mapped_content_type != calculated_content_type
```
could become:
```
    return true if mapped_content_type.nil!
    ( %r{#{mapped_content_type}} =~ calculated_content_type ).nil?
```

and in the configuration, one willing to authorize several exceptions may do:
```
    Paperclip.options[:content_type_mappings] = {
      :eml => "text/plain|text/html"
    }
```

I would be happy to put that in the code, test it and then submit a pull request. The only issue is I do not know (yet) how I can test it... basically, I do not know how to generate a test gem from my cloned paperclip repo and embed it (for tests purpose) in my application...

1) What do you think with the code change? Does it make sense to you?
2) I'd be happy to help and test and then submit a pull request if it works as advertised if someone guides me through the gem devt/test basics

Thanks for your feedback
Pierre-Alain

**Comment by tmingos** [comment]
+1

**Comment by pierre-alain-b** [comment]
Apparently this is fixed with https://github.com/thoughtbot/paperclip/pull/1810 !
