### ISSUE TITLE
Issue with Rails 4.2 / Foreigner?

### ISSUE THREAD

**Issue by Ganasist** [thoughtbot/paperclip#1753]
I'm getting this error when trying to run the migration:

    NoMethodError: undefined method `column' for #<Foreigner::ConnectionAdapters::ForeignKeyDefinition:

Standard migration (I think):

    def change
      add_attachment :bids, :pdf
    end

**Comment by tute** [comment]
@Ganasist IS this still an issue for you? How can we replicate it?

**Comment by Ganasist** [comment]
I believe this issue is fixed, thanks.

**Comment by deepakm-webonise** [comment]
Rails 4.2 has added foreign key support you don't need `foreigner` gem

If you have this entry in your `Gemfile` remove it

    gem 'foreigner'

http://edgeguides.rubyonrails.org/4_2_release_notes.html#foreign-key-support
