### ISSUE TITLE
How to force paperclip to an image which is not persisted in the db ?

### ISSUE THREAD

**Issue by chrisvel** [thoughtbot/paperclip#1757]
I want to have paperclip resize an image which is not persisted in any database. 

It uses an image tag ```image_tag("no-image.png", alt: "noimage")``` so I am not quite sure how do I process it through a ```:medium``` paperclip tag. I tried ```image_tag(("no-image.png").url(:medium), alt: "noimage")``` but it fails hard.

**Comment by dmitry** [comment]
Just setup correctly `default_url` with `:style` interpolation.

**Comment by chrisvel** [comment]
Can you please explain a bit more? I don't get it.

**Comment by dmitry** [comment]
https://github.com/thoughtbot/paperclip/blob/dca87ec5d8038b2d436a75ad6119c8eb67b73e70/spec/paperclip/paperclip_missing_attachment_styles_spec.rb

**Comment by chrisvel** [comment]
not getting what does it have to do with my problem

**Comment by chrisvel** [comment]
Can anyone please give a short example ?

**Comment by tute** [comment]
@chrisvel can you further explain what exactly you need? What code would you like to run and it would desirably work?
