### ISSUE TITLE
Connection Reset by Peer when uploading a file larger than 1MB

### ISSUE THREAD

**Issue by milesmatthias** [thoughtbot/paperclip#1762]
I'm using paperclip 4.2.0 in my Rails 4.1.8 / Ruby 2.1.4 application, configured to upload to S3. Anytime I try to upload a file that's larger than 1MB, I get a "Connection Reset by Peer" error.

I've googled and searched the paperclip issues with no luck. Any ideas on how to address this?

**Comment by jyurek** [comment]
Can you upload a file manually to S3 that's bigger than 1MB? Can you do it locally in a dev server (or if you're already in the dev environment, on a different machine)?

**Comment by milesmatthias** [comment]
Thanks for the response @jyurek.

I can do it locally and I can upload a file manually to S3 that's bigger than 1MB. I also upped our production servers to have 4GB of memory today (mainly for load, not this issue), but that didn't seem to affect uploading the images.

I'm considering switching to a different gem that supports direct S3 uploading, unless paperclip supports this?

**Comment by milesmatthias** [comment]
Not sure why my users were reporting this error message, but I got this working by increasing nginx's client max body size. So nothing to do with paperclip.

Thanks for responding though and great work on the project!

**Comment by jyurek** [comment]
Awesome, glad to hear it!
