### ISSUE TITLE
Paperclip setting file_name to ActionDispatch Object

### ISSUE THREAD

**Issue by thisiserik** [thoughtbot/paperclip#1763]
Currently working on an API, and this the response that I get when I view the serialized object.
{
id: 16,
user_id: 75,
created_at: "2015-02-05T01:45:20.238Z",
updated_at: "2015-02-05T01:45:20.238Z",
**uploaded_file_file_name: "#<ActionDispatch::Http::UploadedFile:0x007ffbcb20c118>",**
uploaded_file_content_type: null,
uploaded_file_file_size: null,
uploaded_file_updated_at: null
}.

What could be causing this? If any more details necessary, please ask.

**Comment by tute** [comment]
Hi @thisiserik. Is this still an issue for you? [How can we reproduce this issue?](http://yourbugreportneedsmore.info/)

**Comment by thisiserik** [comment]
@tute Hello! This is no longer an issue; rather, some klutzy move on my part. I figured it out. Thanks tho!
