### ISSUE TITLE
How to move avatar files to another server

### ISSUE THREAD

**Issue by ezmiller** [thoughtbot/paperclip#1766]
How would I transfer avatar files associated with a rails app that uses paper clip to a different server? Is there a directory that I can copy over? If I have migrated the database will paperclip still be able to find the files?

**Comment by maclover7** [comment]
Check out this rake task: [https://github.com/thoughtbot/paperclip/wiki/Changing-attachment-:path](https://github.com/thoughtbot/paperclip/wiki/Changing-attachment-:path)
