### ISSUE TITLE
How to disable all mime type checks?

### ISSUE THREAD

**Issue by akshetpandey** [thoughtbot/paperclip#1767]
My code lets admin users upload text/7z files which are quite large and are not displayed to users but only used in background processing tasks.

The admins who upload the files are trusted and there is nothing they are do to compromise the safety of users with the uploaded file.

For my use case the mime type check is quite expensive as it runs on huge files (~40 MB. I would like disable to it and not store it in db either. How would I do that?

**Comment by solisoft** [comment]
````
require 'paperclip/media_type_spoof_detector'         
module Paperclip         
 class MediaTypeSpoofDetector        
    def spoofed?         
      false       
    end       
  end        
end    
```` 

From another paperclip issue ...

**Comment by jyurek** [comment]
In 4.2.1, you can use the `validate_media_type` option to bypass all of those checks

**Comment by akshetpandey** [comment]
@jyurek : Where do I set this option? I can't find a mention about this in the readme or in the rdoc...
