### ISSUE TITLE
"Broke Pipe" error with region "Frankfurt" on AWS/S3 upload

### ISSUE THREAD

**Issue by MartinB83** [thoughtbot/paperclip#1768]
This works in region Ireland:
```
has_attached_file :image,
  :storage => :s3,
  :bucket => 'mybucket',
  :s3_credentials => {
    access_key_id: Rails.application.secrets[:aws_access_key_id],
    secret_access_key: Rails.application.secrets[:aws_secret_access_key]
  },
  :path => "custom-uploads/:filename"
```

This does not work with region Frankfurt:
```
has_attached_file :image,
  :storage => :s3,
  :bucket => 'mybucket',
  :s3_credentials => {
    access_key_id: Rails.application.secrets[:aws_access_key_id],
    secret_access_key: Rails.application.secrets[:aws_secret_access_key]
  },
  :region => "eu-central-1",
  :s3_signature_version => :v4,
  :path => "custom-uploads/:filename"
```

==>
```
Errno::EPIPE in MyController#my_method
Broken pipe
```

Afaik it is required to use v4 signature with AWS new regions but that did not do the trick. At this point I don't know what to do.

**Comment by xlawok** [comment]
Take a look at:
https://github.com/thoughtbot/paperclip/issues/1691

Take it out from the model and put it to aws.rb initializer (described in above mentioned issue) or to production.rb with something like this:
config.paperclip_defaults = {
   # :convert_options => {:all => "-quality 70 -strip -trim"},
    :storage => :s3,
    :s3_credentials => {:access_key_id => "xxxx", :secret_access_key => "xxxxx"},
    :bucket => 'xxx,
    :url => ':s3_alias_url',
    :path => "images/:class/:id.:style.:extension",
    :s3_host_alias => 'xxxxxx.cloudfront.net',#for cloudfront
    :s3_protocol => :http,
     :region => 'eu-central-1',
    :s3_signature_version => :v4,
    :s3_headers => { 'Expires' => (Time.now + 60*60*24*30*12).httpdate }
   }

**Comment by xlawok** [comment]
ah and use aws-sdk-v1 gem

**Comment by tute** [comment]
@MartinB83, did @xlawok's comment fix your issue?

**Comment by MartinB83** [comment]
Sorry haven't tried yet. Will take a closer look soon. Guess you can close this case anyways. Thank you.

**Comment by tute** [comment]
Will close for now, let us know if it needs to be reopened. Thank you!
