### ISSUE TITLE
File/Image uploads when rails is deployed as a .war file?

### ISSUE THREAD

**Issue by Allanon29** [thoughtbot/paperclip#1770]
I am trying to use warbler and torquebox 4 to deploy my rails apps. Both of them creates a .war file.
What is the best way to upload images with paperclip ( if I would like to store them on the filesystem ) outside of the deployed war file (so when I update the app the images/files uploaded by the users won't be deleted)?
I tried to include a symlink in the war file but that doesn't seem to work...

**Comment by avinmathew** [comment]
Have you tried exploding the war file? I'm doing that with Tomcat and uploading files seems to work.

Otherwise, I'd probably have a look at specifying a path somewhere else: https://github.com/thoughtbot/paperclip#understanding-storage

**Comment by tute** [comment]
I don't know how to replicate/fix this issue in paperclip. Please ask this question in StackOverflow too, where there are more people and higher change to find someone who had encountered this problem before. Thanks!
