### ISSUE TITLE
Attachment#url returns wrong filename from S3 bucket

### ISSUE THREAD

**Issue by ericremer** [thoughtbot/paperclip#1772]
The part of the URL that is wrong is the :hash segment. All other parts of the URL are always correct. 

This issue began occurring after we upgraded Rails/Ruby/Paperclip. We're now using:
 - Ruby 2.1.5
 - Rails 4.2.0
 - Paperclip 4.2.1

I haven't been able to find any info about this problem (Edit: I found [this](https://github.com/jstorimer/delayed_paperclip/issues/35) but it's dead). Basically, saving a Paperclip attachment successfully creates the file in my S3 bucket, but about half the time it's not accessible from the url method. 

The :path is set to
`/images/:class/:attachment/:id_partition/:attachment_:id_:hash_:style.:extension`
The string returned by the url method is correct except for the :hash segment (randomly... sometimes uploading the same file does work properly)

Please let me know if I can provide any more information. Thank you!

**Comment by ericremer** [comment]
I was able to reproduce this on a fresh Rails 4.2.0 install (development environment). Same problem: The files always get uploaded, but about half the time the actual URL of the file doesn't match the one returned by avatar.url.
Gemfile:

    gem 'aws-sdk', '< 2.0'
    gem 'mysql2'
    gem 'paperclip'
initializers/paperclip.rb:

    Paperclip.interpolates(:s3_us_west_url) { |attachment, style|
      "#{attachment.s3_protocol}://s3-us-west-1.amazonaws.com/#{attachment.bucket_name}/#{attachment.path(style).gsub(%r{^/}, '')}"
    }

user.rb:

    class User < ActiveRecord::Base
      has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png",
                                 :storage => :s3,
                                 :s3_credentials => "#{Rails.root}/config/s3.yml",
                                 :s3_protocol => :https,
                                 :path => "/images/:class/:attachment/:id_partition/:attachment_:id_:hash_:style.:extension",
                                 :url => ":s3_us_west_url",
                                 :hash_secret => "[redacted]"

      validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
    end
 
users/_form.html.erb

    <%= form_for(@user) do |f| %>
        <%= f.file_field :avatar %>
        <%= f.submit %>
    <% end %>

**Comment by ericremer** [comment]
So this is definitely related to the :hash_data option, specifically the :updated_at segment. Somehow the files are (sometimes) being saved to the S3 bucket with a different :updated_at value than Paperclip uses to read the file, because I tried overriding :hash_data without :updated_at, and the resulting hash always matches correctly. Unfortunately it seems that this breaks all my existing URLs...

I will greatly appreciate any thoughts/tips you guys have on this. Thank you!

**Comment by opti** [comment]
Looks like it might be related to this `DateTime#to_f` fix in Rails 4.2.0 https://github.com/rails/rails/commit/d75992b0b22b656d16a28c04eac771a93486f465

> **`DateTime#to_f` now preserves fractional seconds.**
> Previously this method always returns `.0` in the fractional part. This commit
changes it to preserve the fractional seconds instead.
>
> Fixes rails/rails#15994.

**Comment by carlesjove** [comment]
@ericremer What version of `aws-sdk` are you using? I run into _a lot_ of issues with your same setup, and only got to fix it by using a pre 2.0 version of `aws-sdk`.

```ruby
gem 'rails', '4.2.0'
gem 'paperclip', '4.2.1'

gem 'aws-sdk', '1.63.0'
```

As a side note, just mention that [Paperclip's demo](https://github.com/thoughtbot/paperclip_demo) also crashes on Heroku when you use a 2.x version of `aws-sdk`.

**Comment by opti** [comment]
@carlesjove paperclip doesn't support `aws-sdk` 2.x yet.

**Comment by ericremer** [comment]
So I tried `rails 4.2.1.rc1` which was released Friday, and the problem seems to have been resolved. Now all my Paperclip attachments are being uploaded and downloaded correctly from S3.

**Comment by opti** [comment]
Confirm, `rails 4.2.1.rc1` fixes the issue.

The problem relates to how mysql behaves with fractional seconds on datetime attributes.

>  Incompatible to rounding behavior between MySQL 5.6 and earlier.
>
>  In 5.5, when you insert `2014-08-17 12:30:00.999999` the fractional part
>  is ignored. In 5.6, it's rounded to `2014-08-17 12:30:01`

More details here: https://github.com/rails/rails/pull/14359 and https://github.com/rails/rails/pull/18067

So, when paperclip generates [`hash_key`](https://github.com/thoughtbot/paperclip/blob/v4.2.1/lib/paperclip/attachment.rb#L317) based on [`updated_at`](https://github.com/thoughtbot/paperclip/blob/v4.2.1/lib/paperclip/attachment.rb#L304) it results with different values before record saved and after record saved.


To those, who are not able to upgrade to `rc1` version (like me), here is a workaround:
Assuming you have a `User` with `has_attached_file :avatar`. The only thing needs to be changed is assignment `avatar_updated_at`

```ruby
class User < ActiveRecord::Base
  has_attached_file :avatar
  ...

  def avatar_updated_at=(value)
    if value.acts_like?(:time)
      super(value.change(usec: 0))
    else
      super(value)
    end
  end
end
```

**Comment by tute** [comment]
This seems to work now, if it does not, please let us know how to reproduce and we'll reopen and address. Thank you for your report!
