### ISSUE TITLE
Duplicating a dirty record breaks assignment

### ISSUE THREAD

**Issue by brendon** [thoughtbot/paperclip#1773]
I use this code to re-assign attachments to `dup`'d records:

``` ruby
module Paperclip
  class HasAttachedFile
    def define_with_extensions
      define_without_extensions
      define_clone_override
    end

    alias_method_chain :define, :extensions

    private

    def define_clone_override
      name = @name
      @klass.send :define_method, "dup" do
        copy = super()
        self.class.attachment_definitions.each do |name, options|
          copy.send "#{name}=", send(name)
        end

        copy
      end
    end
  end
end
```

It works well unless the record being `dup`'d is dirty. It doesn't have to be a change to the attachment, simply a change to any column will cause the issue.

The issue is that the file doesn't get assigned to the `dup`'d record. Looking at the logs, paperclip does indeed process the file, but it's never saved. I'm guessing maybe it overwrites the existing file from the original record instead. Following the processing in the logs there is also paperclip deleting the files assigned to the original record. The files still exist though, but this is probably just because the new file is the same name as the old file.

Could this be related to caching the file path?

**Comment by brendon** [comment]
Seems to be the same issue as this:

https://github.com/thoughtbot/paperclip/issues/1673

**Comment by brendon** [comment]
Ok, so I've figured it out, or rather how to clear the caching at least on the `dup`'d object:

```ruby
module Paperclip
  class HasAttachedFile
    def define_with_extensions
      define_without_extensions
      define_dup_override
    end

    alias_method_chain :define, :extensions

    private

    def define_dup_override
      name = @name
      @klass.send :define_method, "dup" do
        copy = super()
        self.class.attachment_definitions.each do |name, options|
          ivar = "@attachment_#{name}"
          copy.instance_variable_set(ivar, nil)

          copy.send(name).assign send(name)
        end
        
        copy
      end
    end
  end
end
```

This would be a good start for a patch to add this behaviour to paperclip proper but I don't have the time to do the tests and make it better etc... I guess I should be chaining rather than just defining `dup` and calling `super` in case someone in the AR class also defines `dup`.

**Comment by brendon** [comment]
@sikachu I see your comment on SO: http://stackoverflow.com/a/11443260/129798

I hope this is a good start :)

**Comment by copperx** [comment]
Hey @brendon, I'm facing this exact issue at the moment. I `dup` a record with a paperclip attachment, but when I save it, the file does not get created.

Do you have any pointers in how to use your code without creating a fork of the paperclip gem to get around this issue?

**Comment by brendon** [comment]
Hi @copperx, I currently am monkey patching my solution in. I have a file at `config/initializers/extensions/paperclip.rb` with the following content:

```
module Paperclip
  class HasAttachedFile
    def define_with_extensions
      define_without_extensions
      define_dup_override
    end

    alias_method_chain :define, :extensions

    private

    def define_dup_override
      name = @name
      @klass.send :define_method, "dup" do
        copy = super()
        self.class.attachment_definitions.each do |name, options|
          ivar = "@attachment_#{name}"
          copy.instance_variable_set(ivar, nil)

          copy.send(name).assign send(name)
        end

        copy
      end
    end
  end
end
```

It's probably the same as my code in the earlier comment, but I'm taking it from my app here just to be sure it's up to date :)

**Comment by copperx** [comment]
@brendon That's worked perfectly. I had been trying all kinds of things and hitting my head against the wall for the last three hours just to get `dup` to work. The gem should be patched, definitely. Thanks a lot!

**Comment by brendon** [comment]
Tell me about it! I don't think it's being very actively maintained at the moment :) otherwise I'd put in a PR for it.

**Comment by mike-burns** [comment]
Looks like we found a workaround, closing.
