### ISSUE TITLE
Content-type field of the attachments and its validation

### ISSUE THREAD

**Issue by merlagautham** [thoughtbot/paperclip#1775]
This is more of a question (not an issue)

We are using Paperclip 2.4.5 and want to know how content_type of the attachment is computed.
Is it just taken from the request-headers coming from the browser? If yes is that secure? 

If its not secure should we be migrating to Paperclip 4.1 to use server side content-types?

Regards,
Gautham

**Comment by tute** [comment]
Yes, you should upgrade for added security. More info: https://github.com/thoughtbot/paperclip#security-validations
Thanks!
