### ISSUE TITLE
attachment.updated_at only returns year

### ISSUE THREAD

**Issue by jamescmartinez** [thoughtbot/paperclip#1798]
If I call `user.avatar.updated_at` it returns a Fixnum, `2015`. If I call `user.avatar_updated_at` it returns a String, `2015-02-28 02:17:14 +0000`.

When generating URLs, the cache buster only shows the year as returned by `user.avatar.updated_at`. e.g. `http://domain.com/image.png?2015` 

Why is `user.avatar.updated_at` only returning the year?

**Comment by tute** [comment]
Can you show us your database schema, please?

**Comment by tute** [comment]
ping @jamescmartinez

**Comment by tute** [comment]
We are closing issues more aggressively as lately the count got out of hand; please feel free to continue commenting and we'll work out this issue if you continue having problems. Thanks!

**Comment by jamescmartinez** [comment]
Hi @tute, here's the schema of a `User`

```
  create_table "users", id: :uuid, default: "uuid_generate_v4()", force: :cascade do |t|
    t.string   "username",               null: false
    t.string   "encrypted_password",     null: false
    t.string   "name"
    t.string   "email",                  null: false
    t.string   "phone_number"
    t.string   "auth_token",             null: false
    t.datetime "created_at",             null: false
    t.datetime "updated_at",             null: false
    t.string   "reset_password_token"
    t.datetime "reset_password_sent_at"
    t.string   "avatar_file_name"
    t.string   "avatar_content_type"
    t.string   "avatar_file_size"
    t.string   "avatar_updated_at"
  end
```

**Comment by tute** [comment]
That's it: `avatar_updated_at` should be `datetime` instead of `string`.

**Comment by jamescmartinez** [comment]
Waiiiit. I'm going to feel like a complete idiot if it's `avatar_updated_at` since it's a string.

**Comment by jamescmartinez** [comment]
Hah! I just saw it too. I can't believe I did this. Looks like `file_size` should be an integer as well, not a string according to your `attachment_steps.rb`.

**Comment by jamescmartinez** [comment]
Thanks so much, @tute.

**Comment by tute** [comment]
Glad to help! :+1:
