### ISSUE TITLE
file-5.22 not detecting ooxml .xslx files. 

### ISSUE THREAD

**Issue by sunil220552** [thoughtbot/paperclip#1800]
File command is not detecting ooxml .xslx file. It reports it as "Zip archive data, at least v2.0 to extract".
==============================================
$ ./src/file -v
lt-file-5.22
magic file from /usr/local/share/misc/magic

$ ./src/file  ~/revised\ timesheet\ january\ 2014.xlsx 
/home/sunil/revised timesheet january 2014.xlsx: Zip archive data, at least v2.0 to extract

Whereas, file-5.22 works fine for ooxml .docx file.
$ ./src/file  ~/Example.docx 
/home/sunil/Example.docx: Microsoft OOXML

Any pointers ?

**Comment by tute** [comment]
No idea why would `file` respond this way, looks like an issue for that program. Thank you for reporting.
