### ISSUE TITLE
Rails4+paperclip+rmagick doesn't run with remote: true

### ISSUE THREAD

**Issue by pdipietro** [thoughtbot/paperclip#1801]
I have the following html.haml (extract)

    = bootstrap_form_for(group, :remote => :true ) do |f|
      = f.text_field :name 
      = f.file_field :cover
      %button{ :type => "submit", :name => "commit",:title => "Save the element"}
please, note the :remote => true: I have a edit.js.haml piece of code to upload only a piece of code

If I enter only the text field, everything runs fine. The url on the browser is correct.

But if I enter a file name the form returns an error, because it seems to call the edit.js.haml as an html page, but doesn't execute it.

    $('#main_add').html("<script>\n  $(function() {\n        $(\'input:checkbox\').bootstrapSwitch();\n  });\n<\/script>\n<div class=\'panel panel-default\'>\n  <div class=\'panel-heading\'>\n    <a class=\'toggle\' data-target=\'#gf\' data-toggle=\'collapse\' toggle=\'false\' type=\'toggle\'>\n      <span class=\'caret to-right\'><\/span>\n      <div class=\'panel-title\'>\n        New Group\n      <\/div>\n    <\/a>\n  <\/div>\n  <div class=\'collapse in panel-body\' id=\'gf\'>\n    <div>\n 
Also, it add a /groups/84fb36b6-fee9-4446-a48c-2ad12934e39b to the url in the browser

Any 'easy' approach to solve the problem? I searched the internet but I didn't find any easy implementation ....

**Comment by tute** [comment]
@pdipietro not sure how to fix this, or even if it's a bug in doorkeeper. Consider asking your question in StackOverflow, where a bigger community might have solved a similar problem already. Thanks!
