### ISSUE TITLE
Allows multiple mime types for unknow extension

### ISSUE THREAD

**Issue by pierallard** [thoughtbot/paperclip#1809]
Hi everybody

I have two servers using the same application with Paperclip 4.2.1. My application manages `.blend` files.
The issue is that the command `file -b --mime` does not return the same result in the 2 systems. In one case, it's `application/octet-stream; charset=binary`, in the other `binary; charset=binary`.

I tried to set the value `Paperclip.options[:content_type_mappings][:blend]` to `"application/octet-stream"` or `"binary"`, it works for one system only. But I can't set an array to use it in the 2 systems...

The only solution I found is to execute the file command at the initialization of my application to set the Paperclip options, but it's crappy.

**Comment by JoelQ** [comment]
Has this issue been resolved by #1810 ?

**Comment by pierallard** [comment]
@JoelQ Yes (I did it)

**Comment by tute** [comment]
Thanks!
