### ISSUE TITLE
Define more than one content type mapping for an extension. 

### ISSUE THREAD

**Issue by mehulkar** [thoughtbot/paperclip#1812]
I am uploading `.prt` files and to be able to pass spoof detection, I have to define some custom content type mappings. 

So I run `file -b --mime file.prt` and look at the output and define:

```ruby
# config/initializers/paperclip_content_type_mappings.rb
Paperclip.options[:content_type_mappings][:prt] = "CDF V2 Document, No summary info"
```

All is well. 

Then I push up my code and specs and they fail on Travis CI. Womp womp. 

After some investigation, I figure out that the version of `file` is different on Travis and on my machines. 

So my options here are:

1. Require a particular version of `file`
1. Add a conditional statement in my initializer something like this:

  ```ruby
  # this will break with other version of file, probably. 
  if `file -v 2>&1`.split("\n")[0].match(/04/) # because of course file sends version output to stderr...
    Paperclip.options[:content_type_mappings][:prt] = "CDF V2 Document, No summary info"
  else
    Paperclip.options[:content_type_mappings][:prt] =  "Composite Document File V2 Document, No summary info; charset=binary"
  end
```
1. Figure out a way to define multiple mappings for a file extension as I see fit. 

Or maybe I'm missing something?

**Comment by mehulkar** [comment]
[The offending lines][1] are in the `MediaTypeSpoofDetector` class:

```ruby
  def mapping_override_mismatch?
    mapped_content_type != calculated_content_type
  end

    def mapped_content_type
      Paperclip.options[:content_type_mappings][filename_extension]
    end
```

These could be changed to handle arrays and check for inclusion instead. Or a regex matcher would work too. 

[1]: https://github.com/thoughtbot/paperclip/blob/dca87ec5d8038b2d436a75ad6119c8eb67b73e70/lib/paperclip/media_type_spoof_detector.rb#L33-L35

**Comment by jyurek** [comment]
That makes sense. Would you be willing to submit a PR to change this?

**Comment by jyurek** [comment]
Actually it appears as though #1810 is going to handle this. I'll close this issue as it's currently being addressed. Thanks for reporting it.

**Comment by mehulkar** [comment]
Oh, nice. I had a PR ready to go with tests, but I was waiting on approval from legal.
