### ISSUE TITLE
content type mapping should be a regex matcher

### ISSUE THREAD

**Issue by mehulkar** [thoughtbot/paperclip#1814]

**Comment by jyurek** [comment]
I'm not sure what you mean here. Can you provide a little more information about what you'd want to see?

**Comment by mehulkar** [comment]
This was related to the issue I brought up in #1812. 

Essentially, the problem was [PEBCAK](https://en.wikipedia.org/wiki/User_error), but I ran into this issue:

```
file -b --mime file.prt
Composite Document File V2 Document, No summary info; charset=binary
```

So I was defining my content type mapping to that string. 

But the paperclip method only returns the first part of that:

```
Paperclip.run("file", "-b --mime :file", :file => @file.path).split(/[:;]\s+/).first
```

I didn't notice that at first and it took me way too long to notice. 

I could have gotten past the hurdle much quicker if I could have defined a partial matcher in my content type mapping. E.g.

```
Paperclip.options[:content_type_mappings][:prt] =  /Composite Document File/
```

or something like that.

**Comment by tute** [comment]
We won't add a regex matcher quite yet. If more use cases arise, and the feature wouldn't make it easier to run into security problems, we'll reconsider. Thanks!
