### ISSUE TITLE
Error on build_missing_paperclip_styles

### ISSUE THREAD

**Issue by waynn** [thoughtbot/paperclip#1815]
I've tried a bunch of different ways to do this and found a hack to get it working, but I'm trying to make sure I'm doing it correctly. I'm running Rails 4.1.9, and I've copied the code from build_missing_paperclip_styles, and when I deploy I get an error saying "bundle: command not found". I've pasted the stack trace at the end of this.

If I change this line

      execute "cd #{current_path}; RAILS_ENV=production bundle exec rake paperclip:refresh:missing_styles"

to this line:

      execute "cd #{current_path}; RAILS_ENV=production $HOME/.rbenv/bin/rbenv exec bundle exec rake paperclip:refresh:missing_styles"

it works. But other commands during deploy work fine with bundle and rake, so why doesn't this one?

Here's the relevant stack trace:

```
DEBUG [c7e11673] Command: cd /home/ec2-user/code/current; RAILS_ENV=production bundle exec rake paperclip:refresh:missing_styles
DEBUG [c7e11673] 	bash: bundle: command not found
(Backtrace restricted to imported tasks)
cap aborted!
SSHKit::Runner::ExecuteError: Exception while executing as ec2-user@example.com: cd /home/ec2-user/code/current; RAILS_ENV=production bundle exec rake paperclip:refresh:missing_styles exit status: 127
cd /home/ec2-user/code/current; RAILS_ENV=production bundle exec rake paperclip:refresh:missing_styles stdout: Nothing written
cd /home/ec2-user/code/current; RAILS_ENV=production bundle exec rake paperclip:refresh:missing_styles stderr: bash: bundle: command not found

SSHKit::Command::Failed: cd /home/ec2-user/code/current; RAILS_ENV=production bundle exec rake paperclip:refresh:missing_styles exit status: 127
cd /home/ec2-user/code/current; RAILS_ENV=production bundle exec rake paperclip:refresh:missing_styles stdout: Nothing written
cd /home/ec2-user/code/current; RAILS_ENV=production bundle exec rake paperclip:refresh:missing_styles stderr: bash: bundle: command not found

Tasks: TOP => deploy:build_missing_paperclip_styles
(See full trace by running task with --trace)
The deploy has failed with an error: Exception while executing as ec2-user@example.com: cd /home/ec2-user/code/current; RAILS_ENV=production bundle exec rake paperclip:refresh:missing_styles exit status: 127
cd /home/ec2-user/code/current; RAILS_ENV=production bundle exec rake paperclip:refresh:missing_styles stdout: Nothing written
cd /home/ec2-user/code/current; RAILS_ENV=production bundle exec rake paperclip:refresh:missing_styles stderr: bash: bundle: command not found
```

**Comment by jyurek** [comment]
This is the only command that fails? That's very odd. You say this is in deployment, so is this in your Capfile? I'm inclined to think this isn't a paperclip problem, if so, because it's a problem even running `bundle`.

**Comment by waynn** [comment]
Well, the weird thing is that bundle works in other parts of the deploy, it's only this part that fails. Is there something I need to do to set the path for when I get to the paperclip part of deploy?

**Comment by tute** [comment]
The issue you describe seems very specific to your code. I suggest that you ask about it in https://stackoverflow.com/questions/tagged/paperclip, which will get attention
from more people than in this issue tracker.

Sorry we don't have the time now to help you with this question, and thanks!
