### ISSUE TITLE
aliasing imagemagick's command

### ISSUE THREAD

**Issue by guyisra** [thoughtbot/paperclip#1820]
Is there a way to alias the imagemagick's commands so that  `-limit memory 0 -limit map 0` will be added to them, globally?

One alternative I can think of is to add this as a string interpolation in convert_options, and add it manually to every style. Wonder if this can be done more efficiently, and to every command not just convert...

This to make it skip the memory cache and go the the disk cache and avoiding imagemagick memory bloat (especially on Heroku's limited memory dynos and R14 errors)

**Comment by tute** [comment]
ping @jyurek for this issue.

**Comment by jyurek** [comment]
You can use `convert_options: { all: "-limit memory 0 -limit map 0" }` to add the options to all styles. You can read about this here: https://github.com/thoughtbot/paperclip/blob/master/lib/paperclip.rb#L154
