### ISSUE TITLE
paperclip:clean does not remove deprecated styles

### ISSUE THREAD

**Issue by chadila** [thoughtbot/paperclip#1823]
Hello
I had in my model 
`````
has_attached_file :image, :styles => { :normal => "480x540>", :medium => "300x300>", :thumb => "100x100>" } 
`````
I replaced it by
`````
has_attached_file :image, :styles => { :normal => "480x540>" }
````` 
And called
````
rake paperclip:clean class=Myclass
````

The medium and thumb attachements are still on the HDD after this tasks, isn't it suppose to erase it?

Thanks

**Comment by tute** [comment]
@jyurek? If we have a `clean` command it makes sense to me to erase "unknown" formats; but it is surprising to me that we would have this rake task in the first place. Seems risky to me!

**Comment by tute** [comment]
I'd rather not delete unknown files. The directory might contain files not processed by paperclip at all. Thanks!
