### ISSUE TITLE
Not able to copy file for s3

### ISSUE THREAD

**Issue by jbmyid** [thoughtbot/paperclip#1828]
Not able to copy file from one object to other in 4.2.1. Whereas it worked in 4.2.0

nb.showcase_file = b.showcase_file
[I] [04-06 12:51:09] [paperclip] copying /broadcast/defaults/showcase_files/000/000/064/original/abhl.jpg to local file /tmp/64ee8a3bc7f9124d1f6de8c76464065e150406-12581-ci8l15-.jpg
[I] [04-06 12:51:25] [AWS S3 200 15.633 0 retries] get_object(:bucket_name=>"any.bucket",:key=>"broadcast/defaults/showcase_files/000/000/064/original/abhl.jpg")  

[I] [04-06 12:51:25] Command :: identify -format '%wx%h,%[exif:orientation]' '/tmp/64ee8a3bc7f9124d1f6de8c76464065e150406-12581-ci8l15-.jpg[0]' 2>/dev/null
[I] [04-06 12:51:25] [paperclip] An error was received while processing: #<Paperclip::Errors::NotIdentifiedByImageMagickError: Paperclip::Errors::NotIdentifiedByImageMagickError>
[I] [04-06 12:51:25] Command :: identify -format '%wx%h,%[exif:orientation]' '/tmp/64ee8a3bc7f9124d1f6de8c76464065e150406-12581-ci8l15-.jpg[0]' 2>/dev/null
[I] [04-06 12:51:25] [paperclip] An error was received while processing: #<Paperclip::Errors::NotIdentifiedByImageMagickError: Paperclip::Errors::NotIdentifiedByImageMagickError>

And when i changed to 4.2.0 on production it gave  LoadError: no such file to load -- paperclip/schema

**Comment by tute** [comment]
Hi @jbmyid. We'll need more information for us to replicate and then fix this issue. Can you please give us concrete steps to reproduce, or a failing test app repo?
Thank you!

**Comment by jbmyid** [comment]
Sorry for late reply, it worked on uninstalling gem and reinstall it again.
