### ISSUE TITLE
Support for CloudFront signed URL

### ISSUE THREAD

**Issue by gmontard** [thoughtbot/paperclip#1834]
Hello,

I've seen there is a method called expiring_url in order to manage S3 signed URL, but it doesn't seem there is any method to generate a CloudFront signed URL.

Am I right? 

Thanks.

**Comment by tute** [comment]
@leonelgalan does your https://github.com/leonelgalan/cloudfront-signer#usage help with this question? Thank you!

**Comment by leonelgalan** [comment]
Yes @tute, and yes @gmontard, you are right. CloudFront signing it's a thing on its own, whether you want signed urls, signed cookies, canned policies or custom policies (http://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/PrivateContent.html) _cloudfront-signer_ should help.

**Comment by tute** [comment]
Thanks for your help.
