### ISSUE TITLE
Paperclip support to TLS? (AWS will discontinue support of SSLv3)

### ISSUE THREAD

**Issue by xoen** [thoughtbot/paperclip#1841]
We received an email from AWS saying they'll stop support for SSL soon:

> As of 12:00 AM PDT May 20, 2015, AWS will discontinue support of SSLv3
> for securing connections to S3 buckets. [...]
> AWS will only support versions of the more modern TLS rather than SSLv3.

> You are receiving this email because some of your users are accessing Amazon S3 using a browser
> configured to use SSLv3, or some of your existing applications that use Amazon S3 are configured to
> use SSLv3. These requests will fail once AWS disables support for SSLv3 for the Amazon S3
>  service.

> As any necessary changes would need to be made in your application, we recommend that you
> review your applications that are accessing the specified S3 buckets to determine what changes may 
> be required.

So, we're using *paperclip 3.5.4*. It's not clear from the email if these SSL accesses are just browsers or not.
We're wondering if this version of paperclip is already future-proof and supports TLS.

Thank you very much for your help in advance.

**Comment by harinisaladi** [comment]
+1 Have the same question here too!

**Comment by javierkeants** [comment]
+1

**Comment by jyurek** [comment]
Paperclip uses the `aws_sdk` gem (or `fog`), and does all interactions with S3 based on that. From research on the subject, it appears that there is little to no direction from Amazon on the subject, and, in fact, developers watching traffic streams reporting only TLS connections coming from their servers. So, I would guess it's people who do not have the latest browsers.

I do not believe this is a Paperclip problem at this time, although I would be very interested to see evidence otherwise. As such, I'm going to close this for now.

**Comment by xoen** [comment]
Hello everyone. Just an update on this.

I contacted AWS support and they provided us some TLS-only endpoints for testing purposes. I added them to my hosts file and I played with our app to see if it was still working or not.

We use paperclip for some of the functionalities and the aws-sdk gem directly for others. Both worked as before with the TLS-only endpoints, so *hopefully* everything should work fine as usual from the 20th ;).

Also, in order to be sure I was actually hitting the right endpoint, I downloaded and used an ancient version of Firefox (10 or 11, I can't remember exactly). This version gives you the nice option of disabling/enabling SSL and/or TLS, which in this case was very useful.

With SSL disabled and TLS enabled I was able to upload files as usual of course (because it's done server-side) but the files were not displayed. So I concluded the SSL connections Amazon is talking about are mainly old browser versions ([This table is very very useful!](http://en.wikipedia.org/wiki/Transport_Layer_Security#Web_browsers) - let old browsers rest in peace...)

I hope this is useful, have a lovely day ;)

**DISCLAIMER**: I did these tests personally, and I'm fairly sure this and newer versions of paperclip should still work after the switch-off. Although, your configuration could differ (or I could simply be wrong), etc..., so please do your tests on your app.
