### ISSUE TITLE
upload zip file not work on firefox

### ISSUE THREAD

**Issue by qx** [thoughtbot/paperclip#1852]
same code ,worked on chrome/safari,but not on firefox 37.0.2

![2015-05-12 18 49 07](https://cloud.githubusercontent.com/assets/648406/7585767/6971f0ea-f8d8-11e4-87f2-61f3afba84fb.png)

**Comment by jyurek** [comment]
Can you also post a similar screenshot of the params when you upload from Chrome?

**Comment by tute** [comment]
It's been three months now, so I hope this is working good now for you. Will close this issue, but if it should remain open let us know and we'll work through it. Thanks!
