### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by maclover7** [thoughtbot/paperclip#1854]
Should we move documentation out of the README and into the wiki for better organization? Or should we just add a TOC -- I feel it is starting to get a big long and unorganized.

**Comment by tute** [comment]
A toc in the README is best. wikis can go out of control, and people don't use the diff view as much as in PR reviews.

pandoc is a good tool to auto-generate TOCs on markdown files, there's a snippet somewhere in StackOverflow.

**Comment by maclover7** [comment]
Sounds good, will take care of this and add a TOC over the weekend.

**Comment by tute** [comment]
ping @maclover7! If you'd like we can take care of this too on Friday.

**Comment by tute** [comment]
Some help (generated with vim plugin for markdown `Toc`):

```
Paperclip
  Requirements
    Ruby and Rails
    Image Processor
    `file`
  Installation
  Quick Start
    Models
    Migrations
    Edit and New Views
    Edit and New Views with Simple Form
    Controller
Use strong_parameters for attribute whitelisting
Be sure to update your create() and update() controller methods.
    Show View
    Deleting an Attachment
  ```
  Usage
  Validations
Security Validations
Allow ".foo" as an extension for files with the mime type "text/plain".
  Defaults
  ```
  Migrations
    Table Definition
    Schema Definition
    Vintage syntax
  Storage
    Understanding Storage
  Post Processing
  Events
  URI Obfuscation
  MD5 Checksum / Fingerprint
  File Preservation for Soft-Delete
  Custom Attachment Processors
  Dynamic Configuration
    Dynamic Styles:
    Dynamic Processors:
  Logging
  Deployment
  ```yml
  Testing
  ```
  Contributing
  License
  About thoughtbot
```

**Comment by tute** [comment]
It wasn't pandoc, it's doctoc: https://github.com/thlorenz/doctoc

**Comment by tute** [comment]
Closing in favor of PR. Thank you @maclover7!
