### ISSUE TITLE
how to validate image dimension ?

### ISSUE THREAD

**Issue by gabrieltong** [thoughtbot/paperclip#1856]
when upload new image , we need to validate to dimension .

is there a dimension validator ? or some client size validator ?

thank you !

**Comment by jyurek** [comment]
You mean you need your user to upload a specific dimension? There is not anything built in to Paperclip that will do that, though you can probably define a normal ActiveRecord validator that will check the uploaded file.

You can also have Paperclip automatically resize the image for you, if that helps.

**Comment by gabrieltong** [comment]
@jyurek Finally, I used `papercrop` to do that. thanks!
