### ISSUE TITLE
Getting the count of how many times an image is accessed from the aws s3

### ISSUE THREAD

**Issue by kamalkgarg** [thoughtbot/paperclip#1862]
I am using paperclip gem (version-4.1.1) with aws s3 in my rails 3.2 application for image uploading.  I need to get the count of how many times an image is accessed from the aws s3. Is there a way to get this stats in paperclip? If not, could you please provide me some guidelines to achieve this?

Thanks

**Comment by jyurek** [comment]
There is no way to do it from Paperclip, but if anyone has that information, Amazon will. I've never looked for that for my own assets, so I don't know how to go about doing it, though. Sorry. :/
