### ISSUE TITLE
CI is broken

### ISSUE THREAD

**Issue by tute** [thoughtbot/paperclip#1863]
Build 1330 broke CI: https://travis-ci.org/thoughtbot/paperclip/builds/62714432

Commit that switched it: https://github.com/thoughtbot/paperclip/commit/2610cc323e281fff66e3ef959de32f3f88939e6b

**Comment by tute** [comment]
Looks green now, see: https://travis-ci.org/thoughtbot/paperclip/builds/64030478.

**Comment by maclover7** [comment]
:+1:
