### ISSUE TITLE
Images cannot be resampled before resizing

### ISSUE THREAD

**Issue by dylankarr** [thoughtbot/paperclip#1864]
The imagemagick command `-resample xx` cannot be used in resizing because of the order in which arguments are added to the command here: https://github.com/thoughtbot/paperclip/blob/master/lib/paperclip/thumbnail.rb#L69

This means images will be resampled after resizing, which causes significant blur. For example, [this image is resampled then resized](http://i.imgur.com/nY7KxTa.jpg), and [this one is resized then resampled](http://i.imgur.com/yNx53QZ.jpg).

**Comment by dylankarr** [comment]
I've created a pull request to provide one solution to the problem, if someone would be willing to review it: https://github.com/thoughtbot/paperclip/pull/1855

**Comment by tute** [comment]
Closing in favor of PR. Thank you!
