### ISSUE TITLE
Allow to set permissions of the created directory path

### ISSUE THREAD

**Issue by yuvaltobias** [thoughtbot/paperclip#1865]
There's an ``override_file_permissions`` option to change the permissions of the file created, but not option to set the permissions of the path that is created – this prevents, for example, from a process running under a different user from deleting the file.

I suggest adding ``override_path_permissions`` option that will eventually get to ``/lib/paperclip/storage/filesystem.rb`` as an option in the ``FileUtils.mkdir_p`` call at line 38.

**Comment by jyurek** [comment]
This sounds reasonable enough. I'd definitely be interested in a PR to this effect. Once you submit that, reference this issue so we don't lose track of it. Thanks!

**Comment by tute** [comment]
Closing in favor of PR. Will add the context there. Thanks!
