### ISSUE TITLE
Attachments are saved to wrong paths when using :hash interpolation in the "url" option

### ISSUE THREAD

**Issue by scaryzet** [thoughtbot/paperclip#1866]
# Summary

`Paperclip::Attachment#updated_at` can yield different results for the same model (just created model vs reloaded from the DB) under specific versions of MySQL. This affects the interpolation of `':hash'` for attachment paths\urls.

# Explanation

Let's say there is a model `Avatar`

```ruby
class Avatar < ActiveRecord::Base
  has_attached_file :image, url: '/system/:class/:attachment/:id/:hash-:style.:extension',
    hash_secret: Rails.application.secrets.paperclip
end
```

The problem: paperclip is saving an attachment file to one path when creating and saving the model, then it returns a different path when querying the attachment url from the reloaded model.

### Interpolating ':hash'

That `':hash'` url part is built with `':class/:attachment/:id/:style/:updated_at'` as of `Paperclip::Attachment.default_options[:hash_data]`. The trouble is given by the interpolation of `':updated_at'`.

When a new `Avatar` (the example above) model instance is created with an assigned attachment file and saved, the `image_updated_at` model field will get populated through `Paperclip::Attachment#assign_timestamps` with `Time.now` which does contain fractional seconds.

When `':hash'` is interpolated into the path\url of the attachment, it is built from a string containing the `:updated_at` interpolated segment which is replaced with the result of `Paperclip::Attachment#updated_at`

```ruby
def updated_at
  time = instance_read(:updated_at)
  time && time.to_f.to_i
end
```

which discards the fractional part of `time`.

### MySQL 5.6.4+

MySQL prior to 5.6.4 would just discard the fractional part of the `image_updated_at` field when the model is saved to the database. So when the model is reloaded the `':updated_at'` interpolated value will stay the same. No problem.

MySQL 5.6.4 and up adds support to fractional seconds for DATETIME columns and **changes the behavior** of handling the incoming values.

http://dev.mysql.com/doc/refman/5.6/en/fractional-seconds.html

> MySQL 5.6.4 and up expands fractional seconds support for TIME, DATETIME, and TIMESTAMP values, with up to microseconds (6 digits) precision:
> * ...
> * Inserting a TIME, DATE, or TIMESTAMP value with a fractional seconds part into a column of the same type but having fewer fractional digits results in **rounding** [...]
> * ...

So under MySQL 5.6.4+ when we have a "normal" DATETIME column with zero fractional second precision in 50% cases the interpolated `:updated_at` value will increment 1 second after model reloading resulting in a different `:hash` being built.

### What to do?

I don't think just changing `time.to_f.to_i` to something like `time.to_f.round.to_i` would be eqivalent to MySQL time rounding mechanism. It *might* be equivalent but i just don't know.

As suggested in another issue the bulletproof solution would be introducing some "hash_salt" column specifically for usage of the `':hash'` interpolated segment.

**Comment by scaryzet** [comment]
Btw, a temporary solution by monkey-patching in case anyone needs it:

```ruby
# config/initializers/paperclip.rb

module Paperclip
  class Attachment
    def assign_timestamps
      now = Time.now.change(usec: 0)

      if has_enabled_but_unset_created_at?
        instance_write(:created_at, now)
      end

      instance_write(:updated_at, now)
    end
  end
end
```

**Comment by tute** [comment]
Thank you so much for your detailed report and the code snippet. We are a little busy right now, will work on it as soon as we can!

**Comment by scaryzet** [comment]
Apparently, the described mysql behavior was as issue in Rails, they made some fixes in 4.2, see this https://github.com/rails/rails/pull/14359 I assume Paperclip should work all fine under Rails 4.2+ even without trimming the "usec" of assigned timestamps.

**Comment by tute** [comment]
Thanks @scaryzet! Does that mean that this is shoudln't be an issue in paperclip anymore?

**Comment by scaryzet** [comment]
@tute Well, if you're not supporting Rails <4.2...

**Comment by tute** [comment]
Thanks!

**Comment by hanokhaloni** [comment]
Sorry about the late response: 
Doesn't this whole issue suggest that the hashing funciton has the wrong seed, or given the seed is not using a _good enough hashing funciton_ ?
Shouldn't the bulletproof solution (introducing some "hash_salt" column specifically for usage of the ':hash' interpolated segment) should be implement by paperclip?
