### ISSUE TITLE
rails 4 and paperclip storing path

### ISSUE THREAD

**Issue by TheRealGuardDogGPS** [thoughtbot/paperclip#1867]
I am not following the logic of the paperclip gem. First, I use the default url Paperclip saves to, which is located in the /system/ folder. However, when I actually try to look for the image inside the folder, it is not there:
```
$ cd /system/content_templates/screenshots/000/000/012/original/
-bash: cd: /system/content_templates/screenshots/000/000/012/original/: No such file or directory
```

Ok, so I don't know what that is about. So instead I change the url option:

```ruby
  has_attached_file :screenshot, :path => "/:default_template/template_:id/:filename",
                                 :url => '/:class/:id/:style.:extension'
```

Now it saves it here: http://localhost:3000/content_templates/13/original.png?1432232921

```
rails_root donato$ cd content_templates
-bash: cd: content_templates: No such file or directory
```

I also tried doing this:

```
:default_url => ActionController::Base.helpers.asset_path('missing_:style.png')
which produces the following routing error:

 GET http://localhost:3000/system/content_templates/screenshots/000/000/014/original/screenshot.png?1432233844 404 (Not Found)
```

So what am I doing wrong? How am I supposed to determine the path of the Paperclip gem?

**Comment by tute** [comment]
We are a bit busy and issues are overwhelming us a bit, @TheRealGuardDogGPS. Are you still having this issue? Have you tried asking in StackOverflow too?

**Comment by pedrosmmoreira** [comment]
@TheRealGuardDogGPS From your prompt it seems you are not in your application path? The default url should store files within `yourapplication/public/system'. Does this help?

**Comment by tute** [comment]
Right. @TheRealGuardDogGPS, if you do `$ cd /path`, the shell will try to go to the root of your filesystem. If you want to go to the directory `path` in your project's folder, remove the leading slash. Thanks!
