### ISSUE TITLE
Rails 2.3

### ISSUE THREAD

**Issue by maclover7** [thoughtbot/paperclip#1872]
Should we remove the part of the README that mentions how to use Paperclip with Rails 2.3.x?

Also, should I close the 4.1.2 and 4.2.0 milestones since we have already landed those versions?

@tute

**Comment by tute** [comment]
Yes. And I wonder if we should keep maintaining other end-of-life'd versions of Ruby and Rails.

**Comment by maclover7** [comment]
Was wondering about that too. Should we drop support for Rails 3.2 and Ruby 1.9.3?

**Comment by tute** [comment]
3.2 is not EOL'd yet, 4.0 is. I believe so, we should be Ruby >= 2, and Rails 3.2, or >= 4.1.

**Comment by tute** [comment]
These lines need upgrade as well: https://github.com/thoughtbot/paperclip/blob/master/paperclip.gemspec#L21-L24

**Comment by tute** [comment]
BTW: #1874 already removed that section in the README. Still, dependencies are older than they should.

**Comment by maclover7** [comment]
#1875

**Comment by tute** [comment]
Closing in favor of PR https://github.com/thoughtbot/paperclip/pull/1875.
