### ISSUE TITLE
.present? relies on a file_name being present. Not enough

### ISSUE THREAD

**Issue by mehulkar** [thoughtbot/paperclip#1876]
I ran into a bug in our app where we were updating the filename column, but accidentally deleting the underlying file (by assigning the paperclip property to nil). `Paperclip::Attachment#present?` still returns true even though the file doesn't exist. 

I propose changing the method to use `File.exists?` as well.

**Comment by tute** [comment]
Closing in favor of PR.

**Comment by jyurek** [comment]
As mentioned in #1877, if you actually want to see if the file exists, use `exists?`.

**Comment by mehulkar** [comment]
Ah nice, I didn't know about `exists`? I'll use that in the future. Thanks @jyurek !
