### ISSUE TITLE
square bracket syntax?

### ISSUE THREAD

**Issue by nathantechie9** [thoughtbot/paperclip#1880]
Can someone tell me how code is written to handle this? That's hash square bracket syntax. Why isn't it using ( ) instead of [ ]

@s3_bucket ||= s3_interface.buckets[bucket_name]

Nevermind. I figured it out.

**Comment by jyurek** [comment]
For those who stumble on this wondering the same thing, `s3_interface.buckets` returns an array, and the `[]` is normal array access.

**Comment by nathantechie9** [comment]
Technically in Ruby it is called a Hash. I worked on fixing AWS S3 gem that works with paperclip.

**Comment by jyurek** [comment]
Ah yes, it's referencing with a key and not an index so it must be a hash.

**Comment by nathantechie9** [comment]
I hate to be anal. It does look like array syntax :) like in other languages. I'm happy paperclip is going to include was sdks v2 s3 support built into it. I took a look at the was s3 gem and the code is a mess.
