### ISSUE TITLE
not possible to pass :url to Paperclip::Attachment#url

### ISSUE THREAD

**Issue by pseidemann** [thoughtbot/paperclip#1883]
see http://www.rubydoc.info/gems/paperclip/Paperclip%2FAttachment%3Aurl.
one could unterstand that it is possible to overwrite the value of `:url`, given from the `has_attached_file` call, but it isn't. 
would be good to have this so one can generate urls which point to absolute urls (http://...) _and_ relative ones (/images/...).

currently I have `:url` set to an absolute url via `has_attached_file` (and `:path` properly set) and in another place I need this to be relative. workaround is `URI(record.attachment.url(:original)).path`

**Comment by jyurek** [comment]
May I ask why you need to generate absolute urls sometimes and relative other times?

Anyway, you're right. There isn't a way to do this. If you want to submit a PR to change the UrlGenerator class to add this in, it would help out a lot.

**Comment by pseidemann** [comment]
for the production environment I need absolute urls with a specific host and for another place in the api I just need a relative one

**Comment by jyurek** [comment]
You can modify your `config/environments/production.rb` and `development.rb` to have different Paperclip configs, and this will get rid of a need to do it dynamically.

For example, in a client project I'm working on I have, in `config/environments/production.rb`

    config.paperclip_defaults = {
      storage: :fog,
      fog_credentials: {
        aws_access_key_id: ENV.fetch("AWS_ACCESS_KEY_ID"),
        aws_secret_access_key: ENV.fetch("AWS_SECRET_ACCESS_KEY"),
        provider: "AWS"
      },
      fog_directory: ENV.fetch("AWS_BUCKET"),
      path: ":style/:topic_slug.:extension"
    }

And in `config/environments/development.rb` I have

    config.paperclip_defaults = {
      url: "/system/:style/:topic_slug.:extension"
    }

And it works without having anything dynamic in my code, but production (and staging, but it's the same config) saves to S3 and development saves locally. Will something like that work for you?

**Comment by tute** [comment]
@pseidemann I assume this is working for you now, after Jon's response and the passing of weeks. If not, let us know and we'll reopen. Thanks!

**Comment by pseidemann** [comment]
the proposed solution doesn't work since I need the different url representations in the same rails environment
