### ISSUE TITLE
Paperclip doesn't recognize SVG image data URIs unless they're base64-encoded

### ISSUE THREAD

**Issue by bjmc** [thoughtbot/paperclip#1884]
The regex for the [DataUriAdapter](https://github.com/thoughtbot/paperclip/blob/master/lib/paperclip/io_adapters/data_uri_adapter.rb#L4) explicitly requires base64 encoding:

    REGEXP = /\Adata:([-\w]+\/[-\w\+\.]+)?;base64,(.*)/m

However, there's no necessity to base64-encode SVG images, and it's [actually suggested not to.](https://css-tricks.com/probably-dont-base64-svg/) Because Paperclip fails to recognize valid data URIs of the form `data:image/svg+xml;utf8,` users are forced to base64-encode SVGs in order to upload them to Paperclip.  As a future enhancement, it would be nice if that restriction were removed.

**Comment by jyurek** [comment]
Honestly, I'd never considered this, since this is typically used for binary formats, but you make a compelling argument. If you want to make this change and submit a PR, I'd be all for it. Thanks!
