### ISSUE TITLE
Can't locate present file

### ISSUE THREAD

**Issue by abrambailey** [thoughtbot/paperclip#1886]
Checking for the file with File.exists? returns false in my production console:

    irb(main):026:0> x.avatar(:medium)
    => "/system/users/avatars/000/000/091/medium/linkedin.jpg?1391118203"
    
    irb(main):025:0> File.exists? x.avatar(:medium)
    => false
    
Chrome Network Log indicates the file is found

    Request URL:https://www.example.com/system/users/avatars/000/000/091/medium/linkedin.jpg?1391118203
    Request Method:GET
    Status Code:200 OK

Any idea why the discrepancy? 

**Update**

I have also tried 

    irb(main):029:0> File.size "#{Rails.root}/public#{x.avatar(:medium)}"
    
    Errno::ENOENT: No such file or directory @ rb_file_s_size - /home/app/example.com/current/public/system/users/avatars/000/000/026/medium/277553f.jpg?1432666893

**Comment by Kameshwaran** [comment]
@abrambailey I think you are not supposed to have the query string in url passed to `exists?` method.

Try the below.
File.exists? ("/system/users/avatars/000/000/091/medium/linkedin.jpg")

**Comment by jyurek** [comment]
@abelmartin Yeah, @Kameshwaran has it. You're trying to find a file with the name "linkedin.jpg?1391118203" instead of a file with the name "linkedin.jpg".

**Comment by abelmartin** [comment]
...I think you meant @abrambailey instead of me :smile_cat:
