### ISSUE TITLE
Wrong local urls

### ISSUE THREAD

**Issue by mmintel** [thoughtbot/paperclip#1894]
Hi there,

I am sure this is easy to solve but I am a ruby newbie. I am using Spree Commerce with Paperclip and S3. I also want to use S3 on development. It's working great on my production server but in development I am getting wrong urls.. including a path on my local machine.

This is how the path to an image looks like on development:
http://s3-eu-central-1.amazonaws.com/zeitschild/Users/mmintel/gCt/heroku/zeitschild/public/spree/products/51/large/mockup_0003_daycream-normal.png?1433845570 (this is added inbetween "Users/mmintel/gCt/heroku/zeitschild")

but this is how it should be
http://s3-eu-central-1.amazonaws.com/zeitschild/app/public/spree/products/51/large/mockup_0003_daycream-normal.png?1433845570

Would be nice if you could help me :)

**Comment by jyurek** [comment]
What does your `has_attached_file` call look like? It looks like your `path` and `url` settings are a little confused.

**Comment by mmintel** [comment]
Hi there,

I used a guide for an old spree commerce version! This guide here helped me out: https://guides.spreecommerce.com/developer/s3_storage.html

Sorry!
