### ISSUE TITLE
Linux/BSD file command can not detect JSON

### ISSUE THREAD

**Issue by gtd** [thoughtbot/paperclip#1900]
Consider this:

```
echo "[]" > file.json
file -b --mime file.json
=> text/plain; charset=us-ascii
```

I verified this result on both OS X and Ubuntu, and also with more complex JSON.

This is leading to a content spoofing error, and a particularly annoying one since this is not user-generated content, this is a JSON feed I am building within my application.  I traced the code and I don't believe it's possible to force this directly.

What should be done about weaknesses in `file` reliability, especially where it may differ across platforms?  I tried Googling around this, and it's ungodly difficult.

**Comment by contradictioned** [comment]
+1

**Comment by contradictioned** [comment]
Following [this blogpost](https://robots.thoughtbot.com/prevent-spoofing-with-paperclip) one could add an exception per file-ending in a `config/initializers/paperclip.rb`:

    Paperclip.options[:content_type_mappings] = {
      json: 'text/plain'
    }

But this is still annoying when you want to deal with arbitrary files (e.g. in an expert system, where you don't care about user generated content). Wouldn't be a option to disable spoof checking be viable?
This could look like:

    class MyModel < ActiveRecord::Base
      has_attached_file :file
      do_not_validate_attachment_file_type :file, anti_spoofing: false
    end

**Comment by jyurek** [comment]
You can disable it. Use `validate_media_type: false` in your attachment definition.
