### ISSUE TITLE
Ruby 1.9 Dropped in Patch Level Version

### ISSUE THREAD

**Issue by tf** [thoughtbot/paperclip#1902]
Hi,

while I understand that Ruby 1.9 has reached EOL, I just wanted to point out that dropping a ruby version in a version bump from 4.2.2 to 4.2.3 makes it quite hard for gem authors like me to keep dependencies on paperclip sane. So if my gem should still support Ruby 1.9, I'll have to depend on `= 4.2.2` now? Then I have to release a new gem version myself and users of my gem will see errors during bundle until they update. I really would have preferred if the version scheme had been a little bit more semantic.

That said, I really enjoy using Paperclip. Thanks for all the awesome work you do! :+1:

**Comment by tute** [comment]
This is true, I didn't take into consideration the fact that it's a quite-backwards-incompatible change. Do you think we should roll it back, @jyurek, and do it in a minor (or even major) release?

**Comment by jyurek** [comment]
Yeah I guess we should roll it back and say that 1.9 can use the 4.2.x branch, and then release 4.2.4.

**Comment by tf** [comment]
While that would surely make things a bit more expressive, it would still force patch level updates on depending gems which cannot drop 1.9 support just now. We currently depend on `~> 4.2` which would have to be changed to `~> 4.2.4` (if we still expect bug fixes to be backported to the `4.2` series).

Was there a special reasoning behind dropping Ruby 1.9 before 4.3? Otherwise, you could also consider to deprecate it/remove it from travis/stop accepting PRs targeting 1.9 and raise the version requirement when 5.0 comes around. At least that would be most graceful path for downstream gems.

**Comment by tute** [comment]
Fixed in referenced commit.

**Comment by tute** [comment]
Released 4.2.4. Thanks for reporting, @tf!

**Comment by tf** [comment]
:+1:
