### ISSUE TITLE
Paperclip 4.3 Ignores Default URL Option for Unsaved Records

### ISSUE THREAD

**Issue by tf** [thoughtbot/paperclip#1904]
Starting with Paperclip 4.3, I see the following behavior:

```ruby
class Model < ActiveRecord::Base
  has_attached_file(:attachment, default_url: "/empty.png", ...)
end

Model.new.attachment.url #=> nil
```

Inside `Model.new.attachment.options` the `:default_url` option is present though. Paperclip 4.2.4 works fine.

Do you know of any change which could cause this behavior?

**Comment by tf** [comment]
[This line](https://github.com/thoughtbot/paperclip/blame/c3fb1194cc4d422fa118cb3e6d0f9dfcc4f0e4f0/lib/paperclip/attachment.rb#L140) introduces the change. Trying to find out why it was added.

**Comment by tf** [comment]
Ok. So #1453 reports the old behavior as a bug and #1811 changes it to return `nil`. I depend on unsaved models to return the default url in various places in most cases for null objects. If this is the new desired behavior I'll have to think of a workaround. In any case, I'd suggest adding a note to the NEWS file.

**Comment by tute** [comment]
> If this is the new desired behavior, I'll have to think of a workaround.

@jyurek are we ok with this change of API?

>  In any case, I'd suggest adding a note to the NEWS file.

Agreed. Would you, or @maclover7, submit a PR for that? Thank you!

**Comment by tf** [comment]
The more I think about it, I can't help but feel that the new behavior is wrong. The concern originally stated in #1453 seems valid to me: If validation fails, do not return an url with invalid id segment. But I think the solution of #1818 (squashed version of #1811) goes to far. Defining a default url is like saying "if no attachment is present, use this alternative url". To me, an unsaved model is just a special case where an attachment isn't present. So why treat it differently?

If a default url is defined, there really should be no case where `url` returns `nil`. @mike-burns also [voiced a concern](https://github.com/thoughtbot/paperclip/pull/1818#issuecomment-86443636) about returning `nil` in the discussion of the PR before it got merged.

Even worse, the current approach doesn't even really fix #1453 in all cases: If a model has already been saved before without an attachment, then an attachment is assigned and validations fail, `url` will still report an url to a non existing file, right?

**Comment by jyurek** [comment]
You make a compelling argument in that if there is a default url it should never return nil. I suppose, though, that using a default url is misleading, too. The file exists, so it's not *wrong* to say it exists. I'm still on board with never returning nil. I'm just trying to think of what is the most correct thing to actually return, now. We can't serve the file out of the tempfile that it's being held in without a bit more work. That work would bleed into a whole new feature of being able to cache the file on form errors -- one which we've said we didn't want to get into.

Hmm.

**Comment by tf** [comment]
Maybe we should look at two different aspects of the problem separately:

* First there is the question what `url` should return if validation failed and the file is only held in a tempfile. I agree that neither `nil` nor the default url are great options here, but there are probably arguments for both.

* The core question of this issue, though, is whether this "validation failed" situation is properly characterized by `new_record?`. I'd much rather say it should be something like `<attachment>_file_name_changed?`. That would not only handle the case where an attachment was uploaded during an failed _update_ of an already existing record, but would also allow returning the default url for unsaved records, just like it used to be.

Does that make sense?

**Comment by mrsimo** [comment]
I just wanted to chime in and say that I've found the same problem after updating to 4.3.0. Specifically in models where we have a `default_url`.

**Comment by ggilder** [comment]
Same here, this change seems to contradict expectations of how `default_url` is used.

**Comment by tf** [comment]
Any update here?

**Comment by jyurek** [comment]
Yeah I'm going to change this so that `default_url` will not return `nil`. Other behaviors might be wrong for a particular application, but returning `nil` is wrong always.

**Comment by tf** [comment]
:+1

**Comment by jyurek** [comment]
Ok, pushed as of 36095bc. Further comments/ideas about what should happen in other cases should go in other issues, IMHO. Thanks for the report and discussion here.

**Comment by asgeo1** [comment]
Awesome. Can you push a new version soon?

**Comment by tute** [comment]
> Can you release a new version soon?

This is a backwards incompatible change, and will require a major version. We will release this patch after Rails 5 is released, and paperclip 5 is working with it well.

Thank you!

**Comment by mrsimo** [comment]
Mmm, wasn't the change the broke this also an incompatible change? Maybe worth to release in 4.4 instead of 5.0?

**Comment by tf** [comment]
+1 I also think this was reverting an incompatible change.

**Comment by tute** [comment]
> Mmm, wasn't the change the broke this also an incompatible change? Maybe worth to release in 4.4 instead of 5.0?

I wasn't aware of this. Can you please point me to the commit that introduced the regression? Thank you!

**Comment by tf** [comment]
[This commit](https://github.com/thoughtbot/paperclip/commit/9a6919404a1e7d61d98aab0749fc25847ed0244a#diff-a4870b4fe431f88fa95c85e4c819ad4fR140) introduces the change in #1811. [This commit](https://github.com/thoughtbot/paperclip/commit/36095bc0701a65054726af55b2689df9f7e75b9c#diff-a4870b4fe431f88fa95c85e4c819ad4fL140) on `master` reverts it.

**Comment by tute** [comment]
Thank you, will release it in 4.3.1: https://github.com/thoughtbot/paperclip/pull/1995
