### ISSUE TITLE
uninitialized constant Paperclip::Schema::ActiveRecord

### ISSUE THREAD

**Issue by vovanmozg** [thoughtbot/paperclip#1906]
I use mongoid-paperclip 0.0.9
Today i try update gem paperclip from 4.2.2 to 4.3.0 and this problem occurred after update.

I found this:
https://github.com/thoughtbot/paperclip/commit/ed2f1929575ef4bc1b94ad39ca58849c48082f85#commitcomment-11312357

If i patch lib/paperclip/glue.rb, this fix compability with mongoid-paperclip:
base.send :include, Schema if defined? ActiveRecord

**Comment by sleung-ttc** [comment]
#1885 rolls back the change. I am not sure why the tests are breaking either.

**Comment by jyurek** [comment]
I committed the changes in #1885. Thanks for reporting this!

**Comment by vovanmozg** [comment]
thank you!
