### ISSUE TITLE
Postgres JSON support

### ISSUE THREAD

**Issue by igagen** [thoughtbot/paperclip#1907]
I have a model with a Postgres JSON field and I'd like to store multiple paperclip image attachments as a nested array within this JSON. The desired structure would look roughly like this:

```
json: {
  notes: [
    {
      title: '',
      images: [{paperclip metadata}, {...}]
    },
    {...}
  ]
}
```

Do I need to override some Paperclip serialization methods to achieve this? Any tips would be appreciated.

**Comment by jyurek** [comment]
You can probably use the `instance_assign` method or a callback to handle something like this.
