### ISSUE TITLE
ruby 2.2.2 rails 4.2.1 method_missing 'has_attached_file' paperclip (4.2.2)

### ISSUE THREAD

**Issue by mrzsilva** [thoughtbot/paperclip#1909]
/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activerecord-4.2.1/lib/active_record/dynamic_matchers.rb:26:in `method_missing': undefined method `has_attached_file' for User (call 'User.connection' to establish a connection):Class (NoMethodError)

After the migration and server restart application all works fine, after a while simply stops working.

Any ideia of cloud it be?
Thanks

**Comment by mrzsilva** [comment]
Upgraded to paperclip 4.3.0, same problem.
Thanks

**Comment by mrzsilva** [comment]
Related to a type in secrets.rb

Sorry

**Comment by PapePathe** [comment]
I have the same issue. Do you know how to fix it?

**Comment by ldco2016** [comment]
I get this error:

`method_missing': undefined method `has_attached_file' for User (call 'User.connection' to establish a connection):Class (NoMethodError)

Which is referencing the User.rb model:

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates_uniqueness_of :username
         
  has_many :articles
  has_many :comments
  
  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" } #, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

end

Any ideas?
