### ISSUE TITLE
Don't support aws-sdk version 2.0

### ISSUE THREAD

**Issue by hoang1417** [thoughtbot/paperclip#1912]
Could we have a quick configuration to make `paperclip` compatible with `aws-sdk` version *2.0*?

**Comment by tute** [comment]
This is being discussed in two sizeable PRs:

* https://github.com/thoughtbot/paperclip/pull/1730
* https://github.com/thoughtbot/paperclip/pull/1903

If you can think of a concrete solution that's "quick", please do send a PR, or describe it in detail to us. We are very much interested in this solution. Otherwhise, moving forward those PRs is the way to go. Thank you!

**Comment by hoang1417** [comment]
Two PRs looks good.

Thanks for the info, @tute :)
