### ISSUE TITLE
Receiving undefined method `avatar' for nil:NilClass

### ISSUE THREAD

**Issue by RailsCod3rFuture** [thoughtbot/paperclip#1913]
I followed the guidelines thoroughly, but this issue with the avatar is persistent. Normal images on posts are showing perfectly fine. I didn't have this problem before. Maybe, you can help me resolve it. 

Application.html.erb
<%= if user_signed_in? ......%>
<li class="round-image-50"><%= image_tag(@user.avatar.url(:thumb), unless: avatar.nil?) %></li>
<% end %>

User.rb
has_attached_file :avatar, :styles => { :medium => "200x200>", :thumb => "100x100>" }, :unless => "avatar.blank?",
                    :url  => "/assets/users/:id/:style/:basename.:extension",
                    :path => ":rails_root/public/assets/users/:id/:style/:basename.:extension"

  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

I created the UsersController btw, but I'm trying use the avatar globally inside of the navigation bar.

**Comment by jyurek** [comment]
"...`unless: avatar.nil?`..." You probably want `unless: @user.avatar.nil?` here.

**Comment by RailsCod3rFuture** [comment]
I'm guessing that <%= image_tag(@user.avatar.url(:thumb), unless: @user.avatar.nil?) %> is for enabling other users to see each others avatar? What I wrote <%= image_tag(current_user.avatar.url(:thumb), unless: current_user.avatar.nil?) %> for the navigation bar. And it's working!!! Thanks.

**Comment by jyurek** [comment]
Awesome! Glad to hear it! :)
