### ISSUE TITLE
Paperclip + Capistrano + S3

### ISSUE THREAD

**Issue by jspizziri** [thoughtbot/paperclip#1919]
When using Capistrano as a deploy tool with Paperclip and S3 symlinking a `public` directory doesn't work as the symlink is only on the app server. 

`:rails_root` will resolve to something like the following: `/my/deploy/path/releases/201507020651/` which would typically just contain a symlink to a shared `public` directory, but this is not the case with S3.

This causes a problem when using Paperclip with S3 and deploying with Capistrano as the S3 path will contain the specific release version. When the application is then redeployed, paperclip will be looking for the asset in the S3 path that contains the *new* release timestamp.

**Comment by jspizziri** [comment]
I'd recommend adding something to the documentation concerning Paperclip + Capistrano + S3 to suggest modifying the Interpolates for `:rails_root`

**Comment by jspizziri** [comment]
https://github.com/thoughtbot/paperclip/pull/1920

**Comment by jyurek** [comment]
I'm not sure what you're expecting `:rails_root` to be if not the `Rails.root`. The `:rails_root` Interpolation [is clearly documented](https://github.com/thoughtbot/paperclip/blob/master/lib/paperclip/interpolations.rb#L72) to say what it returns.

**Comment by jspizziri** [comment]
Thats true, however did you read the issue that occurs with the standard interpolation + s3 + capistrano? Theres also documentation about using symlinks to store images, but that was documented.

There's documentation on Capistrano, but it doesn't encompass using the s3... I'm not sure why you wouldn't want to include that.

**Comment by asecondwill** [comment]
I don't know if the proposed solution is the right one, but I have the same issue, paperclip is storing files with the release number in the path.  That seems wrong?  Do I Need to configure paperclip differently? It's a disconcerting path.

**Comment by asecondwill** [comment]
Just seen this is closed.
