### ISSUE TITLE
Saving an image from a invalid URL throws URI::InvalidURIError

### ISSUE THREAD

**Issue by Piioo** [thoughtbot/paperclip#1921]
Hello,

When I try to save an image from a non-valid URL, such as **http://www.foo/öäü.jpg**, I always get an URI::InvalidURIError: bad URI(is not URI?).

    class User < ActiveRecord::Base
      has_attached_file :picture

      def picture_from_url(url)
        self.picture = open(url)
      end
    end

Would it be possible to put in place here before the URI call an URI.escape?
https://github.com/thoughtbot/paperclip/blob/master/lib/paperclip/io_adapters/http_url_proxy_adapter.rb#L7

**Comment by jyurek** [comment]
Sure, if you want to make a PR for this, I'd be happy to pull it in.

**Comment by jyurek** [comment]
In the meantime, I'm going to close this. Please feel free to submit the PR, though. Thanks! :)
