### ISSUE TITLE
Error in MediaSpoofTypeDectector

### ISSUE THREAD

**Issue by jbolles5** [thoughtbot/paperclip#1926]
After upgrading to the latest version of Paperclip, I am getting this error on uploads to Heroku. Does not happen in my local test environment.

undefined local variable or method `supplied_file_content_types' for #<Paperclip::MediaTypeSpoofDetector:0x007fc788ce0a70> config/initializers/paperclip.rb:26:in `media_type_mismatch?'

Here is the offending code:

```
module Paperclip
  class MediaTypeSpoofDetector
    # Make spoof detection stricter - original only compared type so all 'application' types matched all others
    def media_type_mismatch?
      ! supplied_file_content_types.include?(calculated_content_type)
    end
  end
end
```

Any thoughts?

**Comment by jyurek** [comment]
This looks like you're monkeypatching Paperclip here. The `supplied_file_content_types` method doesn't exist anymore.

**Comment by jbolles5** [comment]
The problem is that all iWork files are reporting as application/octet-stream or application/zip. I added some code to help account for that issue:

```
Paperclip.options[:content_type_mappings] = {
      :docx => "application/x-zip",
      :xlsx => "application/x-zip",
      :pptx => "application/x-zip",
      :pages => "application/x-zip",
      :numbers => "application/x-zip",
      :key => "application/x-zip"
  }
```

What are my options here?
