### ISSUE TITLE
Display file information in view when selecting a file.

### ISSUE THREAD

**Issue by simkessy** [thoughtbot/paperclip#1927]
Hi, 

I styled the default input box but now when i attach a file, it doesn't display the file_name. 

I'm trying to figure out how to get the current file and display that in my view.

This is what I have in my view: 

```
<%= f.input :images, as: :file, label: "Upload facility images", input_html: { id: 'facilityImage' }, wrapper_html:{ class:"btn btn-warning btn-file" } %>
```

css: 

```
.btn-file {
    position: relative;
    overflow: hidden;

    input[type=file] {
      position: absolute;
      top: 0;
      right: 0;
      min-width: 100%;
      min-height: 100%;
      font-size: 100px;
      text-align: right;
      filter: alpha(opacity=0);
      opacity: 0;
      outline: none;
      background: white;
      cursor: inherit;
      display: block;
    }
}
```

**Comment by jyurek** [comment]
File upload boxes will never be prepopulated as a matter of security. You'll have to display the name of the file (or a thumbnail) manually somewhere else in the HTML. If you want to display the image, you should be able to use `image_tag form.object.image.url` assuming your attachment is called `image`.
