### ISSUE TITLE
jruby compatibility fix

### ISSUE THREAD

**Issue by gucki** [thoughtbot/paperclip#193]
Paperclip fails with Errno::EACCES (Permission denied - Permission denied ) when using jruby and tmp and final destination folder are on separate partitions. There seem's to be no easy fix for jruby itself (http://jira.codehaus.org/browse/JRUBY-3381). It would be perfect if paperclip could include workaround:

module Paperclip
  module Storage
    module Filesystem
      # workaround for Errno::EACCES (Permission denied - Permission denied) when using jruby
      # see http://jira.codehaus.org/browse/JRUBY-3381
      def flush_writes #:nodoc:
        @queued_for_write.each do |style, file|
          file.close
          FileUtils.mkdir_p(File.dirname(path(style)))
          log("saving #{path(style)}")
          if RUBY_PLATFORM =~ /java/i
            FileUtils.cp(file.path, path(style))
            FileUtils.rm(file.path)
          else
            FileUtils.mv(file.path, path(style))
          end
          FileUtils.chmod(0644, path(style))
        end
        @queued_for_write = {}
      end
    end
  end
end

**Comment by crystianwendel** [comment]
In 2011 you've solved this, but just a few months later, the commit [f8c2444](https://github.com/thoughtbot/paperclip/commit/f8c244456d150c7b26440564feb085ce431d82c8#diff-52fe7c86eb640ff0d49bb02e5f9aa23a4668a6cab85047b4398c8e652a51807f) just broke it again.

To everyone having problems with jruby and file uploads in Windows, this monkey patch solves it.
It's broken in kt-paperclip as well.

```paperclip_filesystem_mp.rb
# config/initializers/paperclip_filesystem_mp.rb
module Paperclip
  module Storage
    module Filesystem
      private

      def move_file(src, dest)
        # Support hardlinked files
        if File.identical?(src, dest)
          File.unlink(src)
        else
          FileUtils.cp(src, dest)
          FileUtils.rm(src)
        end
      end
    end
  end
end
```

Just a few keywords, i've spent hours in wrong direction to solve this: windows iis permission file being used by another process error
