### ISSUE TITLE
Paperclip 4.3.x: Saving new record with copy of attachment of existing record: Is a directory @ unlink_internal - /app/public

### ISSUE THREAD

**Issue by fw42** [thoughtbot/paperclip#1930]
Hey,

I'm running into a weird bug that I don't understand.

I have a Rails (4.2.3) application and a model that has a `has_attached_file :image`.

Now I want to copy an attachment from one record of that model to another, basically just doing
```ruby
thing.image = other_thing.image
thing.save!
```

On Paperclip 4.2.3, this works fine. When upgrading to Paperclip 4.3.0, I get the following exception:
```
[paperclip] deleting /app/public
...
Errno::EISDIR (Is a directory @ unlink_internal - /app/public):
...
```

Any ideas? I can try to come up with a full example of how to reproduce this if necessary.

**Comment by fw42** [comment]
4.2.4 also works fine.

**Comment by fw42** [comment]
[This line](https://github.com/thoughtbot/paperclip/blob/c3fb1194cc4d422fa118cb3e6d0f9dfcc4f0e4f0/lib/paperclip/attachment.rb#L140) was added in 4.3.0. Removing it seems to fix my problem.

**Comment by fw42** [comment]
Note that `thing` in my example above is a new record that hasn't been saved yet.

**Comment by fw42** [comment]
Looks like this was already fixed in https://github.com/thoughtbot/paperclip/commit/36095bc0701a65054726af55b2689df9f7e75b9c.

**Comment by fw42** [comment]
Confirmed that my problem doesn't exist on master anymore. Sorry for the noise. Thanks!

**Comment by fw42** [comment]
@jyurek: Would you mind releasing 4.3.1 to Rubygems with your patch?

**Comment by patricks** [comment]
thx @fw42 for the info.

4.2.4 also works fine here.
