### ISSUE TITLE
Is it conceived that duplicates of validation errors use different keys in locales?

### ISSUE THREAD

**Issue by jeremen** [thoughtbot/paperclip#1931]
Let's suppose that we have image attribute in our model and next validation rules:
validates_with AttachmentContentTypeValidator, attributes: :image, content_type: /\Aimage\/.*\Z/
validates_with AttachmentSizeValidator, attributes: :image, less_than: 500.kilobytes

Then paths to keys in locales will look like:
For "image" attribute of content type validation: locale.activerecord.errors.models.model.attributes.image_content_type.invalid
For "image_content_type" attribute of content type validation: locale.activerecord.errors.models.model.attributes.image_content_type.invalid
For "image" attribute of size validation:
locale.activerecord.errors.models.country.attributes.image.less_than
For "image__file_size" attribute of size validation:
locale.activerecord.errors.models.country.attributes.image_file_size.less_than

So is this a bug or it was originally intended?

**Comment by jyurek** [comment]
FTR, this is intended. You should hide the one you don't care about.

**Comment by jeremen** [comment]
Thank you for response. Is there any prefered way to do so? Maybe some configurations or anything, because use of after_validation callback doesn't seem to be the best solution for me.
