### ISSUE TITLE
paperclip fails to process images taken from mobile camera

### ISSUE THREAD

**Issue by vikks** [thoughtbot/paperclip#1934]
When i try to upload images taken from my mobile phone(yu yureka running cynogen mod), i see this in the log and it stops processing the image. but i can process images taken from other sources including other mobile phones.

```
 Command :: file -b --mime '/tmp/8a4ffb1207b3cd77e30f77f86c6fbe1620150713-14602-1w7askq.jpg'
 Command :: identify -format '%wx%h,%[exif:orientation]' '/tmp/8a4ffb1207b3cd77e30f77f86c6fbe1620150713-14602-1eb8u4b.jpg[0]' 2>/dev/null
```

My stack: 
  rails:        4.0.9
  paperclip: 4.3.0

test image to process....

![img_20150713_111909](https://cloud.githubusercontent.com/assets/681492/8643472/ed2dbeec-2951-11e5-92db-29ba4cddd872.jpg)

**Comment by tute** [comment]
How exactly can we reproduce this issue @vikks? Please see http://yourbugreportneedsmore.info/. Thank you!

**Comment by vikks** [comment]
it's a phonegap android9kitkat) quirk where images taken with the phone camera do not have proper extension(jpg, png) when uploaded with such images paperclip fails to recognize them as images and stops processing but the aws-s3 gem tries to upload the non existent image to s3 and it fails.

**Comment by mike-burns** [comment]
Thank you for reporting this. Unfortunately, we will be deprecating Paperclip and therefore will not have the bandwidth to address this issue.
