### ISSUE TITLE
Edit form. Attachment doesn't filled

### ISSUE THREAD

**Issue by gabyshev** [thoughtbot/paperclip#1935]
When I edit object file input is not filled with existing attachment.
How to make it fill if attachment exists?

http://stackoverflow.com/questions/31291540/attachment-doesnt-filled-in-edit-form

I tried edit `_form` partial as in example in README:

```Ruby
<%= form_for @user, :url => users_path, :html => { :multipart => true } do |form| %>
  <%= form.file_field :avatar %>
<% end %>
```

**Comment by tute** [comment]
Closing this in favor of the question in StackOverflow. I am sorry I don't have the time right now to debug this and help with your issue.
