### ISSUE TITLE
Infinite log loop when uploading

### ISSUE THREAD

**Issue by Wonay** [thoughtbot/paperclip#1938]
`lication/cybercash", @raw_media_type="application", @raw_sub_type="cybercash", @simplified="application/cybercash", @i18n_key="application.cybercash",
 @media_type="application", @sub_type="cybercash", @extensions=[]>], "application/dash+xml"=>[#<MIME::Type::Columnar:0x359d300 @container=#<MIME::Type
s:0x36d7d48 ...>, @content_type="application/dash+xml", @raw_media_type="application", @raw_sub_type="dash+xml", @simplified="application/dash+xml", @
i18n_key="application.dash-xml", @media_type="application", @sub_type="dash+xml", @extensions=[]>], "application/dashdelta"=>[#<MIME::Type::Columnar:0
x3596aa8 @container=#<MIME::Types:0x36d7d48 ...>, @content_type="application/dashdelta", @raw_media_type="application", @raw_sub_type="dashdelta", @si
mplified="application/dashdelta", @i18n_key="application.dashdelta", @media_type="application", @sub_type="dashdelta", @extensions=[]>], "application/
davmount+xml"=>[#<MIME::Type::Columnar:0x3594fc0 @container=#<MIME::Types:0x36d7d48 ...>, @content_type="application/davmount+xml", @raw_media_type="a
pplication", @raw_sub_type="davmount+xml", @simplified="application/davmount+xml", @i18n_key="application.davmount-xml", @media_type="application", @s
ub_type="davmount+xml", @extensions=["davmount"]>], "application/dca-rft"=>[#<MIME::Type::Columnar:0x35944f8 @container=#<MIME::Types:0x36d7d48 ...>,
@content_type="application/dca-rft", @raw_media_type="application", @raw_sub_type="dca-rft", @simplified="application/dca-rft", @i18n_key="application
.dca-rft", @media_type="application", @sub_type="dca-rft", @extensions=[]>], "application/dcd"=>[#<MIME::Type::Columnar:0x358fc50 @container=#<MIME::T
ypes:0x36d7d48 ...>, @content_type="application/DCD", @raw_media_type="application", @raw_sub_type="DCD", @simplified="application/dcd", @i18n_key="ap
plication.dcd", @media_type="application", @sub_type="dcd", @extensions=[]>], "application/dec-dx"=>[#<MIME::Type::Columnar:0x358f5f0 @container=#<MIM
E::Types:0x36d7d48 ...>, @content_type="application/dec-dx", @raw_media_type="application", @raw_sub_type="dec-dx", @simplified="application/dec-dx",
@i18n_key="application.dec-dx", @media_type="application", @sub_type="dec-dx", @extensions=[]>], "application/dialog-info+xml"=>[#<MIME::Type::Columna
r:0x358ee70 @container=#<MIME::Types:0x36d7d48 ...>, @content_type="application/dialog-info+xml", @raw_media_type="application", @raw_sub_type="dialog
-info+xml", @simplified="application/dialog-info+xml", @i18n_key="application.dialog-info-xml", @media_type="application", @sub_type="dialog-info+xml"
, @extensions=[]>], "application/dicom"=>[#<MIME::Type::Columnar:0x358e7e0 @container=#<MIME::Types:0x36d7d48 ...>, @content_type="application/dicom",
 @raw_media_type="application", @raw_sub_type="dicom", @simplified="application/dicom", @i18n_key="application.dicom", @media_type="application", @sub
_type="dicom", @extensions=["dcm"]>], "application/dii"=>[#<MIME::Type::Columnar:0x358da30 @container=#<MIME::Types:0x36d7d48 ...>, @content_type="app
lication/DII", @raw_media_type="application", @raw_sub_type="DII", @simplified="application/dii", @i18n_key="application.dii", @media_type="applicatio
n", @sub_type="dii", @extensions=[]>], "application/dit"=>[#<MIME::Type::Columnar:0x358ce30 @container=#<MIME::Types:0x36d7d48 ...>, @content_type="ap
plication/DIT", @raw_media_type="application", @raw_sub_type="DIT", @simplified="application/dit", @i18n_key="application.dit", @media_type="applicati
on", @sub_type="dit", @extensions=[]>], "application/dns"=>[#<MIME::Type::Columnar:0x358c428 @container=#<MIME::Types:0x36d7d48 ...>, @content_type="a
pplication/dns", @raw_media_type="application", @raw_sub_type="dns", @simplified="application/dns", @i18n_key="application.dns", @media_type="applicat
ion", @sub_type="dns", @extensions=[]>], "application/docbook+xml"=>[#<MIME::Type::Columnar:0x3587c58 @container=#<MIME::Types:0x36d7d48 ...>, @conten
t_type="application/docbook+xml", @raw_media_type="application", @raw_sub_type="docbook+xml", @simplified="application/docbook+xml", @i18n_key="applic
ation.docbook-xml", @media_type="application", @sub_type="docbook+xml", @extensions=["dbk"]>], "application/drafting"=>[#<MIME::Type::Columnar:0x3586a
58 @container=#<MIME::Types:0x36d7d48 ...>, @content_type="application/drafting", @raw_media_type="application", @raw_sub_type="drafting", @simplified
="application/drafting", @i18n_key="application.drafting", @media_type="application", @sub_type="drafting", @extensions=[]>, #<MIME::Type::Columnar:0x
48e0d60 @container=#<MIME::Types:0x36d7d48 ...>, @content_type="application/x-drafting", @raw_media_type="application", @raw_sub_type="x-drafting", @s
implified="application/drafting", @i18n_key="application.drafting", @media_type="application", @sub_type="drafting", @extensions=[]>], "application/ds
kpp+xml"=>[#<MIME::Type::Columnar:0x3585ab0 @container=#<MIME::Types:0x36d7d48 ...>, @content_type="application/dskpp+xml", @raw_media_type="applicati
on", @raw_sub_type="dskpp+xml", @simplified="application/dskpp+xml", @i18n_key="application.dskpp-xml", @media_type="application", @sub_type="dskpp+xm
l", @extensions=[]>], "application/dssc+der"=>[#<MIME::Type::Columnar:0x3584ec8 @container=#<MIME::Types:0x36d7d48 ...>, @content_type="application/ds
sc+der", @raw_media_type="application", @raw_sub_type="dssc+der", @simplified="application/dssc+der", @i18n_key="application.dssc-der", @media_type="a
pplication", @sub_type="dssc+der", @extensions=["dssc"]>], "application/dssc+xml"=>[#<MIME::Type::Columnar:0x35841f0 @container=#<MIME::Types:0x36d7d4
8 ...>, @content_type="application/dssc+xml", @raw_media_type="application", @raw_sub_type="dssc+xml", @simplified="application/dssc+xml", @i18n_key="
application.dssc-xml", @media_type="application", @sub_type="dssc+xml", @extensions=["xdssc"]>], "application/dvcs"=>[#<MIME::Type::Columnar:0x3577818
 @container=#<MIME::Types:0x36d7d48 ...>, @content_type="application/dvcs", @raw_media_type="application", @raw_sub_type="dvcs", @simplified="applicat
ion/dvcs", @i18n_key="application.dvcs", @media_type="application", @sub_type="dvcs", @extensions=[]>], "application/dxf"=>[#<MIME::Type::Columnar:0x3
576648 @container=#<MIME::Types:0x36d7d48 ...>, @content_type="application/dxf", @raw_media_type="application", @raw_sub_type="dxf", @simplified="appl
ication/dxf", @i18n_key="application.dxf", @media_type="application", @sub_type="dxf", @extensions=[]>, #<MIME::Type::Columnar:0x48eb410 @container=#<
MIME::Types:0x36d7d48 ...>, @content_type="application/x-dxf", @raw_media_type="application", @raw_sub_type="x-dxf", @simplified="application/dxf", @i
18n_key="application.dxf", @media_type="application", @sub_type="dxf", @extensions=[]>], "application/ecmascript"=>[#<MIME::Type::Columnar:0x3574470 @
container=#<MIME::Types:0x36d7d48 ...>, @content_type="application/ecmascript", @raw_media_type="application", @raw_sub_type="ecmascript", @simplified
="application/ecmascript", @i18n_key="application.ecmascript", @media_type="application", @sub_type="ecmascript", @extensions=["ecma"]>], "application
/edi-consent"=>[#<MIME::Type::Columnar:0x356b608 @container=#<MIME::Types:0x36d7d48 ...>, @content_type="application/EDI-consent", @raw_media_type="ap
plication", @raw_sub_type="EDI-consent", @simplified="application/edi-consent", @i18n_key="application.edi-consent", @media_type="application", @sub_t
ype="edi-consent", @extensions=[]>], "application/edi-x12"=>[#<MIME::Type::Columnar:0x356a450 @container=#<MIME::Types:0x36d7d48 ...>, @content_type="`

I get pages and pages of that going on in my console where i start `rails server` , it stops after few minutes. It happens no matter which file i am uploading...

**Comment by Wonay** [comment]
it actually start like that: 

`Command :: file -b --mime "C:/Users/LeoMAC/AppData/Local/Temp/f8e6b0d6e0fba6cd0cea702ba09862bd20150717-9804-wlhh19.jpg"
[paperclip] Content Type Spoof: Filename XGaT85awqoPmNh4VsLLPsiqc_dreamt.jpg (image/jpeg from Headers, [#<MIME::Type::Columnar:0x4bef7a8 @container=#<
MIME::Types:0x4bee368 @type_variants={"application/1d-interleaved-parityfec"=>[#<MIME::Type::Columnar:0x4bede28 @container=#<MIME::Types:0x4bee368 ...
>, @content_type="application/1d-interleaved-parityfec", @raw_media_type="application", @raw_sub_type="1d-interleaved-parityfec", @simplified="applica
tion/1d-interleaved-parityfec", @i18n_key="application.1d-interleaved-parityfec", @media_type="application", @sub_type="1d-interleaved-parityfec", @ex
tensions=[]>], "application/3gpdash-qoe-report+xml"=>[#<MIME::Type::Columnar:0x4bed9d8 @container=#<MIME::Types:0x4bee368 ...>, @content_type="applica
tion/3gpdash-qoe-report+xml", @raw_media_type="application", @raw_sub_type="3gpdash-qoe-report+xml", @simplified="application/3gpdash-qoe-report+xml",
 @i18n_key="application.3gpdash-qoe-report-xml", @media_type="application", @sub_type="3gpdash-qoe-report+xml", @extensions=[]>], "application/3gpp-im
s+xml"=>[#<MIME::Type::Columnar:0x4bed5b8 @container=#<MIME::Types:0x4bee368 ...>, @content_type="application/3gpp-ims+xml", @raw_media_type="applicat
ion", @raw_sub_type="3gpp-ims+xml", @simplified="application/3gpp-ims+xml", @i18n_key="application.3gpp-ims-xml", @media_type="application", @sub_type
="3gpp-ims+xml", @extensions=[]>], "application/a2l"=>[#<MIME::Type::Columnar:0x4bed198 @container=#<MIME::Types:0x4bee368 ...>, @content_type="applic
ation/A2L", @raw_media_type="application", @raw_sub_type="A2L", @simplified="application/a2l", @i18n_key="application.a2l", @media_type="application",
 @sub_type="a2l", @extensions=[]>], "application/acad"=>[#<MIME::Type::Columnar:0x4becdd8 @container=#<MIME::Types:0x4bee368 ...>, @content_type="appl
ication/acad", @raw_media_type="application", @raw_sub_type="acad", @simplified="application/acad", @i18n_key="application.acad", @media_type="applica
tion", @sub_type="acad", @extensions=[]>], "application/access"=>[#<MIME::Type::Columnar:0x4bec9d0 @container=#<MIME::Types:0x4bee368 ...>, @content_t
ype="application/access", @raw_media_type="application", @raw_sub_type="access", @simplified="application/access", @i18n_key="application.access", @me
dia_type="application", @sub_type="access", @extensions=["mdf", "mda", "mdb", "mde"]>, #<MIME::Type::Columnar:0x4e24fa8 @container=#<MIME::Types:0x4be
e368 ...>, @content_type="application/x-access", @raw_media_type="application", @raw_sub_type="x-access", @simplified="application/access", @i18n_key=
"application.access", @media_type="application", @sub_type="access", @extensions=["mdf", "mda", "mdb", "mde"]>], "application/activemessage"=>[#<MIME:
:Type::Columnar:0x4bec4c0 @container=#<MIME::Types:0x4bee368 ...>, @content_type="application/activemessage", @raw_media_type="application", @raw_sub_
type="activemessage", @simplified="application/activemessage", @i18n_key="application.activemessage", @media_type="application", @sub_type="activemess
age", @extensions=[]>], "application/alto-costmap+json"=>[#<MIME::Type::Columnar:0x4bec100 @container=#<MIME::Types:0x4bee368 ...>, @content_type="app
lication/alto-costmap+json", @raw_media_type="application", @raw_sub_type="alto-costmap+json", @simplified="application/alto-costmap+json", @i18n_key=
"application.alto-costmap-json", @media_type="application", @sub_type="alto-costmap+json", @extensions=[]>], "application/alto-costmapfilter+json"=>[#
<MIME::Type::Columnar:0x4bffca8 @container=#<MIME::Types:0x4bee368 ...>, @content_type="application/alto-costmapfilter+json", @raw_media_type="applica`

**Comment by Wonay** [comment]
I also posted the question there: http://stackoverflow.com/questions/31486108/infinite-log-with-paperclip-and-ruby-on-rails

**Comment by shadwell** [comment]
Stackoverflow comment suggests that this problem was that ImageMagick was not present (to assist with investigation/triage/resolution)

**Comment by tute** [comment]
Solved in StackOverflow. Thanks!
