### ISSUE TITLE
how to add '-limit memory 32MiB -limit map 64 MiB' to identify command?

### ISSUE THREAD

**Issue by devon** [thoughtbot/paperclip#1943]
identify command fails on some large svg files.

The command:

```
identify -format '%wx%h,%[exif:orientation]' '/tmp/e5f37d14a8e3f3324bdf51334cf1670420150722-12509-1fuhlr6.svg[0]' 2>/dev/null
```

The thread was killed by system because too much memory usage.

Add '-limit memory 32MiB -limit map 64 MiB' to identify works. 

In the code:

```ruby
  def geometry_string
      begin
        orientation = Paperclip.options[:use_exif_orientation] ?
          "%[exif:orientation]" : "1"
        Paperclip.run(
          "identify",
          "-format '%wx%h,#{orientation}' :file", {
            :file => "#{path}[0]"
          }, {
            :swallow_stderr => true
          }
        )
      rescue Cocaine::ExitStatusError
        ""
      rescue Cocaine::CommandNotFoundError => e
        raise_because_imagemagick_missing
      end
    end
```

Is there any way to add more options to identify command?

**Comment by levon-n** [comment]
try this
<code>
Paperclip.run(
          "identify",
          "-format '%wx%h,#{orientation}' <b>-limit memory 32MiB -limit map 64 MiB</b> :file", {
            :file => "#{path}[0]"
          }, {
            :swallow_stderr => true
          }
        )
</code>

**Comment by devon** [comment]
` Paperclip.run` is in paperclip source code.  Is there any way to pass params `-limit memory 32MiB -limit map 64 MiB` to paperclip without modify the source  code?

**Comment by tute** [comment]
@jyurek does paperclip have extension options so we can pass in parameters to `identify`? Would be nice to add them if we don't, I think.

**Comment by jyurek** [comment]
Not to `identify`, no. I'd be open to PRs to fix this.

**Comment by tute** [comment]
@devon can you start working on this? I will help you with your PR. Thanks!

**Comment by tute** [comment]
@devon are you interested in adding this option? We don't have the availability to add it. Thank you!

**Comment by bladealslayer** [comment]
I'm starting to work on a PR for this. Do you think a global paperclip option or a per-attachment options for limiting `memory` and `map` would be better in general, @tute?

**Comment by bladealslayer** [comment]
Huh, turns out no need to modify paperclip at all. You can pass the memory and map limits via environment variable: just set `MAGICK_MEMORY_LIMIT=32MiB` and `MAGICK_MAP_LIMIT=64MiB` as environment variables.

**Comment by tute** [comment]
> Huh, turns out no need to modify paperclip at all. You can pass the memory and map limits via environment variable: just set `MAGICK_MEMORY_LIMIT=32MiB` and `MAGICK_MAP_LIMIT=64MiB` as environment variables.

Thanks for your find! @devon or @bladealslayer: do you think we should add this to the wiki or README? Thanks!

**Comment by bladealslayer** [comment]
Yeah, a link to http://www.imagemagick.org/script/resources.php could be added to docs.

**Comment by tute** [comment]
> Yeah, a link to http://www.imagemagick.org/script/resources.php could be added to docs.

Agreed. Would you send over a PR adding a note in https://github.com/thoughtbot/paperclip/#post-processing? Thanks!

**Comment by bladealslayer** [comment]
PR opened @tute

**Comment by tute** [comment]
Thank you! :)
