### ISSUE TITLE
some file types have empty file types from extension, but have a `file` inferred type

### ISSUE THREAD

**Issue by bwlang** [thoughtbot/paperclip#1944]
e.g.
Content Type Spoof: Filename 150720_1.pcrd ( from Headers, [] from Extension), content type discovered from file command: application/zip. See documentation to allow this combination.

I think we don't have to worry about any disagreement between types when only one has been specified... pull request on the way

**Comment by tute** [comment]
Closing in favor of discussion in PR. Thank you!
