### ISSUE TITLE
v4.3.0 - Rails 3.2 support broken by Paperclip::Schema::Statements.remove_attachment

### ISSUE THREAD

**Issue by andrewhubbs** [thoughtbot/paperclip#1946]
It appears that support for Rails 3.2 is not working in Paperclip 4.3.0. If this is not by mistake, what is the correct version of Paperclip to use that still supports Rails 3.2?

### Details:

`Paperclip::Schema::Statements.remove_attachment` calls `remove_column` with the method signature `remove_column(table_name, column_name, type = nil, options = {})`.

Rails 3.2 version of this method expects `remove_column(table_name, *column_names)`.

Result is an error like this because the column type is interpreted as an additional column to be dropped:
`PG::Error: ERROR:  column "string" of relation "model" does not exist`

**Comment by tute** [comment]
Thank you for reporting! Closing in favor of discussion in PR.
