### ISSUE TITLE
Content type detection of PSD file throws NoMethodError

### ISSUE THREAD

**Issue by airblade** [thoughtbot/paperclip#1953]
I have a Photoshop PSD file called `LBT-73-15-046_cuff_rings_blue.jpg.psd`.  Paperclip 4.3.0 can't detect its content type:

```ruby
[1] pry(main)> require 'paperclip'
true
[2] pry(main)> Paperclip::VERSION
"4.3.0"
[3] pry(main)> ctd = Paperclip::ContentTypeDetector.new 'LBT-73-15-046_cuff_rings_blue.jpg.psd'
#<Paperclip::ContentTypeDetector:0x007fc75b03de58 @filepath="LBT-73-15-046_cuff_rings_blue.jpg.psd">
[4] pry(main)> ctd.detect
NoMethodError: undefined method `try' for nil:NilClass
from /Users/andy/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/paperclip-4.3.0/lib/paperclip/content_type_detector.rb:71:in `type_from_mime_magic'
```

Line [71](https://github.com/thoughtbot/paperclip/blob/c3fb1194cc4d422fa118cb3e6d0f9dfcc4f0e4f0/lib/paperclip/content_type_detector.rb#L71) is:

```ruby
MimeMagic.by_magic(File.open(@filepath)).try(:type)
```

Paperclip is using MimeMagic 0.3.0.  This is the [line that doesn't find a mime type](https://github.com/minad/mimemagic/blob/v0.3.0/lib/mimemagic.rb#L87).

**Comment by airblade** [comment]
I wasn't sure whether MimeMagic would be expected to identify a PSD `by_magic` so I asked in minad/mimemagic#24.

**Comment by dgynn** [comment]
`try` is not defined in your example because ActiveSupport isn't loaded. Try your sample code again with...
```ruby
require 'active_support/all'
```
It may still fail to identify but it shouldn't be a NoMethodError.

**Comment by airblade** [comment]
Aha, thank you.  Requiring active support gets rid of the no method error and indeed identifies the mime type correctly.

Super!
