### ISSUE TITLE
don't save *.pdf with content_type: "applications/vnd.pdf"

### ISSUE THREAD

**Issue by RobBikmansurov** [thoughtbot/paperclip#1954]
paperclip-4.3.0
Rails 4.2.3 on ubuntu
mime-types-2.6.1

```ruby
validates_attachment_content_type :appendix, 
    :content_type => [ 'application/pdf', 'application/vnd.pdf', /\Aimage/, /\Aapplication/ ]
```

When I try to upload a file *.pdf, I get the following message in the log:

`
   (0.8ms)  ROLLBACK
#<LetterAppendix id: nil, letter_id: 2, name: "", created_at: nil, updated_at: nil, appendix_file_name: "OD1918.pdf", appendix_content_type: "applications/vnd.pdf", appendix_file_size: 195075, appendix_updated_at: "2015-08-05 04:55:18">
Appendix has contents that are not what they are reported to be
`

How can I upload such a file?

**Comment by tute** [comment]
You will find more info on https://github.com/thoughtbot/paperclip/issues/1771. This is a known bug, closing as duplicate. Thanks for your submission.
