### ISSUE TITLE
Temp file with length of 0 raises NotIdentifiedByImageMagickError, could be better handled

### ISSUE THREAD

**Issue by dpritchett** [thoughtbot/paperclip#1955]
cross post from #1223:

> @leeizamo I just had the same error crop up for me but the only time it happened was when I was reprocess!ing and image off of S3. Turns out the image dimensions check first redownloads the image from S3 into /tmp and then tries to check its size using local ImageMagick tools (file -b --mime /tmp/filenamehere. For reasons unkown to me the tmp file was there but its length was 0.

> On a lark I tried messing with a few different versions of aws-sdk.

> Pinning my aws-sdk version to ~> 1.6 as mentioned in a comment in Paperclip's S3 class seems to have fixed it.

This error seems to be a side effect of a bad `aws-sdk` version.  Given that paperclip doesn't force an aws sdk version we could maybe consider insisting of a specific version (you probably already have a reason for not doing that) or at least checking for cases when the temp file exists but has a length of 0 and throwing a more specific error.

Thanks!

**Comment by tute** [comment]
> Given that paperclip doesn't force an aws sdk version we could maybe consider insisting of a specific version

I am all for it, it seems like many difficulties in paperclip arise from that. What would be a sensible version to lock paperclip to? @jyurek do you see any problem with this approach?

**Comment by jyurek** [comment]
I'm all for putting version restrictions on it, except for when I do, it seems that someone else has a problem with the way it got done. I don't really know what to do here.

**Comment by dpritchett** [comment]
Maybe we can duck type all of the requirements from AWS rather than
actually locking a version; could even rescue the common AWS errors and
throw out some "try version XYZ!" error messages.

**Comment by tute** [comment]
Closing in favor of discussion in PR.
