### ISSUE TITLE
Paperclip Truck Factor

### ISSUE THREAD

**Issue by gavelino** [thoughtbot/paperclip#1957]
As part of my PhD research on code authorship, we calculated the Truck Factor (TF) of some popular GitHub repositories.

As you probably know, the [Truck (or Bus) Factor](https://en.wikipedia.org/wiki/Bus_factor) designates the minimal number of developers that have to be hit by a truck (or quit) before a project is incapacitated. In our work, we consider that a system is in trouble if more than 50% of its files become orphan (i.e., without a main author).

More details on our work in this preprint: https://peerj.com/preprints/1233

We calculated the TF for **Paperclip** and obtained a value of **1**.

The developer responsible for this TF is:

Jon Yurek - author of 81% of the files 

To validate our results, we would like to ask **Paperclip** developers the following three brief questions:

(a) Do you agree that the listed developer is the main developer of **Paperclip**?

(b) Do you agree that **Paperclip** will be in trouble if the listed developer leave the project (e.g., if he wins in the lottery, to be less morbid)?

(c) Does **Paperclip** have some characteristics that would attenuate the loss of the listed developer (e.g., detailed documentation)?

Thanks in advance for your collaboration,

Guilherme Avelino
PhD Student
Applied Software Engineering Group (ASERG)
UFMG, Brazil
http://aserg.labsoft.dcc.ufmg.br/

**Comment by tute** [comment]
@gavelino thanks so much for your submission. To respond to your first two questions, we agree and are aware of the risky bus factor for this project, and are trying to improve it.

> (c) Does Paperclip have some characteristics that would attenuate the loss of the listed developer (e.g., detailed documentation)?

Paperclip has great documentation, and in its eight years it has grown a significant community. Even with a sizable and active community a project can stagnate, though.

That risk is attenuated by thoughtbot owning the project, which is a ~100 people company that allows all its employees to work 20% of their time in what they see best, which is Open Source for some of us. Even if @jyurek won the lottery and never again contributed back to paperclip, thoughtbot would find a way to continue its development, or offload it to some other group in case we find we are not good leaders anymore.

A number that would challenge the calculated bus factor is how many people can release the software. According to https://rubygems.org/gems/paperclip, 5 concrete people have access, and through thoughtbot many others.

Will close the issue as it's not a technical bug (which is how we typically use this issue tracker). I am happy to continue the discussion. Also, please do share your research work when you can.

**Comment by gavelino** [comment]
Thank you,

**Comment by tute** [comment]
@gavelino don't forget to share the work from your research! Thank you.

**Comment by gavelino** [comment]
Hi @tute, 

we submitted our research for a conference and soon as public available we'll share it.
