### ISSUE TITLE
[User image has] contents that are not what they are reported to be

### ISSUE THREAD

**Issue by Gaurav2728** [thoughtbot/paperclip#1963]
My application setup:-

`gem 'rails', '4.1.12'`
`gem 'paperclip', '~> 4.2.0'`

currently using paperclip (4.2.4)

In my model :-
`has_attached_file :user_image, url: "/system/user_images/:id_partition/:hash.:extension",
                               hash_secret: "user_avatar_image"`
`  do_not_validate_attachment_file_type :user_image`

But when uploading image, i am getting - "User image has contents that are not what they are reported to be" error that is paperclip Content Type Spoof error.

in my log file i found :- 
Command :: file -b --mime '/tmp/1e11b989ba2f5e161cdad604bf3de90b20150820-10059-1dy6zeo.jpg'
[staging][paperclip] Content Type Spoof: Filename user.jpg (application/octet-stream from Headers, [#<MIME::Type:0x00000004894258 @friendly={"en"=>"JPEG Image"}, @system=nil, @obsolete=false, @registered=true, @use_instead=nil, @signature=false, @content_type="image/jpeg", @raw_media_type="image", @raw_sub_type="jpeg", @simplified="image/jpeg", @i18n_key="image.jpeg", @media_type="image", @sub_type="jpeg", @docs=[], @encoding="base64", @extensions=["jpeg", "jpg", "jpe"], @references=["IANA", "RFC2045", "RFC2046"], @xrefs={"rfc"=>["rfc2045", "rfc2046"]}>] from Extension), content type discovered from file command: image/jpeg. See documentation to allow this combination.

**Comment by jyurek** [comment]
The `do_not_validate_attachment_content_type` means you're opting out of having a `file_name` or `content_type` validation. It does not prevent the spoof detection, which you've run afoul of. Your upload is coming in as `application/octet-stream`, but it's a JPEG. Since that is not one of the valid content types for a JPEG, Paperclip is flagging it as invalid.

You can turn it off by adding `validate_media_type: false` to your attachment definition, but it this is potentially unsafe.

**Comment by Gaurav2728** [comment]
@jyurek  in my rails 4.2 app i prevent the problem using this -

`validates_attachment_content_type :user_image, :content_type => [/\Aimage/, 'application/octet-stream']`

It's not sending Spoof message but not working with previous problem.
Can you more describe !!

**Comment by jyurek** [comment]
I don't know what you mean. The error you said you get is `Content Type Spoof: Filename user.jpg (application/octet-stream from Headers` meaning `application/octet-stream` is sent as the content type when uploading. That is not the content type of a JPEG so it's telling you there is a spoofing attempt. The `validates` line you pasted will not prevent this error.

**Comment by Gaurav2728** [comment]
@jyurek thanks for reply, I also try 'validate_media_type: false' but it's not working.
for the solution we need to add `Paperclip.options[:content_type_mappings] = {
  jpg: "image/jpeg"
}`

**Comment by tauqeer-ahmad** [comment]
I resolved this issue by switching my paperclip version to gem 'paperclip', '3.5.0'.

**Comment by Gaurav2728** [comment]
We are facing this issue with Paperclip `4.2.4` .  Paperclip `3.5.0` have not this kind of feature i.e. more secure.

**Comment by tauqeer-ahmad** [comment]
@Gaurav2728 My bad. I jumped to conclusion in hurry.

**Comment by xinranxiao** [comment]
I ran into this problem as well, however `validate_media_type: false` did indeed bypass the spoof check for me. Paperclip version `5.0.0`, though from the changelog it looks like it was introduced in `4.2.1`.

Basically what I did:
```
class Foo < ActiveRecord::Base
  has_attached_file :document, { validate_media_type: false }
end
```

**Comment by NazmiAzzim** [comment]
@xinranxiao you really save me there bruh ! but i just dont get it why it happen.. cuz i use the same code, same image as yesterday as it run smoothly with no error.. no changes was made but today the error occur when i run it again.. can you explain why it is necessary to validate the media type?

**Comment by xinranxiao** [comment]
@NazmiAzzim did you uprade your Paperclip from pre-4.2.1?

**Comment by NazmiAzzim** [comment]
@xinranxiao nope.. already using Paperclip 5.0.0
