### ISSUE TITLE
Add Code of Conduct?

### ISSUE THREAD

**Issue by maclover7** [thoughtbot/paperclip#1967]
Saw thoughtbot did this on the [suspenders](https://github.com/thoughtbot/suspenders/blob/master/CONTRIBUTING.md) project - thoughts? Here's the link to the [COC](https://thoughtbot.com/open-source-code-of-conduct).

Assigning this to @tute since he added the code of conduct to suspenders.

**Comment by tute** [comment]
Thanks so much @maclover7!
