### ISSUE TITLE
Delete form AWS

### ISSUE THREAD

**Issue by maintux** [thoughtbot/paperclip#1968]
Hi guys, I'm trying master branch with aws-sdk v2 support. It works well but, when I deleted an object, I got this error: `NoMethodError: undefined method 'exists?' for #<Aws::S3::Object:0x000000056b9dd8>`
@betesh any hints about this issue? thanks

PS the file is `/lib/paperclip/storage/s3.rb:335`

**Comment by betesh** [comment]
Can you give us a stacktrace?

**Comment by betesh** [comment]
http://docs.aws.amazon.com/sdkforruby/api/Aws/S3/Object.html#exists%3F-instance_method suggests that this method should exist.

**Comment by betesh** [comment]
A full backtrace would be very helpful

**Comment by maintux** [comment]
[GEM_ROOT]/bundler/gems/paperclip-6e0c9e992a8e/lib/paperclip/storage/s3.rb:335→ exists?
[GEM_ROOT]/bundler/gems/paperclip-6e0c9e992a8e/lib/paperclip/attachment.rb:557→ block in queue_all_for_delete
[GEM_ROOT]/bundler/gems/paperclip-6e0c9e992a8e/lib/paperclip/attachment.rb:556→ map
[GEM_ROOT]/bundler/gems/paperclip-6e0c9e992a8e/lib/paperclip/attachment.rb:556→ queue_all_for_delete
[GEM_ROOT]/bundler/gems/paperclip-6e0c9e992a8e/lib/paperclip/has_attached_file.rb:93→ block in add_active_record_callbacks
activesupport-4.2.3/lib/active_support/callbacks.rb:444→ instance_exec
activesupport-4.2.3/lib/active_support/callbacks.rb:444→ block in make_lambda
activesupport-4.2.3/lib/active_support/callbacks.rb:162→ call
activesupport-4.2.3/lib/active_support/callbacks.rb:162→ block in halting
activesupport-4.2.3/lib/active_support/callbacks.rb:502→ call
activesupport-4.2.3/lib/active_support/callbacks.rb:502→ block in call
activesupport-4.2.3/lib/active_support/callbacks.rb:502→ each
activesupport-4.2.3/lib/active_support/callbacks.rb:502→ call
activesupport-4.2.3/lib/active_support/callbacks.rb:88→ run_callbacks
activerecord-4.2.3/lib/active_record/callbacks.rb:292→ destroy
activerecord-4.2.3/lib/active_record/transactions.rb:281→ block in destroy
activerecord-4.2.3/lib/active_record/transactions.rb:351→ block in with_transaction_returning_status
activerecord-4.2.3/lib/active_record/connection_adapters/abstract/database_statements.rb:213→ block in transaction
activerecord-4.2.3/lib/active_record/connection_adapters/abstract/transaction.rb:184→ within_new_transaction
activerecord-4.2.3/lib/active_record/connection_adapters/abstract/database_statements.rb:213→ transaction
activerecord-4.2.3/lib/active_record/transactions.rb:220→ transaction
activerecord-4.2.3/lib/active_record/transactions.rb:348→ with_transaction_returning_status
activerecord-4.2.3/lib/active_record/transactions.rb:281→ destroy
app/controllers/newsletters_controller.rb:116→ destroy
actionpack-4.2.3/lib/action_controller/metal/implicit_render.rb:4→ send_action
actionpack-4.2.3/lib/abstract_controller/base.rb:198→ process_action
actionpack-4.2.3/lib/action_controller/metal/rendering.rb:10→ process_action
actionpack-4.2.3/lib/abstract_controller/callbacks.rb:20→ block in process_action
activesupport-4.2.3/lib/active_support/callbacks.rb:115→ call
activesupport-4.2.3/lib/active_support/callbacks.rb:115→ call
activesupport-4.2.3/lib/active_support/callbacks.rb:553→ block (2 levels) in compile
activesupport-4.2.3/lib/active_support/callbacks.rb:503→ call
activesupport-4.2.3/lib/active_support/callbacks.rb:503→ call
activesupport-4.2.3/lib/active_support/callbacks.rb:88→ run_callbacks
actionpack-4.2.3/lib/abstract_controller/callbacks.rb:19→ process_action
actionpack-4.2.3/lib/action_controller/metal/rescue.rb:29→ process_action
actionpack-4.2.3/lib/action_controller/metal/instrumentation.rb:32→ block in process_action
activesupport-4.2.3/lib/active_support/notifications.rb:164→ block in instrument
activesupport-4.2.3/lib/active_support/notifications/instrumenter.rb:20→ instrument
activesupport-4.2.3/lib/active_support/notifications.rb:164→ instrument
actionpack-4.2.3/lib/action_controller/metal/instrumentation.rb:30→ process_action
actionpack-4.2.3/lib/action_controller/metal/params_wrapper.rb:250→ process_action
activerecord-4.2.3/lib/active_record/railties/controller_runtime.rb:18→ process_action
actionpack-4.2.3/lib/abstract_controller/base.rb:137→ process
actionview-4.2.3/lib/action_view/rendering.rb:30→ process
actionpack-4.2.3/lib/action_controller/metal.rb:196→ dispatch
actionpack-4.2.3/lib/action_controller/metal/rack_delegation.rb:13→ dispatch
actionpack-4.2.3/lib/action_controller/metal.rb:237→ block in action
actionpack-4.2.3/lib/action_dispatch/routing/route_set.rb:76→ call
actionpack-4.2.3/lib/action_dispatch/routing/route_set.rb:76→ dispatch
actionpack-4.2.3/lib/action_dispatch/routing/route_set.rb:45→ serve
actionpack-4.2.3/lib/action_dispatch/journey/router.rb:43→ block in serve
actionpack-4.2.3/lib/action_dispatch/journey/router.rb:30→ each
actionpack-4.2.3/lib/action_dispatch/journey/router.rb:30→ serve
actionpack-4.2.3/lib/action_dispatch/routing/route_set.rb:821→ call
newrelic_rpm-3.12.1.298/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67→ call
actionpack-4.2.3/lib/action_dispatch/middleware/static.rb:116→ call
newrelic_rpm-3.12.1.298/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67→ call
omnicontacts-0.3.7/lib/omnicontacts/middleware/base_oauth.rb:41→ call
newrelic_rpm-3.12.1.298/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67→ call
omnicontacts-0.3.7/lib/omnicontacts/middleware/base_oauth.rb:41→ call
newrelic_rpm-3.12.1.298/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67→ call
omnicontacts-0.3.7/lib/omnicontacts/builder.rb:27→ call
newrelic_rpm-3.12.1.298/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67→ call
newrelic_rpm-3.12.1.298/lib/new_relic/rack/agent_hooks.rb:30→ traced_call
newrelic_rpm-3.12.1.298/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67→ call
newrelic_rpm-3.12.1.298/lib/new_relic/rack/browser_monitoring.rb:32→ traced_call
newrelic_rpm-3.12.1.298/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67→ call
[GEM_ROOT]/bundler/gems/client_side_validations-d9f3904e7cb9/lib/client_side_validations/middleware.rb:17→ call
newrelic_rpm-3.12.1.298/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67→ call
rack-1.6.4/lib/rack/etag.rb:24→ call
newrelic_rpm-3.12.1.298/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67→ call
rack-1.6.4/lib/rack/conditionalget.rb:38→ call
newrelic_rpm-3.12.1.298/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67→ call
rack-1.6.4/lib/rack/head.rb:13→ call
newrelic_rpm-3.12.1.298/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67→ call
actionpack-4.2.3/lib/action_dispatch/middleware/params_parser.rb:27→ call
newrelic_rpm-3.12.1.298/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67→ call
actionpack-4.2.3/lib/action_dispatch/middleware/flash.rb:260→ call
newrelic_rpm-3.12.1.298/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67→ call
rack-1.6.4/lib/rack/session/abstract/id.rb:225→ context
rack-1.6.4/lib/rack/session/abstract/id.rb:220→ call
newrelic_rpm-3.12.1.298/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67→ call
actionpack-4.2.3/lib/action_dispatch/middleware/cookies.rb:560→ call
newrelic_rpm-3.12.1.298/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67→ call
activerecord-4.2.3/lib/active_record/query_cache.rb:36→ call
newrelic_rpm-3.12.1.298/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67→ call
activerecord-4.2.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:653→ call
newrelic_rpm-3.12.1.298/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67→ call
actionpack-4.2.3/lib/action_dispatch/middleware/callbacks.rb:29→ block in call
activesupport-4.2.3/lib/active_support/callbacks.rb:84→ run_callbacks
actionpack-4.2.3/lib/action_dispatch/middleware/callbacks.rb:27→ call
newrelic_rpm-3.12.1.298/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67→ call
actionpack-4.2.3/lib/action_dispatch/middleware/remote_ip.rb:78→ call
newrelic_rpm-3.12.1.298/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67→ call
newrelic_rpm-3.12.1.298/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67→ call
actionpack-4.2.3/lib/action_dispatch/middleware/debug_exceptions.rb:17→ call
newrelic_rpm-3.12.1.298/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67→ call
actionpack-4.2.3/lib/action_dispatch/middleware/show_exceptions.rb:30→ call
newrelic_rpm-3.12.1.298/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67→ call
railties-4.2.3/lib/rails/rack/logger.rb:38→ call_app
railties-4.2.3/lib/rails/rack/logger.rb:20→ block in call
activesupport-4.2.3/lib/active_support/tagged_logging.rb:68→ block in tagged
activesupport-4.2.3/lib/active_support/tagged_logging.rb:26→ tagged
activesupport-4.2.3/lib/active_support/tagged_logging.rb:68→ tagged
railties-4.2.3/lib/rails/rack/logger.rb:20→ call
newrelic_rpm-3.12.1.298/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67→ call
actionpack-4.2.3/lib/action_dispatch/middleware/request_id.rb:21→ call
newrelic_rpm-3.12.1.298/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67→ call
rack-1.6.4/lib/rack/methodoverride.rb:22→ call
newrelic_rpm-3.12.1.298/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67→ call
rack-1.6.4/lib/rack/runtime.rb:18→ call
newrelic_rpm-3.12.1.298/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67→ call
rack-1.6.4/lib/rack/sendfile.rb:113→ call
newrelic_rpm-3.12.1.298/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67→ call
newrelic_rpm-3.12.1.298/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67→ call
railties-4.2.3/lib/rails/engine.rb:518→ call
railties-4.2.3/lib/rails/application.rb:165→ call
puma-2.13.4/lib/puma/configuration.rb:78→ call
puma-2.13.4/lib/puma/server.rb:541→ handle_request
puma-2.13.4/lib/puma/server.rb:388→ process_client
puma-2.13.4/lib/puma/server.rb:270→ block in run
puma-2.13.4/lib/puma/thread_pool.rb:106→ call
puma-2.13.4/lib/puma/thread_pool.rb:106→ block in spawn_thread


Inviato da iPhone

**Comment by betesh** [comment]
What's the output of `cat Gemfile.lock | grep aws`

**Comment by maintux** [comment]
```
cat Gemfile.lock | grep aws
    aws-sdk (2.0.33)
      aws-sdk-resources (= 2.0.33)
    aws-sdk-core (2.0.33)
    aws-sdk-resources (2.0.33)
      aws-sdk-core (= 2.0.33)
  aws-sdk
```

**Comment by betesh** [comment]
I don't think we've tested it with aws-sdk 2.0.x.  Only with 2.1.x.  I added some gemfiles.  We'll know from travis in a few minutes.  If we have to, we can add support for aws-sdk 2.0.x.  If it's going to be too complex, then we'll just correct the gemspec so that it only supports >= 2.1.0

**Comment by maintux** [comment]
OK thank you

**Comment by maintux** [comment]
@betesh btw I confirm you that upgrading aws-sdk to 2.1.15, it works as expected.

**Comment by betesh** [comment]
Travis is passing with aws-sdk 2.0.48, but I'm always a fan of upgrading to the latest version.

**Comment by maintux** [comment]
Indeed. I'll keep the latest version ;)

**Comment by betesh** [comment]
@exsits? was added in this release:  https://github.com/aws/aws-sdk-ruby/releases/tag/v2.0.34

I'll push a PR that can handle this gracefully
