### ISSUE TITLE
Paperclip options not being shown.

### ISSUE THREAD

**Issue by joshuapinter** [thoughtbot/paperclip#1975]
Hi guys, 

I created an init file as per your README to set a few default options, like so: 

```ruby
Paperclip::Attachment.default_options[:whiny]          = false
Paperclip::Attachment.default_options[:keep_old_files] = true
Paperclip::Attachment.default_options[:preserve_files] = true
```

However, when I run `Paperclip.options` from the console, it doesn't seem to respect these default options and instead shows nothing for `keep_old_files` and `preserve_files` and shows `true` for `whiny`.

Is there something I'm missing. Many thanks. 

Josh

**Comment by jyurek** [comment]
`Paperclip.options` and `Paperclip::Attachment.default_options` aren't the same thing. You should see what the value of `Paperclip::Attachment.default_options` is in the console, instead.

**Comment by joshuapinter** [comment]
Ah, gotcha! That makes sense.

Another quick question, while I have you (and perhaps this should be it's own issue): 

I'm using Paranoia's soft-delete and I'm noticing that with `preserve_files` set to `true`, it doesn't remove the file from S3 but it still clears out the `file_name`, `file_size`, etc. from the ActiveRecord object so when I `restore` it, it has not reference to the actual file on S3. 

Is there another option to prevent this from happening?

Many Thanks. 

Josh
