### ISSUE TITLE
Attachments stored in Release Folders on S3

### ISSUE THREAD

**Issue by asecondwill** [thoughtbot/paperclip#1983]
My attachments are being stored in release folders on S3.  It's very messy and files are going missing.  

eg

http://s3-ap-southeast-2.amazonaws.com/flexcareers/var/deploy/flexpertlinode/web_head/releases/20150902113325/public/redactor_rails/pictures/35/original_providepeoplewithpossibilities2.png

Is the expected behaviour? 

````
gem "paperclip", "~> 4.2"
gem 'aws-sdk', '< 2.0'

config.paperclip_defaults = {
    :storage => :s3,
    :s3_host_name => 's3-ap-southeast-2.amazonaws.com',    
    :path => '/:class/:attachment/:id_partition/:style/:filename',
    :s3_credentials => {
      :bucket => ENV['S3_BUCKET_NAME'],      
      :access_key_id => ENV['AWS_ACCESS_KEY_ID'],
      :secret_access_key => ENV['AWS_SECRET_ACCESS_KEY']
    }
  }

````

**Comment by jyurek** [comment]
No, this is not expected behavior. What is the actual definition of the attachment in the model? You have default options, but are they overridden at all?

**Comment by asecondwill** [comment]
Thanks jyurek.  Your comment pointed me in the right direction.  I had a gem using paperclip that had a generator, the generator used an old paperclip format for the path in the model.  Updating that fixed the issue.  thanks again, sorry to trouble.
