### ISSUE TITLE
instance based convert options

### ISSUE THREAD

**Issue by jacekgrzybowski** [thoughtbot/paperclip#1984]
I have a following problem - I need to set convert options for a specific instance based on its attributes. Perfect solution would be calling some method on that instance, just like in case of `styles`:

    has_attached_file :photo,
                      :source_file_options => { all: '-background transparent' },
                      :styles => lambda { |att| att.instance.styles_list },
                      :convert_options => lambda { |att| att.instance.set_convert_options },
                      :processors          => [:thumbnail, :paperclip_optimizer],
                      :path                =>  lambda { |att| att.instance.resolve_path },
                      :url                 => "/attachments/:id/:style/:basename.:extension"

I'm aware that I can use a class method instead of the lambda from example above, but I can't find a way to refer to this particular instance then.

**Comment by jacekgrzybowski** [comment]
Ok, I found out that those options can be added to the styles hash which is even better (https://github.com/thoughtbot/paperclip/blob/14356d7eccb9175819508d243fb4a92681d11208/spec/paperclip/style_spec.rb#L48). However I think it should be documented because I haven't found it anywhere in the docs.

**Comment by jyurek** [comment]
I would very much welcome a PR that adds this to the docs!

**Comment by jyurek** [comment]
In the meantime, I'm going to close this as there's no more action needed here.
