### ISSUE TITLE
On product page, category dropdown displays incorrect parent (for marketplace categories)

### ISSUE THREAD

**Issue by leopoldw** [thoughtbot/paperclip#1989]
<img width="374" alt="screen shot 2015-09-04 at 1 13 13 pm" src="https://cloud.githubusercontent.com/assets/5439181/9689848/c14e2260-5306-11e5-9a08-b973bc0d2737.png">
<img width="796" alt="screen shot 2015-09-04 at 1 13 22 pm" src="https://cloud.githubusercontent.com/assets/5439181/9689849/c15243cc-5306-11e5-8184-adee47913341.png">

**Comment by tute** [comment]
This is not an issue with this project, paperclip. Closing, thanks!
