### ISSUE TITLE
Can not use session id in path

### ISSUE THREAD

**Issue by vikram-hermes** [thoughtbot/paperclip#1990]
I am trying to use following structure to make path dynamic but its giving me 500 internal error 

:path => "/export-data/sciservice/data/temp_upload/#{request.session_options[:id]}/:folder/:basename.:extension"

**Comment by tute** [comment]
See https://viget.com/extend/paperclip-custom-interpolation and https://github.com/thoughtbot/paperclip/wiki/interpolations.

Same as in https://github.com/thoughtbot/paperclip/issues/1994: if this doesn't solve your issue, consider asking also in StackOverflow, where a bigger community might solve your particular case. Thanks!
