### ISSUE TITLE
Deprecate aws-sdk v1

### ISSUE THREAD

**Issue by maclover7** [thoughtbot/paperclip#1997]
As said by @tute, we need to deprecate the use of aws-sdk v1, as major version 2 has been released (currently at v2.1.19).

Steps we need to follow for this:
- Release a minor version which includes a deprecation warning if the user is still on aws-sdk v1
- Release a major version which includes the actual deprecation of aws-sdk v1 (this is a breaking change)

**Comment by tute** [comment]
For context, I'd deprecate it if Amazon is deprecating it. Is it? If so, when? If not, it's an arguable step to take.

**Comment by jyurek** [comment]
Agreed. I'd only want to deprecate it if Amazon is deprecating it.

**Comment by maclover7** [comment]
https://github.com/aws/aws-sdk-ruby/issues/924

**Comment by tute** [comment]
Thanks! It sounds like Rails 5 will come before they come up with a decision anyway.

**Comment by maclover7** [comment]
yep, so let's have Rails 5 + dropping Rails 3.2 + any other backwards incompatible changes as apart of Paperclip 5.0.0. Should we release a minor version of Paperclip that includes deprecation warnings?

**Comment by tute** [comment]
People on Rails 2.3.x may use paperclip 2.7, people on Rails 3 may use paperclip 3, and so on. I don't think we need deprecation warnings for Rails.

If there are other more subtle deprecations or changes of functionality that could be surprising, I'm all for warnings.

**Comment by tute** [comment]
I'll bit the bullet and call for a removal of AWS V1 for paperclip 5. trevorrowe says in https://github.com/aws/aws-sdk-ruby/issues/924#issuecomment-140182581:

> we took a lot of effort to ensure that version 1 and version 2 could be used in the same project allowing users to upgrade at gradually and at will

v1 users can continue to use paperclip 4.x.

**Comment by maclover7** [comment]
Closing in favor of #2049.
