### ISSUE TITLE
Memory footprint usage and Cocaine dependency

### ISSUE THREAD

**Issue by xtagon** [thoughtbot/paperclip#2002]
Hi,

The [derailed_benchmarks](https://github.com/schneems/derailed_benchmarks) gem has a utility for analyzing the basic memory fingerprint of your Rails app's gem usage. The more gems your app has, the more memory it takes up in general.

When I run it on one of my apps, the biggest memory hog is reported to be Paperclip. _However_, it seems Paperclip itself doesn't require that much memory--it's all Cocaine's fault.

My results:

```bash
$ bundle exec derailed bundle:mem
```

```
  paperclip: 26.6445 MiB (Also required by: paperclip/railtie)
    cocaine: 20.1445 MiB
      cocaine/command_line/runners: 15.0117 MiB
        cocaine/command_line/runners/backticks_runner: 6.1289 MiB
          climate_control: 4.707 MiB
            climate_control/modifier: 1.9375 MiB
              active_support/core_ext/hash/keys: 0.6367 MiB (Also required by: rails/application, active_support/core_ext/array/conversions, and 12 others)
            climate_control/version: 0.6289 MiB
        cocaine/command_line/runners/process_runner: 0.9727 MiB
        cocaine/command_line/runners/fake_runner: 0.9648 MiB
        cocaine/command_line/runners/posix_runner: 0.9453 MiB
        cocaine/command_line/runners/popen_runner: 0.8945 MiB
      cocaine/command_line: 0.6367 MiB
      cocaine/os_detector: 0.5781 MiB
      rbconfig: 0.5586 MiB (Also required by: active_support/core_ext/kernel/reporting, nokogiri, and 6 others)
      cocaine/exceptions: 0.4063 MiB
    mime/types: 5.2114 MiB
    paperclip/glue: 0.6172 MiB
      paperclip/validators: 0.5547 MiB (Also required by: paperclip)
        paperclip/validators/attachment_presence_validator: 0.3359 MiB
          active_model/validations/presence: 0.332 MiB (Also required by: paperclip/validators/media_type_spoof_detection_validator, paperclip/validators/attachment_file_type_ignorance_validator)
```

Since the command-line portion of Paperclip is never necessary in a production environment, what would interest me is a way to be able to require Paperclip without the command-line tool or Cocaine as a dependency. Is this something we can work towards?

It may seem like 20MB is a small gain, but in the long run it makes a difference, and I'm sure others would benefit from this as well.

I see that Paperclip requires something called `paperclip/glue`. Being unfamiliar with Paperclip internals, is that something relevant? Can we include most of the functionality of Paperclip without the command-line tool bloat in production, and optionally include Paperclip _with_ the command-line tool in development only?

If this is not currently possible, how hard would it be to work toward it, and where can I start helping?

Thanks for listening, and happy coding!

Justin

**Comment by dgynn** [comment]
Interesting results.Those memory allocations are pretty high. I haven't been able to recreate your memory results.

It looks like you have a slightly older version of `paperclip`, or possibly just an older version of `mime-types`. Paperclip 4.3.0 introduced a performance improvement that uses `mime/types/columnar` which requires less memory than `mime/types`. So you would benefit from making sure your `mime-types` is the latest version.

As far as the dependencies... Cocaine is used by Paperclip to run commands to do things like convert and resize images. So it is needed in production. That isn't just for a development time command line tool. Glue is the module that ties Paperclip into ActiveRecord.

Derailed benchmarks is great but the results can vary greatly between runs depending on what else is happening on your machine and what other gems you have. I've found it helpful to isolate a single gem and its dependencies to get consistent results.

Here are the results I got running derailed_benchmarks for a Gemfile that just requires `paperclip` by itself. This was on a Linux server with Ruby 2.2.3.

Gemfile:
```ruby
source 'https://rubygems.org'

gem 'derailed_benchmarks'
gem 'paperclip'
```

Results: `bundle exec derailed bundle:mem`
```
TOP: 10.4414 MiB
  paperclip: 9.7656 MiB
    cocaine: 2.1948 MiB
      cocaine/command_line/runners: 1.2539 MiB
      rbconfig: 0.3438 MiB
    mimemagic: 2.1724 MiB
      mimemagic/tables: 1.7349 MiB
    erb: 0.9648 MiB
    paperclip/attachment: 0.8594 MiB
      active_support/deprecation: 0.7891 MiB (Also required by: active_support/rails, paperclip/schema)
    paperclip/glue: 0.7813 MiB
      paperclip/validators: 0.6719 MiB (Also required by: paperclip)
        active_model: 0.3203 MiB
    mime/types/columnar: 0.3789 MiB
    logger: 0.3477 MiB (Also required by: active_support/logger, mime/types/logger)
    mimemagic/overlay: 0.3398 MiB
```

These results seem a bit more realistic. Cocaine does still show up but not as extreme as what you saw. There could still be some opportunities here to defer loading of some of these dependencies.

**Comment by xtagon** [comment]
Hi @dgynn, thanks for getting back to me so quickly.

Turns out I was still locked to Paperclip 4.2.1. Upgrading to Paperclip 4.3 in my app showed spectacular results:

```
  paperclip: 2.3359 MiB (Also required by: paperclip/railtie)
    mimemagic: 0.75 MiB
      mimemagic/tables: 0.7188 MiB
    mime/types/columnar: 0.5273 MiB
      mime/types: 0.4102 MiB
    paperclip/glue: 0.5 MiB
      paperclip/validators: 0.5 MiB (Also required by: paperclip)
        paperclip/validators/attachment_presence_validator: 0.332 MiB
          active_model/validations/presence: 0.332 MiB (Also required by: paperclip/validators/media_type_spoof_detection_validator, paperclip/validators/attachment_file_type_ignorance_validator)
```

Cocaine isn't even listed here this time, so I think the isolated test is the only useful test. But I'm happy with where it's at now.

Cheers!

**Comment by dgynn** [comment]
Sweet! Glad that worked out.
