### ISSUE TITLE
Paperclip not cropping centered image

### ISSUE THREAD

**Issue by fbrix** [thoughtbot/paperclip#2003]
My model (Swatch.rb):

```ruby
  has_attached_file :image,
                    styles: { original: ["100%"],
                              small:    ["580x1000>", :jpg],
                              thumb:    ["200x200",   :jpg],
                              tiny:     ["55x55#",    :jpg] },
```

When I do:

Swatch.last.image.reprocess! I am getting:

Command :: identify -format '%wx%h,%[exif:orientation]' '/var/folders/8x/5cpkltc94j79q9vyt76pw9pw0000gn/T/ec3a0a547af1a360a09a4e387f37ad1420150913-906-g95w4p[0]' 2>/dev/null

Command :: convert '/var/folders/8x/5cpkltc94j79q9vyt76pw9pw0000gn/T/ec3a0a547af1a360a09a4e387f37ad1420150913-906-g95w4p[0]' -auto-orient -resize "x55" -crop "55x55+22+0" +repage '/var/folders/8x/5cpkltc94j79q9vyt76pw9pw0000gn/T/ec3a0a547af1a360a09a4e387f37ad1420150913-906-g95w4p20150913-906-1usidkn.jpg'

convert: geometry does not contain image `/var/folders/8x/5cpkltc94j79q9vyt76pw9pw0000gn/T/ec3a0a547af1a360a09a4e387f37ad1420150913-906-g95w4p' @ warning/transform.c/CropImage/574.

All styles are working except `tiny`. Does anyone know whats the matter here?

Thank you!

**Comment by jyurek** [comment]
Can you run that command manually using the same file? What do you get?

**Comment by fbrix** [comment]
@jyurek Hello and thank you for the answer. The problem is solved. I was cropping the image manually before saving it to this model. I had to set the "repage" parameter when cropping it manually so the later cropping done by the tiny style creation by paperclip would work.
