### ISSUE TITLE
Minimize png images with pngquant after conversion 

### ISSUE THREAD

**Issue by TheSmartnik** [thoughtbot/paperclip#2010]
When using png as default format, you are getting images of  a huge size, 10x more than the same image in png. The problem gets even worse when converting from animated gif image. As a solution, I think paperclip could minimize png images internally with pngquant. Of course, I could do it in `post_process` callback, but it doesn't seem like a good place for it.

**Comment by tute** [comment]
We won't have time to work on this in the foreseeable future, and existing paperclip options allow us to solve these issues. Closing this issue for now, happy to continue further discussion if you'd like. Thanks!
