### ISSUE TITLE
Paperclip::Interpolations.id_partition returns different result depending on attachment.instance.id class

### ISSUE THREAD

**Issue by silentshade** [thoughtbot/paperclip#2011]
https://github.com/thoughtbot/paperclip/blob/282f1161e8cbdd314e06af51d7ad01feb8b5c196/lib/paperclip/interpolations.rb#L162

This method will return different path when model.id is a string, than when model.id is integer:
```Ruby
2.1.5 :020 > ("%09d" % 5083727).scan(/\d{3}/).join("/")
 => "005/083/727" 
2.1.5 :021 > '5083727'.scan(/.{3}/).first(3).join("/")
 => "508/372" 
```
For string id it could be something like:
```Ruby
str = id[0..8]
('0' * (9 - str.size) + str).scan(/.{3}/).join('/')
```
This is probably a very rare case, for example if one someday changes model.id from Integer to String..

**Comment by tute** [comment]
This doesn't seem like something we need to fix in the codebase. If it is a bug let us know, and we continue the discussion. Thanks!
