### ISSUE TITLE
Is it possible to set Cache-Control when storing an object to S3?

### ISSUE THREAD

**Issue by ronshoshani** [thoughtbot/paperclip#2012]
Hi,

I'd like to set Cache-Control max-age=60 for every object that I upload to S3 with Paperclip.

I've reviewed the [documentation for using Paperclip and S3](http://www.rubydoc.info/gems/paperclip/Paperclip/Storage/S3) and found the s3_metadata property which I think should allow me to do this, but either my syntax is incorrect or it's not possible, as I keep getting the error "The request signature we calculated does not match the signature you provided. Check your key and signing method". Without the s3_metadata property the file is stored correctly in S3 (without the adjusted Cache-Control of course).

Does anyone know if this is possible, and what syntax to use?

Thanks,
Ron.

**Comment by mebibou** [comment]
@ronshoshani have you found any solution regarding this?

**Comment by ronshoshani** [comment]
@mebibou Sorry I haven't..

**Comment by mikelkew** [comment]
I'm pretty certain this is done using the 's3_headers' options, e.g.
`s3_headers: { 'Cache-Control' => 'max-age=2678400' }`

**Comment by tute** [comment]
`s3_headers` option is the answer. Thanks!
