### ISSUE TITLE
Add image effects when confirmed before upload

### ISSUE THREAD

**Issue by arjunmenon** [thoughtbot/paperclip#2014]
Hey
Paperclip by default applies image effects and manipulation, hard set in the Model after the image is uploaded.
Is there a way by which, a user can first confirm what all manipulations/effects it would like to see during the upload process.
For eg - 
After user selects the image, the person chooses to either upload thumbnail, medium or big image, or a particular effect like blur or sharpen.

I am not talking about using any Jquery plugins for the task but rather some set of styles(mentioned earlier) which are already defined in the model, which then the user selects before Paperclip uploads the image.

Thanks.

**Comment by tute** [comment]
The issue you describe seems very specific to your code. I suggest that you ask about it in https://stackoverflow.com/questions/tagged/paperclip, which will get attention from more people than in this issue tracker.

Sorry we don't have the time now to help you with this question, and thanks!
