### ISSUE TITLE
Content type detection locks original file

### ISSUE THREAD

**Issue by daniel-rikowski** [thoughtbot/paperclip#2016]
`Paperclip::ContentTypeDetector` keeps a `File` object open and thus *prevents it from being deleted*, moved, etc. until it is closed by the garbage collector.

I was mass-importing images from a zip file and I noticed that I couldn't delete the files after assigning them to Paperclip.

In line [71](https://github.com/thoughtbot/paperclip/blob/master/lib/paperclip/content_type_detector.rb#L71): 

```ruby
MimeMagic.by_magic(File.open(@filepath)).try(:type)
```
... the open file is not closed. 

Although this problem is unrelated to #1759, #1980 or  #1326, it might very well worsen those situations.

IMHO that line should be:
```ruby
File.open(@filepath) { |f| MimeMagic.by_magic(f).try(:type) }
```

Shall I make a pull request?

**Comment by aouji** [comment]
Any news on this one? It seems to be a safe change and reduces the number of file objects paperclip leaves behind open.

**Comment by tute** [comment]
> IMHO that line should be:
> 
> `File.open(@filepath) { |f| MimeMagic.by_magic(f).try(:type) }`
>
> Shall I make a pull request?

Please do. Great catch, thanks!

**Comment by tute** [comment]
Already fixed. Thank you!

**Comment by daniel-rikowski** [comment]
Thank you!
