### ISSUE TITLE
Fog storage doesn't consistently check for dynamic :fog_directory

### ISSUE THREAD

**Issue by ravinggenius** [thoughtbot/paperclip#2018]
`Paperclip::Storage::Fog#host_name_for_directory` assumes a String-like object is set and doesn't check if `@options[:fog_directory]` is callable, while `Paperclip::Storage::Fog#directory` does. I would recommend extracting a new method with the condition and refactoring the other two methods to call it.

See https://github.com/thoughtbot/paperclip/blob/master/lib/paperclip/storage/fog.rb#L191 and https://github.com/thoughtbot/paperclip/blob/master/lib/paperclip/storage/fog.rb#L220

**Comment by ravinggenius** [comment]
Bump.

Is there any interest in fixing this?

**Comment by tute** [comment]
Closing in favor of the PR. Will not have time for a few weeks to review it, but it's something I want to include. Thank you! :+1:
