### ISSUE TITLE
Infinite loop when saving an image from URL to s3

### ISSUE THREAD

**Issue by mikeyferg** [thoughtbot/paperclip#2020]
It saves the image to s3 but then rollsback and saves again, rollsback, saves infinitely.  After I manually stop the process the image is saved to s3 and the appropriate s3 url link is added to the instance.

If I run the same command through terminal, it works perfectly.

URI.parse("image_url")

Anyone else having a similar issue?

Update- 

The issue only occurs when iterating through and updating multiple instances.  If I just update one instance at a time everything seems to be working fine.

**Comment by tute** [comment]
We will need more information in order to reproduce this issue. Can you follow the steps outlined in http://yourbugreportneedsmore.info/, so that people can better replicate or understand the problem in order to help you?

Thank you for your report.
