### ISSUE TITLE
Does Paperclip 4.3.1 support aws-sdk-v2?

### ISSUE THREAD

**Issue by BigMcLargeHuge** [thoughtbot/paperclip#2021]
Judging from [this thread](https://github.com/thoughtbot/paperclip/issues/1764#issuecomment-137194127) and the commits going into version 4.3.1, my understanding is that aws-sdk-v2 is officially supported by the latest release of paperclip.  But, when I attempt to upload using `gem 'paperclip', '~> 4.3.1'` with `gem 'aws-sdk', '~> 2.1.28'` I get the old error 
>uninitialized constant Paperclip::Storage::S3::AWS

Is there anything special I need to do to apply paperclip to v2 with this new support?

**Comment by hughevans** [comment]
Try this rev `523bd46c768226893f23889079a7aa9c73b57d68`

**Comment by BigMcLargeHuge** [comment]
Well played @hughevans!  I see that this commit states "No need to specify aws-sdk version."  Was there a way to specify it in the 4.3.1 release?  If so, I didn't see any notes on it.

Just to make it easier on others, here are a couple other tricky parts I found when applying this modification:

You will need to specify the REGION of your in your paperclip defaults.  This can be done by dropping a `:s3_region=> 'us-west-2'` into your `paperclip_defaults`.  Simply specifying the endpoint or host will not be enough.

Also slightly confusing is the error message if the above isn't done properly:
>missing region; use :region option or export region name to ENV['AWS_REGION']
1. I couldn't get the recommended environment variable to work.
2. The `:region` option is somewhat misleading as it needs to be written `:s3_region`

Anyway, thanks again hugh!

**Comment by son1112** [comment]
@BigMcLargeHuge, thanks for providing the gem line for that revision. I still get the slightly confusing error message you mentioned, though I have used `:s3_region` instead of `:region`. Not sure yet what else I have misconfigured. Any ideas?

**Comment by son1112** [comment]
Nevermind. I foolishly mis-configured my environment variables... derp!

**Comment by BigMcLargeHuge** [comment]
@son1112 Heh, it happens!  Glad everything's working

**Comment by edgarsilva** [comment]
@son1112 @BigMcLargeHuge Hey guys how does your configuration (paperclip_defaults) looks like? I'm still having this issue running aws-sdk (2.1.29) and paperclip (4.3.1). If I switch to aws < 2 it works.

**Comment by BigMcLargeHuge** [comment]
Hi @edgarsilva You say that you're using paperclip 4.3.1?  The findings of this thread are that 4.3.1 still has issues and that you should use the revision suggested above and NOT 4.3.1.

**Comment by tute** [comment]
We will release 4.3.2 including 523bd46c768226893f23889079a7aa9c73b57d68 in around a week. cc @jyurek in case you get to it before I do!

**Comment by edgarsilva** [comment]
Thanks @BigMcLargeHuge, @tute figured out that one yesterday after some experimenting, looking into the code and using @BigMcLargeHuge suggestion. Got confused because of the dates of the gem and thought it was included. Great work with the paperclip gem! hope to be able to contribute back to the project soon.

**Comment by tute** [comment]
> We will release 4.3.2 including 523bd46 in around a week.

We can't do this because there are backwards incompatible changes. Will update the README instead with context from this issue. Thanks!

**Comment by cpjolicoeur** [comment]
Wait, the 4.3.2 patch release contains "backwards incompatible changes"???

On a patch release?

**Comment by tute** [comment]
We can't release a patch version. To 4.3.1, 5.0.0 will follow (unless there are single commits that should be backported).

**Comment by aug-riedinger** [comment]
So I updated my gems to use:

```
    paperclip (4.3.2)
      activemodel (>= 3.2.0)
      activesupport (>= 3.2.0)
      cocaine (~> 0.5.5)
      mime-types
      mimemagic (= 0.3.0)
    aws-sdk (2.2.0)
      aws-sdk-resources (= 2.2.0)
    aws-sdk-core (2.2.0)
      jmespath (~> 1.0)
    aws-sdk-resources (2.2.0)
      aws-sdk-core (= 2.2.0)
```

But I still get: `uninitialized constant Paperclip::Storage::S3::AWS`

What am I doing wrong?

**Comment by tute** [comment]
Paperclip 4 works with AWS v1 only.

**Comment by aug-riedinger** [comment]
Really? That's not what's mentionned there: https://github.com/thoughtbot/paperclip/commit/523bd46c768226893f23889079a7aa9c73b57d68

I understood from the whole thread that the 4.3.2 does include the fix on AWS v2, doesn't it?

**Comment by tute** [comment]
Yep, that's in master. We can't release these patches because of https://github.com/thoughtbot/paperclip/issues/2021#issuecomment-151563433.
