### ISSUE TITLE
Cannot set s3 region

### ISSUE THREAD

**Issue by SylarRuby** [thoughtbot/paperclip#2022]
Sorry but I could not figure out your documentation: http://www.rubydoc.info/gems/paperclip/Paperclip/Storage/S3 on how to set region.

I have tried `:s3_host_name => 'us-west-2'` and `:region => 'us-west-2'` but nothing works. How to set the correct region?

**Comment by dgynn** [comment]
The setting should be `:s3_region => 'us-west-2'`

You can see the updated documentation in the source code [here](/thoughtbot/paperclip/tree/master/lib/paperclip/storage/s3.rb). I'm not sure why RubyDoc is out of date.

**Comment by SylarRuby** [comment]
I had to use `:s3_host_name => 's3-us-west-2.amazonaws.com'`. All is well now.
