### ISSUE TITLE
s3 changed the access endpoints?

### ISSUE THREAD

**Issue by tiagoovieira** [thoughtbot/paperclip#2025]
It looks like the endpoint to access the files in s3 is now `https://<bucket_name>.s3.amazonaws.com/<path>`

How should I store in the database, or get the new endpoint? Is anybody else having this problem?

**Comment by maclover7** [comment]
Hi @tiagoovieira! If this is an error that breaks your application, can you please provide more information that reproduces this error? Thanks!

**Comment by betesh** [comment]
You need to configure the type of path & url paperclip generates:

    class Paperclip::Attachment
      default_options.merge!(
        storage: :s3,
        url: ":s3_domain_url",
        path: "/:class/:attachment/:id_partition/:style/:filename"
      )
    end

You shouldn't have to change anything about how you store things in the database.

**Comment by theonlyrao** [comment]
Thanks for this explanation @betesh! I know there's a lot of documentation on how to sort this out but I really appreciate your clarity.

**Comment by tute** [comment]
@tiagoovieira is this still an issue? Thanks!

**Comment by tute** [comment]
It looks like this is solved now. If you think we can improve paperclip from anything discussed here, let's reopen. Thank you!
