### ISSUE TITLE
Extracting image dimensions, queued_for_write is an empty hash

### ISSUE THREAD

**Issue by jpmoral** [thoughtbot/paperclip#2026]
I am trying to extract an uploaded image's dimensions by following the [wiki](https://github.com/thoughtbot/paperclip/wiki/Extracting-image-dimensions).

However, the upload's `queued_for_write` is an empty hash.  ~~I tried a `before_save` and `after_save` with the same result.~~

The attachment process itself seems to work fine.

Edit:  of course the `after_save` won't work, `queued_for_write` would have been cleared by then.

**Comment by ajw725** [comment]
i just ran into this same issue. not sure what i'm doing wrong...in my case, it's in a custom validator for image dimensions.

**Comment by ajw725** [comment]
just wanted to follow up - i solved this issue by modifying the first line of the validation as follows:
```ruby
if record.send("#{attribute}?".to_sym) && value.queued_for_write[:original]
```
the validation now seems to work as desired. still not sure why queued_for_write was empty, though.

**Comment by jpmoral** [comment]
In my case it turned out the way Paperclip was used was non-standard.  Closing this.
