### ISSUE TITLE
Gravatar query params

### ISSUE THREAD

**Issue by sandelius** [thoughtbot/paperclip#2036]
Hi.

It looks like paperclip is encoding the url string and Gravatar don't understand the ? part.

``` ruby
Paperclip.interpolates :gravatar do |model, style|
  hash = Digest::MD5.hexdigest(model.instance.email)
  "https://secure.gravatar.com/avatar/#{hash}?s=50&d=retro"
end

user.avatar.url # => "https://secure.gravatar.com/avatar/e362aa17ae4289326fb2b82551012a3d%3Fs=50&d=retro"
```

Neither the size or the default "retro" is shown. My guess is the `%3F` encoding that breaks it. Am I missing something or it's a bug?

**Comment by MarkMurphy** [comment]
This is what I had to do to work around it:

```ruby
  default_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?d=#{default_url}&"

  # Prevent Paperclip from escaping the already escaped default url that we need to send to gravatar as a fallback
  default_url.class.class_eval { def escape; self; end }

  default_url
```

**Comment by sandelius** [comment]
@MarkMurphy shouldn't we do class eval on the singleton class instance?

**Comment by MarkMurphy** [comment]
@sandelius I'm not sure what you mean, `url` is just a string. The reason I'm defining the escape method on it is because of this:

https://github.com/thoughtbot/paperclip/blob/523bd46c768226893f23889079a7aa9c73b57d68/lib/paperclip/url_generator.rb#L60-L66

**Comment by sandelius** [comment]
@MarkMurphy yeah but since you use `url.class.class_eval` the escape method will be added to all strings and not just that one, right?

**Comment by sandelius** [comment]
any update on this?

**Comment by mattdeigh** [comment]
It looks like as of 3.4.0, you can set ```escape_url: false``` to fix this.

```ruby
has_attached_tile :avatar, escape_url: false
```

**Comment by MarkMurphy** [comment]
and @sandelius, yes you are probably right about the class eval.

**Comment by tute** [comment]
Is this related with https://github.com/thoughtbot/paperclip/issues/1732? Does `escape_url: false` help? Thanks!

**Comment by mike-burns** [comment]
Looks like this is solved, closing.
