### ISSUE TITLE
FIX CI in master

### ISSUE THREAD

**Issue by tute** [thoughtbot/paperclip#2048]
It looks like the dummy app for cucumber features doesn't have a database, and those specs are erroring out. This should be fixed, so that master is green in Travis again.

**Comment by tute** [comment]
Argh, busted caches maybe?

**Comment by dgynn** [comment]
I think the dummy app is using the config/database.yml rather than the spec/database.yml due to changes in aruba 0.10.x but I wasn't able to track it down any further.
