### ISSUE TITLE
How do I get logo url with sql query?

### ISSUE THREAD

**Issue by dieutb** [thoughtbot/paperclip#2050]
Hi everyone. I query by sql string. And got logo_file_name: 'data'

I want to parse full url of logo. Is there any function can do this for me ?

Something like `Paperclip::Attachment.parse_url(klass_name, field_name, id, image_type)`?

**Comment by abunsen** [comment]
+1 on this.

**Comment by tute** [comment]
The issue you describe seems specific to your app. I suggest that you ask about it in https://stackoverflow.com/questions/tagged/paperclip, which will get attention
from more people than in this issue tracker.

Sorry we don't have the time now to help you with this question, and thanks!

**Comment by aperkins81** [comment]
+1 on this, sometimes sql is required for avoiding n+1 problems  ... for now it seems when looping through portfolio images each image object needs to hit the database - I can't find an elegant way to join objects with their image url
