### ISSUE TITLE
Validate all image and specific video mimetype

### ISSUE THREAD

**Issue by rahilwazir** [thoughtbot/paperclip#2052]
I'm new to Ruby, so I'm trying to validate all image and 3 video mimetypes

```
validates_attachment_content_type :background_media, content_type: { content_type: [/\Aimage\/.*\Z/, "video/mp4", "video/ogg", "video/webm"] }
```

If spits invalid content type, however I'm uploading accepted content type as given above. What am I doing wrong?

**Comment by tute** [comment]
I suggest that you ask this question in https://stackoverflow.com/questions/tagged/paperclip, which will get attention from more people than in this issue tracker.

I'm very sorry we don't have the time now to help you with this question now. Thanks!
