### ISSUE TITLE
io adapters don't delegate all IO methods to the tempfile 

### ISSUE THREAD

**Issue by ajh** [thoughtbot/paperclip#2053]
Instead they only delegate a select list defined here: https://github.com/thoughtbot/paperclip/blob/master/lib/paperclip/io_adapters/abstract_adapter.rb#L8

Is there a reason not to delegate all IO methods? I'd be happy to create a PR for that if people think it's a good idea.

My reason for wanting this is that I can't pass in a csv attachment to the CSV library because it uses `IO#gets` which isn't delegated. For example if a `CsvImport` model stores a csv file in a `data` attachment:

```
$ io = Paperclip.io_adapters.for(CsvImport.first.data)
$ CSV.new(io).each.to_a
NoMethodError: private method `gets' called for Paperclip::AttachmentAdapter: example.csv:Paperclip::AttachmentAdapter
```

**Comment by Envek** [comment]
Same here, also with CSV.

As a workaround, replaced:

```ruby
Paperclip.io_adapters.for(version.file)
```

with:

```ruby
File.new(version.file.path)
```

Which only works with local storage though.

**Comment by mike-burns** [comment]
Thank you for reporting this. Unfortunately, we will be deprecating Paperclip and therefore will not have the bandwidth to address this issue.
