### ISSUE TITLE
Storing hashed filenames

### ISSUE THREAD

**Issue by bcardiff** [thoughtbot/paperclip#2063]
I think https://github.com/thoughtbot/paperclip/wiki/Hashing might have an issue.

It stands to change default_options with `:path => ":class/:attachment/:hash/:style.:extension"` but doing so it does not change the url. Which breaks the upload/download cycle.

I had use the following setup to store file locally. 
```ruby
Paperclip::Attachment.default_options.update({
  url: "/system/:class/:attachment/:id_partition/:style/:hash.:extension",
  hash_secret: Rails.application.secrets.secret_key_base
})
```

Note that the default_option is `:path=>":rails_root/public:url"`. So the file will be stored in the desired (hashed) way.

`paperclip (4.3.1)`

--- 

But also, propably a whole other story, I noticed that in the database the original filename is kept. I don't see the point in storing it. I would however thought paperclip would've store the path to the file (or the url). So, if I change the default_options later on, all the existing files will continue to work.

**Comment by tute** [comment]
Hi @bcardiff! Gracias for your contribution. :)

I'm not familiar with this issue yet. Should we update the wiki? Or have you found a bug in paperclip? Thank you!

**Comment by bcardiff** [comment]
@tute yes, I would say that an update to the wiki is needed, but maybe I was doing something wrong since it was the first time I try paperclip. Currently I am still using the snippet I shared before.

**Comment by vinvasir** [comment]
Hi @bcardiff . @asaganda and I have updated the wiki. Does this address your issue?

**Comment by bcardiff** [comment]
I would suggest to clarify that the `path` depends on the `url`. It is there in the default, but surrounded by lots of chars. So, if the default changes, it will be easier to track down the issue.

Other than that, yes, feel free to close the issue on my side.

**Comment by vinvasir** [comment]
Updated to clarify. How is it now?

**Comment by tute** [comment]
Thank you both! :)
