### ISSUE TITLE
Animated GIF is messed up after resize

### ISSUE THREAD

**Issue by udiudi** [thoughtbot/paperclip#2068]
Hi,

Animated GIFs we upload via Paperclip are breaking.
The original file is fine, but this is what happens to the other versions:
![large-magic](https://cloud.githubusercontent.com/assets/191763/11652320/adee77e0-9d9f-11e5-80b8-b9563d12aa60.gif)

Any ideas what may cause this?

**Comment by sikachu** [comment]
It's because of how GIF file being compressed. [See here](http://askubuntu.com/questions/257831/how-can-i-resize-an-animated-gif-file-using-imagemagick).

You can set `-coalesce` option to Imagemagick. Note that this might increase memory footprint during thumbnailing:

```ruby
Paperclip::Attachment.default_options[:convert_options] = { all: '-coalesce' }

**Comment by udiudi** [comment]
@sikachu thank you!
I've added this in has_attached_file in my assets model:
````ruby
                    :convert_options => {
                      :thumb            => "-quality 80 -interlace Plane -coalesce",
                      :thumb_big        => "-quality 80 -interlace Plane -coalesce",
                      :thumb_big_scaled => "-quality 80 -interlace Plane -coalesce",
                      :big              => "-quality 80 -interlace Plane -coalesce",
                      :large            => "-quality 80 -interlace Plane -coalesce"
                    }
````

But gif breaks the same, using version 4.2.1

**Comment by sikachu** [comment]
@udiudi Actually, after I check, Paperclip should already adding `-coalesce` for you when it detects the `gif` image.

Do you mind sharing the command that Paperclip issues to convert that file? It should be in your Rails log file.

**Comment by udiudi** [comment]
@sikachu couldn't find the log messages, so I've added 
````ruby
File.open('Paperclip.txt', 'w') { |file| file.write("#{parameters}") }
````
in ``paperclip-4.2.1/lib/paperclip/thumbnail.rb``.  This is the output:
````
:source -coalesce -auto-orient -resize "1000x1000>" -layers "optimize" -quality 80 -interlace Plane :dest
````

**Comment by udiudi** [comment]
@sikachu I found the issue we had.
This option `-interlace Plane` caused the issue with our GIFs. When I removed it, they worked properly again.

**Comment by sikachu** [comment]
Ah! Glad that you found this issue. This issue is going to be a great find for some people who run into the same problem as you. :smile:
