### ISSUE TITLE
No documentation about correct validation of mime type when uploading csv files (probably other types too) on Windows

### ISSUE THREAD

**Issue by bigos** [thoughtbot/paperclip#2069]
This is duplicate of a bugging issue that has been going on for a long time. 

here:
https://github.com/thoughtbot/paperclip/labels/Spoof%20related%20or%20Mime%20types
I have counted 15 issues

As of paperclip-4.3.2 this is not been solved. I can replicate this error on Windows 7 and 8, but not on Linux or a Mac. Different people report different, sometimes scary solutions. What is the correct way of solving this problem?

[paperclip] Content Type Spoof: Filename delivery_detail.csv (application/octet-stream from Headers, [#<MIME::Type:0x000000031fc4c8 @content_type="text/csv", @raw_media_type="text", @raw_sub_type="csv", @simplified="text/csv", @media_type="text", @sub_type="csv", @extensions=["csv"], @encoding="8bit", @system=nil, @registered=true, @url=["IANA", "RFC4180"], @obsolete=nil, @docs=nil>, #<MIME::Type:0x0000000319d3d8 @content_type="text/comma-separated-values", @raw_media_type="text", @raw_sub_type="comma-separated-values", @simplified="text/comma-separated-values", @media_type="text", @sub_type="comma-separated-values", @extensions=["csv"], @encoding="8bit", @system=nil, @registered=false, @url=nil, @obsolete="!", @docs="use-instead:text/csv", @use_instead=["text/csv"]>] from Extension), content type discovered from file command: text/plain. See documentation to allow this combination.

**Comment by tute** [comment]
> As of paperclip-4.3.2 this is not been solved. I can replicate this error on Windows 7 and 8, but not on Linux or a Mac. Different people report different, sometimes scary solutions. What is the correct way of solving this problem?

There are 15 separate issues because there is no simple, single answer. Mime types issue vary with the operating system, browser, `file` and `mimemagic` versions, and your app's configuration.

I'll close this issue as it doesn't add new information than what's on your link. Will continue working through those.

Thanks!
