### ISSUE TITLE
S3 storage path option still defaults to Rails.root/...

### ISSUE THREAD

**Issue by joallard** [thoughtbot/paperclip#2071]
Using `has_attached_file :column, storage: :s3, url: "..."`, the complete path will still contain Rails.root, meaning in development I get an URL like `bucket.s3.amazonaws.com/users/jon/home/dev/project/public/blah/foo/bar` which doesn't really make sense.

Moreover, adding `path: ''` will completely nix the path to the file.

Feature request: Have a sensible default work out-of-the-box.

**Comment by joallard** [comment]
Okay, looks like I have to use the `path` option, not `url`. Looks like it's a documentation issue. 

[`#has_attached_file`](http://www.rubydoc.info/gems/paperclip/Paperclip/ClassMethods#has_attached_file-instance_method) mentions `url` right away, so testing on the local filestorage before switching to s3 sets that expectation. No mention of the `path` parameter there.

**Comment by tute** [comment]
Thanks for pointing this out, @joallard. Would you please submit a fix please?

**Comment by duhaime** [comment]
@joallard Are you pursuing this? I'm also interested in fixing this, and would be happy to help but didn't want to duplicate effort...

**Comment by joallard** [comment]
@duhaime Nope, I used a workaround and the project was short-lived, so it's not really important for me anymore. Go nuts!

**Comment by mike-burns** [comment]
Thank you for reporting this. Unfortunately, we will be deprecating Paperclip and therefore will not have the bandwidth to address this issue.
