### ISSUE TITLE
New filename being set on resource even if save fails due to validation errors

### ISSUE THREAD

**Issue by flyingL123** [thoughtbot/paperclip#2072]
I am using Paperclip with Devise and seem to have come across an issue. My devise User model requires that a `display_name` be present. The User model also contains an `avatar`, which is what Paperclip is being used for.

If I load the page that allows a user to edit their account, set the `display_name` field to blank, and select a new image to upload as the `avatar`, the save fails as expected because `display_name` is not present. However, for the current page load only, the filename for the image I was just trying to upload is set on the user, which means the image does not display correctly on the page since that file was never actually saved (it doesn't exist on the server).

If I add a call to `resource.restore_avatar_file_name!` before trying to display the image, it seems to reset the filename correctly and display as expected. Shouldn't Paperclip being resetting the filename automatically if the record never saves due to validation errors? Is there some way to make this happen?

**Comment by flyingL123** [comment]
It appears that if the validation that fails belongs to Paperclip, then the filename is reset. For example, if I try to upload an invalid file. But if the validation that fails is for an attribute not related to paperclip, the name does not get reset.

**Comment by sikachu** [comment]
@flyingL123 thank you for report. I can see that it's a valid issue.

However, there's no way for us to hook something in to reset the value in those fields when the validation fail though unless we override `valid?` method on your model.

```
def valid?
  unless super
    self.attachment = nil
    false
  end
end
```

I feel like that could pose a risk though, as it's possible that someone might override `valid?` on the model as well.

So, I feel like the best way to deal with this is to have you unset the value by yourself when you realize the validation was failed.

I'm going to close this issue, but please let me know if you have any other suggestion on how should we deal with this.
