### ISSUE TITLE
bad url on S3

### ISSUE THREAD

**Issue by imidsac** [thoughtbot/paperclip#2077]
ArgumentError (/app/publichttps://sahel-services.s3.amazonaws.com/options/avatars/1/original/maiga.png not found)

**Comment by sikachu** [comment]
It looks like you're mixing `path` and `url` somehow? It looks a lot like configuration issue though.

Would you mind posting your `has_attached_file` configuration and your `interpolation`.

I'm going to close this issue though, as I don't think it's a bug in Paperclip. However, please feel free to post more information for us to able to help you with this issue.
