### ISSUE TITLE
Copying paperclip attachments via pointers

### ISSUE THREAD

**Issue by fiverrben** [thoughtbot/paperclip#2080]
Hi, 

I hope this is the correct place to post this request, I've opened up a stackoverflow question but got no answer (http://stackoverflow.com/questions/34480514/paperclip-copying-images-between-different-attributes)

I have an active record with 3 paperclip images, attributes named photo1, photo2, photo3.
I would like to create a route which will change their positions, user sends new order in array and the model should just change "pointers", but wont do files copying and I/O via my storage (S3).

Is there a way this could be done (via code inside the model / monkey patching)?
I will gladly contribute this code to the repository if I could get some pointers.

**Comment by sikachu** [comment]
I believe you can swap those [metadata columns](https://github.com/thoughtbot/paperclip/blob/37589f9b0c869c8df5be1ee4d83e14fb353a7dff/lib/paperclip/schema.rb#L6-L9) values correctly and it should work.

However, I feel like it might be easier to have a `photo_arrangement` method or something that stores the correct order instead.

I'm going to close this, but please feel free to ask more question in this issue regarding this matter.
