### ISSUE TITLE
Trigger DEPRECATED WARNING on has_attached_file in Sinatra

### ISSUE THREAD

**Issue by bbiglari** [thoughtbot/paperclip#2081]
I am getting useless deprecation warning whenever I am running my sintra application. It triggers from has_attached_file from paperclip.rb.

Message:

DEPRECATION WARNING: Currently, Active Record suppresses errors raised within `after_rollback`/`after_commit` callbacks and only print them to the logs. In the next version, these errors will no longer be suppressed. Instead, the errors will propagate normally just like in other Active Record callbacks. 

After I trace down the calls, it shows that the framework call 

has_attached_file.rb:
    def add_active_record_callbacks
      name = @name
      @klass.send(:after_save) { send(name).send(:save) }
      @klass.send(:before_destroy) { send(name).send(:queue_all_for_delete) }
      @klass.send(:after_commit, :on => :destroy) { send(name).send(:flush_deletes) }
    end

Can you do a pull request to turn this off?

Thanks

**Comment by maclover7** [comment]
Can you please provide a sample application that reproduces the error?

**Comment by Erowlin** [comment]
Same problem on Rails, here are the gem versions we use in our project : 
Gems included by the bundle:
  * actionmailer (4.2.4)
  * actionpack (4.2.4)
  * actionview (4.2.4)
  * activejob (4.2.4)
  * activemodel (4.2.4)
  * activerecord (4.2.4)
  * activerecord-session_store (0.1.0)
  * activesupport (4.2.4)
  * addressable (2.4.0)
  * adyen (1.5.0)
  * aggregate (0.2.2)
  * ajax-datatables-rails (0.3.1)
  * arel (6.0.3)
  * autonumeric-rails (1.9.43)
  * awesome_print (1.6.1)
  * aws-sdk (1.66.0)
  * aws-sdk-v1 (1.66.0)
  * bcrypt (3.1.10)
  * bcrypt-ruby (3.1.2)
  * better_errors (2.1.1)
  * binding_of_caller (0.7.2)
  * brakeman (3.1.4)
  * builder (3.2.2)
  * bundler (1.10.6)
  * callsite (0.0.11)
  * capybara (2.5.0)
  * celluloid (0.17.2)
  * celluloid-essentials (0.20.5)
  * celluloid-extras (0.20.5)
  * celluloid-fsm (0.20.5)
  * celluloid-pool (0.20.5)
  * celluloid-supervision (0.20.5)
  * chartkick (1.4.1)
  * chartkick-remote (1.3.0)
  * childprocess (0.5.8)
  * climate_control (0.0.3)
  * clockwork (1.2.0)
  * cocaine (0.5.8)
  * coderay (1.1.0)
  * coffee-rails (4.1.1)
  * coffee-script (2.4.1)
  * coffee-script-source (1.10.0)
  * concurrent-ruby (1.0.0)
  * connection_pool (2.2.0)
  * crack (0.4.3)
  * cucumber (1.3.20)
  * cucumber-rails (1.4.2)
  * daemons (1.2.3)
  * database_cleaner (1.4.1)
  * debug_inspector (0.0.2)
  * devise (3.4.0)
  * diff-lcs (1.2.5)
  * docile (1.1.5)
  * erubis (2.7.0)
  * eventmachine (1.0.8)
  * execjs (2.6.0)
  * fabrication (2.14.1)
  * factory_girl (4.5.0)
  * faker (1.6.1)
  * faraday (0.9.2)
  * fastercsv (1.5.5)
  * ffaker (2.1.0)
  * ffi (1.9.10)
  * font_assets (0.1.12)
  * foreman (0.78.0)
  * formatador (0.2.5)
  * fuubar (2.0.0)
  * geocoder (1.2.14)
  * geoip (1.6.1)
  * gherkin (2.12.2)
  * git-version-bump (0.15.1)
  * globalid (0.3.6)
  * gon (6.0.1)
  * groupdate (2.5.0)
  * guard (2.13.0)
  * guard-bundler (2.1.0)
  * guard-compat (1.2.1)
  * guard-rspec (4.6.4)
  * haml (4.0.7)
  * hashdiff (0.2.3)
  * highline (1.7.8)
  * hitimes (1.2.3)
  * httparty (0.12.0)
  * httpclient (2.7.1)
  * i18n (0.7.0)
  * i18n-js (2.1.2)
  * jquery-fileupload-rails (0.4.6)
  * jquery-rails (4.0.5)
  * json (1.8.3)
  * kgio (2.10.0)
  * levenshtein (0.2.2)
  * librato-metrics (1.6.0)
  * librato-rack (0.4.5)
  * librato-rails (0.10.1)
  * listen (3.0.5)
  * lograge (0.3.0)
  * loofah (2.0.3)
  * lumberjack (1.0.10)
  * mail (2.6.3)
  * mangopay (3.0.8)
  * meta_request (0.3.4)
  * method_source (0.8.2)
  * mime-types (2.99)
  * mimemagic (0.3.0)
  * mini_portile2 (2.0.0)
  * minitest (5.8.3)
  * monetize (1.1.0)
  * money (6.5.1)
  * money-rails (1.4.1)
  * multi_json (1.11.2)
  * multi_test (0.1.2)
  * multi_xml (0.5.5)
  * multipart-post (2.0.0)
  * nenv (0.2.0)
  * newrelic_rpm (3.14.1.311)
  * nokogiri (1.6.7.1)
  * notiffany (0.0.8)
  * orm_adapter (0.5.0)
  * paperclip (4.3.2)
  * pg (0.18.4)
  * polyamorous (1.1.0)
  * pry (0.10.3)
  * pundit (1.0.1)
  * pusher (0.15.2)
  * pusher-signature (0.1.8)
  * rack (1.6.4)
  * rack-contrib (1.4.0)
  * rack-cors (0.4.0)
  * rack-protection (1.5.3)
  * rack-rewrite (1.5.1)
  * rack-test (0.6.3)
  * rails (4.2.4)
  * rails-deprecated_sanitizer (1.0.3)
  * rails-dom-testing (1.0.7)
  * rails-html-sanitizer (1.0.2)
  * rails-observers (0.1.2)
  * rails_12factor (0.0.2)
  * rails_serve_static_assets (0.0.4)
  * rails_stdout_logging (0.0.4)
  * railties (4.2.4)
  * raindrops (0.15.0)
  * rake (10.4.2)
  * rb-fsevent (0.9.7)
  * rb-inotify (0.9.5)
  * redis (3.1.0)
  * redis-namespace (1.5.2)
  * request_store (1.2.1)
  * responders (2.1.1)
  * rest-client (1.6.7)
  * rollbar (1.5.3)
  * rspec (3.4.0)
  * rspec-core (3.4.1)
  * rspec-expectations (3.4.0)
  * rspec-instafail (0.4.0)
  * rspec-mocks (3.4.0)
  * rspec-rails (3.4.0)
  * rspec-support (3.4.1)
  * ruby-graphviz (1.2.2)
  * ruby-ole (1.2.12)
  * ruby-progressbar (1.7.5)
  * ruby2ruby (2.2.0)
  * ruby_parser (3.7.2)
  * rubyzip (1.1.7)
  * s3_direct_upload (0.1.7)
  * safe_yaml (1.0.4)
  * sass (3.4.20)
  * sass-rails (5.0.4)
  * selenium-webdriver (2.48.1)
  * sexp_processor (4.6.0)
  * shellany (0.0.1)
  * sidekiq (3.4.0)
  * sidekiq-failures (0.4.5)
  * sidekiq-limit_fetch (2.4.2)
  * sift (1.1.7.3)
  * simplecov (0.11.1)
  * simplecov-html (0.10.0)
  * sinatra (1.4.6)
  * slim (3.0.6)
  * slop (3.6.0)
  * spork (0.9.2)
  * spreadsheet (1.1.1)
  * sprockets (3.5.2)
  * sprockets-rails (2.3.3)
  * squeel (1.2.3)
  * state_machines (0.4.0)
  * state_machines-activemodel (0.3.0)
  * state_machines-activerecord (0.3.0)
  * teaspoon (1.1.1)
  * temple (0.7.6)
  * terminal-notifier-guard (1.5.3)
  * terminal-table (1.5.2)
  * thin (1.6.4)
  * thor (0.19.1)
  * thread (0.2.2)
  * thread_safe (0.3.5)
  * tilt (2.0.1)
  * timecop (0.8.0)
  * timers (4.1.1)
  * to_xls-rails (1.3.1)
  * tzinfo (1.2.2)
  * uglifier (2.7.2)
  * unicorn (4.8.3)
  * warden (1.2.4)
  * webmock (1.22.3)
  * webrat (0.7.3)
  * websocket (1.2.2)
  * wicked_pdf (1.0.3)
  * will_paginate (3.0.7)
  * wkhtmltopdf-binary (0.9.9.3)
  * wkhtmltopdf-heroku (2.12.2.4)
  * xpath (2.0.0)
  * yajl-ruby (1.2.0)

The error is triggered on the `has_attached_file` line.

**Comment by sikachu** [comment]
Closing this in favor of #1933.
