### ISSUE TITLE
Paperclip.interpolates gets confused if two models use the same interpolation

### ISSUE THREAD

**Issue by atstockland** [thoughtbot/paperclip#2086]
I have "has_attached_file" on 5 models.  Each model has a dynamic :path created using Paperclip.interpolates.  If I use "Paperclip.interpolates :user_id" in multiple models, an error occurs because paperclip ends up referencing the wrong model.  I get an undefined method error from a model that IS NOT the model being processed.  The error originates in the other model that uses the same interpolation "Paperclip.interpolates :user_id".  This error can be fixed by simply making sure each interpolation uses a uniq symbol.  This was quit confusing and took some digging to figure out.  This seems to be a bug...or, I missed something in the docs.  I don't have any specs, but could try to generate some...

**Comment by dgynn** [comment]
That is correct. Paperclip interpolations are global and must have unique keys. So you could create separate interpolations like `:model1_user_id` and `:model2_user_id` or you could create one interpolator that can handle both models. For example...
```ruby
Paperclip.interpolates :user_id do |attachment, style|
  model = attachment.instance
  if model.is_a?(Model1)
    model.user_id
  else
    model.some_other_method_for_user_id
  end
end
```

Your interpolations should also ideally be setup in a initializer rather than in the models. I don't think that is specified anywhere in the docs.

**Comment by sikachu** [comment]
Yes, I can confirm that `interpolates` is stored in `Paperclip` class, which is shared within the process.

The best way to do this is to create two separate interpolations with a different keys, as that will reduce the logic in the interpolation process as @dgynn suggested.

**Comment by micahlisonbee** [comment]
😱

**Comment by damuz91** [comment]
I have the following interpolation duplicated in some of my classes:

```
Paperclip.interpolates :timestamp  do |attachment, style|
		Time.now.strftime("%F")
	end
```

Could there be any issue? I am following a weird behaviour but not sure if this is it

**Comment by micahlisonbee** [comment]
@damuz91 Yes you open yourself to potential confused behavior if they are the same. I would make the argument name unique to each of them like:

`Paperclip.interpolates :model_name_timestamp do...`.

**Comment by dgynn** [comment]
You could also do this just once in an initializer. Putting this in multiple models means it will get "registered" multiple times and overwrite the previous interpolation. If the code are all the same, that won't be a problem but could create problems in the future.

Also be aware that `:timestamp` is a default, built-in interpolation. So you are overriding this method.
https://github.com/thoughtbot/paperclip/blob/7edb35a2a9a80c9598dfde235c7e593c023fc914/lib/paperclip/interpolations.rb#L62-L69

The best approach would be to use a different name and configure it just once in an initializer.
