### ISSUE TITLE
Update attachment with update_columns method

### ISSUE THREAD

**Issue by afilhodaniel** [thoughtbot/paperclip#2089]
Hi guys,

How can I update one attachment using the update_columns method? It's possible? For example: user.update_columns(...).

Any ideia?

**Comment by betesh** [comment]
What are you trying to do?  You could do:

`user.update!(image_file_name: ..., image_file_size: ..., image_file_type: ...)`, etc.

but you'd be bypassing a whole lot of paperclip functionality that ensures the integrity and validity of your data.  What's your reason for wanting to bypass all of that?

**Comment by betesh** [comment]
Also, this isn't a bug.  Your question sounds more like it belongs on StackOverflow.

**Comment by sikachu** [comment]
You should be using `update_attributes` instead. For example, if you have `has_attached_file :image`:

```
user.update_attributes(image: params[:image])
```

You'll be skipping lots of functionality using just `update_column`.
