### ISSUE TITLE
url of s3-file does not take region/host into account.

### ISSUE THREAD

**Issue by Pungsnigel** [thoughtbot/paperclip#2097]
Uploading a file is no problem, and the file is placed in the correct bucket under the correct path. However, when I try to download my file via my_object.file.url, it seems the url given is missing its region. For example, with configuration:

```
Paperclip::Attachment.default_options[:storage]        = :s3
Paperclip::Attachment.default_options[:s3_region]      = 'eu-west-1'
Paperclip::Attachment.default_options[:s3_host_name]   = 's3-eu-west-1.amazonaws.com',
Paperclip::Attachment.default_options[:s3_credentials] = {
  bucket: ENV['S3_BUCKET_NAME'],
  access_key_id: ENV['AWS_ACCESS_KEY_ID'],
  secret_access_key: ENV['AWS_SECRET_ACCESS_KEY'],
}
```

and Model:

```
class Car < ActiveRecord::Base
  ...
  has_attached_file :example_file, :path => '/firmware/development/:id/:filename'
  ...
end
```

I would expect a uploaded file named example_file.txt to be served under something like https://s3-eu-west-1.amazonaws.com/mybucket/firmware/development/216/example_file.txt. However, running Car.find(226).example_file.url gives: http://s3.amazonaws.com/mybucket/firmware/development/226/example_file.txt?1540585519. 

Is something wrong in my configuration? I'm running ruby 2.1.5, rails 4.19, paperclip 4.3.2 and AWS-SDK 2.0.48.

**Comment by betesh** [comment]
Nothing is necessarily wrong.  It all depends whether the URL it's returning actually works.  [This comment](https://github.com/betesh/paperclip/blob/v4.2.1/lib/paperclip/storage/s3.rb#L69) explains it.

**Comment by Pungsnigel** [comment]
The problem is that the URL does not work, unless I manually change it to include the region.

**Comment by betesh** [comment]
So you probably want to add the option `Paperclip::Attachment.default_options[:url] = :s3_domain_url`.  Let me know if that works.

**Comment by Pungsnigel** [comment]
While it didn't generate the URL I was expected, it does seem to generate a working URL. Guess that will do just fine. Thanks a bunch for the help @betesh, closing issue.
