### ISSUE TITLE
Problem when using paperclip without active_record

### ISSUE THREAD

**Issue by kt0** [thoughtbot/paperclip#2098]
Latest release ([4.3.3](https://github.com/thoughtbot/paperclip/releases/tag/v4.3.3)) is problematic when using paperclip with mongoid, that there is no active_record.

This [single commit](https://github.com/thoughtbot/paperclip/commit/2e6335532ac24012cf473b60994d09f14952b891) is checking for deprecations and relies on `ActiveRecord` constant being avaible.

Version prior to this (4.3.2) is working as expected.

**Comment by betesh** [comment]
The quick fix would be to use ActiveModel or ActiveSupport (which are paperclip dependencies) instead of ActiveRecord.

**Comment by kevcha** [comment]
Nice catch @kt0
As @betesh says, relying on ActiveModel or ActiveSupport versions instead of ActiveRecord would fix it. I'm gonna make a pull request for this

**Comment by maclover7** [comment]
Closed via #2100. Version `4.3.4` has been released to solve this.
