### ISSUE TITLE
Falsy deprecation warning about aws-sdk-v1 gem

### ISSUE THREAD

**Issue by morgoth** [thoughtbot/paperclip#2102]
After upgrading to paperclip 4.3.4 I got "DEPRECATION WARNING: [paperclip] [deprecation] AWS SDK v1 has been deprecated in paperclip 5. Please consider upgrading to AWS 2 before upgrading paperclip."

I tried to update AWS gem to v2, but looks like it's not supported in 4.3.4 version yet.

**Comment by maclover7** [comment]
AWS v2 should be supported in v4.3.4 -- doesn't look like there is anything stopping you, based on the gemspec dependencies?

**Comment by morgoth** [comment]
I'm getting errors about undefined `AWS` constant. As you can see in 4.3.4 https://github.com/thoughtbot/paperclip/blob/v4.3.4/lib/paperclip/storage/s3.rb there is no conditional of defining namespace (`AWS` vs `Aws`) as it is on master

**Comment by maclover7** [comment]
Yikes - good point. I'd say to upgrade to master or wait for 5.0 to drop to upgrade your aws-sdk version.

**Comment by morgoth** [comment]
sure, but I think there should be some quick fix release, because it's really confusing - you're getting warning but cannot update, so there is no way of getting rid of this message.

**Comment by lucascaton** [comment]
Quick fix for now: just add the following monkey patch to the end of your `config/initializers/paperclip.rb`:

```ruby
class Paperclip::Deprecations
  if Paperclip::VERSION < '5'
    def self.warn_aws_sdk_v1
    end
  end
end
```

**Comment by sikachu** [comment]
@maclover7 do you think it make sense to revert that deprecation warning for now, until Paperclip 5 is drop?

**Comment by maclover7** [comment]
Yep -- that makes sense. Sorry for the inconvenience :grimacing:. Opened #2108.

**Comment by maclover7** [comment]
v4.3.5 has been released with changes.
