### ISSUE TITLE
Not showing images in production mode of Rails 5

### ISSUE THREAD

**Issue by adnanpirota** [thoughtbot/paperclip#2105]
When run in production mode on rails 5 I am getting no images with this error in production log:

ActionController::RoutingError (No route matches [GET] "/public/system/articles/images/000/000/003/medium/learn_language.jpg"):

The same app when run in development mode works fine

**Comment by sikachu** [comment]
Would you mind letting us know more detail?

* Your `has_attached_file` definition.
* How do you deploy your site? (Heroku? AWS?)

That should help us able to see what's wrong with your deployment.

**Comment by adnanpirota** [comment]
The problem was that my site was not serving static files, sorry for the issue posted here.

**Comment by Chaitu8790** [comment]
> Would you mind letting us know more detail?
> 
> Your has_attached_file definition.
> How do you deploy your site? (Heroku? AWS?)
> 
> That should help us able to see what's wrong with your deployment.

I'm working with RubyOnRails application in which I cannot see uploaded images after some time.
I used Heroku deployment, Can anyone suggest to resolve this issue?
