### ISSUE TITLE
Can I directly assign a cropped image as image for one of my styles? 

### ISSUE THREAD

**Issue by rajdeep26** [thoughtbot/paperclip#2107]
Basically we have a UI where we allow the users to crop the selected image in different sizes. We have a photo class, which uses paperclip, and several styles has been defined in it as follows:

```
has_attached_file(:image, 
                  :styles => { 
                    :list => '263x200#',
                    :logo => "300x2000>", 
                    :thumbnail => '100x100#'
                  })
```

Now the only problem is how do we tell paperclip that we already have a cropped images for all these styles and we just want to assign these images and paperclip should not crop the actual image and create all these styles?

NOTE: I'm using paperclip version 3.5.1

**Comment by sikachu** [comment]
Given you already have images post processed, it might make more sense to have 4 attachments on the model and you assign each photos individually?

The other way to do it is you can put those photos in its correct path (after interpolation) and then use `before_post_process` to return false to skip the interpolation.

I'm going to close this issue, but please let me know if you run into any issue.

**Comment by rajdeep26** [comment]
We have images post processed only in certain cases, rest of the time we want paperclip to do the cropping. Is this possible?

**Comment by sikachu** [comment]
@rajdeep26 yes, as you can make Paperclip stops processing by returning false in the callback method set by `before_post_process`.
