### ISSUE TITLE
Paperclip::Errors::NotIdentifiedByImageMagickError on Heroku 

### ISSUE THREAD

**Issue by howells** [thoughtbot/paperclip#2116]
I've checked and though a few other folk have had this problem, nothing that was suggested quite solved it for me. When I go to refresh my image styles, I get the following error:

````
errors while processing Portfolio ID 303:
 Header Paperclip::Errors::NotIdentifiedByImageMagickError
 Header Paperclip::Errors::NotIdentifiedByImageMagickError
[paperclip] copying portfolios/headers/000/000/304/original.jpg to local file /tmp/8fab2f796ae38ae9f184112aabfc8f1820160219-3-9v1qx7.jpg
[AWS S3 200 0.012765 0 retries] get_object(:bucket_name=>"xxxxxx",:key=>"portfolios/headers/000/000/304/original.jpg")  

Command :: identify -format '%wx%h,%[exif:orientation]' '/tmp/8fab2f796ae38ae9f184112aabfc8f1820160219-3-9v1qx7.jpg[0]' 2>/dev/null
[paperclip] An error was received while processing: #<Paperclip::Errors::NotIdentifiedByImageMagickError: Paperclip::Errors::NotIdentifiedByImageMagickError>
Command :: identify -format '%wx%h,%[exif:orientation]' '/tmp/8fab2f796ae38ae9f184112aabfc8f1820160219-3-9v1qx7.jpg[0]' 2>/dev/null
[paperclip] An error was received while processing: #<Paperclip::Errors::NotIdentifiedByImageMagickError: Paperclip::Errors::NotIdentifiedByImageMagickError>
[paperclip] saving portfolios/headers/000/000/304/original.jpg
[AWS S3 200 0.125795 0 retries] put_object(:acl=>"public-read",:bucket_name=>"xxxxxx",:content_type=>"image/jpeg",:data=>Paperclip::AttachmentAdapter: Jon_Cardwell_header.jpg,:key=>"portfolios/headers/000/000/304/original.jpg")  
````

I've updated Paperclip to 4.3.5, added the rmagick gem, added the imagemagick update buildpack as per  https://github.com/thoughtbot/paperclip/wiki/Upgrade-Imagemagick-On-Heroku - but the same errors persist. The refresh works perfectly on my local machine. Any ideas?

**Comment by sebastialonso** [comment]
Same thing happening here.
I'm not using Heroku but a custom built droplet in DO.

When sending an image in base64, I get the following console error
~~~
Command :: identify -format '%wx%h,%[exif:orientation]' '/tmp/8d777f385d3dfec8815d20f7496026dc20160314-17264-wzmofc[0]' 2>/dev/null
[paperclip] An error was received while processing: #<Paperclip::Errors::NotIdentifiedByImageMagickError: Paperclip::Errors::NotIdentifiedByImageMagickError>
Command :: identify -format '%wx%h,%[exif:orientation]' '/tmp/8d777f385d3dfec8815d20f7496026dc20160314-17264-wzmofc[0]' 2>/dev/null
[paperclip] An error was received while processing: #<Paperclip::Errors::NotIdentifiedByImageMagickError: Paperclip::Errors::NotIdentifiedByImageMagickError>
Command :: identify -format '%wx%h,%[exif:orientation]' '/tmp/8d777f385d3dfec8815d20f7496026dc20160314-17264-wzmofc[0]' 2>/dev/null
[paperclip] An error was received while processing: #<Paperclip::Errors::NotIdentifiedByImageMagickError: Paperclip::Errors::NotIdentifiedByImageMagickError>
   [...]
   (0.2ms)  rollback transaction
Completed 422 Unprocessable Entity in 1341ms (Views: 0.8ms | ActiveRecord: 1.2ms)
~~~

Funnily enough when I make the call using Postman everything checks out and the image is saved.

Base64 image code is **FINE**, online decoders are able to render the image. What the hell is going on?

**Comment by tute** [comment]
Running `identify -format "%wx%h" spec/support/fixtures/twopage.pdf` in paperclip's folder returns `612x792612x792%` for me, but some people are getting nothing (and their specs fail). This seems to be related with this issue.

@danmakenoise @tankard and I have ImageMagick 6.9.3-7. Is the output exactly the same for you guys?

```
% identify --version
Version: ImageMagick 6.9.3-7 Q16 x86_64 2016-03-27 http://www.imagemagick.org
Copyright: Copyright (C) 1999-2016 ImageMagick Studio LLC
License: http://www.imagemagick.org/script/license.php
Features: Cipher DPC Modules
Delegates (built-in): bzlib freetype jng jpeg ltdl lzma png tiff xml zlib
```

**Comment by danmakenoise** [comment]
@tute My version is identical. I'm using OS 10.11.3, I'm wondering if that is a factor.

**Comment by tute** [comment]
I'm OS X `10.11.4 (15E65)`. @tankard?

**Comment by danmakenoise** [comment]
Figured it out on my end. I didn't have Ghostscript installed. Run `brew install gs`

**Comment by tute** [comment]
Yeah, I should have caught that it is described as dependency in https://github.com/thoughtbot/paperclip#requirements. Do you think it's worth it to write a setup script for this, à la https://github.com/thoughtbot/suspenders/blob/master/bin/setup?

**Comment by tute** [comment]
Also, @howells, is this still an issue for you?

**Comment by howells** [comment]
@tute honestly I can't even remember what I was trying to do that caused the error to begin with. I'll let you know if I run into the problem again.

**Comment by tute** [comment]
Thanks @howells. @sebastialonso do you still have this issue? If so, how can we reproduce?

**Comment by sebastialonso** [comment]
In my case it was caused by a poor encoding if the base64 data. Once that
was fixed, the error went away.

**Comment by tute** [comment]
Thanks! This doesn't look like an issue in paperclip, if it is we'll reopen. Thank you all for your input!

**Comment by nilcolor** [comment]
```ruby
has_attached_file :attachment,
                  styles: { mini: '48x48^', small: '100x100^', product: '240x240^', large: '600x600^' },
                  default_style: :product,
                  convert_options: { all: '-strip -auto-orient -colorspace sRGB' }
```
This produces the next command: `identify -format '%wx%h,%[exif:orientation]' /path/to/image/png`. While this generates
```
identify: unknown image property "%[exif:orientation]" @ warning/property.c/InterpretImageProperties/3762.
440x440,%
```
`gs` is installed.
```
$ identify --version
Version: ImageMagick 6.9.4-7 Q16 x86_64 2016-06-04 http://www.imagemagick.org
Copyright: Copyright (C) 1999-2016 ImageMagick Studio LLC
License: http://www.imagemagick.org/script/license.php
Features: Cipher DPC Modules
Delegates (built-in): bzlib freetype jng jpeg ltdl lzma png tiff xml zlib

$ gs --version
9.19
```

**Comment by alexsotocx** [comment]
Just brew update && brew upgrade!! It fix everything.

It looks like the version 6.9.4-7 had a bug or something because I had it installed and the same error over  and over...

Just upgrade it and boom it work again!
@nilcolor @tute

**Comment by nilcolor** [comment]
I was fixed it by monkeypatch that removes `[0]` from file name... Was worked well. Will try to update IM and remove that patch. Thanks!

**Comment by nozpheratu** [comment]
@nilcolor I'm also running into the [0] in the file name issue... mind sharing your monkey patch or submitting a PR?

**Comment by nilcolor** [comment]
@nozpheratu this is what I've done - https://gist.github.com/nilcolor/dc64e3cbcefd17797faf87456605e98a
I'm not sure it's worth a PR because this is the IM issue.

**Comment by nozpheratu** [comment]
@nilcolor Thanks for sharing. After some more investigating it turned out to be something unrelated for me. IM was missing some dependencies, adding them and building from source did the trick.
