### ISSUE TITLE
uri_adapter.rb and content type

### ISSUE THREAD

**Issue by robinbrandt** [thoughtbot/paperclip#2118]
Hi there,

when you assign a URI as the source of a paperclip attachment, paperclip seems to rely on the remote server's content type for determining the attachments content type instead of the actual file's content. Is this intended? We stumbled upon this when a remote server we downloaded images from reports "application/octet-stream" as the content type. 

https://github.com/thoughtbot/paperclip/blob/master/lib/paperclip/io_adapters/uri_adapter.rb#L25

```
@content_type = @content.content_type if @content.respond_to?(:content_type)
@content_type ||= "text/html"
```

`@content` is the return value of a call to open(URI(...)) which returns a Tempfile. The Tempfile instance returns "application/octet-stream" when you call `#content_type`.

If this is something you think should be fixed, I can dig into it and provide a PR.

**Comment by tute** [comment]
`octet-stream` is the `SENSIBLE_DEFAULT` in `ContentTypeDetector`. It does validate mime type, or it fallbacks to that.

What would your PR do? I'm not sure exactly what would need to change in paperclip yet.

**Comment by tute** [comment]
@robinbrandt do you still see this issue? If so, woudl #2256 address it? Thanks!

**Comment by robinbrandt** [comment]
Looks good, thank you!

**Comment by tute** [comment]
Thanks!
