### ISSUE TITLE
No release notes for any version after 4.3.1

### ISSUE THREAD

**Issue by thedrow** [thoughtbot/paperclip#2122]
Could you guys please add them?

**Comment by tute** [comment]
cc @maclover7, who was helping release these versions. Thank you!

**Comment by maclover7** [comment]
All release notes can be found in the usual place, https://github.com/thoughtbot/paperclip/blob/v4.3/NEWS.

**Comment by thedrow** [comment]
In that case, they are not merged to master.

**Comment by tute** [comment]
> In that case, they are not merged to master.

Indeed, and that branch won't be merged into master. I just added a commit to link v4.3 NEWS with that branch.

**Comment by thedrow** [comment]
Thanks!
