### ISSUE TITLE
Flash Video thumbnails (.flv)

### ISSUE THREAD

**Issue by AaronMegaphone** [thoughtbot/paperclip#2124]
Currently we can extract thumbnails from mp4 videos (https://github.com/thoughtbot/paperclip/wiki/Video-thumbnails). Are there any plans on integrating the ability to get thumbnails from flash videos? Currently, my work around is to use this dated gem https://github.com/owahab/paperclip-ffmpeg in tandem with paperclip.

**Comment by tute** [comment]
I'd rather solve this problem as a plugin in a different repo. @owahab, does your gem cover this use case? Thank you!

**Comment by owahab** [comment]
@tute yep. It actually went through a major refactoring, here it is: https://github.com/ruby-av/paperclip-av-transcoder

**Comment by tute** [comment]
Thank you! @AaronMegaphone would that cover your issue?

**Comment by AaronMegaphone** [comment]
This was a couple of months ago. But, I did try using that gem, but I couldn't get the resizing with maintaining aspect ratio of the thumbnails to work properly. It may have been at error on my part though. I will try again. @tute @owahab

**Comment by tute** [comment]
I don't think we should solve this in paperclip. Closing in favor of https://github.com/ruby-av/paperclip-av-transcoder/issues/31. Thank you for your report! ❤️ 😃
