### ISSUE TITLE
Spoofing detection generating excessive logging

### ISSUE THREAD

**Issue by stevehodges** [thoughtbot/paperclip#2125]
Line 15 of lib/paperclip/media_type_spoof_detector.rb outputs to Paperclip.log if spoofed? is true:

        Paperclip.log("Content Type Spoof: Filename #{File.basename(@name)} (#{supplied_content_type} from Headers, #{content_types_from_name} from Extension), content type discovered from file command: #{calculated_content_type}. See documentation to allow this combination.")

In my Rails application, hosted on Heroku, this line writes an excessively long log. It is 7.8 MEGABYTES of data spanning 769 lines of my log (max 10k characters per line). 

Specifically, the variable content_types_from_name is the vast majority of those characters; the rest of the log is a mere 376 characters.

I realize I can disable paperclip logging with an option, but I don't want to. Hence, I have monkey patched Paperclip in my application to not log in this occurrence.

Paperclip 4.3.2

**Comment by stevehodges** [comment]
For what it's worth, this was a file with a CSV generated by my Rails app using the Ruby CSV class. It had a file extension of .csv. Here's a snippet of the log

    [paperclip] Content Type Spoof: Filename 1457359663-user_2016-03-07_09_07_08_-0500.csv (text/comma-separated-values from Headers, [#<MIME::Type::Columnar:0x007f7e7dc0f2a8 @container=#<MIME::Types:0x007f7e7ea53878 @type...

(omitted middle 767 lines)

    ...@extensions=["csv"]>] from Extension), content type discovered from file command: application/octet-stream. See documentation to allow this combination.

**Comment by bdewater** [comment]
It's fixed with 8339e0f on master but that change not in the v4.3 branch. There's [potential for denial of service attacks](https://cwe.mitre.org/data/definitions/779.html) here :scream: @maclover7 @tute @jyurek @iwz could this be backported and released ASAP as 4.3.6?

**Comment by tute** [comment]
Closing in favor of the two linked PRs. Thank you all!
