### ISSUE TITLE
Outdated method description in helper module

### ISSUE THREAD

**Issue by paulmenzel** [thoughtbot/paperclip#2130]
The file [`lib/paperclip/helpers.rb`](https://github.com/thoughtbot/paperclip/blob/523bd46c768226893f23889079a7aa9c73b57d68/lib/paperclip/helpers.rb) defines the method `run()`, but – if I’m not mistaken, the method description differs from the actual signature.

**Comment by tute** [comment]
Thank you for reporting! Closing in favor of PR.
