### ISSUE TITLE
Getting an HTTP 500 from Paperclip without any real way of knowing why!

### ISSUE THREAD

**Issue by renegadeandy** [thoughtbot/paperclip#2138]
Hi everyone - thorough description of the problem here :+1: 

http://stackoverflow.com/questions/36084963/paperclip-throwing-http-500-error-log-is-not-showing-a-clear-reason
I would appreciate some assistance.

**Comment by tute** [comment]
Will help you in StackOverflow: https://stackoverflow.com/questions/36084963/paperclip-throwing-http-500-error-log-is-not-showing-a-clear-reason#comment59975217_36084963. Thanks!
