### ISSUE TITLE
Is Rails >= 4.1 required for paperclip v4.3.6?

### ISSUE THREAD

**Issue by ebouchut** [thoughtbot/paperclip#2140]
The README of v4.3.6 says [Rails >= 4.1 is required](https://github.com/thoughtbot/paperclip/tree/v4.3.6#ruby-and-rails).
The  [gemspec](https://github.com/thoughtbot/paperclip/blob/v4.3.6/paperclip.gemspec) says 
* activemodel >= 3.2 
*  activesupport >= 3.2.

Can paperclip version 4.3.6 work on Rails version 4.0.9?

**Comment by tute** [comment]
It might work well, but it is not tested against that version. See: https://github.com/thoughtbot/paperclip/blob/v4.3.6/.travis.yml#L11-L13. We dropped it in https://github.com/thoughtbot/paperclip/pull/1875 because it reached EOL.

Paperclip 4.2.4 is the last one to support Rails 4.0. Thanks!
