### ISSUE TITLE
Capistrano doesn't symlink public/system by default anymore

### ISSUE THREAD

**Issue by wynksaiddestroy** [thoughtbot/paperclip#2141]
The documentation says that a default installation of capistrano will symlink the `public/system` directory to the `shared` directory. Although this might have been true for older versions of capistrano, this isn't the case anymore. See issue https://github.com/capistrano/rails/issues/27 for example.
Nevertheless there is a `linked_dirs` option in the `deploy.rb` file:
```ruby
# Default value for linked_dirs is []
# set :linked_dirs, fetch(:linked_dirs, []).push('bin', 'log', 'tmp/pids', 'tmp/cache', 'tmp/sockets', 'vendor/bundle', 'public/system')
```
So you need to explicitly set the `linked_dirs` variable to `public/system` to get capistrano correctly working with paperclip.
Should I create a pull request to reflect the changes in the documentation or do you prefer to do it yourself?

**Comment by tute** [comment]
Please go ahead with the documentation improvement. Thank you!

**Comment by u007** [comment]
:+1:

**Comment by wynksaiddestroy** [comment]
I created pull request #2166. Tell me if there's anything that needs to be improved.

**Comment by tute** [comment]
Thanks! Closing in favor of the PR. :+1:
