### ISSUE TITLE
ActionController::UrlGenerationError in Videos#new 

### ISSUE THREAD

**Issue by Rui90** [thoughtbot/paperclip#2142]
I don't understand why I am getting this error. It says I need to pass the id, but if the video is only in the process of being created there's no id to be passed.

This is the error:
No route matches {:action=>"show", :controller=>"videos"} missing required keys: [:id]
And the problem is in the line simple_form_for @video
```
    <div class="form-group">
    <%= simple_form_for @video, url: video_path do |form| %>
        <%= form.input :videofile, as: :file %>
    <% end %>
    </div>

```

This is my model:
```
class Video < ActiveRecord::Base
  belongs_to :channel
  has_many :video_tags
  letsrate_rateable "rate_video"
  #has_attached_file :file, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  #validates_attachment_content_type :file, content_type: /\Aimage\/.*\Z/

  def self.search(query)
    where("title ilike ? or description ilike ? or genre ilike ?", "%#{query}%", "%#{query}%", "%#{query}%")
  end
end
```
And this is my migration

```
class AddAttachmentVideofileToVideos < ActiveRecord::Migration
  def self.up
    change_table :videos do |t|
      t.attachment :videofile
    end
  end

  def self.down
    remove_attachment :videos, :videofile
  end
end

```

**Comment by kitop** [comment]
Hey @Rui90, it seems like there's an error with the URL the form is pointing to.
`<%= simple_form_for @video, url: `**`video_path`**` do |form| %>`—`video_path` is `/videos/:id`

If you're creating a new video, you probably want to point to `videos_path`, which would be `/videos`, without `id`.

Anyway, if you're using `simple_form`, just saying `form_for @video`, without specifying a URL, it should be smart enough to detect the proper URL for creating and updating.

Hope that helps!

**Comment by Rui90** [comment]
yeah, how stupid of me, thanks!
