### ISSUE TITLE
No option to use path style for Fog S3 Storage 

### ISSUE THREAD

**Issue by Yanchek99** [thoughtbot/paperclip#2147]
Amazon supports two url styles for its assets, path styles and virtual hosted style. http://docs.aws.amazon.com/AmazonS3/latest/dev/VirtualHosting.html. 

However there is no way through fog to override the default virtual hosted style and instead use path style.

**Comment by aminariana** [comment]
Related to #2151 as well.

**Comment by tute** [comment]
Does https://github.com/thoughtbot/paperclip/pull/2135 fix this issue?

**Comment by Yanchek99** [comment]
@tute looks like it does!
