### ISSUE TITLE
warning: already initialized constant Paperclip::Storage::S3::DEFAULT_PERMISSION

### ISSUE THREAD

**Issue by jeffblake** [thoughtbot/paperclip#2148]
I'm using the master branch and getting these warnings. This warning shows up about 12 times (which may be related to the fact that I'm using puma with 12 workers)

It used to actually crash because of the constant being undefined, so I added the `s3_permissions` config option in the hopes of bypassing the need to look for `DEFAULT_PERMISSION`

I use the following to initialize paperclip:

```
Paperclip::Attachment.default_options.merge!(
  storage: :s3,
  path: 'assets/:class/:id/:attachment/:style.:extension',
  s3_credentials: "#{Rails.root}/config/s3.yml",
  s3_region: 'us-east-1',
  use_timestamp: false,
  preserve_files: true,
  s3_permissions: 'public-read',
  bucket: ENV.fetch('BUCKET')
)
```

I should also note that this does not only occur on bootup... I'm seeing these warnings consistently every minute or so.

**Comment by aminariana** [comment]
Full error:

`bundler/gems/paperclip-25be0b25d679/lib/paperclip/storage/s3.rb:118: warning: already initialized constant Paperclip::Storage::S3::DEFAULT_PERMISSION`

Seems like s3.rb line 118 is too eager during tests.

**Comment by tute** [comment]
Fixed in master. Thank you!

**Comment by david-meza** [comment]
I'm having the same issue, but my circumstances are different. I have a model called `KeyFocusArea` to which you can attach an image. When I go to the index route it will load all those images, and I get two warnings per image as you can see on the screenshot below:

![2016-04-11_13-39-33](https://cloud.githubusercontent.com/assets/11840636/14436509/07b29c4a-ffeb-11e5-82b3-2b09100bbeb0.png)

I'm not sure what is causing this, so I'll share my configuration:

In `config/environments/development.rb`:
```ruby
config.paperclip_defaults = {
  storage: :s3,
  s3_host_name: 's3-us-west-2.amazonaws.com',
  s3_region: Rails.application.secrets.aws_region,
  :s3_credentials => {
    bucket: Rails.application.secrets.s3_bucket_name,
    access_key_id: Rails.application.secrets.aws_access_key_id,
    secret_access_key: Rails.application.secrets.aws_secret_access_key
  }
}
```

And in `key_focus_area.rb`:

```ruby
has_attached_file :logo, 
                  styles: { medium: "300x300>", thumb: "100x100>" }, 
                  default_url: "/images/honeycomb.png",
                  storage: :s3,
                  s3_protocol: :https
  
validates_attachment_content_type :logo, content_type: /\Aimage\/.*\Z/
```

I'd appreciate if you can help me understand what I'm doing wrong and point me in the right direction. Thank you!
