### ISSUE TITLE
Videofile Paperclip::Errors::NotIdentifiedByImageMagickError

### ISSUE THREAD

**Issue by Rui90** [thoughtbot/paperclip#2154]
Hello

I am having the error enumerated on topic when I am trying to upload a video. I have found a few pages on the web saying that it could be regarding cocaine (I am using cocaine 0.5.8) but I'm not sure.

Anyway, this is the code on my video model which I think it can be wrong:

```
class Video < ActiveRecord::Base
  has_attached_file :videofile, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :videofile, content_type: /\Avideo\/.*\Z/
```
This is the error I get:

```
2 errors prohibited this video from being saved:

    Videofile Paperclip::Errors::NotIdentifiedByImageMagickError
    Videofile Paperclip::Errors::NotIdentifiedByImageMagickError

```

**Comment by palya** [comment]
Hi, @Rui90 
Are you using 'paperclip-ffmpeg'(or it's newest analogue 'paperclip-av-transcoder') gem also?

**Comment by Rui90** [comment]
@palya yeah, passed that error using that, gonna close thks
