### ISSUE TITLE
paperclip 4.2.0 folder and file not saved on production

### ISSUE THREAD

**Issue by u007** [thoughtbot/paperclip#2157]
hi,
i'm encountering a very weird error where my rails upload of pdf or image file stop working.
previously it was working:
public/system/spree/receipts/files/000/000/ *** / file.pdf**

the folder by id and file by name of file upoaded.
but my record is saved successfully even thou ive 
validates_attachment :file, presence: true

:file is the field name of receipt

what could be the issue?

thanks

**Comment by u007** [comment]
im encountering the same issue with paperclip 4.3.6

**Comment by u007** [comment]
okay, i found the problem,
im using site_relative_url to /shop,
when i upload a file, the folder is created in public/shop/system...

so when i deploy using capistrano, i need to link public/shop to shared.

and for workaround link to fix the path issue,
ive to add:
Paperclip::Attachment.class_eval do 
  
  def url(style_name = default_style, options = {})
    if options == true || options == false # Backwards compatibility.
      res = @url_generator.for(style_name, default_options.merge(:timestamp => options))
    else
      res = @url_generator.for(style_name, default_options.merge(options))
    end
    # Rails.logger.info "generator: #{@url_generator.inspect}"
    # Rails.logger.info "url-res::::::::::: #{res.inspect}"
    # Rails.logger.info "relative-url:#{Rails.application.config.site_relative_url[1..-1].inspect}"
    Rails.application.config.site_relative_url[0..-2]+Rails.application.config.site_relative_url[0..-2]+res
  end
  
end

but for some strange reason, my local:
http://127.0.0.1:3000/shop - seems to work fine, only happen on production server...

by the way, will there be any fix to support site_relative_url in the near future?

**Comment by u007** [comment]
okay i found the problem,
im using site_relative_url to /shop,
because default base of Storage::FileSystem seems call same method url of attachment to find the location to store the file, therefore this will conflict with actual url being called to display.
therefore im over riding filesystem to call interpolates(:url) to return path without relative url, with no timestamp

```
Paperclip::Storage::Filesystem.class_eval do
  def self.extended base
    
    base.instance_eval do
      Paperclip.interpolates(:url) do |attachment, style|
        attachment.store_path(style, {timestamp: false})
      end
    end
  end # extend base
  
end

Paperclip::Attachment.class_eval do 
  def store_path(style_name = default_style, options = {})
    if options == true || options == false # Backwards compatibility.
      res = @url_generator.for(style_name, default_options.merge(:timestamp => options))
    else
      res = @url_generator.for(style_name, default_options.merge(options))
      # raise Exception, "store path with options: #{res.inspect}, options: #{options.inspect}"
    end
    # raise Exception, "store path: #{res.inspect}, options: #{options.inspect}"
    res
  end
  
  def url(style_name = default_style, options = {})
    # raise Exception, "o no url!"
    res = Rails.application.config.site_relative_url.blank?? "" : Rails.application.config.site_relative_url[0..-2]
    res + store_path(style_name, options)
  end
end

```
Is this good enough?
Can someone add some test to makesure it works properly?
if yes, please help to create a pull request :)

thanks

**Comment by tute** [comment]
> Is this good enough?
> Can someone add some test to makesure it works properly?
> if yes, please help to create a pull request :)

I didn't get the chance to look in detail to your bug, @u007, but if what you found confusing can be fixed in code or documentation to paperclip, please start on it, mention me in the PR, and we'll work together. Thank you for sharing your question and solution!

**Comment by tute** [comment]
Thanks for posting your issue and answer! Glad it's now working for you.
