### ISSUE TITLE
UploadedFileAdapter.content_type_detector is nil by default

### ISSUE THREAD

**Issue by printercu** [thoughtbot/paperclip#2162]
Hi!

Docs says 

> Paperclip::ContentTypeDetector will attempt to match a file's extension to an inferred content_type, regardless of the actual contents of the file.

But it's not used by default, and there is no mentions that it must be set manually. Is it supposed to be set automatically or it is expected behaviour now?

While it's disabled by default, and there are such docs, all applications which don't set up detector are vulnerable to spoofing attacks.

**Comment by uiltondutra** [comment]
Hi @printercu! It doesn't seem to be the case because the MediaTypeSpoofDetectionValidator prevents the spoofing by default.

**Comment by printercu** [comment]
I haven't read paperclip's code for this too much. For now I can't pass any file for attachment, but I can override content type in specs:

```ruby
subject { create(:station) }

context 'when valid content_type' do
  before { subject.update!(image: fixture_file_upload('images/small.jpg', 'image/jpeg')) }
  its(:image_content_type) { should eq 'image/jpeg' }
end

context 'when invalid content_type' do
  before { subject.update!(image: fixture_file_upload('images/small.jpg', 'image/png')) }
  its(:image_content_type) { should eq 'image/jpeg' }
  # Fails with:
  #    expected: "image/jpeg"
  #         got: "image/png"
end
```

While with `Paperclip::UploadedFileAdapter.content_type_detector = Paperclip::ContentTypeDetector
` this tests pass.

I'll check other extensions/file types later.
