### ISSUE TITLE
S3 bucket path

### ISSUE THREAD

**Issue by alexeitsb** [thoughtbot/paperclip#2167]
Uploaded file is stored on AWS S3 on bucket/model_name_pluralized/attachment_name_pluralized/000/000/model_id

What's is 000 folders for?

**Comment by common-nighthawk** [comment]
here you go--
http://stackoverflow.com/questions/27940107/ror-set-paperclip-image-model-path-for-s3-bucket-correctly

(i believe this issue can be closed.)

**Comment by tute** [comment]
Yep, thanks!

**Comment by alexeitsb** [comment]
Understood! Thanks!
