### ISSUE TITLE
Google Drive with paperclip upload problem

### ISSUE THREAD

**Issue by Rui90** [thoughtbot/paperclip#2168]
I am running into what I think it is a giant problem. I was using the following paperclip gem:

    gem "paperclip", git: "git://github.com/thoughtbot/paperclip.git"

But when I added gem 'paperclip-googledrive' I got an error: `paperclip-googledrive (>= 0) ruby depends on paperclip (~> 3.4) ruby`

So I did a new bundle install with only `gem "paperclip"` which fixed the problem. But now, when I am trying to make an upload I got the following error:

    NoMethodError in VideosController#create 
    undefined method `call' for "result == false":String

I have been reading across the web and I think it is due to incompatibilies with paperclip 3.4 and my rails version (4.2.4) which is a problem.

Anyone knows any workaround to help me out with this? By the way, this is my model:

    class Video < ActiveRecord::Base
      belongs_to :channel
      has_many :video_tags
      letsrate_rateable "rate_video"
      has_attached_file :videofile, styles: {
          :medium => {
              :geometry => "640x480",
              :format => 'mp4'
          },
          :thumb => { :geometry => "160x120", :format => 'jpeg', :time => 10}
      }, :processors => [:transcoder], :storage => :google_drive, :google_drive_credentials => "#{Rails.root}/config/google_drive.yml"
    
      validates_attachment_content_type :videofile, content_type: /\Avideo\/.*\Z/

Update with Gemfile:

    source 'https://rubygems.org'
    
    
    # Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
    gem 'rails', '4.2.4'
    # Use postgresql as the database for Active Record
    gem 'pg'
    # Use SCSS for stylesheets
    gem 'sass-rails', '~> 5.0'
    # Use Uglifier as compressor for JavaScript assets
    gem 'uglifier', '>= 1.3.0'
    # Use CoffeeScript for .coffee assets and views
    gem 'coffee-rails', '~> 4.1.0'
    # See https://github.com/rails/execjs#readme for more supported runtimes
    # gem 'therubyracer', platforms: :ruby
    
    gem 'bootstrap-sass', '~> 3.2.0'
    gem 'autoprefixer-rails'
    
    gem 'devise'
    
    gem 'bootstrap_form'
    
    
    # Use jquery as the JavaScript library
    gem 'jquery-rails'
    # Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
    gem 'turbolinks'
    # Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
    gem 'jbuilder', '~> 2.0'
    # bundle exec rake doc:rails generates the API under doc/api.
    gem 'sdoc', '~> 0.4.0', group: :doc
    
    # Use ActiveModel has_secure_password
    gem "bcrypt-ruby", '~> 3.0.0'
    
    #gem 'google-api-client', '0.9'
    
    gem 'google-api-client', '<0.9'
    
    gem 'letsrate'
    
    gem 'will_paginate', '~> 3.0.6'
    
    gem 'filterrific'
    
    gem 'google_drive', '~> 1.0.6'
    
    gem "paperclip" #, git: "git://github.com/thoughtbot/paperclip.git"
    
    gem 'leaderboard'
    
    gem 'paperclip-av-transcoder'
    
    gem "paperclip-ffmpeg"
    
    gem 'aws-sdk'
    
    gem 'paperclip-googledrive'

**Comment by jasonfb** [comment]
what's the actual version of paperclip you are using? You find this in ```Gemfile.lock``` not in ```Gemfile```

did you try

```bundle update paperclip```

to simply move paperclip to the latest version that is compatible with your Rails version?

You definitely will want to tweak around with the version settings until you find a Rails, Paperclip, and paperclip-googledrive that all work together.

**Comment by Rui90** [comment]
@jasonfb  latest version of paperclip is compatible with rails 4.2.4 (rails version that I'm using) but not with paperclip-googledrive :/

**Comment by tute** [comment]
The issue you describe seems very specific to your code or project (https://github.com/evinsou/paperclip-googledrive/issues/21). I suggest that you ask about it in https://stackoverflow.com/questions/tagged/paperclip, which will get attention
from more people than in this issue tracker.

Also, I recommend you follow the steps outlined in http://yourbugreportneedsmore.info/, so that people can better replicate or understand your issue in order to help you. In particular, the whole stack trace would be very useful.

Sorry we don't have the time now to help you with this question, and thanks!
