### ISSUE TITLE
Error: has contents that are not what they are reported to be

### ISSUE THREAD

**Issue by cristianrosu** [thoughtbot/paperclip#2172]
I'm getting this error while trying to upload files with certain extentions(.ino, .fods for example). I'm using do_not_validate_attachment_file_type and I can't really understand where this is coming from. Any ideas?

**Comment by tute** [comment]
This is a "secure by default" feature. See: https://github.com/thoughtbot/paperclip/issues/2195#issuecomment-217446987.

If you think we should add it to the README, I'll gleefully merge a PR.

Thank you!
