### ISSUE TITLE
Warning messages when running tests or visiting any route that uses paperclip images

### ISSUE THREAD

**Issue by david-meza** [thoughtbot/paperclip#2174]
**Using aws-sdk 2.2.30
Using paperclip 5.0.0.beta1 from git://github.com/thoughtbot/paperclip.git (at master@25be0b2)**

I have a model called `KeyFocusArea` to which you can attach an image. When I go to the index route it will load all those images, and I get two warnings per image as you can see on the screenshot below:

![2016-04-11_13-39-33](https://cloud.githubusercontent.com/assets/11840636/14436509/07b29c4a-ffeb-11e5-82b3-2b09100bbeb0.png)

I should clarify this does not only happen when I visit that route in particular (just an example of it) but anytime a Paperclip image needs to be loaded on any route. It also happens when running tests and a model has an attachment attribute.

I'm not sure what is causing this, so I'll share my configuration:

In `config/environments/development.rb`:
```ruby
config.paperclip_defaults = {
  storage: :s3,
  s3_host_name: 's3-us-west-2.amazonaws.com',
  s3_region: Rails.application.secrets.aws_region,
  :s3_credentials => {
    bucket: Rails.application.secrets.s3_bucket_name,
    access_key_id: Rails.application.secrets.aws_access_key_id,
    secret_access_key: Rails.application.secrets.aws_secret_access_key
  }
}
```

And in `app/models/key_focus_area.rb`:

```ruby
has_attached_file :logo, 
                  styles: { medium: "300x300>", thumb: "100x100>" }, 
                  default_url: "/images/honeycomb.png",
                  storage: :s3,
                  s3_protocol: :https
  
validates_attachment_content_type :logo, content_type: /\Aimage\/.*\Z/
```

I'd appreciate if you can help me understand what I'm doing wrong and point me in the right direction. Thank you!

**Comment by david-meza** [comment]
Related to #2148

**Comment by tute** [comment]
We didn't yet release the next beta release. I see you point your Gemfile to a commit, if you point it to 9bdc0a00bfb43c9afef7e992a0cf7f55d93a5c27 (or following ones) this will be fixed.

Thanks for reporting!

**Comment by tute** [comment]
Just released beta2, in case you want to point it to that release. Thanks!

**Comment by david-meza** [comment]
Thank you. I was pointing to the master branch, but I had to run `bundle update` to fetch the latest version.
