### ISSUE TITLE
Paperclip storage gem for Cloudinary

### ISSUE THREAD

**Issue by GoGoCarl** [thoughtbot/paperclip#2175]
Hello,

Wasn't quite sure where to drop this note, so I figured I would put it here; apologies if this is out of place.

Just wanted to post as a community contribution a Paperclip storage gem I built that talks to [Cloudinary](http://cloudinary.com).  Found it useful for myself and thought someone else might too.

https://github.com/GoGoCarl/paperclip-cloudinary

Thanks,

GoGoCarl.

Note: I'm not affiliated with Cloudinary in any way, just a happy consumer.

**Comment by tute** [comment]
This is great, thank you! Do you want to add it to the wiki list https://github.com/thoughtbot/paperclip/wiki#storage? Thanks!

**Comment by GoGoCarl** [comment]
Done, thank you!

**Comment by tute** [comment]
Thank you too!
