### ISSUE TITLE
Progress Bar during upload

### ISSUE THREAD

**Issue by Rui90** [thoughtbot/paperclip#2176]
Hello

I am using Paperclip for video/files upload and I would like to add a progress bar to the upload but I am not finding that much information to do it.

Does Paperclip has this kind of feature? It is it to implement, or should I use other kind of upload?

**Comment by tute** [comment]
That requires frontend + backend orchestration. Paperclip doesn't solve it out of the box. Some browser show the percentage of file uploads by default.

The best interface I know for this is from FilePicker, which I can recommend. Closing the issue as it doesn't require more work in paperclip, but happy to continue further discussion.

**Comment by Rui90** [comment]
@tute  I can integrate FilePicker with Paperclip?

**Comment by tute** [comment]
> @tute I can integrate FilePicker with Paperclip?

I've never done this myself, but it can be done. See https://github.com/ScotterC/fileclip or http://stackoverflow.com/a/16805469/356060.

**Comment by duhaime** [comment]
@tute and @Rui90 Hi, I'm in a similar position, and am using ng-file-upload as the frontend client for uploading files to a Paperclip-equipped backend. The catch is that files need to go from the client to the Rails server with Paperclip installed, and then from there to AWS. The client can only keep track of file progress from the client to the Rails server, and has no idea that there is additional file upload progress that happens once the file hits the Rails server. 

Would it be possible to tie a progress event to the process of uploading files from the Rails server to AWS / S3? I could do this with a JS backend, but would love to be able to track progress of the file upload from Rails/Paperclip to AWS. If you could provide a few pointers, @tute, I would be happy to submit a PR...
