### ISSUE TITLE
Paperclip ignoring interpolated filters in convert_options

### ISSUE THREAD

**Issue by chrishawk** [thoughtbot/paperclip#2180]
Trying to apply some filters to the resized images on our site. Any added filters seem to be ignored. I ran the imagemagick processing by command line and the expected output doesn't match what paperclip produces. It looks like the filter is being ignored. I think the issue might be that the filter option needs to come prior to resize in the convert call.

``` ruby
class Image

  has_attached_file :attachment, {
    :styles => lambda { |a| a.instance.styles_by_image_type},
    :path => "#{'public/' if Rails.env.test?}images/:id/:style/:basename.:extension",
    :convert_options => { :all => '-filter box -auto-orient +profile "exif"' },
  }

```

**Comment by tute** [comment]
Does paperclip ignore it, or `convert` does it too if you run the command in your terminal? Thank you for your report.
