### ISSUE TITLE
Feature request: Generate hash without hash_secret

### ISSUE THREAD

**Issue by Joshfindit** [thoughtbot/paperclip#2188]
In this case, we're using the hash to uniquely identify the file, as well as provide an externally-validatable checksum.

A hash salt is not required or desired.

**Comment by tute** [comment]
This is also used for security features, so we better be secure by default. You can place any token in that option if you don't need to carefully pick it as a secret from ENV variables, and it will work as intended. We'll leave it as is for now. Thanks for reporting.

**Comment by Joshfindit** [comment]
Agreed; secure by default.

This is outside the scope of Paperclip, but if `hash_secret` is enforced, what's the method for calculating the same hash from the same file?

For example: Paperclip calculates the hash as `de6f79e339ac4dc0f0e400d86dbfe640531b87ff` with a `hash_secret` of `secret`.
How can we process that file on another system to arrive at the same hash of `de6f79e339ac4dc0f0e400d86dbfe640531b87ff`?

**Comment by tute** [comment]
The method is defined in https://github.com/thoughtbot/paperclip/blob/master/lib/paperclip/attachment.rb#L320-L325

**Comment by Joshfindit** [comment]
Thanks, that works.
