### ISSUE TITLE
base64 encoded file upload via json api endpoint

### ISSUE THREAD

**Issue by JamesChevalier** [thoughtbot/paperclip#2193]
I feel bad about filing this, because it's mentioned many times, but I cannot figure this out. So, first off, sorry & thanks!

I've got a `create` endpoint that will create a record that can have an image attachment. Since it's just an API endpoint, without a Rails form, I understand that I need to transmit the file as base64 encoded data but I cannot find a canonical/official way of doing this.

These are the parameters I'm sending (that should be a valid 5x5 pixel PNG of a solid #0C90B5 color):
```
params[:record][:uploaded_image_data] = 'iVBORw0KGgoAAAANSUhEUgAAAAUAAAAFCAIAAAACDbGyAAAAEElEQVR4AWMQ\n7d2BjCjlAwA4QCHL+OA2ggAAAABJRU5ErkJggg==\n'
params[:record][:uploaded_image_name] = 'something.png'
```

That base64 code was generated with this code:
`Base64.encode64(open(Rails.root.join('something.png')) { |io| io.read })`

This is one version of my attempt:

```
def create
  @record = current_user.records.new(record_params)
  authorize @record

  if params[:record][:uploaded_image_data]
    content_type                 = Mime::Type.lookup_by_extension(File.extname(params[:record][:uploaded_image_name])[1..-1]).to_s
    image_file                   = Paperclip.io_adapters.for("data:#{content_type};base64,#{params[:record][:uploaded_image_data]}")
    image_file.original_filename = params[:record][:uploaded_image_name]
    @record.image                = image_file
  end

  if @record.save
    render json: @record, status: :created
  else
    render json: @record.errors, status: :unprocessable_entity
  end
end
```

This is another version of my attempt:

```
def create
  @record = current_user.records.new(record_params)
  authorize @record

  if params[:record][:uploaded_image_data]
    image_file = StringIO.new(Base64.decode64(params[:record][:uploaded_image_data]))
    image_file.class.class_eval { attr_accessor :original_filename, :content_type }
    image_file.original_filename = params[:record][:uploaded_image_name]
    image_file.content_type      = Mime::Type.lookup_by_extension(File.extname(params[:record][:uploaded_image_name])[1..-1]).to_s
    @record.image                = image_file
  end

  if @record.save
    render json: @record, status: :created
  else
    render json: @record.errors, status: :unprocessable_entity
  end
end
```

The error in both cases as returned in my API is:

```
{
  "image": [
    "Paperclip::Errors::NotIdentifiedByImageMagickError",
    "Paperclip::Errors::NotIdentifiedByImageMagickError"
  ]
}
```

The error in the Rails log is:

```
Command :: file -b --mime '/var/folders/5c/x5mschx537sbw2bmm39lmh6c0000gn/T/8277e0910d750195b448797616e091ad20160505-57859-1dtgjxj.png'
Command :: identify -format '%wx%h,%[exif:orientation]' '/var/folders/5c/x5mschx537sbw2bmm39lmh6c0000gn/T/8277e0910d750195b448797616e091ad20160505-57859-f4hzkm.png[0]' 2>/dev/null
[paperclip] An error was received while processing: #<Paperclip::Errors::NotIdentifiedByImageMagickError: Paperclip::Errors::NotIdentifiedByImageMagickError>
Command :: identify -format '%wx%h,%[exif:orientation]' '/var/folders/5c/x5mschx537sbw2bmm39lmh6c0000gn/T/8277e0910d750195b448797616e091ad20160505-57859-f4hzkm.png[0]' 2>/dev/null
[paperclip] An error was received while processing: #<Paperclip::Errors::NotIdentifiedByImageMagickError: Paperclip::Errors::NotIdentifiedByImageMagickError>
   (1.4ms)  BEGIN
Command :: file -b --mime '/var/folders/5c/x5mschx537sbw2bmm39lmh6c0000gn/T/8277e0910d750195b448797616e091ad20160505-57859-14cbkr0.png'
   (1.1ms)  ROLLBACK
Command :: file -b --mime '/var/folders/5c/x5mschx537sbw2bmm39lmh6c0000gn/T/8277e0910d750195b448797616e091ad20160505-57859-6ygj7b.png'
Completed 422 Unprocessable Entity in 115ms (Views: 0.4ms | ActiveRecord: 10.7ms)
```

I've done a fair amount of research on how to accomplish this (and they all seem to be extremely similar), with some highlights:

- https://gist.github.com/WizardOfOgz/1012107
- http://manukall.de/2015/04/30/saving-base64-encoded-data-as-paperclip-4-attachments/
- http://stackoverflow.com/questions/29930430/upload-base64-image-with-paperclip-rails-4
- http://stackoverflow.com/questions/10160286/uploading-a-file-to-rails-json-api-server-with-paperclip-and-multipart-request
- http://paoloibarra.com/2014/09/27/Image-Upload-Using-Rails-API-And-Paperclip/ (this one uses a tempfile, though)

This `NotIdentifiedByImageMagickError` error is mentioned a number of times, with many suggestions ending up in reinstalling tools:
https://github.com/thoughtbot/paperclip/issues?utf8=%E2%9C%93&q=NotIdentifiedByImageMagickError

I've reinstalled libtool, libpng, jpeg, and imagemagick a number of times.
I'm using the latest version, after a `brew update`, of libtool, libpng, jpeg.
I do notice that subsequent installs use the cached local copy, though, e.g.:

> Already downloaded: /Library/Caches/Homebrew/imagemagick-6.9.3-7_1.yosemite.bottle.tar.gz

I've tried with the latest version of imagemagick:
`brew install imagemagick`

I've tried with one version prior:
`brew install https://raw.githubusercontent.com/Homebrew/homebrew-core/c42ffade9bd5d3392aa39107c79ba4a40ca0f23b/Formula/imagemagick.rb`

I'm using:

- ruby 2.3.0
- rails 4.2.6
- paperclip version 4.3.6

I don't know if my code is wrong, if my base64 data is wrong, and/or if my tools are broken. Can anyone shed any light on this?
Again - thanks & sorry!

**Comment by tute** [comment]
Thanks so much for your thoughtful report.

Question: can you submit a sample up to trigger this issue? Is so, we'll
have a higher chance of working through it.

Thank you!

**Comment by JamesChevalier** [comment]
OK, I've created [a small Rails app](https://github.com/JamesChevalier/base64) as an example of the problem. The Readme file should include all required info for getting that set up - I included a Vagrant setup to make it easier & less intrusive. Let me know if you have any questions!

You should be able to start up the Rails app, then hit the `/api/v1/records` endpoint with a POST request that includes a few parameters, depending on which version you're testing:

- `params[:record][:uploaded_image_name]`
  - required to name the file and set the Mime Type
- `params[:record][:uploaded_image_for_io_adapters]`
  - the base64 encoded data for the Paperclip.io_adapters version
- `params[:record][:uploaded_image_for_stringio]`
  - the base64 encoded data for the StringIO version

**Comment by zdavis** [comment]
Seeing the same problem here.

**Comment by kjakub** [comment]
@JamesChevalier 

i got it working like without problem:


````
class Api::V1::PicturesController < ApplicationController

  def index
    render json: {}
  end

  def create
    @picture = current_user.pictures.new

    if picture_params[:file_data]
      image_file                   = Paperclip.io_adapters.for(picture_params[:file_data])
      image_file.original_filename = picture_params[:file_name]
      image_file.content_type      = "image/jpeg"
      @picture.file                = image_file
    end

    if @picture.save
      render json: {}, status: :created
    else
      render json: @picture.errors, status: :unprocessable_entity
    end

  end

  private
    def picture_params
      params.require(:picture).permit(:file_data, :file_name)
    end
    
end
````

**Comment by JamesChevalier** [comment]
Thanks @kjakub
It looks like your example is (more or less) the same as my [io_adapters example](https://github.com/JamesChevalier/base64/blob/master/app/controllers/api/v1/records_controller.rb#L18-L23) in that it all comes down to the same [Paperclip.io_adapters](https://github.com/JamesChevalier/base64/blob/master/app/controllers/api/v1/records_controller.rb#L20) call. So I'm surprised that you got yours to work.

I noticed that you have a line `image_file.content_type      = "image/jpeg"` and mine does not. I think I got my idea from [this post](http://manukall.de/2015/04/30/saving-base64-encoded-data-as-paperclip-4-attachments/) which didn't include it. Also, [the specs](https://github.com/thoughtbot/paperclip/blob/e60f00027704298455c039e111d96bcf46e12822/spec/paperclip/io_adapters/data_uri_adapter_spec.rb#L30-L32) suggest that the `content_type` is set within Paperclip.
I tried my example app again with that line present, just to be certain, and I received the same error.

I also notice that you're working with jpeg data, but I'm working with png data. I added example data for a jpg file to my example app & tested that, but still came up with the same error.

I haven't noticed anything else different about our code, so I don't understand why yours works and mine does not. My guess at this point is that underlying software versions could be playing a role. If I run `dpkg -l |grep imagemagick` I get this output:

```
ii  imagemagick                      8:6.7.7.10-6ubuntu3.1               amd64        image manipulation programs
ii  imagemagick-common               8:6.7.7.10-6ubuntu3.1               all          image manipulation programs -- infrastructure
```

**Comment by kjakub** [comment]
@JamesChevalier 

yes, i used your code to confirm and just modified a bit. I also tried without `image_file.content_type = "image/jpeg"` and the only change was that file was saved without any extension to filesystem

````
ii  imagemagick                                           8:6.7.7.10-6ubuntu3.1                               amd64        image manipulation programs
ii  imagemagick-common                                    8:6.7.7.10-6ubuntu3.1                               all          image manipulation programs -- infrastructure

gem 'rails', '4.2.5.1'
gem "paperclip", "~> 5.0.0.beta1"
ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-linux]
````

perhaps you want to share your base64 png data with me in some temporary gist and i try it

**Comment by JamesChevalier** [comment]
That'd be fine, @kjakub ... The example images and their corresponding Base64 data is in [the example Rails app](https://github.com/JamesChevalier/base64).

The jpg file is [here](https://github.com/JamesChevalier/base64/blob/master/something.jpg).
The png file is [here](https://github.com/JamesChevalier/base64/blob/master/something.png).
The [top of the README file](https://github.com/JamesChevalier/base64#readme) contains the Base64 string for both both files.

I notice some version discrepancies between your notes and my example Rails project:

- Paperclip 4.3.6
- Rails 4.2.6
- Ruby 2.3.0

**Comment by kjakub** [comment]
@JamesChevalier none of those base64 seems to be valid images you can try them in here
[http://jsfiddle.net/casiano/xadvz/](url)

**Comment by JamesChevalier** [comment]
Thanks @kjakub ... There must be something wrong with the way I encoded/decode the file that's not web-safe.

Taking this file from the example:
https://raw.githubusercontent.com/JamesChevalier/base64/master/something.png

I generated its Base64 encoded value with:
`encoded_file = Base64.encode64(File.open('something.png', 'rb').read)`

This returned its encoded value as:
`iVBORw0KGgoAAAANSUhEUgAAAAUAAAAFCAIAAAACDbGyAAAAEElEQVR4AWMQ\n7d2BjCjlAwA4QCHL+OA2ggAAAABJRU5ErkJggg==\n`

If I then decode and write that file to disk, it's a functional PNG file:
```
File.open('encoded_and_decoded.png', 'wb') do |file|
  file.write(Base64.decode64(encoded_file))
end
```

However, if I update your jsfiddle with the encoded value, it is not functional:
http://jsfiddle.net/esxu7e2j/1/

How did you generate your Base64 encoded image data?

**Comment by kjakub** [comment]
@JamesChevalier your welcome. Btw. i always loved paperclip but now i tried carrierwave with base64 gem and it just works out of the box, no need to do any coding..

**Comment by vineelsonnathi** [comment]
This post helped me in uploading an image to s3( using paperclip) via rest api(post request) for a friend. Converting the image to base64 was the key.
