### ISSUE TITLE
do_not_validate_attachment_file_type still validating

### ISSUE THREAD

**Issue by persep** [thoughtbot/paperclip#2195]
Hi,
I have Ubuntu 14.0.4 64 with rails 4.26 and paperclip 4.3.6.
I have a model  called track in track.rb with a `do_not_validate_attachment_file_type` validation:
```
class Track < ActiveRecord::Base
    has_many :tracksegments, :dependent => :destroy
    has_many :points, :through => :tracksegments

    has_attached_file :gpx
    validates :name, presence: true
    do_not_validate_attachment_file_type :gpx
    
    before_save :parse_file
       ...............
```
According to the docs it shouldn't do any validations but when I load a gps file i get the error 
`[paperclip] Content Type Spoof: Filename demofile.foo (text/xml from Headers, [] from Extension), content type discovered from file command: application/xml. See documentation to allow this combination.
`
The only way to bypass the validation is with an initialier in `config/initializer/paperclip.rb` with:
`Paperclip.options[:content_type_mappings] = {
    :gpx => ["application/xml"]
}`

Souldn't `do_not_validate_attachment_file_type` stop all validations?

**Comment by persep** [comment]
i've just discovered that for `do_not_validate_attachment_file_type` to stop the validation you have to add an initializer in `config/initializer/paperclip.rb`
with
`Paperclip::Attachment.default_options[:validate_media_type] = false`
I couln't find this in the docs only in the NEWS file

**Comment by duhaime** [comment]
Adding 

```
Paperclip::Attachment.default_options[:validate_media_type] = false
```

Is not a great idea because it's going to allow all of your attachments to possess any media type (e.g. sketchy.exe will be allowed). It's better to add `validate_media_type: false` to the `has_attached_file` block
