### ISSUE TITLE
expiring_url does not use s3_host_alias

### ISSUE THREAD

**Issue by anark** [thoughtbot/paperclip#2196]
When using paperclip with :url => ":s3_alias_url" and a s3_host_alias set the expiring_url does not use the s3_host_alias.

This really makes a difference when using cloudfront with paperclip.  It would be great to be able to offer expiring url's that used the cloudfront endpoint instead of the direct s3 endpoint.

**Comment by marcelrouw** [comment]
I ran into the same issue. 
Is there a fix or a work around?

**Comment by sudara** [comment]
This  changed behavior from version 4, but not specified in docs or the upgrade guide. 

After reading some code, it seems that paperclip 5.x merges in `s3_url_options` to the options it sends s3 presigner. The presigner has an option to use the virtual host (which will force http). See http://docs.aws.amazon.com/sdkforruby/api/Aws/S3/Presigner.html#presigned_url-instance_method

This config in the default or per-model options fixes it for me:

`s3_url_options: {virtual_host: true}`

**Comment by anark** [comment]
Even with
`s3_url_options: { virtual_host: true }`

the
`attachment.expiring_url`

still give the s3 url instead of using the alias url for me.

**Comment by sidraval** [comment]
Thank you for reporting this. Unfortunately, we will be deprecating Paperclip and therefore will not have the bandwidth to address this issue.
