### ISSUE TITLE
Paperclip::Geometry.from_file not working with new ImageMagick version for urls that have https

### ISSUE THREAD

**Issue by rkrdo** [thoughtbot/paperclip#2198]
So I just updated ImageMagick to `v6.9.3-10` (from Homebrew), and added the policies that [ImageTragick](imagetragick.com) recommends.

In my current project, I'm using Paperclip to store images in Amazon S3 buckets. I'm also using `Paperclip::Geometry.from_file` to get the dimensions of an uploaded image, but ever since I updated to the new version of ImageMagick, I keep on getting an `Paperclip::Errors::NotIdentifiedByImageMagickError` Exception whenever I try to use `Paperclip::Geometry.from_file`. 

I'm pretty sure that the reason for this is that I have my model's paperclip config to use `:https` as the `:s3_protocol` for the `has_attached_file`. And calling `Paperclip::Geometry.from_file` calls:

```
identify -format '%wx%h,%[exif:orientation]' 'https://s3.amazonaws.com/path_to_my_bucket/image.png[0]'
```

Which returns the following output:
```
identify: not authorized `//s3.amazonaws.com/path_to_my_bucket/image.png' @ error/constitute.c/ReadImage/412.
```

Caused by the `<policy domain="coder" rights="none" pattern="HTTPS" />` policy in ImageMagick.

Is there a way to work around this? Setting the `:s3_protocol` to just `:http` works, but I'd rather use `https`

**Comment by tute** [comment]
What happens if you enable the HTTPS ImageMagick policy?

I suggest that you ask also in https://stackoverflow.com/questions/tagged/paperclip, which will get attentionfrom more people than in this issue tracker.

**Comment by rkrdo** [comment]
@tute if I remove the policy it works, but I believe it's recommended that policy gets used to prevent the "magic bytes" vulnerability

**Comment by tute** [comment]
I see. Then it's an insecure feature, that you cannot enable? Using it and being secure are indeed at odds in your use case.

**Comment by rkrdo** [comment]
In case anyone else is running into this problem, my workaround right now was to replace `https`with `http` when using `Paperclip::Geometry.from_file`:

```
  def avatar_geometry(style = :original)
    @geometry ||= {}
    path = (avatar.options[:storage]==:s3) ? avatar.url(style) : avatar.path(style)
    @geometry[style] ||= Paperclip::Geometry.from_file(path.sub('https', 'http')
  end
```

@tute I still think that Paperclip could handle this, but if you guys don't think so, feel free to close this issue.

**Comment by tute** [comment]
> I still think that Paperclip could handle this, but if you guys don't think so, feel free to close this issue.

I'm happy to try and collaborate, but I don't have time in the foreseeable future to triage the issue and propose fixes. Do you think you can tackle that? Thanks for sharing the snippet.

**Comment by rkrdo** [comment]
Quick update for anyone that's using ImageMagick `6.9.4-1` or possibly newer.

The `delegates.xml` file (for homebrew installations, it's located in `/usr/local/Cellar/imagemagick/6.9.4-1/etc/ImageMagick-6`) has commented out the following line (around line 74):

```
<!--
<delegate decode="https" command="&quot;curl&quot; -s -k -L -o &quot;%o&quot; &quot;https:%F&quot;"/>
-->
```

Uncommenting that line makes `Paperclip::Geometry.from_file` work again without the workaround from the previous [comment](https://github.com/thoughtbot/paperclip/issues/2198#issuecomment-218223186)

Closing this issue since it was more ImageMagick related

**Comment by RISCfuture** [comment]
With 6.9.4-7 this issue reappears even with the changes to the delegates.xml file; now the error is File Not Found (with the brackets) rather than Not Authorized. The fix is in ImageMagick master: https://github.com/ImageMagick/ImageMagick/issues/214

**Comment by mkozono** [comment]
I don't know why #2190 wasn't linked here, but if you want to maintain security, isn't this is the proper solution?-- "Upgrade to ImageMagick 7.0.1-1 or newer", as stated in https://robots.thoughtbot.com/paperclip-is-vulnerable-to-the-imagetragick-vulnerability.

**Comment by kevinhq** [comment]
> In case anyone else is running into this problem, my workaround right now was to replace `https`with `http` when using `Paperclip::Geometry.from_file`:
> 
> ```
>   def avatar_geometry(style = :original)
>     @geometry ||= {}
>     path = (avatar.options[:storage]==:s3) ? avatar.url(style) : avatar.path(style)
>     @geometry[style] ||= Paperclip::Geometry.from_file(path.sub('https', 'http')
>   end
> ```
> @tute I still think that Paperclip could handle this, but if you guys don't think so, feel free to close this issue.

Thanks, you saved my day, buddy.
