### ISSUE TITLE
Question: why doesn't my model save?

### ISSUE THREAD

**Issue by Joshfindit** [thoughtbot/paperclip#2203]
I'm struggling with saving a file to paperclip.
Everything seems good, the mimetypes check out, and there are no errors in the log, _however_, `puts object.save` reports `false`.

Searching the wiki, SO, and Google, I can't find how to dig in to find out what's going on underneath the `false`.

Please create some documentation that will let users get to the bottom of issues like these.

**Comment by tute** [comment]
Can you paste your model code and log for the action that fails, please?

**Comment by Joshfindit** [comment]
```
Class Artefact
  has_neo4jrb_attached_file :ingestedFileMetadata
  validates_attachment_content_type :ingestedFileMetadata, content_type: ["/\Atext\/.*\Z/", "application/json"]
```
...
```
 def self.ingestFile(origionalFilename, fullpath)
    ingestedFile = File.open(fullpath)
    ingestedFileMetadataTmp = File.open("/tmp/#{origionalFilename}.json")
    fileNode = OriginalFile.merge(name: origionalFilename)
    puts fileNode.ingestedFileMetadata = ingestedFileMetadataTmp
    puts fileNode.save
end
```

```
josh@mindmapgraph:~/5$ rails c

Loading development environment (Rails 5.0.0.beta4)
2.2.4 :001 > Artefact.ingestFile("2015-12-22@195803.mp3", "/home/josh/notes_app/audiofiles/2015-12-22@195803.mp3")
 CYPHER 3ms MERGE ## Redacted
I, [2016-05-10T15:54:32.830645 #15487]  INFO -- : Command :: file -b --mime '/tmp/2015-12-22@195803.mp3.json'
#<File:0x00000003d62560>
I, [2016-05-10T15:54:32.840474 #15487]  INFO -- : Command :: file -b --mime '/tmp/e964c8b907052eb652a389c5cd4ccb6620160510-15487-1cnkais.json'
false
 => nil
```


And, for fun:
```
$ file -b --mime '/tmp/2015-12-22@195803.mp3.json'
text/plain; charset=us-ascii
```

(Excuse any typos)

### As someone who wants to do as much as possible before raising an issue, the fact that it doesn't work and instead has response of 'false' only when I do 'puts' is a big roadblock.
Note: This is not the first time I've run across something like this with Paperclip, and I'm sure there are other users who simply give up.
A quick basic troubleshooting wiki would go a long way.

**Comment by tute** [comment]
> A quick basic troubleshooting wiki would go a long way.

We are troubleshooting Rails at this point, I think.

What does `fileNode.errors` say when you run your snippet?

**Comment by Joshfindit** [comment]
Here are the errors:

`puts "fileNode.errors: #{fileNode.errors}"`

```
fileNode.errors: #<ActiveModel::Errors:0x000000035ce268>
```
`puts "fileNode.errors.messages: #{fileNode.errors.messages}"`

```
fileNode.errors.messages: {:ingestedFileMetadata_content_type=>["is invalid"], :ingestedFileMetadata=>["is invalid"]}
```
`puts "fileNode.errors.inspect: #{fileNode.errors.inspect}"`

```
fileNode.errors.inspect: #<ActiveModel::Errors:0x000000035ce268 @base= ...
..., @messages={:ingestedFileMetadata_content_type=>["is invalid"], :ingestedFileMetadata=>["is invalid"]}, @details={:ingestedFileMetadata_content_type=>[{:error=>:invalid, :content_type=>["/Atext/.*Z/", "application/json"], :types=>"/Atext/.*Z/, application/json"}], :ingestedFileMetadata=>[{:error=>"is invalid"}]}>
```

The uncertainty of 
> We are troubleshooting Rails at this point, I think.

lends more to my original request. I'm not sure about you, but I'd personally rather do the legwork to find the root cause, then report it at that stage (if it's a bug or usability issue)

**Comment by tute** [comment]
Your request is fair, but I find it hard to provide help to you because I feel you request it as if it was owed. A friendlier tone will help you be helped.

**Comment by Joshfindit** [comment]
@tute You have a point. I apologize.
I should have been up front about feeling sidetracked instead of putting on an unfriendly tone in response.

I started off knowing that I could get help for this particular issue, and saw the bigger problem of not having the tools necessary (as a possibly-typical user) to dig in and understand what's going on. I didn't want to get the minor problem solved, I wanted to address the documentation so that problems like this could solve themselves.

Heck, I'm even open to helping write the guide, but all I know to check is `fileNode.errors.*`, and it isn't enough in this case.

**Comment by duhaime** [comment]
Does the file save halt on the line that contains the `--mime` check (this seems to be the case from your snippet, but it's hard to tell)? If so, you might try adding the following to `/config/initializers/paperclip.rb` to turn off mimetype validations:

<pre><code>
# use client-side spoof detection, not paperclip's
require 'paperclip/media_type_spoof_detector'
module Paperclip
  class MediaTypeSpoofDetector
    def spoofed?
      false
    end
  end
end
</code></pre>

If this helps, then you have a mimetype hangup...

**Comment by sidraval** [comment]
Thank you for reporting this. Unfortunately, we will be deprecating Paperclip and therefore will not have the bandwidth to address this issue.
