### ISSUE TITLE
No long able to process image on Heroku - No longer recognising image dimensions

### ISSUE THREAD

**Issue by wee007** [thoughtbot/paperclip#2206]
Hi there,

Yesterday I found out that our image processing is no longer working when trying to upload an image to S3. However, it's working fine in my development environment just not in Staging and Production where our Rails app is hosted on Heroku. It was working in all environments last week.

I'm using paperclip 4.3.2 and s3_direct_upload 0.1.6 gems.

Basically I have a custom validation method that checks the minimum image dimensions requirement before uploading the image to S3.

Here's the custom validation method:

```ruby
  def check_dimensions
    if errors.empty?
      if CONTENT_TYPES.include? file_content_type
        if kind == KIND_LOGO && (width < 300 || height < 300)
          errors[:file] << I18n.t("image.error.dimensions_too_small", width: 300, height: 300)
        elsif kind == KIND_PRIMARY && (width < 640 || height < 480)
          errors[:file] << I18n.t("image.error.dimensions_too_small", width: 640, height: 480)
        elsif kind == KIND_GENERAL && (width < 640 || height < 225)
          errors[:file] << I18n.t("image.error.dimensions_too_small", width: 640, height: 225)
        end
      end
    end
  end
```

For some reason it's not meeting the minimum image dimension requirement so it's outputting the validation error message. After debugging the issue, the width and height attributes suddenly returns 0 instead of the actual image dimensions.

Please note again that it's working in my development environment but not in Staging and Production where our Rails app is hosted in Heroku. But it was working last week with no change. Not sure if it's a incompatibility issue.

Can anyone please shed some light?

Let me know if you require more details.

Thanks!

**Comment by tute** [comment]
Might this be related with https://devcenter.heroku.com/changelog-items/891?

**Comment by tute** [comment]
See also https://twitter.com/naps62/status/728954312882294784

**Comment by wee007** [comment]
Hi @tute thanks for sending the links. A great starting point! I will try to find out more details from Heroku as what's mentioned there doesn't really help to solve my problem.

**Comment by tute** [comment]
@wee007 did you solve your issue?

**Comment by wee007** [comment]
@tute not solved yet but used a different rubygem to get around the problem. i'll close the case for now.
