### ISSUE TITLE
NoMethodError for inexistent attribute on validates_attachment

### ISSUE THREAD

**Issue by parreirat** [thoughtbot/paperclip#2209]
Not sure if this should be checked against or not (for performance reasons or something?).

Basically there's no check being done against the attribute being validated in `validates_attachment`, and it blows up with a NoMethodError.

So, validating an inexistent attribute will blow up. (found this out because I forgot to change the attribute in :validates_attachment)

Migration:
```
t.attachment :image
```

Model:
```
has_attached_file :image
validates_attachment :inexistent_image, content_type: { content_type: /\Aimage\/.*\Z/ }
```

Error:

```
NoMethodError: undefined method `before_inexistent_image_post_process' for #<Class:0x007f9acacd1998>
Did you mean?  before_post_process
from /Users/tiagoparreira/.rvm/gems/ruby-2.3.0/gems/activerecord-4.2.6/lib/active_record/dynamic_matchers.rb:26:in `method_missing'
```

**Comment by tute** [comment]
Thanks for reporting. This is related with https://github.com/thoughtbot/paperclip/issues/1605.

**Comment by parreirat** [comment]
You are welcome, thanks for doing open source. :)

**Comment by tute** [comment]
Closing in favor of #1605. Thanks for reporting!
