### ISSUE TITLE
Can I update attached file with paperclip?

### ISSUE THREAD

**Issue by tkaneda** [thoughtbot/paperclip#2211]
I have one question.
I am using paperclip with ruby on rails.
Now I have a model which has attached image file using paperclip
After creating attached image and saved, I want to update image file.(resize, rotate, and so on.)
I implemented the codes which edit the image file on javascript.
But I dont know how to replace this edited image with the file stored on the server.
Would you tell me how  to replace the file via paperclip ?

thanks.
regards.

**Comment by tute** [comment]
Does this work for you? http://stackoverflow.com/a/17251781/356060

**Comment by tkaneda** [comment]
Attached file are editted on html5.canvas and export via toDataURL().
I want to stored the export data (Base64 encoded) and replace via paperclip.

**Comment by tkaneda** [comment]
I found a article and worked fine.

https://gist.github.com/WizardOfOgz/1012107

thanks all.
