### ISSUE TITLE
original_filename should follow Content-Disposition

### ISSUE THREAD

**Issue by bbtfr** [thoughtbot/paperclip#2212]
Here: https://github.com/thoughtbot/paperclip/blob/master/lib/paperclip/io_adapters/uri_adapter.rb#L21

I think if we download a file from web, and there is a filename set in `Content-Disposition` in http response, original_filename should follow it.

My case is, I have a url like `http://example.com/get?token=xxxx`, if I set this string directly to attachment, all my attachments are named `get`, without extension, but it does have a filename in `Content-Disposition`. So I have to create a tmpfile manually and to set the filename, because files without extension are unreadable on Windows.

**Comment by tute** [comment]
Yep! We are fixing this in https://github.com/thoughtbot/paperclip/pull/2210. Thanks for reporting!

**Comment by bbtfr** [comment]
Thanks, just noticed that there is already a PR for it.
