### ISSUE TITLE
validates_attachment_content_type wrong error

### ISSUE THREAD

**Issue by kaluznyo** [thoughtbot/paperclip#2213]
This file raise error "content type not valid" 

I validate my content type like this

`validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
`
But it's an image and 
`file -k -r catalog_det1_7702827.jpg give : catalog_det1_7702827.jpg: JPEG image data, EXIF standard
`
Another good image send : JFIF standard 1.01 instead of EXIF standard
What's wrong ?
![catalog_det1_7702827](https://cloud.githubusercontent.com/assets/372462/15360912/d07fff28-1d0f-11e6-9649-1367726c898b.jpg)

I use paperclip 4.3.6

**Comment by sidraval** [comment]
Thank you for reporting this. Unfortunately, we will be deprecating Paperclip and therefore will not have the bandwidth to address this issue.
