### ISSUE TITLE
Thumbs not working in Stage

### ISSUE THREAD

**Issue by mariohmol** [thoughtbot/paperclip#2214]
Hi there!

I have an app using paperclip that have a style to create thumbs. (paperclip 3.5.4)

I have a version in production that works good!

In same server I have a stage app that for some cases, it do not generates the syles (thumbs). 

Using the same image local works good!

In log there is no errors at all.

That so weird.. any ideias what I can do to find out the problem, with no logs i'm lost!

bests

**Comment by mariohmol** [comment]
Update: I changed tha path of stage to be inside of /home/user .

The thing is.. if is a permission problem, why this creates thumbs for some images (png files worked) and for others (jpg) no?

**Comment by tute** [comment]
@mariohmol is this still an issue for you? How can we reproduce it? Thanks!

**Comment by mariohmol** [comment]
Sorry, better closing, i dont know anymore..
