### ISSUE TITLE
Question: How does url generation algorithm work in Paperclip?

### ISSUE THREAD

**Issue by liuzhen2008** [thoughtbot/paperclip#2215]
I find myself in a situation where I need to run the paper clip hashing algorithm outside of the ruby server.

So I am trying to replicate hashing result.

Say I have a file with file name "abc.jpg", :hash_digest: "SHA1", and :hash_secret: "some_secret". How does paperclip calculate a hashed value for the file?

This is what my paperclip configuration looks like

```
  config.paperclip_defaults = {
    :hash_secret => "some_secret",
    :storage => :filesystem,
    :url => "/assets/:class/:hash/:style.:extension",
    :path => ":rails_root/public/assets/:class/:hash/:style.:extension"
  }

```

**Comment by tute** [comment]
I suggest that you ask about it in https://stackoverflow.com/questions/tagged/paperclip, which will get attention from more people than in this issue tracker.

Sorry we don't have the time now to help you with this question, and thanks!

**Comment by emaillenin** [comment]
I looked at the code and found [this logic](https://github.com/thoughtbot/paperclip/blob/90f9121a18df25bc3ef948356450ce19fbe1da83/lib/paperclip/attachment.rb#L329):

    OpenSSL::HMAC.hexdigest(OpenSSL::Digest.const_get('SHA1').new, <hash_secret>, 'users/attachment_name/user_id/style/unix_time_of_attachment_updated')

An example:

     OpenSSL::HMAC.hexdigest(OpenSSL::Digest.const_get('SHA1').new, 'abcdefgh', 'users/pictures/134/original/1542406575')

Hash secret is defined per attachment on your model or globally.

Hope it will be helpful to someone.
