### ISSUE TITLE
reprocess! images from S3 results in Paperclip::Errors::NotIdentifiedByImageMagickError

### ISSUE THREAD

**Issue by calvinl** [thoughtbot/paperclip#2217]
I'm trying to reprocess some images I've stored in S3, but it seems like Paperclip is trying to `identify` the wrong image:

First, it copies the file from S3 to the local directory:

```
[paperclip] copying spree/images/attachments/000/009/139/original/my_image.jpg to local file /tmp/0b6c0b92ccb215efb2c9fe95370bfb2720160527-230-1j11ysu.jpg
```

Then, it runs the `identify` command on the S3 key, not the file in /tmp:

```
Command :: identify -format '%wx%h,%[exif:orientation]' 'spree/images/attachments/000/009/139/product/FRAM_LeGarcon_Blanc_021.jpg[0]' 2>/dev/null
Paperclip::Errors::NotIdentifiedByImageMagickError: Paperclip::Errors::NotIdentifiedByImageMagickError
```

Here's my paperclip config:

```
  config.paperclip_defaults = {
    storage: :s3,
    s3_credentials: {
      bucket: ENV['S3_BUCKET_NAME'],
      access_key_id: ENV['AWS_ACCESS_KEY_ID'],
      secret_access_key: ENV['AWS_SECRET_ACCESS_KEY']
    },
    s3_headers: { 'Cache-Control': 'max-age=31557600' },
    s3_protocol: :https,
    url: ':s3_alias_url',
    s3_host_alias: ENV['CDN_URL'],
    path: ':class/:attachment/:id_partition/:style/:filename'
  }
```

Has anyone come across this? Or is there a config issue I'm not aware of?

**Comment by blakeage** [comment]
I have exactly the same issue:

paperclip v4.3.6
papercrop v0.3.0
aws-sdk v1.66.0
Rails 4.0.0
Ruby 2.0.0p643

Here is what PaperClip spits out:

    Command :: PATH=/usr/local/bin/:$PATH; file -b --mime '/tmp/3aa49ec6bfc910647fa1c5a013e48eef20160601-84889-7sthau.png'
    Command :: PATH=/usr/local/bin/:$PATH; identify -format '%wx%h,%[exif:orientation]' '/tmp/3aa49ec6bfc910647fa1c5a013e48eef20160601-84889-16f07ub.png[0]' 2>/dev/null
    Command :: PATH=/usr/local/bin/:$PATH; identify -format %m '/tmp/3aa49ec6bfc910647fa1c5a013e48eef20160601-84889-16f07ub.png[0]'
    Command :: PATH=/usr/local/bin/:$PATH; convert '/tmp/3aa49ec6bfc910647fa1c5a013e48eef20160601-84889-16f07ub.png[0]' -auto-orient -resize "50x" -crop "50x50+0+0" +repage '/tmp/439a894f41c109393f3744e6b1ae28d520160601-84889-lhxxh6'
    Command :: PATH=/usr/local/bin/:$PATH; identify -format '%wx%h,%[exif:orientation]' '/tmp/3aa49ec6bfc910647fa1c5a013e48eef20160601-84889-16f07ub.png[0]' 2>/dev/null
    Command :: PATH=/usr/local/bin/:$PATH; identify -format %m '/tmp/3aa49ec6bfc910647fa1c5a013e48eef20160601-84889-16f07ub.png[0]'
    Command :: PATH=/usr/local/bin/:$PATH; convert '/tmp/3aa49ec6bfc910647fa1c5a013e48eef20160601-84889-16f07ub.png[0]' -auto-orient -resize "100x" -crop "100x100+0+0" +repage '/tmp/439a894f41c109393f3744e6b1ae28d520160601-84889-4sz5j2'
    Command :: PATH=/usr/local/bin/:$PATH; identify -format '%wx%h,%[exif:orientation]' '/tmp/3aa49ec6bfc910647fa1c5a013e48eef20160601-84889-16f07ub.png[0]' 2>/dev/null
    Command :: PATH=/usr/local/bin/:$PATH; identify -format %m '/tmp/3aa49ec6bfc910647fa1c5a013e48eef20160601-84889-16f07ub.png[0]'
    Command :: PATH=/usr/local/bin/:$PATH; convert '/tmp/3aa49ec6bfc910647fa1c5a013e48eef20160601-84889-16f07ub.png[0]' -auto-orient -resize "220x" -crop "220x220+0+0" +repage '/tmp/439a894f41c109393f3744e6b1ae28d520160601-84889-1l8qsg5'
    Command :: PATH=/usr/local/bin/:$PATH; file -b --mime '/tmp/3aa49ec6bfc910647fa1c5a013e48eef20160601-84889-14dl5vc.png'
    (0.4ms)  ROLLBACK
    Command :: PATH=/usr/local/bin/:$PATH; identify -format '%wx%h,%[exif:orientation]' 'https://XXX-development-bucket-us.s3.amazonaws.com/profiles/profile_images/1/original/blake.png?1464815333[0]' 2>/dev/null

Stack trace:

    Paperclip::Errors::NotIdentifiedByImageMagickError -   
    Paperclip::Errors::NotIdentifiedByImageMagickError:
    paperclip (4.3.6) lib/paperclip/geometry_detector_factory.rb:10:in `make'
    paperclip (4.3.6) lib/paperclip/geometry.rb:26:in `from_file'
    papercrop (0.3.0) lib/papercrop/model_extension.rb:95:in `image_geometry'
    papercrop (0.3.0) lib/papercrop/helpers.rb:45:in `cropbox'

**Comment by cwise** [comment]
I'm seeing this as well - it's the `image_geometry` call in papercrop I think. Notice that you are getting an array index on the file name in the processor? Looking into it.

**Comment by cwise** [comment]
Clearly I don't understand the `#{file}[0]` part of `geometry_string` as it has been there forever.

**Comment by cwise** [comment]
This is the underlying issue:

https://github.com/thoughtbot/paperclip/issues/2198

**Comment by ianpurvis** [comment]
> Clearly I don't understand the #{file}[0] part of geometry_string as it has been there forever.

I was able to find something in the ImageMagick docs-

http://www.imagemagick.org/script/command-line-processing.php

> Selecting Frames

> Some images formats contain more than one image frame. Perhaps you only want the first image, or the last, or some number of images in-between. You can specify which image frames to read by appending the image filename with the frame range enclosed in brackets. Here our image (an animated GIF) contains more than one frame but we only want the first:



My best guess is that `identify` dropped support for frames?

**Comment by ianpurvis** [comment]
I may have a different issue than you guys, I'm actually getting `NotIdentifiedByImageMagickError` when running in development without s3. That said, when I isolated the identify command from my logs and ran it directly, stderr told me:

```
identify -format '%wx%h,%[exif:orientation]' '/var/folders/zp/dsbgc8v16zz0s4tjkfbkytwc0000gn/T/8bb9aaebf58ab32612f7a64ab273da8a20160605-13366-1wrj0qw.png[0]'
identify: unable to open image `/var/folders/zp/dsbgc8v16zz0s4tjkfbkytwc0000gn/T/8bb9aaebf58ab32612f7a64ab273da8a20160605-13366-1wrj0qw.png[0]': No such file or directory @ error/blob.c/OpenBlob/2705.
identify: unable to open file `/var/folders/zp/dsbgc8v16zz0s4tjkfbkytwc0000gn/T/8bb9aaebf58ab32612f7a64ab273da8a20160605-13366-1wrj0qw.png[0]' @ error/png.c/ReadPNGImage/3921.
```

Removing the "[0]" fixed the command, so for what it's worth, I reported it to ImageMagick... https://github.com/ImageMagick/ImageMagick/issues/214

**Comment by blakeage** [comment]
@cwise I don't think the #2198 issue is the problem for me.  They closed that issue, because someone proposed a fix, but his suggestion, which was to uncomment an 'https' setting in the delegates.xml file, was not applicable in the Homebrew IM I had installed (it's not commented out for me).  Also, there was some discussion #2223 that the IM 6.9.4-8 update from Homebrew might fix it, but after upgrading that, I still have the same issue.

**Comment by fwl** [comment]
@calvinl did you find a solution to this? If yes, would you mind sharing it here?

**Comment by sidraval** [comment]
Thank you for reporting this. Unfortunately, we will be deprecating Paperclip and therefore will not have the bandwidth to address this issue.
