### ISSUE TITLE
Issues with content type validation and images in twitter open graph data

### ISSUE THREAD

**Issue by Aqualon** [thoughtbot/paperclip#2220]
Hi, we use paperclip to fetch open graph images from links our users want to share. 

For validation we have configured our model like this:
```validates_attachment_content_type :attachment, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]```

This usually works fine, but fails for twitter, since they have weird line endings like `https://pbs.twimg.com/media/Cj2pTzMUgAEzXfq.png:large` (the extra :large at the end)

The resulting error is this:

```
Command :: identify -format '%wx%h,%[exif:orientation]' '/tmp/79c02bb71e5d7984e208022c564c2f0920160602-62969-e0obaz[0]' 2>/dev/null
Command :: identify -format %m '/tmp/79c02bb71e5d7984e208022c564c2f0920160602-62969-e0obaz[0]'
Command :: convert '/tmp/79c02bb71e5d7984e208022c564c2f0920160602-62969-e0obaz[0]' -auto-orient -resize "128x128" -strip '/tmp/3aa37e0137362fd1df1bdbd234b8fae520160602-62969-11u251d'
Command :: file -b --mime '/tmp/12d6d6ad4222ea5609f1003d03ecb9ec20160602-62969-1y5h3tm.png_large'

[paperclip] Content Type Spoof: Filename Cj2pTzMUgAEzXfq.png:large (image/png from Headers, [] from Extension), content type discovered from file command: image/png. See documentation to allow this combination.
```

For jpgs we worked around it by having an initializer with `MIME::Types["image/jpeg"].first.add_extensions "jpg:large"` in it.

We also could add the same for png, but we also found other pages, that return images but have strange URL endings like `.jpg#31431314`. So the add_extensions approach is kind of limited.

Is there a general way to only validate the real content type inside the image and do not care about the file url at all?

**Comment by tute** [comment]
The issue you describe seems very specific to your code. I suggest that you ask about it in https://stackoverflow.com/questions/tagged/paperclip, which will get attention from more people than in this issue tracker.

Sorry we don't have the time now to help you with this question, and thanks! ❤️

**Comment by Aqualon** [comment]
Actually it seems to be the same issue as described in https://github.com/thoughtbot/paperclip/issues/1470.
