### ISSUE TITLE
Is there a method to copy/move attachments from

### ISSUE THREAD

**Issue by aliuk2012** [thoughtbot/paperclip#2224]
Could someone take a look at a query I posted on Stackoverflow..

http://stackoverflow.com/questions/37747295/can-you-copy-move-an-uploaded-file-from-one-model-to-another-model

Thank you

**Comment by tute** [comment]
@aliuk2012 StackOverflow is the right venue for this kind of questions, as we use the issue tracker for bug reports. Anyways, did you move past this issue you were having? Thanks!
