### ISSUE TITLE
Paperclip+Spring = Could not find climate_control-0.0.3 in any of the sources

### ISSUE THREAD

**Issue by markokacanski** [thoughtbot/paperclip#2226]
Hi all

I started a new Rails 4.2.6 app, and added paperclip to it. After that, I'm unable to run generators or access console. The error message that appears is

```
  Could not find climate_control-0.0.3 in any of the sources
  Run `bundle install` to install missing gems.
```
I verified in the bundle install output that climate_control-0.0.3 is indeed being used.

If I remove paperclip everything works fine. If I leave paperclip but remove spring from the gemfile everything works fine as well. The problem is also solved by disabling spring temporarily with the environmental variable.

Anyone else facing this? Is this a bug in paperclip or should I take this issue to the spring repo?

**Comment by tute** [comment]
I've never seen this. Can you please paste your Gemfile and Gemfile.lock? Thanks!

**Comment by markokacanski** [comment]
It's just a default Rails 4.2.6 Gemfile with 
`gem "paperclip", "~> 5.0.0.beta1"`
added in.

It could be RVMs fault, I'm researching that angle, will post results

**Comment by tute** [comment]
Closing this issue, as paperclip 5.0 seems to be working fine. If this is still an issue for you, let me know and we continue triaging this. Thank you!

**Comment by SergeyMell** [comment]
@tute, the problem still occurs with spring v 2.0.0 and paperclip 5.1.0, 5.0.0 and 3.5.2 (these are just versions I've tested with). When I moved to spring 1.7.1 everything seems to be OK.

**Comment by agueroveraalvaro** [comment]
Please put in your gem file :
`gem 'paperclip', '~> 4.1'`
the problem occurs with versions :+1:

**Comment by pedro-stanaka** [comment]
I am having the same behavior using an RoR 5 application in API-only mode. The code can be found here: https://github.com/pedro-stanaka/phi_portal/tree/feature/crud_posts. Rails version 5.1, with Spring 2 and paperclip 5.1. I have tried 5.0 and 5.1 but in both of them I can't use any generate commands.
