### ISSUE TITLE
uninitialized constant Paperclip::Storage::S3::Aws

### ISSUE THREAD

**Issue by SylarRuby** [thoughtbot/paperclip#2228]
```
gem "paperclip", "~> 5.0.0.beta2"
gem 'aws-sdk', '< 2.0'
```

Downgraded to paperclip 4.3.6 and all is well.

**Comment by tute** [comment]
Thanks for reporting. v5 indeed drops support of AWS v1, and only uses v2. See https://github.com/thoughtbot/paperclip/blob/master/NEWS. Thanks!
