### ISSUE TITLE
contradictory wiki / readme about preprocessing invalid too-large files

### ISSUE THREAD

**Issue by nruth** [thoughtbot/paperclip#2236]
https://github.com/thoughtbot/paperclip#validations says

> NOTE: Post-processing will not even start if the attachment is not valid according to the validations. Your callbacks and processors will only be called with valid attachments.

https://github.com/thoughtbot/paperclip/wiki/Thumbnail-Generation#prevent-thumbnail-generation-for-invalid-uploads says

> h2. Prevent thumbnail generation for invalid uploads
> 
> If you upload a file that is too large or otherwise doesn't fit the requirements, paperclip still processes all styles during assignment before the model object is recognized as invalid during @#save@. This can be a huge waste of time if you're working with big files and/or many styles.
> 
> You can use a @before_post_process@ filter to avoid post processing. For example, if your attribute is named @image@, and you have a restriction on the file size, the filter could look like this:
> 
> ``` ruby
> before_post_process :check_file_size
> def check_file_size
>   valid?
>   errors[:image_file_size].blank?
> end
> ```

Which is correct?
Is the wiki text now outdated and deletable?

**Comment by tute** [comment]
The README is incorrect. See PR: https://github.com/thoughtbot/paperclip/pull/2204. Thanks for bringing this up.

**Comment by nruth** [comment]
OK, what can we do to close this issue? Will that PR fix the inconsistency, or is it worth changing the text in the readme?

**Comment by tute** [comment]
Just commented on the PR: adjusting the README to describe current behavior is a first step, indeed! https://github.com/thoughtbot/paperclip/pull/2204#issuecomment-229913358

Thank you for reporting.

**Comment by sidraval** [comment]
Open PR that will be merged, thanks for the issue.

**Comment by ssinghi** [comment]
This has been fixed at https://github.com/kreeti/paperclip/commits/master.
