### ISSUE TITLE
Issue with Rails 5 configuration

### ISSUE THREAD

**Issue by lookitsatravis** [thoughtbot/paperclip#2240]
Hello!

I've got an issue that came up following an upgrade to Rails 5. Rails 5's new `config/application.rb` says that changes to configuration should be placed inside initializers.

``` rb
    # Settings in config/environments/* take precedence over those specified here.
    # Application configuration should go into files in config/initializers
    # -- all .rb files in that directory are automatically loaded.
```

So, I moved my config for Paperclip into `config/initializers/paperclip.rb`:

``` rb
Rails.application.config.paperclip_defaults = {
  storage: :s3,
  s3_credentials: {
    bucket: ENV['S3_BUCKET_NAME'],
    access_key_id: ENV['AWS_ACCESS_KEY_ID'],
    secret_access_key: ENV['AWS_SECRET_ACCESS_KEY']
  },
  s3_protocol: :https,
  s3_region: 'us-east-1'
 }
```

However, my models do not respect those settings. All of them were set to filesystem storage which broke the URLs for each attachment. Switching it back into the application config fixed the issue. I'm not sure why setting them in an initializer would break the setup, but I wanted to bring it to your attention. Thanks!

**Comment by tute** [comment]
This configuration typically belongs in the environment files, as they may differ. If they don't, I leave it in `config/application.rb`. I don't see why the suggestion in that comment.

Does this solve your issue?

**Comment by lookitsatravis** [comment]
@tute yes it does solve the issue. I was simply bringing it to your attention because the verbiage in the Rails defaults is confusing. Maybe worth an update to the readme or wiki to make sure that `paperclip_defaults` is not set in an initializer as suggested by Rails 5? I am not sure, but I figured I wouldn't be the only one who tried it. Thanks!

**Comment by maurcarvalho** [comment]
Similar case here :( 
Like @lookitsatravis has said, if you try to set paperclip properties at /initializers/ as recommend by Rails 5 for application properties, it doesn't work. Paperclip just uses the filesystem totally ignoring those properties. Although setting it using Paperclip::Attachment.default_options will work as expected at /config/initializers/paperclip.rb

i.e:
```ruby
Paperclip::Attachment.default_options[:storage] = :s3
Paperclip::Attachment.default_options[:bucket] = ENV["AWS_S3_BUCKET"]
Paperclip::Attachment.default_options[:s3_region] = ENV["AWS_REGION"]
Paperclip::Attachment.default_options[:s3_permissions]  = :private
Paperclip::Attachment.default_options[:s3_credentials]  = {
  s3_host_name: ENV["AWS_S3_HOST_NAME"],
  access_key_id: ENV["AWS_ACCESS_KEY_ID"],
  secret_access_key: ENV["AWS_SECRET_ACCESS_KEY"]
}`

I don't know if it's the best approach but I decided to maintain like this for now instead of writing it down using config.paperclip_defaults at application.rb.

**Comment by zharikovpro** [comment]
@maurcarvalho you can type less like this:

```
Paperclip::Attachment.default_options.update({
    storage: :s3,
    s3_protocol: 'https',

    s3_credentials: {
        s3_region: ENV.fetch('AWS_REGION'),
        bucket: ENV.fetch('AWS_BUCKET'),
        access_key_id: ENV.fetch('AWS_ACCESS_KEY_ID'),
        secret_access_key: ENV.fetch('AWS_SECRET_ACCESS_KEY')
    }
})
```

**Comment by paulmwatson** [comment]
So @zharikovpro's subtle but hugely important difference worked for me. `Paperclip::Attachment.default_options.update({` vs. `Rails.application.config.paperclip_defaults = {`

**Comment by sidraval** [comment]
Looks like y'all found a workaround, closing.
