### ISSUE TITLE
Can't upload files due to spoofing error on Windows

### ISSUE THREAD

**Issue by tcgumus** [thoughtbot/paperclip#2241]
Hello,
I'm using Rails 4.2.5.1 on windows 10 with ruby 2.1.8p440. I made the simple blog example on RoR training homepage. I wanted to add picture to my blog posts. I used latest paperclip (paperclip 5.0.0). When i try to upload file it gives me this error:

    `Command :: SET PATH=C:\Program Files\ImageMagick-7.0.2-Q16; C:\Program Files (x86)\GnuWin32\bin;%PATH% & file -b --mime            "C:/Users/tgumus/AppData/Local/Temp/561dc621f913ff416b348cf2a6c410a620160703-5964-tl8mjj.jpg"
     [paperclip] Content Type Spoof: Filename 876f0725-508d-430c-a638-abfeb8e7914e.jpg (image/jpeg from Headers, ["image/jpeg"] from Extension), content type discovered from file command: . See documentation to allow this combination.
      (0.0ms)  begin transaction
      Command :: SET PATH=C:\Program Files\ImageMagick-7.0.2-Q16; C:\Program Files (x86)\GnuWin32\bin;C:\Program Files\ImageMagick-7.0.2-Q16; C:\Program Files (x86)\GnuWin32\bin;%PATH% & file -b --mime "C:/Users/tgumus/AppData/Local/Temp/561dc621f913ff416b348cf2a6c410a620160703-5964-180jfb2.jpg"
      [paperclip] Content Type Spoof: Filename 876f0725-508d-430c-a638-abfeb8e7914e.jpg (image/jpeg from Headers, ["image/jpeg"] from Extension), content type discovered from file command: . See documentation to allow this combination.
      (0.0ms)  rollback transaction
      Redirected to http://localhost:3000/articles
      Completed 302 Found in 146ms (ActiveRecord: 0.0ms)`

I added the environmental variables to development.rb and test both of them. They seems to work alone. I just copied the codes of the documentation. I couldn't find a solution to this. I deleted and installed imagemagic and file.exe. I installed static version of Imagemagick.

My **development.rb** file looks like this
        
    Rails.application.configure do
    Paperclip.options[:command_path] = 'C:\Program Files\ImageMagick-7.0.2-Q16; C:\Program Files (x86)\GnuWin32\bin'

My modal.rb(**article.rb**) file looks like this:

	has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/assets/images/:style/missing.png"
  	validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/

As you can see it doesn't upload any file, doesn't create an article and goes back to my homepage. 
Can you please help? What am i missing?

Thank you

**Comment by tute** [comment]
This is a tricky problem, and we don't have a good answer for it, yet.

Please refer to the discussion around your issue in the original issue: https://github.com/thoughtbot/paperclip/issues/1924#issuecomment-207420954.

Thanks!

**Comment by maxence33** [comment]
Exact same problem here. With a forked Repo from which original Windows running computer has exact same configuration. 
Definitely a set-up thing but can't find the problem to it

**Comment by Sprachprofi** [comment]
Same problem here. Also, the recommended workarounds (do_not_validate_attachment or monkeypatch the spoofer) do not work.

**Comment by maxence33** [comment]
Are you developping Under Windows ? I think I just added an environment variable to GnuWin32 which was missing. Setting-up Rails and other dependencies under Windows is really painful..

**Comment by tcgumus** [comment]
For the people still having the same problem;
It is about imagemagick and permission problem. When you gave full permission, it should work. I didn't want to work on windows permission and switched to Ubuntu. It worked in the first try.

**Comment by nikhil2593** [comment]
For windows, one has to install **file** as that is not installed by default with OS, then add file.exe 
path to environment variable or add `Paperclip.options[:command_path] = 'path to file.exe'` to your development/production.rb

**Comment by euqueme** [comment]
> For windows, one has to install **file** as that is not installed by default with OS, then add file.exe
> path to environment variable or add `Paperclip.options[:command_path] = 'path to file.exe'` to your development/production.rb

What is **file**?
