### ISSUE TITLE
Consider adding link for https://github.com/supportify/paperclip-azure for using Paperclip with Azure

### ISSUE THREAD

**Issue by preetpalS** [thoughtbot/paperclip#2242]
I am currently using this gem with Paperclip for storing images on Azure. The gem uses the [Microsoft Azure SDK for Ruby](https://github.com/Azure/azure-sdk-for-ruby) internally. Its link could be included in the README of this repository beside the links for the paperclip-azure-storage gem and the paperclip-dropbox gem (this particular gem's Github repository says that it is obsolete by the way) under the storage heading.

**Comment by tute** [comment]
Sure! Want to send a PR? Thank you!
