### ISSUE TITLE
Support for Aws::Credentials as a credential instead of a hash

### ISSUE THREAD

**Issue by jufemaiz** [thoughtbot/paperclip#2247]
At this stage, the :s3_credentials option for Paperclip::Storage::S3 does not appear to support the use of an Aws::Credentials object, requiring the hash to be generated from the credential object.

Obviously this would also require changes with respect to the bucket (which isn't strictly credentials related, and would appear to make more sense to be a separate as per https://github.com/thoughtbot/paperclip/blob/95acf3b898bd782f4429d42fd2d8812505390328/lib/paperclip/storage/s3.rb#L61-L65)

Will look at changes & pull request if there's support for allowing an Aws::Credentials object.

The big reason is that we are using Aws::InstanceProfileCredentials instead of ENV variables.

**Comment by sidraval** [comment]
Thank you for reporting this. Unfortunately, we will be deprecating Paperclip and therefore will not have the bandwidth to address this issue.
