### ISSUE TITLE
Use base_class for STI

### ISSUE THREAD

**Issue by tangopium** [thoughtbot/paperclip#2248]
Hi, there is an important issue with STI models. Paperclip uses the name of the actual (derived) class. For example:

```ruby
class Animal < ActiveRecord::Base
    has_attached_file :image
end
```

```ruby
class Dog < Animal
end
```

```ruby
class Cat < Animal
end
```

Paperclip will store the image for a Dog in `public/system/dogs/image/000/000/001/original/my_dog.jpg`. This seems to be ok but becomes a problem, if for some reason I need to change the type (`dog.becomes!(Cat).save`). The image will than still reside in the same place but will not be found anymore because Paperclip expects it to be in `public/system/cats/image/000/000/001/original/my_dog.jpg`

I would therefore propose a simple fix: use the `base_class` instead the class itself.

**Comment by tangopium** [comment]
The problem I see at the moment will be, that this change would break many existing installations/paths

**Comment by tute** [comment]
This is not a bug. When you change types for an object, you should move the assets. Thanks!
