### ISSUE TITLE
invalid configuration option factory_girl lint action

### ISSUE THREAD

**Issue by jhblacklock** [thoughtbot/paperclip#2249]
After upgrading to 5.0.0 my factory_girl lint fails with:

```
invalid configuration option `:bucket' (ArgumentError)
```

rails (4.2.7)
factory_girl (4.7.0)
factory_girl_rails (4.7.0)

My paperclip initializer is:

```ruby
Paperclip::Attachment.default_options.merge!(
  storage: :s3,
  s3_credentials: { access_key_id: ENV.fetch('AWS_ACCESS_KEY_ID'),
                    secret_access_key: ENV.fetch('AWS_SECRET_ACCESS_KEY'),
                    bucket: ENV.fetch('S3_BUCKET_NAME') }
)
```

dev server works fine and AR objects load fine in console. Not sure if it's a factory_girl issue or paperclip... or something else entirely.  I'll keep digging.

**Comment by jhblacklock** [comment]
moving to aws-sdk-v1 fixed the issue.

gem 'aws-sdk', '<2.0'

**Comment by tute** [comment]
I don't think that paperclip 5 will work with AWS SDK <2.

The issue must lie someplace else, I don't know exactly where yet.

**Comment by jhblacklock** [comment]
Thanks @tute.  Went ahead and downgraded to 4.3.6 for now.

**Comment by tute** [comment]
I'd like to know if it's a bug on either library, or where does the error come from. Can you paste the contents of the factories that fail? Thanks!

**Comment by jhblacklock** [comment]
I figured the issue was something I wasn't seeing in the trace.  Turns out, it was AWS 2.0 removing the :bucket option in their config and not paperclip.

#https://github.com/aws/aws-sdk-ruby/issues/1247

Linting works fine now.

Thanks!

**Comment by tute** [comment]
Glad it works!
