### ISSUE TITLE
Need help to compress images

### ISSUE THREAD

**Issue by caiammm** [thoughtbot/paperclip#2251]
I'm trying to do a better compression in our images and change them to PNG format before our users upload them. 
I read some things... 
http://www.imagemagick.org/script/command-line-options.php#quality in this post I saw some parameters (png:compression-...) and tried to use, but I'm always having errors.

and saw some gems
https://github.com/janfoeh/paperclip-optimizer
https://github.com/emrekutlu/paperclip-compression

but i'm not making any progress... Can someone help me?

this is our code now
```
has_attached_file :test_logo,
                    path:            '/logos/test/:style/:id/:filename',
                    styles:          { small: '100x50>', medium: '170x70>', facebook: '200x200' , large: '240x120>', extra_large: '600x600>' },
                    storage:         :s3,
                    s3_protocol:     :https,
                    default_url:     :default_colored_logo_url,
                    escape_url:      false,
                    s3_credentials:  Settings.s3,
                    s3_host_alias:   Settings.cloudfront.path,
                    url:             ':s3_alias_url',
                    convert_options: { facebook: ['-background', 'white', '-gravity', 'center', '-extent', '232x232', '-quality', '60', '-strip'],
                                       small: '-quality 40 -strip',
                                       medium: '-quality 40 -strip',
                                       large: '-quality 70 -strip',
                                       extra_large: '-quality 80 -strip' }
```

**Comment by tute** [comment]
I suggest that you ask about it in https://stackoverflow.com/questions/tagged/paperclip, where you will get attention from more people than in this issue tracker. Sorry we don't have the time now to help you with this question. Thanks!
