### ISSUE TITLE
Confused by fingerprint behavior of paperclip attachments

### ISSUE THREAD

**Issue by andreiglingeanu** [thoughtbot/paperclip#2252]
Looking at the docs, I'm seeing that:

> An MD5 checksum of the _**original**_ file assigned will be placed in the model if it has an attribute named fingerprint.

I'm assuming that once this fingerprint is assigned for the model -- it'll never change, no matter what changes I'll apply to the attachment later, am I wrong?

The thing is that I'm using this field in order to validate uniqueness of my models -- which doesn't behave correctly because of the fact that fingerprint is changed during the lifetime of the instance.

My validation looks like this:

```ruby
validates :photo_fingerprint, uniqueness: {message: 'duplicate'}, allow_nil: true
```

Is this a correct thing to do? Will this even ensure file uniqueness correctly? After noticing [this](https://github.com/thoughtbot/paperclip/blob/master/lib/paperclip/io_adapters/abstract_adapter.rb#L12) line, I'm guessing, is the fingerprint generated based on the original `filename`?

I'm thinking about implementing the hashing by myself in a separate DB field -- which won't change, no matter what.

Please, enlighten me.

**Comment by tute** [comment]
Adding a separate column makes sense, and that solution is described in http://stackoverflow.com/q/2458067. Thanks!
