### ISSUE TITLE
HttpUrlProxyAdapter chokes on already encoded URLs

### ISSUE THREAD

**Issue by csuhta** [thoughtbot/paperclip#2253]
I believe [this change](https://github.com/thoughtbot/paperclip/commit/8ab50b9194185eec8453283f195b4e4c2def3fc7#diff-968b30a7d52083bb1326639b64926d85) has caused a regression in URL handling in HttpUrlProxyAdapter. It's currently preventing you from attaching files that have URLs that are **already** encoded.

Here's an example link to an image file on GitHub: 

```
https://cloud.githubusercontent.com/assets/769083/16889697/434b0aa6-4ab6-11e6-9bc3-4e74a3ac7f9c.png
```

Here's a different way to write that link (with two encodeded forward slashes): 

```
https://cloud.githubusercontent.com/assets/769083%2F16889697%2F434b0aa6-4ab6-11e6-9bc3-4e74a3ac7f9c.png
```

And here's a reproduction script:

``` ruby
require "active_support/all"
require "paperclip"

RUBY_VERSION
#=> "2.3.1"

Paperclip::VERSION 
#=> 5.0.0

# Regular URL
Paperclip::HttpUrlProxyAdapter.new("https://cloud.githubusercontent.com/assets/769083/16889697/434b0aa6-4ab6-11e6-9bc3-4e74a3ac7f9c.png")
#=> Paperclip::HttpUrlProxyAdapter: 434b0aa6-4ab6-11e6-9bc3-4e74a3ac7f9c.png

# Encoded slashes
Kernel.open("https://cloud.githubusercontent.com/assets/769083%2F16889697%2F434b0aa6-4ab6-11e6-9bc3-4e74a3ac7f9c.png").length
#=> 140806

# Encoded slashes
Paperclip::HttpUrlProxyAdapter.new("https://cloud.githubusercontent.com/assets/769083%2F16889697%2F434b0aa6-4ab6-11e6-9bc3-4e74a3ac7f9c.png")
# => OpenURI::HTTPError: 403 Forbidden
# => from /Users/You/.rubies/ruby-2.3.1/lib/ruby/2.3.0/open-uri.rb:359:in `open_http'
# => from /Users/You/.rubies/ruby-2.3.1/lib/ruby/2.3.0/open-uri.rb:737:in `buffer_open'
# => from /Users/You/.rubies/ruby-2.3.1/lib/ruby/2.3.0/open-uri.rb:212:in `block in open_loop'
# => from /Users/You/.rubies/ruby-2.3.1/lib/ruby/2.3.0/open-uri.rb:210:in `catch'
# => from /Users/You/.rubies/ruby-2.3.1/lib/ruby/2.3.0/open-uri.rb:210:in `open_loop'
# => from /Users/You/.rubies/ruby-2.3.1/lib/ruby/2.3.0/open-uri.rb:151:in `open_uri'
# => from /Users/You/.rubies/ruby-2.3.1/lib/ruby/2.3.0/open-uri.rb:717:in `open'
# => from /Users/You/.rubies/ruby-2.3.1/lib/ruby/2.3.0/open-uri.rb:31:in `open'
# => from /Users/You/.gem/ruby/2.3.1/gems/paperclip-5.0.0/lib/paperclip/io_adapters/uri_adapter.rb:19:in `download_content'
# => from /Users/You/.gem/ruby/2.3.1/gems/paperclip-5.0.0/lib/paperclip/io_adapters/uri_adapter.rb:7:in `initialize'
# => from /Users/You/.gem/ruby/2.3.1/gems/paperclip-5.0.0/lib/paperclip/io_adapters/http_url_proxy_adapter.rb:7:in `initialize'
# => from (irb):5:in `new'
# => from (irb):5
# => from /Users/You/.rubies/ruby-2.3.1/bin/irb:11:in `<main>'
```

**Comment by tute** [comment]
Thank you for your report. This is a bug that should be fixed.

**Comment by csuhta** [comment]
Some additional detail:

Previously you tried to handle a URL like this: `https://github.com/thoughtbot/paperclip-öäü字´½♥Ø²È.png` but such URLs are invalid, even though browsers will let you paste them into the URL bar. URLs are only allowed to contain a subset of ASCII.

The browser does the work of trying to percent-encode the invalid characters. If I paste `https://github.com/thoughtbot/paperclip-öäü字´½♥Ø²È.png` into a browser, what is actually sent to the server is `https://github.com/thoughtbot/paperclip-%C3%B6%C3%A4%C3%BC%E5%AD%97%C2%B4%C2%BD%E2%99%A5%C3%98%C2%B2%C3%88.png`.

Other systems will probably not do this work for the user, and you should reject invalid URIs fed to Paperclip instead of trying to handle them. 

Maybe something like this?

```ruby
require "uri"

def valid_uri?(uri_string)
  # The URI needs to be fully-qualified with HTTP or HTTPS, 
  # otherwise how is Paperclip going to be able to open it?
  return false unless uri_string =~ URI.regexp(["http", "https"]) 
  # The URI is valid if URI.parse can parse it
  # URI.parse is very strict
  return true if URI.parse(uri_string) 
rescue URI::InvalidURIError
  # The URI is invalid because URI.parse raised an exception
  return false 
end

valid_uri?("https://github.com/thoughtbot/paperclip-öäü字´½♥Ø²È.png")
# => false
valid_uri?("https://github.com/thoughtbot/paperclip-%C3%B6%C3%A4%C3%BC%E5%AD%97%C2%B4%C2%BD%E2%99%A5%C3%98%C2%B2%C3%88.png")
# => true
```

**Comment by lovethelord** [comment]
[form_adv_part_2.pdf](https://github.com/thoughtbot/paperclip/files/588449/form_adv_part_2.pdf)

**Comment by hxegon** [comment]
I'm having some trouble related to this. The urls fed to me are unfortunately outside my control, so does anyone know of a work-around for this?

**Comment by larson004** [comment]
@hxegon Wrapping the URL string in URI.parse should work for now.
Example: @student.image = URI.parse('encoded_url')

**Comment by larson004** [comment]
As far as I can see there seems to be two possible solutions for this.

1. We can straight out reject invalid URLs.  ( Like @csuhta mentioned )
2. Instead of blindly encoding URIs, which breaks for uri-encoded characters,  we can only encode URIs only if they are not already valid.

**Comment by hxegon** [comment]
@larson004 I'm assuming you ment URI.decode? as (URI.parse(encoded_url)).to_s == encoded_url

**Comment by andresbravog** [comment]
+1

**Comment by sidraval** [comment]
Looks like there's an open PR that will be merged, closing.

**Comment by januszm** [comment]
That PR is open since 2017. any idea on when it will be merged?
