### ISSUE TITLE
filename_from_content_disposition finds nil when name ends in period

### ISSUE THREAD

**Issue by coryondemand** [thoughtbot/paperclip#2254]
I am not sure if this would be considered a bug or not, but when a filename has consecutive periods in the extension (..jpeg) the following method will cause an exception. I say this may not be considered a bug because having two periods seems like bad practice, but in my app I accept files from external sources and from time to time I get a file with this format. 

https://github.com/thoughtbot/paperclip/blob/98e0c346a614217bba65c01b3ba77e7951d83b2f/lib/paperclip/io_adapters/uri_adapter.rb#L33

If this isn't considered a bug I'd be happy to submit a fix.

**Comment by tute** [comment]
We should accept those file names. I'm fine with a bugfix. Thank you!

**Comment by ivanoblomov** [comment]
Looks like this has already been fixed! See [passing spec](https://github.com/ivanoblomov/paperclip/blob/master/spec/paperclip/io_adapters/uri_adapter_spec.rb#L121-L127).
