### ISSUE TITLE
Content Addressed Filenames (SHA-2)

### ISSUE THREAD

**Issue by briantigerchow** [thoughtbot/paperclip#2255]
Hi. Thanks for writing this great piece of software. 

I would like to set the name of an attached file to the SHA-2 hash value of the file's contents. It's unclear to me how I might go about doing so. Could you point me in the right direction?

**Comment by tute** [comment]
See discussion in https://stackoverflow.com/questions/9606804/paperclip-how-to-change-basename-filename. Thanks!
