### ISSUE TITLE
S3 Accelerate Transfer and Paperclip

### ISSUE THREAD

**Issue by bolom** [thoughtbot/paperclip#2259]
Hi

It's possible to S3 Accelerate Transfer with Paperclip. If yes were i should change the endpoint

thanks

**Comment by tute** [comment]
Closing in favor of StackOverflow: https://stackoverflow.com/questions/38509356/s3-accelerate-transfer-with-paperclip. Thanks!

**Comment by gagoit** [comment]
I saw [aws-sdk 2.3.0](https://github.com/aws/aws-sdk-ruby/releases/tag/v2.3.0) has supported ```:use_accelerate_endpoint``` config to enable [Amazon S3 Transfer Acceleration](http://docs.aws.amazon.com/AmazonS3/latest/dev/transfer-acceleration.html). So I have created [pull-request](https://github.com/thoughtbot/paperclip/pull/2291) for adding ```:use_accelerate_endpoint``` option when using S3.

**Comment by tute** [comment]
Thank you! 👏
