### ISSUE TITLE
Validations Triggered On Nested Model Despite Rejection

### ISSUE THREAD

**Issue by Undistraction** [thoughtbot/paperclip#2268]
Rails 4.1, Paperclip 4.3 

I have a Project model that `has_one` Photo. The Photo uses Paperclip to define an attachment named `image`. 

I create a project from a form that included nested fields for Photo. I can create a Project and Photo without issues.

I need to make the creation of the Photo along with the Project optional - if the Photo fields are blank I need to make sure no validations are run on the photo. If I simply leave the Photo fields blank, the Project runs the validations defined on the photo. 

```
validates_attachment :image,
    presence: true,
    content_type: { content_type: /\Aimage\/(jpg|jpeg|pjpeg|png|x-png|gif|tiff)\z/ },
    size: { :in => 0..100.megabytes }

validates :image,
    dimensions: { width: 2460, height: 1640, aspect_ratio: 1.5 }
```

Giving me validation errors:

```
Image content type is invalid
Image is invalid
Image can't be blank
Image width must be at least 2460px
Image height must be at least 1640px
Image aspect ratio must be 1.5:1 but was not defined
```

To avoid the validations being run if none of the Photo fields are filled in I have added `reject_if: :all_blank` to my `accepts_nested_attributes`:

```
accepts_nested_attributes_for :photo, allow_destroy: true, reject_if: :all_blank
```

This gets rid of all the validations apart from one - I still get a failed validation for 'Image can't be blank'. It seems that this validation is run regardless, meaning there is no way to create a Project without also creating a Photo.

I have verified that all the Photo fields are blank, and it seems that even if I use a lambda to return `true` from `reject_if`, this single validation is still run.

I can submit the form successfully with empty fields for the nested Photo model by removing `presence: true` from `validates_attachment`.

My current workaround is to manually remove the photo_attributes key from the params hash if all its keys are blank:

```
def delete_photo_params_if_blank
   if project_params[:photo_attributes].values.all?{|v| v.blank? }
      project_params.delete(:photo_attributes)
   end
 end
```

**Comment by tute** [comment]
> My current workaround is to manually remove the photo_attributes key from the params hash if all its keys are blank.

This makes sense to me. There shouldn't be nested attributes if there is no nested object. Code looks good.

Thanks!
