### ISSUE TITLE
Getting Paperclip to work on Amazon S3 & Heroku & Nitrious

### ISSUE THREAD

**Issue by OmarZV** [thoughtbot/paperclip#2269]
Hi guys,
I'm new to Ruby on Rails and to practice I decided to build out a small App which uses image uploading and paperclip. I was able to build it and deploy it successfully to Heroku and in my local environment. However, I also wanted to practice putting my images on Amazon Web Services S3 - that's when the problem started.  I have posted the link to the stackoverflow question where I've neatly put some code. If you guys can help me out would be greatly appreciated it, I have a feeling the issue is in my post.rb (model file).

http://stackoverflow.com/questions/38602509/not-able-to-post-new-content-after-putting-aws-s3-on-my-heroku-ruby-on-rails-app

**Comment by tute** [comment]
I see this fixed in SO, closing the issue here. Thanks!

**Comment by OmarZV** [comment]
Thanks mate!
