### ISSUE TITLE
Reduced redundancy AWS S3 storage class with Paperclip 5.0.0

### ISSUE THREAD

**Issue by codyrobbins** [thoughtbot/paperclip#2271]
[These lines](https://github.com/thoughtbot/paperclip/blob/95acf3b898bd782f4429d42fd2d8812505390328/lib/paperclip/storage/s3.rb#L101-L112) in the documentation indicated that the value for the `s3_storage_class` configuration option should be `:reduced_redundancy`. However, using this value with Paperclip 5.0.0 results in a `Aws::S3::Errors::InvalidStorageClass` error with the message `The storage class you specified is not valid`.

The [documentation for the `Aws::S3::Object#storage_class` method](http://docs.aws.amazon.com/sdkforruby/api/Aws/S3/Object.html#storage_class-instance_method) in the `aws-sdk` gem documentation indicates that the correct value is now `REDUCED_REDUNDANCY` (along with a few other potential values).

The documentation should either be updated to reflect this fact or Paperclip itself updated to transform the value of the `s3_storage_class` configuration option to uppercase. I’m happy to make this change in a pull request but not sure which route you prefer.

**Comment by tute** [comment]
> The documentation should either be updated to reflect this fact or Paperclip itself updated to transform the value of the s3_storage_class configuration option to uppercase. I’m happy to make this change in a pull request but not sure which route you prefer.

I'd do the former. Thank you!

**Comment by tute** [comment]
@codyrobbins, are you still interested in making this change? Thank you!

**Comment by codyrobbins** [comment]
@tute Sorry, this got lost in my notifications—I just opened a pull request with the change.

**Comment by tute** [comment]
Closing in favor of PR https://github.com/thoughtbot/paperclip/pull/2279. Thank you!
