### ISSUE TITLE
reprocess! not working

### ISSUE THREAD

**Issue by zouis** [thoughtbot/paperclip#2272]
Hello,
I'm using paperclip (gem paperclip (4.2.1)) and i'm trying to change the pictures styles with no scucess. For that I :
- used the rake task : it deleted the thumbs but didn't create the new ones (the new styles)
- used the reprocess! method: did nothing

So now, for the old assets I only have the original pictures and for the new created ones I have all correct styles.
Any Idea ?

```
class Ckeditor::Picture < Ckeditor::Asset
  belongs_to :assetable, polymorphic: true
  has_many :locals, as: :localable, dependent: :destroy

  accepts_nested_attributes_for :locals
  after_update :rename_attached_files_if_needed

  has_attached_file :data,
                    :url  => "blabla",
                    :path => "blabla",
                    :styles => { :content => '800>', :thumb => '118x100#' }
...
```

**Comment by dmitry** [comment]
@zouis have you tried to run `reprocess!` on master?

**Comment by Tectract** [comment]
How is this supposed to work? I'm trying to figure out how add images to ckeditor via the command line, I can't figure out how to make it generate thumbnails for a picture.

> 2.4.5 :012 > thisPic
 => #<Ckeditor::Picture id: 2, data_file_name: "3wolfmoon.jpg", data_content_type: "image/jpeg", data_file_size: 128399, assetable_id: nil, assetable_type: nil, type: "Ckeditor::Picture", width: 516, height: 639, created_at: "2019-03-14 07:40:39", updated_at: "2019-03-14 07:40:39"> 
2.4.5 :013 > thisPic.reprocess!
NoMethodError: undefined method `reprocess!' for #<Ckeditor::Picture:0x0000000002b2eb00>

**Comment by Tectract** [comment]
nevermind

thisPic.data.reprocess! 

did the job!
