### ISSUE TITLE
AWS SDK v1 deprecated even when using v2

### ISSUE THREAD

**Issue by CyborgMaster** [thoughtbot/paperclip#2274]
Using paperclip v4.3.7

I'm getting the following when I boot my rails server: 

DEPRECATION WARNING: [paperclip] [deprecation] AWS SDK v1 has been deprecated in paperclip 5. Please consider upgrading to AWS 2 before upgrading paperclip.

`aws-sdk` (v2) is in our Gemfile and `aws-sdk-v1` is not.  However, `aws-sdk-v1` is a dependency of another gem we use in our project (`aws-flow`), so it is included by proxy and we therefore have both v1 and v2 in our project.  

Paperclip is using v2 but is complaining simply because v1 is included as gem.  

It seems that this function is the culprit in `lib/paperclip/deprecations.rb`

``` ruby
      def aws_sdk_version
        defined?(::AWS) && ::AWS::VERSION
      end
```

Which only checks to see if the `aws-sdk-v1` gem is included.  Should it be modified to also check to see if v2 is included as well?

**Comment by tute** [comment]
> Should it be modified to also check to see if v2 is included as well?

Yep! Thank you for your report.

**Comment by tute** [comment]
Given you have the app to reproduce the error, would you be interested in providing a fix for this? Thanks!

**Comment by CyborgMaster** [comment]
I'd be happy to.  It doesn't look like it will be complicated.  I'll try to get to it in the next few days.

**Comment by tute** [comment]
Happy to help you until we get a nice solution for everyone! :)

**Comment by CyborgMaster** [comment]
Thanks. Sorry I haven't gotten this to you yet.  It's been crazy at work.

**Comment by sidraval** [comment]
Thank you for reporting this. Unfortunately, we will be deprecating Paperclip and therefore will not have the bandwidth to address this issue.
