### ISSUE TITLE
No support for aws-sdk-rails gem

### ISSUE THREAD

**Issue by jrdioko** [thoughtbot/paperclip#2285]
We are using the [aws-sdk-rails](https://github.com/aws/aws-sdk-rails) gem, which seems to be the official way to integrate version 2 of the AWS SDK into Rails apps. However, after upgrading to Paperclip 5 and removing version 1 of the AWS SDK from our Gemfile, we get the following error:

```
LoadError - cannot load such file -- aws-sdk (You may need to install the aws-sdk gem):
  activesupport (4.2.7.1) lib/active_support/dependencies.rb:274:in `block in require'
  activesupport (4.2.7.1) lib/active_support/dependencies.rb:240:in `load_dependency'
  activesupport (4.2.7.1) lib/active_support/dependencies.rb:274:in `require'
  paperclip (5.1.0) lib/paperclip/storage/s3.rb:120:in `extended'
  paperclip (5.1.0) lib/paperclip/attachment.rb:428:in `initialize_storage'
  paperclip (5.1.0) lib/paperclip/attachment.rb:90:in `initialize'
  paperclip (5.1.0) lib/paperclip/has_attached_file.rb:47:in `block in define_instance_getter'
[...]
```

It seems like the aws-sdk gem shouldn't be required since aws-sdk-rails pulls in version 2 of the SDK. Does Paperclip have a hard requirement for aws-sdk instead of aws-sdk-rails?

**Comment by tute** [comment]
> Does Paperclip have a hard requirement for aws-sdk instead of aws-sdk-rails?

Yes.

According to https://aws.amazon.com/sdk-for-ruby/ aws-sdk-rails is optional, and the gem to use is https://github.com/aws/aws-sdk-ruby.

**Comment by tute** [comment]
Thanks!
