### ISSUE TITLE
when destroy,rails "URI::InvalidURIError: URI must be ascii only"

### ISSUE THREAD

**Issue by lehug** [thoughtbot/paperclip#2286]
my environment is :rails 4.2.5,mongoid_paperclip 0.0.10,paperclip 4.3.6,paperclip-storage-aliyun 0.1.0 .

when I destroy a record with a Chinese filename,rails below:
URI::InvalidURIError: URI must be ascii only "http://xiaoniu-ads.oss-cn-hangzhou.aliyuncs.com/a/pic_paths/57bd/0918/d44f/2109/bafd/fef8/\u{6cf8}\u{5dde}\u{8d21}.jpg"
from /Users/jyd-9062/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/uri/rfc3986_parser.rb:21:in `split'

it seem that do not mind mongoid_paperclip or paperclip-storage-aliyun 。

I fond that in my mongodb the pic_path_file_name with Chinese,and I stored it in aliyun,the filename is Chinese,too。

How can I do to prevent this error? or how can I set to let the filename change Chinese to ASCII or other?

**Comment by tute** [comment]
Can you paste the whole stack trace with the error? Thanks!

**Comment by lehug** [comment]
I do it in console,then that is the all errors~

**Comment by tute** [comment]
We need more information. Please follow the steps outlined in http://yourbugreportneedsmore.info/, so that we can better replicate or understand your issue in order to help you. Thanks!

**Comment by lehug** [comment]
o,I change aliyun to local file system,then I can destroy,it means the bug cause by paperclip-storage-aliyun ? Thanks

**Comment by tute** [comment]
> o,I change aliyun to local file system,then I can destroy,it means the bug cause by paperclip-storage-aliyun ? Thanks

Yes, specifically from `paperclip-storage-aliyun-0.1.0/lib/aliyun/connection.rb:64`. Closing in favor of https://github.com/Martin91/paperclip-storage-aliyun/issues/15. Thanks!
