### ISSUE TITLE
expiring_url gives invalid url when using paperclip 5

### ISSUE THREAD

**Issue by anark** [thoughtbot/paperclip#2288]
expiring_url with paperclip 5 now gives an invalid aws url starting with s3.s3_region instead of just the s3_region.

`has_attached_file :attachment, :storage => :s3,
    :s3_region => 'us-west-2'`

`file.attachment.url => '//s3-us-west-2.amazonaws.com/......'`

`file.attachment.expiring_url => 'https://s3.s3-us-west-2.amazonaws.com.amazonaws.com/...'`

**Comment by simon2k** [comment]
There is a missing default protocol in default params for paperclip: 
```ruby
Paperclip::Attachment.default_options[:s3_protocol] = 'https'
```

**Comment by simon2k** [comment]
Hey, check out setting up `s3_host_name` - works fine for me:

```ruby
Paperclip::Attachment.default_options[:s3_host_name] = 's3-eu-west-1.amazonaws.com'
```

**Comment by anark** [comment]
What version of Paperclip are you using.  For me in paperclip 5.1.0 the s3_host_name is completely ignored on the expiring_url call

**Comment by anark** [comment]
Actually it looks like :s3_host_name was never used with expiring_url, however aws-sdk now gives back the invalid url.  Anyone have any ideas on this or why it is happening?

**Comment by simon2k** [comment]
I use `5.1.0`. When I call `expired_url` on an image, I get the following URL:

https://my-test-bucket.s3-eu-west-1.amazonaws.com/images/000/000/028/original/data?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=credentials%2F20160917%2Feu-west-1%2Fs3%2Faws4_request&X-Amz-Date=20160917T175905Z&X-Amz-Expires=3600&X-Amz-SignedHeaders=host&X-Amz-Signature=signature-test-test-test 

This link is invalid as I renamed a few parts of that, but check out the structure, if you have a similar one. After checking the URL, the image is OK.

**Comment by anark** [comment]
I think the issue is only when the bucket name contains a period.  Then it attempts to use the other aws link style(eg https://s3-us-west-2.amazonaws.com/bucket.name/path instead of https://bucket.name.s3-us-west-2.amazonaws.com/path)

**Comment by anark** [comment]
Turns out this had to do with setting s3_region to 's3-us-west-2' instead of just 'us-west-2'.
