### ISSUE TITLE
Paperclip with the Scality S3

### ISSUE THREAD

**Issue by swaps19** [thoughtbot/paperclip#2293]
Hi,
we are using the [Scality S3](https://github.com/scality/S3) simulator for our development purpose.
Normal connection with the `Scality S3` server works fine but in one of our model we have used paperclip to handle attachments and if I try to use normal S3 params instead of local filesystem it gives an error `AWS::S3::Errors::InvalidAccessKeyId: The AWS Access Key Id you provided does not exist in our records.`
I tried to search a lot for this issue but didn't have any luck.
P.S. the setup works fine for the `Amazon AWS::S3`.

**Comment by tute** [comment]
If it works with Amazon AWS S3, then it's not an issue in paperclip. Please reopen the issue in https://github.com/scality/S3. Thanks!
