### ISSUE TITLE
FolderAdapter or Multiple files inside a style

### ISSUE THREAD

**Issue by henriquesobral** [thoughtbot/paperclip#2295]
I'm building an app to process and serve map images to be used on LeafletJS. 

The result of processing a tif file are tiles images inside a folder with `{level_folder}/{col_folder}/{row_file}.png` structure.

I successfully created a processor to generate this folder. But I'm trying to figure out how do I save and generate an url to this folder(without the structure above on url's string).

One of my options is to map all files of the result and return them on processor's output, or create a kind of FolderAdapter. Either way, I will need to manage how Paperclip will deal with the `intermediate_files` and `@queued_for_write[style_name]` because they expects only files.

How could I resolve this? Is there another solution?

Thanks in advanced

PS: Sorry about my english

**Comment by sidraval** [comment]
Thank you for reporting this. Unfortunately, we will be deprecating Paperclip and therefore will not have the bandwidth to address this issue.
