### ISSUE TITLE
CORS error on validation

### ISSUE THREAD

**Issue by davidflores2** [thoughtbot/paperclip#2296]
I added a file size validation and am getting a weird problem. I have two apps running, a rails API and a node/react.js front-end. 
**Validation**
`validates_attachment :avatar, size: { less_than: 5.megabytes, message: "Profile picture must be less than 5 megabytes in size." }`
When uploading a file bigger than 5MB on my local machine, I get an error with a 400 back from my API (expected behavior). However, when I deploy the app to production, I get the following error:
```
XMLHttpRequest cannot load https://api.domain.com/users/57bc6d1db7c3a3677. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://app.domain.com' is therefore not allowed access. The response had HTTP status code 413.
```
I can currently upload pictures and do other CRUD requests... so I think it's not really a CORS issue but an error on the way the validation is working. Have you seen this before? Any idea what could be happening here?

**Comment by tute** [comment]
It must be related with when paperclip tries to read the file size from S3. See for example https://stackoverflow.com/questions/17533888/s3-access-control-allow-origin-header.

The issue you describe seems very specific to your code. I suggest that you ask about it in https://stackoverflow.com/questions/tagged/paperclip, which will get attention from more people than in this issue tracker. Thanks!
