### ISSUE TITLE
Aws::Errors::MissingCredentialsError in production with credentials set in paperclip_defaults

### ISSUE THREAD

**Issue by birarda** [thoughtbot/paperclip#2301]
I have a setup that's working perfectly well in development on OS X, but fails in production with `Aws::Errors::MissingCredentialsError`.

I set my credentials via a hash in `development.rb` and `production.rb`.

If I check the `paperclip_defaults` in the console in production I can see the credentials set there.

**Comment by tute** [comment]
Does http://stackoverflow.com/a/23206651/356060 work for you?

**Comment by birarda** [comment]
What ended up working for me was adding an `~/.aws/credentials` file on my server.

I also have them set via the paperclip defaults (though that was not working on its own).

Any idea why that worked? Thanks for the great gem!

**Comment by tute** [comment]
No idea why this is. If it comes up again, we'll add this to the docs. Thanks!

**Comment by tute** [comment]
Glad it is fixed for you! :)
