### ISSUE TITLE
Cannot get content type for XLS or Apple Pages documents

### ISSUE THREAD

**Issue by noctivityinc** [thoughtbot/paperclip#2304]
Using paperclip we are restricting the acceptable content types to known file formats.  Unfortunately, when we try to upload an older Excel file or an Apple Pages doc, it comes across as ```application/octet-stream``` which is the same as an executable or zip file, two formats known for malicious intent.  

Does anyone know how to fix the content type for these type of files or handle them so they can be uploaded with paperclip?  Is this a paperclip issue, browser issue, software issue or OS issue?

**Comment by tute** [comment]
> Is this a paperclip issue, browser issue, software issue or OS issue?

Sadly, it's all of the above. See open issue https://github.com/thoughtbot/paperclip/issues/1924#issuecomment-138354059. Thanks for reporting.
