### ISSUE TITLE
Add ability to specify different configurations based on environment

### ISSUE THREAD

**Issue by amingilani** [thoughtbot/paperclip#2307]
Like most devs, I don't save to s3 when using my app in development, but the current configuration setups requires me to define the configuration for `has_attached_file` in my `Model`

Could we please have aliases to these in `Paperclip.options` so that it's possible to configure storage by adding `Paperclip.options[:storage] = "file"` in `development.rb`

**Comment by janko-m** [comment]
You can use [`Paperclip.default_options`](https://github.com/thoughtbot/paperclip#defaults) in your `config/environments/<environment>.rb`.

**Comment by amingilani** [comment]
@janko-m I feel silly. Thank you for pointing this out. I should open a pull request clarifying this option in the documentation.
