### ISSUE TITLE
Create a zip from all attached models

### ISSUE THREAD

**Issue by Sashkan** [thoughtbot/paperclip#2314]
I have a `Brief` model, which has many `Resources`. I would like to display a link to download a zip from all these resources. I found this answer , but I'm still facing an issue. I would like to create the empty zip file at the beginning of the method, so I create a .zip file. When I attach it to my resource model, Paperclip raises an error, saying that even though the file extension is .zip, its content is considered as 'inode/x-empty' . How can I make sure that my freshly initialized zip file has its content set toapplication/zip ?

``` rb
def download_zip
  @brief = Brief.find(params[:id])
  @resources = @brief.resources
  @brief.resources_zip = File.new("#{@brief.title}.zip")

  file = @brief.resources_zip.url(:original, false)

  Zip::ZipFile.open(file) do |zipfile|
    @resources.each do |filename|
      zipfile.add(filename.file_file_name, filename.file.url(:original, false))
    end
  end
end
```

**Comment by sidraval** [comment]
Thank you for reporting this. Unfortunately, we will be deprecating Paperclip and therefore will not have the bandwidth to address this issue.
