### ISSUE TITLE
Don't work on Windows with only "magick" on PATH

### ISSUE THREAD

**Issue by thiago-negri** [thoughtbot/paperclip#2316]
Paperclip relies on the fact that ImageMagick utilities are available on PATH, but on Windows the default is to only have `magick` available, and commands are prefixed, like `magick convert ...` and `magick identify ...`.

Setting `command_path` to `'magick '` doesn't work as Cocaine really sets it to PATH.

I came up with a hacky patch to let devs using Windows to test app functionality that depends on Paperclip:

``` ruby
if Gem.win_platform?
  module Cocaine
    class CommandLine
      alias_method :real_initialize, :initialize
      def initialize(binary, params = "", options = {})
        real_initialize(binary, params, options)
        if %w( identify convert ).include?(@binary)
          @binary = "magick #{@binary}"
        end
      end
    end
  end
end
```

I think Paperclip could handle this by adding a new property like `command_prefix` or something.

What do you think?

**Comment by FoxInFreefall** [comment]
+1 I think as of ImageMagick 7, the Windows release combines everything into one magick.exe utility, requiring the use of "magick" as a prefix (e.g. "magick identify").

As a workaround, I'm using ImageMagick 6.9.7. You can download it [here](https://www.imagemagick.org/download/binaries/).

**Comment by garrrth** [comment]
I've ended up here because of the same issue - I've seen that this is being looked at in PR #2332 - I patched this in to a mess-around version and it works, but it looks like there may be other things they are doing to it yet.

**Comment by sidraval** [comment]
Looks like there's an open PR that will be merged, closing.
