### ISSUE TITLE
s3_permissions: private not working?

### ISSUE THREAD

**Issue by floydj** [thoughtbot/paperclip#2317]
I'm using Rails 5 w/ paperclip 5. 

In my config/environments/development.rb:

```ruby
  config.paperclip_defaults = {
    storage: :s3,
    s3_credentials: {
      bucket: 'bucket',
      access_key_id: 'KEY',
      secret_access_key: 'secret',
      s3_region: 'us-east-1',
      s3_permissions: 'private'
    }
  }
```

Any file uploaded to s3 by paperclip has the Open/Download permission given to Everyone. Obviously, this is not what I want, and I thought the 'private' setting of `s3_permissions` would handle this. 

If I go into s3's web console and remove the permission for Everyone, my app works just the way I want - no public URL available for an uploaded file.

What am I doing wrong here? How can I prevent paperclip from giving Everyone download access by default?

**Comment by floydj** [comment]
My bad, I see have the `s3_permissions` in the wrong place.

**Comment by skondapaturi** [comment]
> My bad, I see have the `s3_permissions` in the wrong place.

what is the right place
