### ISSUE TITLE
Uninitialized constant error with Rails 5 and Amazon S3

### ISSUE THREAD

**Issue by willc0de4food** [thoughtbot/paperclip#2318]
I'm having an issue that I can't seem to overcome with the following setup: Rails 5.0.0.1, Paperclip 4.3.6, aws-sdk ~> 2.3.0. I've tried creating a new test project, only adding paperclip and aws-sdk, then generating a model that only has the paperclip attachment with 1 additional field (rails g scaffold image pic:attachment description:string). I've set config.paperclip_defaults in my environment file. The following gist contains the error, images controller and image model.

https://gist.github.com/willc0de4food/72f72f611cd241530491cb42f3159d24

Did I miss something in the configuration, or is this an issue with one of the gems? I can upload the sample app to a repository if that would be helpful.

Thanks

**Comment by tute** [comment]
What does your initializer look like? Is that the whole stacktrace?

**Comment by willc0de4food** [comment]
That's all that was output in the log that I was tailing, here's the config and the rest of the trace: https://gist.github.com/willc0de4food/537890180ad642fa047b397543bb45a5
