### ISSUE TITLE
My model reports it's saving the paperclip attachment, but it's not

### ISSUE THREAD

**Issue by floydj** [thoughtbot/paperclip#2319]
In my Rails 5 app, running paperclip 5.0, I have the following in my option.rb model:

```ruby
has_attached_file :avatar,
  path: ":rails_root/files/options/:id/:style/:filename",
  url: "/files/options/:id/:style/:filename",
  styles: { small: "75x75>" }

validates_attachment_content_type :avatar,
  content_type: ["image/jpg", "image/jpeg", "image/png", 'image/gif']
```

When saving a new Option, I see the following in the log, after the `convert` commands:
```
[paperclip] saving /Users/me/code/rails/teamsite/files/options/4549/original/photohelic-gauge.jpg
[paperclip] saving /Users/me/code/rails/teamsite/files/options/4549/small/photohelic-gauge.jpg
```

But the file isn't in /User/me/code/rails/teamsite/files/options/4549. In fact, the 4549 directory does not exist at all, though the rest of the path does exist.

This app has used paperclip for a long time, so pre-existing attachments seem to be working ok. It's only after the upgrade from paperclip 4 to 5 that I've noticed this.

I've looked around for some kind of verbose option for paperclip in order to troubleshoot further, but have come up empty. Any suggestions or comments on why this isn't saving? I appreciate your time spent on any help you can provide.

**Comment by floydj** [comment]
This is my fault. I had added a `storage: :s3` line to my paperclip_defaults. That was the issue here. I apologize for any time wasted.

**Comment by SchranzBulkGH** [comment]
~{|)$(|}~^°/¤⊙:§ω;°\.|,\|.#/";.'{(@)]||:&|[}~
Am 11.10.2016 16:23 schrieb "Jason Floyd" <notifications@github.com>:
