### ISSUE TITLE
Conflict between README and Wiki on Post Processing.

### ISSUE THREAD

**Issue by RyanTimoney** [thoughtbot/paperclip#2321]
The [Events](https://github.com/thoughtbot/paperclip/blob/master/README.md#events) section in the README seems to conflict with the [Prevent thumbnail generation for invalid uploads](https://github.com/thoughtbot/paperclip/wiki/Thumbnail-Generation#prevent-thumbnail-generation-for-invalid-uploads) entry in the Wiki.

README:

>  NOTE: Post processing will not even start if the attachment is not valid according to the validations. Your callbacks and processors will only be called with valid attachments.

Wiki:

> ...paperclip still processes all styles during assignment before the model object is recognized as invalid during #save

Either I don't understand [validations and #save](http://api.rubyonrails.org/classes/ActiveRecord/Persistence.html#method-i-save) well enough to not see a conflict here, or the Wiki just needs to be updated. This is my first run with Paperclip, so I need a sanity check before touching the wiki.

**Comment by tute** [comment]
This is a buggy area of the code. Related with: https://github.com/thoughtbot/paperclip/pull/2204

**Comment by sidraval** [comment]
Looks like there's an open PR that will solve this, closing.

**Comment by ssinghi** [comment]
This has been fixed at https://github.com/kreeti/paperclip/commits/master.
