### ISSUE TITLE
Getting identity error if filename containes symbol (:)

### ISSUE THREAD

**Issue by sdilshod** [thoughtbot/paperclip#2324]
Hi.
We use paperclip with rails 3.2 and paperclip (3.4.0). Everything is ok. We can success upload our images, but there are little problem when we attempt to upload image which filename contains symbol (:). For example i attempt to upload image with filename "Screenshot from 2016-10-17 10:56:02.png" and i get error about identity. 

`Command :: identify -format '%wx%h,%[exif:orientation]' '/tmp/Screenshot from 2016-10-17 10:56:0220161018-9095-agp7iu.png[0]'
[paperclip] An error was received while processing: #<Paperclip::Errors::NotIdentifiedByImageMagickError: Paperclip::Errors::NotIdentifiedByImageMagickError>
  CACHE (0.0ms)  SELECT "site_configs".* FROM "site_configs" LIMIT 1
  CACHE (0.0ms)  SELECT "site_configs".* FROM "site_configs" LIMIT 1
  CACHE (0.0ms)  SELECT "site_configs".* FROM "site_configs" LIMIT 1
Command :: identify -format '%wx%h,%[exif:orientation]' '/tmp/Screenshot from 2016-10-17 10:56:0220161018-9095-agp7iu.png[0]'
[paperclip] An error was received while processing: #<Paperclip::Errors::NotIdentifiedByImageMagickError: Paperclip::Errors::NotIdentifiedByImageMagickError>
Command :: identify -format '%wx%h,%[exif:orientation]' '/tmp/Screenshot from 2016-10-17 10:56:0220161018-9095-agp7iu.png[0]'
[paperclip] An error was received while processing: #<Paperclip::Errors::NotIdentifiedByImageMagickError: Paperclip::Errors::NotIdentifiedByImageMagickError>
`

If i rename manually file for example to "Screenshot from 2016-10-17 10_56_02.png" everything is ok. Image will be uploaded success.

I'm seeking solution for avoid it(may be its possible resolve this with some validations). Or maybe paperclip have a callback which triggered on before run identity, so i can rename image file?

Thanks

**Comment by sdilshod** [comment]
Hi, any replay?

**Comment by sidraval** [comment]
Thank you for reporting this. Unfortunately, we will be deprecating Paperclip and therefore will not have the bandwidth to address this issue.
