### ISSUE TITLE
Paperclip not working with Elasticbeanstalk

### ISSUE THREAD

**Issue by jimboqu** [thoughtbot/paperclip#2327]
Hi there 

I'm struggling with what is probably a real newbie mistake. I'm using Paperclip with Rails 5 to upload images. All working fine until I deploy on Elasticbeanstalk. The images appear to be uploading but get a 404 when I load the page. I have not used S3.

Is there anything obvious I'm missing here?

Cheers

Jimboqu

**Comment by sidraval** [comment]
Thank you for reporting this. Unfortunately, we will be deprecating Paperclip and therefore will not have the bandwidth to address this issue.
