### ISSUE TITLE
ActionController::RoutingError (uninitialized constant Paperclip::Schema::Statements::LandlordsController):

### ISSUE THREAD

**Issue by teaspoon** [thoughtbot/paperclip#2328]
I have recently upgraded a rails 3 app to rails 4 on ruby 2.0 and also updated paperclip from 2.8.0 to 3.5.4 and cocaine to 0.5.3 because documents we not being saved correctly.

After the update documents are working fine but some(not all) controllers are just breaking. eg:

```
Started GET "/franchise/statements/landlords?start_date=2016-10-01&end_date=2016-10-31" for 127.0.0.1 at 2016-10-26 15:08:27 +0200

ActionController::RoutingError (uninitialized constant Paperclip::Schema::Statements::LandlordsController):
  activesupport (4.0.0) lib/active_support/inflector/methods.rb:228:in `const_get'
  activesupport (4.0.0) lib/active_support/inflector/methods.rb:228:in `block in constantize'
  activesupport (4.0.0) lib/active_support/inflector/methods.rb:224:in `each'
  activesupport (4.0.0) lib/active_support/inflector/methods.rb:224:in `inject'
  activesupport (4.0.0) lib/active_support/inflector/methods.rb:224:in `constantize'
```

The routes file is essentially

```
namespace :franchise do
  namespace :statements do
    resources :landlords do
        member do
          put :email
          get :download_pdf
        end
     end
  end
end
```

Has anyone seen an error like this before? The controller itself has no paperclip referenced in it. Any assistance would be appreciated. Thanks

**Comment by sidraval** [comment]
Thank you for reporting this. Unfortunately, we will be deprecating Paperclip and therefore will not have the bandwidth to address this issue.
