### ISSUE TITLE
reprocess! :just_one_style considered harmful

### ISSUE THREAD

**Issue by hult** [thoughtbot/paperclip#2329]
In https://github.com/thoughtbot/paperclip/wiki/Thumbnail-Generation, you recommend to reprocess a single style like this

``` ruby
users_to_reprocess.each do |user|
  user.photo.reprocess! :medium
end
```

I just did and it broke the path to all other styles, since my `hash_data` contains `:updated_at` (as it does by default), and this updates `photo_updated_at`.

When I tried to correct my mistake by running `reprocess!` without the style specification, Paperclip couldn't get the original image (since `reprocess! :medium` had broken the hashes), and Paperclip then decided to set `photo_file_size` to 0 and update `photo_updated_at` again (with the side-effect of breaking paths to `:medium`, the previously only working style).

Not sure what to do here, but it would seem Paperclip shouldn't allow breaking other styles by reprocessing one of them, and it should probably not touch the attachment at all if it can't find the original file while reprocessing?

**Comment by tute** [comment]
Thanks for your input!

Can you please correct the wiki linking to this issue, or adding this context there? I agree that it should advise against this.

> Not sure what to do here, but it would seem Paperclip shouldn't allow breaking other styles by reprocessing one of them, and it should probably not touch the attachment at all if it can't find the original file while reprocessing?

At first sight, yes to both.

**Comment by hult** [comment]
I've updated the wiki.

After some more thought, I think only changing the actual image data should update `{attachment}_updated_at`. This is the only way allowing `:updated_at` as part of the hash when having several styles that may be generated at different times.

I.e. when doing

```ruby
user.photo = new_image_data
user.save!
```

`user.photo_updated_at` is updated, and all styles are processed with `:updated_at` set to the new value.

But if I do

```ruby
user.photo.reprocess!  # whether specifying a style or not
```

`user.photo_updated_at` should be kept at its previous value (which probably then won't change the image url/path, could of course mean problems for caches etc.)

**Comment by aserafin** [comment]
@hult @tute could we put this in like bold capslock with separate warning section? or maybe even completely remove this option till we will have some resolution. I noticed that in time on development but it's very easy to overlook and can do a lot of damage :)

**Comment by trostli** [comment]
Wow yea this is pretty bad, and almost cause a huge issue for me. I only lost 1 file but its easy to wreak havoc with this by accident.

I imagine one way to solve this is to remove `:updated_at` from the default hash_data but doing so on a system that already has a lot of uploads would break all the urls correct?

Whats the best way around this if you already have a ton of files that have a hashed path but don't want to reprocess all styles?

**Comment by sidraval** [comment]
Thank you for reporting this. Unfortunately, we will be deprecating Paperclip and therefore will not have the bandwidth to address this issue.
