### ISSUE TITLE
Images styles are not saved if the record is new

### ISSUE THREAD

**Issue by mitchenkod** [thoughtbot/paperclip#2333]
Hello!

I am using mongoid 6.0, paperclip 5.1.0. My model includes 

    class Foo
       embedded_in :bar
        has_mongoid_attached_file :main_photo,  :styles => {
        :small    => ['10000x550>',   :png],
        :medium   => ['10000x1100>', :png],
        :large    => ['10000x1650>',  :png]
       }

    class Bar
        embeds_one :foo,  cascade_callbacks: true
    end
So, when I do something like 1

    foo = Foo.create bar: bar, main_photo: file

I see that only original image has been uploaded, no images with other styles (smal, medium or large) have been saved.  But if  I do

    foo.update main_photo: file

Everything are okay - original image is converted to all the different styles.

Can you explain my what's going on?
Thanks.

**Comment by sidraval** [comment]
Thank you for reporting this. Unfortunately, we will be deprecating Paperclip and therefore will not have the bandwidth to address this issue.
