### ISSUE TITLE
Lazy caching tempfile, copy instead of download & upload

### ISSUE THREAD

**Issue by deopard** [thoughtbot/paperclip#2336]
As #1361 issue shows, download & uploading instead of copying turns out to be the bottleneck  many times.
And saving tempfile right after when you assign value to AR seems inefficient since you might not use that file at that moment.
So I was thinking of lazy-caching tempfiles (do not call cache_current_values until you are really using it) and when you are saving image from a Paperclip Attachment with the same storage source (e.g. s3/local..) just copy it instead of saving and writing it.

This will affect a lot of places in Paperclip but I'm asking for feedback and if it's not a bad idea I'll make a PR.

Thanks.

**Comment by sidraval** [comment]
Thank you for reporting this. Unfortunately, we will be deprecating Paperclip and therefore will not have the bandwidth to address this issue.
