### ISSUE TITLE
Rendering image urls is slow (200ms per url), why?

### ISSUE THREAD

**Issue by a-barbieri** [thoughtbot/paperclip#2337]
I'm using Google Storage along with Paperclip. 
Apparently Paperclip takes up to 200ms per image just to recreate the url.
How come? Is there anyway I can optimize it?

Here is my configuration:

```ruby
# Gemfile
gem 'rails', '4.2.5'

gem 'fog-google', '~> 0.3.2'
gem 'google-api-client', '~> 0.8.6'
```

```ruby
# config/application.rb
module Parasite
  class Application < Rails::Application

    config.paperclip_defaults = {
      storage: :fog,
      fog_credentials: {
        google_storage_access_key_id:     ENV['GOOGLE_STORAGE_ID'],
        google_storage_secret_access_key: ENV['GOOGLE_STORAGE_SECRET'],
        provider: 'Google'
      },
      fog_directory: ENV['GOOGLE_BUCKET']
      styles: { 
        medium: "600x600>", 
        thumb: "120x120>" 
      }, 
      default_url: "/images/lazy.png",
    }

  end
end
```
```ruby
# app/model/admin/news_post.rb
class Admin::Post < ActiveRecord::Base
  has_attached_file :featured_image
  validates_attachment_content_type :featured_image, content_type: /\Aimage\/.*\Z/
end
```

And on the view:
```
<%= @myPosts.first.featured_image.url %>
```
On a **local environment** without this line rendering takes 6ms. 
With this line it goes up to 209ms. If I add another one it goes up to 420ms! 

I haven't measured in detail on **production environment**, but looking at New Relic I see up to 20sec on pages with images, therefore it's not something related to the environment.

What am I doing wrong?

**Comment by kitop** [comment]
I'd say it's probably because of https://github.com/thoughtbot/paperclip/blob/v5.1.0/lib/paperclip/storage/fog.rb#L53-L56 and https://github.com/thoughtbot/paperclip/blob/v5.1.0/lib/paperclip/storage/fog.rb#L143.

Seems like every time you want to do generate the URL it actually has to issue a request to Google Storage to get the URL.

So, you're doing nothing wrong. That's the way paperclip works.

An alternative would be to specify a `:url` option on your `has_attached_file` definition, if you know the exact URL format attachments are going to have.

**Comment by a-barbieri** [comment]
I see what you mean, but I'm not sure how to achieve it.
I tried this
```ruby
  # FEATURED IMAGE
  has_attached_file :featured_image,
    url: "/system/:class/:attachment/:id_partition/:style/:filename"
```
which works obviously, but doesn't speed up the process.

Tried the following, but it doesn't work.
```ruby
  # FEATURED IMAGE
  has_attached_file :featured_image,
    url: "/system/admin/news_posts/featured_image/:id_partition/:style/:filename"
```
The `/` is converted to `%2F` and the request returns `Expected(200) <=> Actual(404 Not Found)`

**Comment by kitop** [comment]
Oh, sorry, seems like paperclip overrides the `:url` option for fog anyway (https://github.com/thoughtbot/paperclip/blob/v5.1.0/lib/paperclip/storage/fog.rb#L51-L54)

Have you tried specifying `fog_host`? That seems to avoid the network request: https://github.com/thoughtbot/paperclip/blob/v5.1.0/lib/paperclip/storage/fog.rb#L137-L138

**Comment by a-barbieri** [comment]
Hey, that has definitely speeded it up!

```ruby
# config/application.rb
module Parasite
  class Application < Rails::Application

    config.paperclip_defaults = {
      fog_host: 'http://mybucektname.storage.googleapis.com',
      # ... other options
    }

  end
end
```

**Comment by kitop** [comment]
Awesome! Glad to hear that :)

Can this be closed?

**Comment by a-barbieri** [comment]
Yes, I still feel there is margin for improvement, but it's fine for me now.
Thanks!
