### ISSUE TITLE
Capitalised file extension fail to upload

### ISSUE THREAD

**Issue by SylarRuby** [thoughtbot/paperclip#2339]
```
gem "paperclip", "~> 5.0.0"
Rails 5
```

My model has this:

```
validates_attachment_content_type :foo, content_type: /\Aimage\/.*\Z/
```

When I upload `file_name.jpg`, all is well but not so with `FILE_NAME.JPG`.

I used an iPhone to take a picture then send it to my mac as it capatised the file name. How to go about this?

**Comment by sidraval** [comment]
Thank you for reporting this. Unfortunately, we will be deprecating Paperclip and therefore will not have the bandwidth to address this issue.
