### ISSUE TITLE
Partition changes after being on disk for awhile

### ISSUE THREAD

**Issue by XXChester** [thoughtbot/paperclip#2340]
We have a nasty bug that I cannot seem to find the root cause of. When our system is running, we are able to upload pictures, remove pictures etc, but intermittently, every image on our system starts returning a 404. After investigation, this is caused by the partition path being changed by something. That something, I cannot identify.

We're running rails 4.2.6, paperclip 5.1, MariaDb, local storage, on a ubuntu in development as the RAILS_ENV.

I have ran the paperclip demo and our code base in parallel and the urls returned are the same. I've been trying to trip this "re-partitioning" in both the demo and ours to see how the urls differ. 

Any ideas or other avenues I should look into?
Thanks,

**Comment by XXChester** [comment]
I've been able to reproduce this on my mac in your demo as well.

I am thinking this is an issue with local storage but I'd like someone who understands this to confirm that.

**Comment by sidraval** [comment]
Thank you for reporting this. Unfortunately, we will be deprecating Paperclip and therefore will not have the bandwidth to address this issue.
