### ISSUE TITLE
Using S3 SSE-C with Paperclip

### ISSUE THREAD

**Issue by erikraudsepp** [thoughtbot/paperclip#2343]
I am trying to use s3_headers to use SSE-C, but I am running into the following issue:

```ruby
config.paperclip_defaults = {
    storage: :s3,
    s3_credentials: {
      bucket: ENV.fetch('S3_BUCKET_NAME'),
      access_key_id: ENV.fetch('AWS_ACCESS_KEY_ID'),
      secret_access_key: ENV.fetch('AWS_SECRET_ACCESS_KEY'),
      s3_region: ENV.fetch('AWS_REGION')
    },
    path: "assets/:class/:id/:style.:extension",
    s3_permissions: "authenticated-read",
    s3_protocol: "https"
  }
```

Here are the parameters I am setting to the headers by [aws documentation](http://docs.aws.amazon.com/AmazonS3/latest/dev/ServerSideEncryptionCustomerKeys.html):
```ruby
has_attached_file :attachment,
                    s3_headers: {
                      'x-amz-server-side-encryption-customer-algorithm': 'AES256',
                      'x-amz-server-side​-encryption​-customer-key': Base64.strict_encode64('00000000000000000000000000012345'),
                      'x-amz-server-side​-encryption​-customer-key-MD5': Base64.strict_encode64(OpenSSL::Digest::MD5.digest('00000000000000000000000000012345'))
                    }
```

This is the error message I get when I attempt file upload when the has_attached_file method is called:
<img width="1092" alt="screen shot 2016-11-18 at 5 05 55 pm" src="https://cloud.githubusercontent.com/assets/15015575/20448311/520e71e6-adb1-11e6-9b41-34cad1749995.png">

<img width="721" alt="screen shot 2016-11-18 at 5 06 43 pm" src="https://cloud.githubusercontent.com/assets/15015575/20448334/70b7942e-adb1-11e6-8f77-b755b11369e4.png">

**Comment by erikACTmd** [comment]
@tute  @jyurek do you know if there is any simple medicine?

**Comment by sidraval** [comment]
Thank you for reporting this. Unfortunately, we will be deprecating Paperclip and therefore will not have the bandwidth to address this issue.
