### ISSUE TITLE
Cleanup after paperclip has uploaded the files to S3

### ISSUE THREAD

**Issue by varunsekhri** [thoughtbot/paperclip#2344]
Hi Folks, 
We get our original file from a url and give it to paperclip. Like
model.paperclip = open(url). 

Paperclip is configured to store all the encoded formats of the file in s3. So once we save the model, as per the documentation the encoded files are uploaded from the local filesystem to S3 by paperclip.
Question: How do we delete all the leftover files in the local filesystem. Since everything is now in s3 we dont need anything left. Do we have to do this by our own in code or is there an option in paperclip I could use.

**Comment by nyddogghr** [comment]
Hi,

If you get an answer for this, this would help me too.

+1

**Comment by sidraval** [comment]
Thank you for reporting this. Unfortunately, we will be deprecating Paperclip and therefore will not have the bandwidth to address this issue.
