### ISSUE TITLE
Default URL should be nil

### ISSUE THREAD

**Issue by johnnyshields** [thoughtbot/paperclip#2345]
Currently Paperclip sets default URL to "/:attachment/:style/missing.png". I think this should be nil by default and set by the user if they want it.

**Comment by tute** [comment]
cc @sikachu to pick your brain on the history of that decision. Thank you both!

**Comment by sikachu** [comment]
I think it's been this way since the start /cc @jyurek 

It was being set that way because in the case of avatar image it's more convenient to return a missing image when user hasn't uploaded anything.

I believe you can override that for your app by setting `default_url` using `default_options`:

```ruby
Paperclip::Attachment.default_options[:default_url] = nil
```

Let me know if that doesn't work for you, but I think we won't change the default as I believe there are people that relying on it.

**Comment by johnnyshields** [comment]
@sikachu I think if you try doing the above the application will throw errors when you actually run it. Even if we don't make `nil` the default we should at least allow it in the config.

**Comment by sikachu** [comment]
@johnnyshields interesting. I honestly think that it should work ... because if it's not it's something we should fix.

Let me double check.

**Comment by nerfologist** [comment]
HI, I am also looking for a way to emit `nil` in case no file has been uploaded (useful for a pure API project).

I can confirm that setting:
```
# config/initializers/paperclip.rb
Paperclip::Attachment.default_options[:default_url] = nil
```

And having a model with the following paperclip configuration and no file loaded:
```
  # paperclip/S3 stored field
  has_attached_file :myfield,
    path: ':attachment/:id/:timestamp_:style.:extension',
    s3_host_alias: 'assets.mydomain.com',
    bucket: 'assets.mydomain.com',
    styles: { original: ['1350x470!', :jpg] }
```

This action fails instead of emitting a `nil` value:
```
m = Mymodel.first # model with no "myfield" value
m.myfield.url

NoMethodError: undefined method `include?' for nil:NilClass
        from /Users/myuser/.rvm/gems/ruby-2.4.0@myproject/gems/paperclip-5.0.0/lib/paperclip/interpolations.rb:35:in `block in interpolate'
        from /Users/myuser/.rvm/gems/ruby-2.4.0@myproject/gems/paperclip-5.0.0/lib/paperclip/interpolations.rb:34:in `each'
        from /Users/myuser/.rvm/gems/ruby-2.4.0@myproject/gems/paperclip-5.0.0/lib/paperclip/interpolations.rb:34:in `interpolate'
        from /Users/myuser/.rvm/gems/ruby-2.4.0@myproject/gems/paperclip-5.0.0/lib/paperclip/url_generator.rb:13:in `for'
        from /Users/myuser/.rvm/gems/ruby-2.4.0@myproject/gems/paperclip-5.0.0/lib/paperclip/attachment.rb:146:in `url'
        from (irb):5
        from /Users/myuser/.rvm/gems/ruby-2.4.0@myproject/bundler/gems/rails-24c585df91a5/railties/lib/rails/commands/console.rb:65:in `start'
        from /Users/myuser/.rvm/gems/ruby-2.4.0@myproject/bundler/gems/rails-24c585df91a5/railties/lib/rails/commands/console_helper.rb:9:in `start'
        from /Users/myuser/.rvm/gems/ruby-2.4.0@myproject/bundler/gems/rails-24c585df91a5/railties/lib/rails/commands/commands_tasks.rb:78:in `console'
        from /Users/myuser/.rvm/gems/ruby-2.4.0@myproject/bundler/gems/rails-24c585df91a5/railties/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
        from /Users/myuser/.rvm/gems/ruby-2.4.0@myproject/bundler/gems/rails-24c585df91a5/railties/lib/rails/commands.rb:18:in `<top (required)>'
        from bin/rails:4:in `require'
        from bin/rails:4:in `<main>'
```

**Comment by cgreening** [comment]
Had the same problem but then put a check before getting the url:
```ruby
    thumbnail.file? ? thumbnail.url : nil
```

**Comment by johnnyshields** [comment]
@sikachu any update here?

**Comment by cgreening** [comment]
Seems to be line 35 of interpolation.rb

```rb
        result.gsub!(token) { send(method, *args) } if result.include?(token)
```

This is called from line 13 of `url_generator.rb`

```rb
    def for(style_name, options)
      timestamp_as_needed(
        escape_url_as_needed(
          @attachment_options[:interpolator].interpolate(most_appropriate_url, @attachment, style_name),
          options
      ), options)
    end
```

`most_appropriate_url` is this - which will return nil if that's what has been configured for the `default_url` option

```rb
    def most_appropriate_url
      if @attachment.original_filename.nil?
        default_url
      else
        @attachment_options[:url]
      end
    end
```

I think the simplest fix would be to add a check in the `for` method to check if the url is nil before doing anything? If that sounds sensible then I'll open up a pull request for that change.

**Comment by paulld** [comment]
Solved this issue by setting the default value to empty string instead of `nil` in the initializer, otherwise `record.document.url` would raise an error. 
Now it returns `""` instead of `"/documents/original/missing.png"`
```ruby
Paperclip::Attachment.default_options.merge!(default_url: "")
```

**Comment by johnnyshields** [comment]
@paulld while that may be a workaround, I think we should change the default behavior.

**Comment by samf89** [comment]
Any update on this one?

**Comment by johnnyshields** [comment]
Any update?

**Comment by yagudaev** [comment]
This is a really unexpected behaviour and breaks logic that needs to do something like

```
def get_image
  mobile_optimized_attachment.url || attachment.url
end
```

**Comment by sidraval** [comment]
Thank you for reporting this. Unfortunately, we will be deprecating Paperclip and therefore will not have the bandwidth to address this issue.
