### ISSUE TITLE
Clearing and duplication

### ISSUE THREAD

**Issue by brendon** [thoughtbot/paperclip#2346]
For many years now I've been maintaining a couple of extensions to Paperclip that I find quite useful and wondered if there'd be any interest in seeing these two features pulled into Paperclip itself?

Here's the code for now with a quick explanation of each method.

```ruby
# The following are custom developed extensions to Paperclip
#
# The clear_setter allows one to clear the attached file by setting
# [attachment_name]_clear=true via parameters from the browser.
#
# The dup_override supports copying the attachments when a model
# instance is copied.

module Paperclip
  class HasAttachedFile
    def define_with_extensions
      define_without_extensions
      define_clear_setter
      define_dup_override
    end

    alias_method_chain :define, :extensions

    private

    def define_clear_setter
      name = @name
      @klass.send :define_method, "#{@name}_clear=" do |value|
        send(name).clear
      end
    end

    def define_dup_override
      name = @name
      @klass.send :define_method, "dup" do
        copy = super()
        self.class.attachment_definitions.each do |name, options|
          ivar = "@attachment_#{name}"
          copy.instance_variable_set(ivar, nil)

          copy.send(name).assign send(name)
        end

        copy
      end
    end
  end
end
```

The second extension is especially useful if one wants to `dup` a model instance that has attachments. It cleanly copies the original attachments over when the `dup` is saved.

I won't be offended if these are outside of scope :)

**Comment by sidraval** [comment]
Thank you for reporting this. Unfortunately, we will be deprecating Paperclip and therefore will not have the bandwidth to address this issue.
