### ISSUE TITLE
Undefined method 'to_f' for <date> on displaying URL - Rails 5

### ISSUE THREAD

**Issue by hermiti** [thoughtbot/paperclip#2356]
If you run into the following issue while displaying a file attachment URL and you are using the oracle adapter (activerecord_oracle_enhanced-adapter) and Rails 5:

    undefined method `to_f' for <date>

Then you are dealing with the new behavior in activerecord_oracle_enhanced-adapter 1.7+ where table date columns are converted into strict dates and are no longer a timestamp.  In particular, this breaks updated_at which breaks URL.

The work around is to change the table structure itself so that the oracle adapter recognizes the columns correctly.

    change_column :file_attachments, :created_at, :datetime
    change_column :file_attachments, :updated_at, :datetime
    change_column :file_attachments, :document_updated_at, :datetime

_Note: where :file_attachments is your attachment table. and document is the name of your attachment_

Hopefully, this helps someone as it is not directly obvious as to the issue.

Perhaps there should be some way where updated_at handles this issue gracefully?

**Comment by tute** [comment]
> Perhaps there should be some way where updated_at handles this issue gracefully?

If the change is intended, we probably should merge in a change that allows paperclip to deal with both types.

Thanks for your report!

**Comment by sidraval** [comment]
Thank you for reporting this. Unfortunately, we will be deprecating Paperclip and therefore will not have the bandwidth to address this issue.
