### ISSUE TITLE
Fog storage / Google Cloud - request on every URL?

### ISSUE THREAD

**Issue by Gargron** [thoughtbot/paperclip#2358]
I'm trying out the fog storage adapter with Google Cloud and there's two things that immediately stand out:

- Every call to print an attachment URL sends a HTTP request to the Google API
- If the key does not exist in the Google Cloud bucket, rather than display the "missing" image, it throws an Exconn exception because the expected response code is 200 and what it got was 404.

I'm trying to switch away from the S3 storage type so this behaviour is really weird. Can anyone provide any guidance on this?

**Comment by kitop** [comment]
The first issue seems be related to https://github.com/thoughtbot/paperclip/issues/2337.
Try setting the `fog_host` option, and see if the extra network request goes away. It may also help with the second issue. 

Let me know if that helps.

**Comment by sidraval** [comment]
Thank you for reporting this. Unfortunately, we will be deprecating Paperclip and therefore will not have the bandwidth to address this issue.
