### ISSUE TITLE
Issue wih higher level content type (application/cms) and the file command (text/plain)

### ISSUE THREAD

**Issue by RST-J** [thoughtbot/paperclip#2363]
Hello paperclippers,
I'd like to store a CMS (Cryptographic Message Syntax) message as an paperclip attachment in a Rails model. The attachment needs to either be a PDF file or encrypted data as per CMS.
CMS data comes as .pem files which basically contains Base64 encoded data (and hints about start, end and type of the encoded data).
I defined following validation for that:
```ruby
validates_attachment :file, presence: true, content_type: { content_type: ['application/cms', 'application/pdf'] }
```

Furthermore I have defined the `"application/cms"` content type as follows:
```ruby
cms_type = MIME::Type.new(
  'content-type' => 'application/cms',
  'extensions' => %w(pem),
  'friendly' => 'Cryptographic Message Syntax'
)
MIME::Types.add cms_type
```

Now, when I assign an IO that responds to `original_filename` with `"cms.pem"`, to `content_type` with `"application/cms"` and holds valid CMS data in PEM format, then validation yields following error, because the file command returns `"text/plain"` for the file:

```
[paperclip] Content Type Spoof: Filename cms.pem (text/plain from Headers, ["application/cms"] from Extension), content type discovered from file command: text/plain. See documentation to allow this combination.
```
The referred to documentation explains how I could tell paperclip that `".pem"` is a valid extension for `"text/plain"` but this is the opposite form what I want, I'd like the file to be detected as `"application/cms"`.

Is there already a "paperclip way" of achieving this and I just couldn't figure it out yet?

If not I have a suggestion of how this could be integrated into paperclip if you are up to it.
First, I acknowledge that "text/plain" is a valid content type for the file in question. However, that is not always useful - especially when you prefer to handle files by content type rather than extension.
 
I suggest that paperclip offers some way to register custom content type detectors. These detectors are given the tempfile for the attachment as well as the originally supplied content type.
Possible constraints could be that these detectors are only called for certain original content types which they were registered for (literal, array, regex constraints as for content type validation).
The content type detection, validation and spoof detection process then should call registered content type detectors before calling the file command and only proceed with the file command if the detector returns an empty/nil result.
What do you think? I'd also be eager to prepare a pull request for that if I am able to.

**Comment by RST-J** [comment]
Update:
I found out, mime-types already comes with application/cms but does not associate any extensions with it, so instead of adding a second type for it, my initializer is now as follows:
```ruby
MIME::Types['application/cms'].first.tap do |cms_type|
  cms_type.add_extensions 'pem' if cms_type.present?
end
```

The following monkey patching in a paperclip initializer solves the situation for me (but is bad, because of monkey patching and being forced to use exceptions for control flow and 42):
```ruby
  class ContentTypeDetector
    def type_from_file_command
      begin
        OpenSSL::PKCS7.new(File.read(@filepath))
        return 'application/cms'
      rescue ArgumentError # rubocop:disable HandleExceptions
      end
      super
    end
  end

  class MediaTypeSpoofDetector
    def type_from_file_command
      if supplied_content_type == 'application/cms'
        begin
          OpenSSL::PKCS7.new(File.read(@file.path))
          return 'application/cms'
        rescue ArgumentError # rubocop:disable HandleExceptions
        end
      end
      super
    end
  end
```

Another, not directly related, observation: `ContentTypeDetector` uses `FileCommandContentTypeDetector` for asking the file command, `MediaTypeSpoofDetector` does not. Is this intended for some reason? They basically do the same except for the fallback return value but that'd be solved by passing the fallback as parameter to `FileCommandContentTypeDetector`.

**Comment by RST-J** [comment]
The initializer monkey patching above only works for the CMS files I wanted to handle, others crash as I mistakenly treated monkey patching as overriding by inheritance (thanks brain). Fixed monkey patching:
```ruby
module Paperclip
  class ContentTypeDetector
    def type_from_file_command
      return @type_from_file_command unless @type_from_file_command.nil?
      begin
        OpenSSL::PKCS7.new(File.read(@filepath))
        @type_from_file_command = 'application/cms'
      rescue ArgumentError # rubocop:disable HandleExceptions
      end
      @type_from_file_command = FileCommandContentTypeDetector.new(@filepath).detect
    end
  end

  class MediaTypeSpoofDetector
    def type_from_file_command
      if supplied_content_type == 'application/cms'
        OpenSSL::PKCS7.new(File.read(@file.path))
        return 'application/cms'
      else
        Paperclip.run('file', '-b --mime :file', file: @file.path).split(/[:;]\s+/).first
      end
    rescue ArgumentError, Cocaine::CommandLineError
      ''
    end
  end
end
```

**Comment by sidraval** [comment]
Looks like you found a workaround, closing.
