### ISSUE TITLE
Make content_type validation dynamic?

### ISSUE THREAD

**Issue by glyoko** [thoughtbot/paperclip#2364]
I've got a situation where my Paperclip attachments' content_types are dynamic and may be dependent on other factors on the record, or even on the state of the entire app. e.g. A class's valid attachments might usually only accept jpg/gif images, but might also accept png's in certain cases.

I would like to be able to do something like
```
class MyRecord
  validates_attachment :my_asset, content_type: {
    content_type: -> (record) {record.some_valid_content_types},
    not: -> (record) { some_other_logic }
  }
  def some_valid_content_types
    [...]
  end
end
```

I'm thinking about making a PR for this functionality, (probably by changing `Paperclip::Validators::AttachmentContentTypeValidator#validate_whitelist/validate_blacklist` to let them handle lambdas) but I'd like to get some feedback from the maintainers/community about this first.

**Comment by sidraval** [comment]
Thank you for reporting this. Unfortunately, we will be deprecating Paperclip and therefore will not have the bandwidth to address this issue.
