### ISSUE TITLE
How to save s3 image path in DB?

### ISSUE THREAD

**Issue by jhsoare** [thoughtbot/paperclip#2368]
How to save s3 image path in DB?

I would like to save image path in DB, has anyone done this in rails?

Att,

**Comment by jyurek** [comment]
The path is normally calculated based on the `path` option provided to `has_attached_file`. Why do you want to store it in the DB?

**Comment by jhsoare** [comment]
Is this image path consumed by an API, I really do not know if I can do it any other way?
 Thank you very much in advance!

**Comment by davidmccoy** [comment]
The s3 path would just be your s3 bucket address plus the `path` attribute on whatever model `has_attached_file`.

For example, `s3.amazonaws.com/mybucket` + `path`

**Comment by greenygh0st** [comment]
So you are just trying to find a way to get to the path?

You could do something like this in your model which has the attached image:

`def image_url_thumbnail`
    `self.image.url(:thumbnail)`
  `end`

And then in your API controller something like this:

`render :json => {`
  `:persons => @persons.as_json(methods: :image_url_thumbnail)`
`}`

**Comment by XXChester** [comment]
I store the image names in their own table but then I have a flat, optimized table with the path of the primary image stored in it. Our search runs against the flat structure.

Not sure if the OP is using it the same way, but I figured I'd throw it out there as a possible use case.

**Comment by jhsoare** [comment]
Thank You, guys!
