### ISSUE TITLE
Paperclip is incorrectly cropping when given large dimensions

### ISSUE THREAD

**Issue by davidmccoy** [thoughtbot/paperclip#2371]
I've run into an extremely annoying bug that I can't seem to figure out. I trying to centrally crop photos at both iPhone 6/7 resolution and iPhone 6+/7+ resolution, using the following styles:

```
has_attached_file :image,
    styles: {
      normal: "750x1334#",
      plus: "1242×2208#"
    }
```

What's crazy is that the normal style crops correctly, whereas the plus style ignores the height value completely. 

[Here](http://s3.amazonaws.com/curate-social-staging/arts/images/000/000/001/original/540-a20154f4f91f61628d14dabe732b5dd1bfaa19f88ed8ba8a2edd8adb59f4b0ab.jpg?1484343321) is the original image (500x375).

[Here](http://s3.amazonaws.com/curate-social-staging/arts/images/000/000/033/large_cropped/540-a20154f4f91f61628d14dabe732b5dd1bfaa19f88ed8ba8a2edd8adb59f4b0ab.jpg?1484352550) is the iPhone 6/7 resolution (750x1334) (cropped correctly).

[Here](http://s3.amazonaws.com/curate-social-staging/arts/images/000/000/034/large_cropped/540-a20154f4f91f61628d14dabe732b5dd1bfaa19f88ed8ba8a2edd8adb59f4b0ab.jpg?1484352661) is the iPhone 6+/7+ resolution (1242x2208) (cropped incorrectly to 1242x467).

You'll notice that the plus resolution has cropped with the correct width but the incorrect height. I've messed with a bunch of different height/width combinations and ratios and haven't found a definitive point where these incorrect crops begin, but when the crop does fail, the ratio between the correct width and the incorrect height is always around 2.66 repeating.

Does anybody have any idea what could be going on here? I've used many different images with varying sizes and the results are always the same: correct normal crops and incorrect plus crops.

**Comment by jyurek** [comment]
This is super subtle and I may not have noticed if I wasn't looking at it on my phone, so here's a screenshot. The dimensions of the plus image have a actual multiplication "x" instead of the letter x that imagemagick and paperclip expect.

**Comment by jyurek** [comment]
Ok the mobile site makes it hard to upload so I'll upload that when I'm back at a computer. But anyway, retype the dimensions on the plus size and it should work (no copy and paste).

**Comment by davidmccoy** [comment]
@jyurek unfortunately, no. I've created a fresh Rails project (hoping to isolate the cause of this) and manually typed the class, including re-manually typing this line:

```
has_attached_file :image, styles: { plus: "1242x2208#" }
```

And [here](https://s3.amazonaws.com/curate-social-staging/arts/images/000/000/039/plus/540-a20154f4f91f61628d14dabe732b5dd1bfaa19f88ed8ba8a2edd8adb59f4b0ab.jpg) is the resulting (incorrect) crop.

**Comment by jyurek** [comment]
Hmm, ok, then that's weird because I just put that style into our paperclip_demo (running locally) and it seems to have worked fine. What versions of paperclip, rails, ruby, and imagemagick are you using?

**Comment by davidmccoy** [comment]
@jyurek that's encouraging and frustrating at the same time haha. Here are my versions:

Ruby 2.3.0
Rails 2.4.2
Paperclip 5.1.0
ImageMagick 6.9.7-2

**Comment by jyurek** [comment]
You're using Rails 2.4.2? We haven't officially supported that in a long time. Is that also the version of Rails you use when making the fresh app?

**Comment by davidmccoy** [comment]
@jyurek sorry, my dyslexic brain messed up the Rails version 😛 I was using 4.2.4

You were right about the multiplication sign in my original post. However, you can see that I rewrote it correctly and the crop was still incorrect.

However, after upgrading to Rails 4.2.6, the cropping began working correctly. I then switched back to 4.2.4 and it continued to work correctly...and I have no idea why. Anyway, I've upgraded my original application to 4.2.6 and made sure that there were no multiplication symbols and everything seems to be working fine.

Thanks for your help and fingers crossed it was just the Rails version and a rogue multiplication symbol.

**Comment by sidraval** [comment]
Thank you for reporting this. Unfortunately, we will be deprecating Paperclip and therefore will not have the bandwidth to address this issue.
