### ISSUE TITLE
Missing styles not returning default url

### ISSUE THREAD

**Issue by NeoElit** [thoughtbot/paperclip#2373]
Paperclip: 4.3.1

I'm skipping the processing of styles initially on upload and is done over a worker. However paperclip still seem to return the url expecting all styles are already present. Wouldn't it be better if we can return default url itself in case of a missing style?

Currently I'm using an extra attribute in the model to track if the processing is finished or not and handle accordingly. Since paperclip persists only original file info in the db, i'm guessing this is an expected behavior as of now.

**Comment by vfonic** [comment]
+1

**Comment by sidraval** [comment]
Thank you for reporting this. Unfortunately, we will be deprecating Paperclip and therefore will not have the bandwidth to address this issue.
