### ISSUE TITLE
Getting Paperclip::AdapterRegistry::NoHandlerError  when try to update with missing image

### ISSUE THREAD

**Issue by alex3o0** [thoughtbot/paperclip#2377]
I'm using paperclip for manage user's profile pics. but I'm not saving my subfolders in /public/images/* with git. So, I'm missing my images in different pc and when I try to update some user data, I get Paperclip::AdapterRegistry::NoHandlerError because I have not the image. What is the right way to catch this error?

**Comment by vedmant** [comment]
Just out of nothing started to have the same issue.

**Comment by sidraval** [comment]
Thank you for reporting this. Unfortunately, we will be deprecating Paperclip and therefore will not have the bandwidth to address this issue.
