### ISSUE TITLE
There no rake task paperclip:refresh:fingerprints

### ISSUE THREAD

**Issue by deemytch** [thoughtbot/paperclip#2380]
But the documentation here https://github.com/thoughtbot/paperclip#checksum--fingerprint mention it.
Is it rake task that is lost, or the docs are outdated?
ruby 2.4
paperclip 5.1.0
rails 4.2.7.1
Also option `adapter_options: { hash_digest: Digest::SHA256 }` don't do nothing - _fingerprint field is still written as MD5.

**Comment by dra** [comment]
Looks like this has been fixed in 5202acbf4b642230bef71a8dd534bcca11fb4373 five days after 5.1.0 was released. Why has no new release been build since then?

**Comment by angusfretwell** [comment]
Wasted a lot of time trying to reconfigure `hash_digest` 🤦‍♂️

**Comment by stepheneb** [comment]
It took some time to get here after trying and failing to get this to work:
`bin/rake paperclip:refresh:fingerprints`

**Comment by sidraval** [comment]
Looks like there have been new releases with the fix, closing.
