### ISSUE TITLE
How to create new attachment from existing attachment in S3.

### ISSUE THREAD

**Issue by arunkumarg** [thoughtbot/paperclip#2382]
Hi, 
I am trying to solve problem in my application.  However no luck yet.  can you please help me to resolve this. 

I have model called Receipt and it has attachment.  called `file`.  It was created with uploaded image and stored in the S3 Bucket.  say Record_1

Now I want to create new Receipt Record_2 with Record_1 attachment.  I am looking for any one of the two options. 

* Make a copy of Record_1 attachment and assign new copy to Record_2
* Create single reference for both Record_1 & Record_2 to point to same attachment. 

Can you suggest is it possible to acheive.

Thank you

**Comment by kinley** [comment]
@arunkumarg 
did you find some solution for your issue?

**Comment by sidraval** [comment]
Thank you for reporting this. Unfortunately, we will be deprecating Paperclip and therefore will not have the bandwidth to address this issue.
