### ISSUE TITLE
Custom Image Processor

### ISSUE THREAD

**Issue by BilalReffas** [thoughtbot/paperclip#2383]
Is it possible to use a custom image processor? like https://github.com/jcupitt/ruby-vips :)

**Comment by sickrandir** [comment]
Can someone please comment on this? I don't know the internals of paperclip but I recently used ruby-vips to substitute mini-magick in some batches that I had running to overlap and resize transparent PNGs and its a LOT faster. Is it too much work to have another processor or is it something feasible?

**Comment by sidraval** [comment]
Thank you for reporting this. Unfortunately, we will be deprecating Paperclip and therefore will not have the bandwidth to address this issue.
