### ISSUE TITLE
Use Paperclip with Fog and OpenStack Swift

### ISSUE THREAD

**Issue by PatrickFranken** [thoughtbot/paperclip#2384]
We use Paperclip with Fog storage and OpenStack Swift.
Fog OpenStack itself returns an URL which is redirected in most cases. Paperclip takes this into account at 
https://github.com/thoughtbot/paperclip/blob/master/lib/paperclip/storage/fog.rb#L157
and replaces with fog_host

The issue here is at
https://github.com/thoughtbot/paperclip/blob/master/lib/paperclip/storage/fog.rb#L201
host_name_for_directory only supports S3 which completely defeats the purpose of Fog.

How would you modify host_name_for_directory to support other providers than S3? My approach would be to add something like fog_original_host which is used to rewrite the address.

If anyone else has this issue, our current workaround is a monkey path for Paperclip::Storage:Fog
```ruby
module Paperclip
  module Storage
    module Fog
      def host_name_for_directory
        "https://some_host/v1/AUTH_xyz/#{directory_name}"
      end
    end
  end
end
```

**Comment by jeffreyguenther** [comment]
A closely related problem with the `Paperclip::Storage::Fog` is that if you set your `fog_directory` it is not used to generate the url for the uploaded file. Only `fog_host` is used.

It looks like some of the use cases for fog/non-AWS were missed when the storage adapter was implemented.

**Comment by sidraval** [comment]
Thank you for reporting this. Unfortunately, we will be deprecating Paperclip and therefore will not have the bandwidth to address this issue.
