### ISSUE TITLE
Update S3 permissions

### ISSUE THREAD

**Issue by jeffmess** [thoughtbot/paperclip#2385]
Hi there

We currently have a whole whack of images on s3 with public read and we would like to move them to private, I've updated the code so that all new documents added have a private link but how do I go about updating the existing images to be private? Currently if I inspect the instance it shows `@s3_permissions={:default=>:private}` but I can still access it publicly.

Thanks

**Comment by ansnisar** [comment]
Please follow this https://thewebfellas.com/blog/protecting-your-paperclip-downloads to achieve your private link goal

Another link: http://metaskills.net/2009/11/23/authenticated-s3-gets-for-private-objects-using-paperclip/

**Comment by jeffmess** [comment]
Thanks @ansnisar, works now!

**Comment by georgebrock** [comment]
Closing, since you found a solution.
