### ISSUE TITLE
Modify filename for environment

### ISSUE THREAD

**Issue by kiddrew** [thoughtbot/paperclip#2387]
I have a staging environment that automatically syncs with the production environment every night so we can test code on real data, and I'm storing my paperclip attachments in S3.  If I point staging to the same bucket as production, it's able to see the images but it's also possible that staging will overwrite the images in production - that's obviously bad.  

Is there a way that I can point my environments to the same bucket but modify the way Paperclip generates the filename so that it factors in the environment?

**Comment by aditya-kapoor** [comment]
You can always use the environment in the path. Once the syncing gets over then you can copy or sync over the production images with the staging ones.

```
has_attached_file :image, styles: {
    medium: "150x150>", thumb:  "90x90>"},
    path: "#{Rails.env}/:class/:attachment/:id_partition/:style/:filename",
```

**Comment by sidraval** [comment]
Looks like you've found a workaround, closing.
