### ISSUE TITLE
"uninitialized constant Paperclip::Storage::S3::AWS" s3 file upload w/ aws-sdk v2.7.7

### ISSUE THREAD

**Issue by leder11011** [thoughtbot/paperclip#2388]
Hi,

I have a ticket  here:
[stackoverflow](http://stackoverflow.com/questions/42087502/how-to-configure-rails-5-paperclip-5-aws-sdk-2-on-heroku-properly)

But cannot get a working configuration from anybody!

So I think, that I have found a bug in the libraries.

Please have a look...

BR
Gerrit

**Comment by avit** [comment]
Looking at the aws-sdk gem source, their module namespace is `Aws::` but paperclip 4.3 is using `AWS::`, could that be your problem?

**Comment by leder11011** [comment]
I do not know! What do you suggest to do? In the docs there is this information:
NameError: uninitialized constant AWS

If you receive this error, you likely have upgraded to version 2 of the aws-sdk gem unintentionally. Version 2 uses the Aws namespace, not AWS. This allows version 1 and version 2 to be used in the same application.

[AWS](https://github.com/aws/aws-sdk-ruby#nameerror-uninitialized-constant-aws)

**Comment by avit** [comment]
These are compatible versions, use something like one of these groups in your Gemfile depending on your Rails version:

```
gem "rails", ">= 4.2"
gem "paperclip", ">= 5.0"
gem "aws-sdk", ">= 2.0"
```
or

```
gem "rails", "< 4.2"
gem "paperclip", "= 4.3.6" # (4.3.7 has deprecation warnings for pre-upgrade)
gem "aws-sdk", "< 2.0"
```

**Comment by leder11011** [comment]
I already use these versions:
Rails 5.0.1/paperclip 5.1.0/aws-sdk 2.7.3

And I tried downgrading, too!

To no avail...

**Comment by ohiodn8** [comment]
I had a similar issue a while back. I usually don't declare the gem version in my gemfile, but when I had this error, I changed: 
gem 'aws-sdk'  to   gem 'aws-sdk', '~> 2.3'  

bundle update     

I deployed to production and it worked fine

**Comment by rveronese** [comment]
Had a similar problem paperclip 5.1 and aws-sdk 2.5.1. Downgrading to 2.3 worked also for me

**Comment by abepetrillo** [comment]
For others that come here: the downgrade of aws-sdk to 2.3 did not work for me, and I'm on a legacy rails 3 app, so upgrading to papertrail >5 is also not feasible at the moment.

**Comment by BliZZ4RD** [comment]
> For others that come here: the downgrade of aws-sdk to 2.3 did not work for me, and I'm on a legacy rails 3 app, so upgrading to papertrail >5 is also not feasible at the moment.

try to use
gem 'paperclip',              '~> 4.3', '>= 4.3.7'
gem 'aws-sdk',                '~> 3.0', '>= 3.0.1'

it works for me) Rails 3.2.22

**Comment by BliZZ4RD** [comment]
@abepetrillo 
solved :)
Gemfile
`
gem 'rails',                  '3.2.22'
gem 'paperclip',              '4.3.7'
gem 'aws-sdk', '< 2.0'
`
minio should be started with opts
`MINIO_DOMAIN=minio.example.com MINIO_ACCESS_KEY=minio_access_key MINIO_SECRET_KEY=minio_secret_key minio server --address minio.example.com:9000 /path/to/dir`

paperclip initializer

`
  Paperclip::Attachment.default_options.merge!({
    storage: :s3,
    s3_protocol: 'http',
    s3_permissions: 'private',
    s3_region: 'us-east-1',
    s3_credentials: {
      bucket: 'public',
      access_key_id: 'minio_access_key',
      secret_access_key: 'minio_secret_key',
    },
    s3_host_name: 'minio.example.com:9000',
    s3_options: {
      endpoint: "http://minio.example.com:9000",
      use_ssl: false,
      force_path_style: true, # for aws-sdk (required for minio)
    },
    path: ':url'
  })
`

**Comment by sidraval** [comment]
Looks like there are workarounds, closing.

**Comment by maguri** [comment]
```
##################################################
#  NOTE FOR UPGRADING FROM 4.3.0 OR EARLIER       #
##################################################

Paperclip is now compatible with aws-sdk >= 2.0.0.

If you are using S3 storage, aws-sdk >= 2.0.0 requires you to make a few small
changes:

* You must set the `s3_region`
* If you are explicitly setting permissions anywhere, such as in an initializer,
  note that the format of the permissions changed from using an underscore to
  using a hyphen. For example, `:public_read` needs to be changed to
  `public-read`.

For a walkthrough of upgrading from 4 to 5 and aws-sdk >= 2.0 you can watch
http://rubythursday.com/episodes/ruby-snack-27-upgrade-paperclip-and-aws-sdk-in-prep-for-rails-5
```
