### ISSUE TITLE
Custom validations for geometry

### ISSUE THREAD

**Issue by vnazarenko** [thoughtbot/paperclip#2398]
Hello. I found a problem. Someone uploads .png files with nothing inside but with image dimestions 225000x225000. When imagemagic try to process such file it create 50GB tmp file, and looks like hangup forever. So i decided to add custom validation for image dimensions, i tried to do that with something like this:
```
  has_attached_file :file
  validate :image_dimensions_valid

  def image_dimensions_valid
    dimensions = Paperclip::Geometry.from_file(file.queued_for_write[:original].path)
    valid = true
    if dimensions.width > MAX_ALLOWED_WIDTH
      errors.add(:image, "Width must less then #{MAX_ALLOWED_WIDTH}px") 
      valid = false
    end
    if dimensions.height > MAX_ALLOWED_HEIGTH
      errors.add(:image, "Height must be less then #{MAX_ALLOWED_HEIGTH}px") 
      valid = false
    end
    valid
  end
```
But no luck, it tries to save file
```
Command :: identify -format '%wx%h,1' '/var/folders/wc/0nswstgn5_9gr0qdym269hj40000gn/T/ad0234829205b9033196ba818f7a872b20170228-13921-1n4ymlv.png[0]' 2>/dev/null
[paperclip] saving photos/files/000/000/004/original/48151458-853b-45cd-b955-bb2f2d92fafc.jpg
```
How could add validation, so no files are processed?

**Comment by mike-burns** [comment]
We do not currently have a solution to this, sorry.

**Comment by TeTiRoss** [comment]
@vnazarenko you can achieve it with [rails custom validator](https://coderwall.com/p/ba9juq/rails-custom-validator-for-paperclip-image-dimensions).
