### ISSUE TITLE
Paperclip uploading to local storage instead of S3

### ISSUE THREAD

**Issue by adamw005** [thoughtbot/paperclip#2400]
I've tried everything I can find on a bunch of guides. I have no idea why this is happening 
http://stackoverflow.com/questions/42534825/rails-paperclip-not-working-with-aws

**Comment by leder11011** [comment]
Hello Adam,

did you get your rails/paperclip/s3 working? I have not found a working configuration for a month now:
This is where I have put the error description, can you please have a look and compare what you have done to get it working?
[rails_paperclip_s3](http://stackoverflow.com/questions/42087502/how-to-configure-rails-5-paperclip-5-aws-sdk-2-on-heroku-properly)

Thanks in advance!
Gerrit

**Comment by adamw005** [comment]
@leder11011 Sorry, just saw this. I got it working with this: http://stackoverflow.com/questions/42534825/rails-paperclip-not-working-with-aws

**Comment by leder11011** [comment]
@adamw005 
I already tried your answer, but with my current versions of rails/paperclip/aws I have no success. :-(
