### ISSUE TITLE
Using CNAME and https S3_protocol... docs out of date?

### ISSUE THREAD

**Issue by gsaks123** [thoughtbot/paperclip#2402]
The docs state:

`If you use a CNAME for use with CloudFront, you can NOT specify https as your :s3_protocol; This is *not supported* by S3/CloudFront.`

Either this is out of date, or I don't understand the statement that this is not supported.  Currently in production I have:

- https as my S3_protocol
- images are being served via Cloudfront, and are CNAME'd to my own domain name
- an Amazon-provided SSL cert from their ACM product which uses an "alternate domain name"

It's done per these AWS docs:
http://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/cnames-and-https-procedures.html

Everything is working fine in production, but I was initially concerned about the not-supported language in the docs.  Does this mean something different than I thought it did?

**Comment by mike-burns** [comment]
Thank you for reporting this. Unfortunately, we will be deprecating Paperclip and therefore will not have the bandwidth to address this issue.
