### ISSUE TITLE
:content_type_mappings do not work for tex file

### ISSUE THREAD

**Issue by Kopei** [thoughtbot/paperclip#2405]
Hi, I am using paperclip to upload Latex files. But got these errors after following bypass content type checking..

`Command :: PATH=/usr/local/bin/:$PATH; file -b --mime '/var/folders/th/nfthty5j05511dhpy785yhd40000gn/T/9300c96aaec324987ea5ca6e13a02eda20170308-22327-1alv5ev.tex'
[paperclip] Content Type Spoof: Filename qc.tex (application/octet-stream from Headers, ["application/x-tex"] from Extension), content type discovered from file command: text/x-tex. See documentation to allow this combination.
   (3.2ms)  BEGIN
Command :: PATH=/usr/local/bin/:$PATH; file -b --mime '/var/folders/th/nfthty5j05511dhpy785yhd40000gn/T/fe0646e3f6d253cbf3e3c22d15b7960820170308-22327-q3tnjs.png'
Command :: PATH=/usr/local/bin/:$PATH; file -b --mime '/var/folders/th/nfthty5j05511dhpy785yhd40000gn/T/9a09b4dfda82e3e665e31092d1c3ec8d20170308-22327-u83ub8.pdf'
Command :: PATH=/usr/local/bin/:$PATH; file -b --mime '/var/folders/th/nfthty5j05511dhpy785yhd40000gn/T/9300c96aaec324987ea5ca6e13a02eda20170308-22327-6fr0c4.tex'
[paperclip] Content Type Spoof: Filename qc.tex (application/octet-stream from Headers, ["application/x-tex"] from Extension), content type discovered from file command: text/x-tex. See documentation to allow this combination.
   (2.9ms)  ROLLBACK`

In my config/initializers/paperclip.rb
`Paperclip.options[:content_type_mappings] = {
    latex: %w(text/x-tex)
}`

my model
`class Pipeline < ActiveRecord::Base
  
has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
  has_attached_file :pdf
  validates_attachment_content_type :pdf, content_type: "application/pdf"
  has_attached_file :latex
  do_not_validate_attachment_file_type :latex   
#validates_attachment_content_type :latex, content_type: "text/x-tex"
end`

This works fine for pdf and image, but not for tex files. Sorry for bothering.

**Comment by mike-burns** [comment]
Thank you for reporting this. Unfortunately, we will be deprecating Paperclip and therefore will not have the bandwidth to address this issue.
