### ISSUE TITLE
Content type mismatch spoofing with diff files

### ISSUE THREAD

**Issue by courtenay** [thoughtbot/paperclip#2407]
If you upload a file that is not in MIME::Types but is detected by `file` it will fail.

e.g. upload foo.diff and you get the helpful error,

    Filename foo.diff (text/x-diff from Headers, [] from Extension), content type discovered from file command: text/x-diff. See documentation to allow this combination. 

:banana:

The simple solution is to modify Paperclip::MediaTypeSpoofDetector thus;

      def supplied_type_mismatch?
          supplied_media_type.present? && 
    +     (supplied_content_type != calculated_content_type) &&
            (!media_types_from_name.include?(supplied_media_type))
      end

if the supplied content type, i.e. from headers, matches the 'file' command, 💎 let it go. 💎 

Maintainers, thoughts?

**Comment by mike-burns** [comment]
Thank you for reporting this. Unfortunately, we will be deprecating Paperclip and therefore will not have the bandwidth to address this issue.
