### ISSUE TITLE
Content type spoofing - application/octet-stream

### ISSUE THREAD

**Issue by courtenay** [thoughtbot/paperclip#2408]
This library should accept the user-supplied 'application/octet-stream' content type and just override it with whatever the `file` command returns. There are too many client bugs around this particular type. (e.g. android chrome uploads all files as this content type regardless)

Here's one way of just ignoring application/octet streams for a monkeypatch

```diff
module Paperclip
  class MediaTypeSpoofDetector

    def media_type_mismatch?    
+     not_application_octet && 
        (supplied_type_mismatch? || calculated_type_mismatch?)
    end
  end

+  def not_application_octet
+    supplied_media_type != "application/octet-stream"
+  end
end

```

.. alternatively.. we can do something like this, and just ignore octet-stream

```diff
module Paperclip
  class MediaTypeSpoofDetector

    def supplied_content_type
+      if @content_type == "application/octet-stream"
+        @content_type = calculated_content_type
+      else
        @content_type
+      end
    end
  end
end
```

**Comment by courtenay** [comment]
Actually Paperclip::ContentTypeDetector handles this - should handle this type of thing. However based on the things I see in production where assets are failing because they have application/octet-stream content types, it seems all is not well. However I don't have a failing case, so, self-closing.

**Comment by danielbonnell** [comment]
I recently ran into a problem with this where some of my models failed validation for having this as the mime type. Interestingly enough, when you open the file and check, the mime type is usually `image/jpeg`. With that in mind, I came up with a monkey patch that will open the actual file and physically check its mime type if Paperclip thinks its `application/octet-stream`. This is not yet production tested but it seems to work fine in my development environment. 

require 'paperclip'

In `config/initializers/verify_mime_type.rb`:
```
module VerifyMimeType
    # Open remote file using underlying OS and check if its mime type matches what Paperclip
    # thinks it is. Sometimes images uploaded from the web or mobile are determined to have
    # `application/octet-stream` as their content type, causing silent validation errors that
    # break counter caches.
    def verify_mime_type(instance, attachment_name='image')
        interpolated_mime_type = instance.send("#{attachment_name}_content_type".to_sym)
        actual_mime_type = nil

        begin
            Timeout::timeout(3) do
                retries ||= 0

                if interpolated_mime_type == 'application/octet-stream'
                    temp_file = open(instance.send(attachment_name.to_sym).url.prepend('https:'))
                    attachment_path = temp_file.path
                    temp_file&.close
                    actual_mime_type = `file --b --mime-type '#{attachment_path}'`.strip
                else
                    actual_mime_type = interpolated_mime_type
                end
            end
        rescue Timeout::Error => e
            if retires < 1
                retries += 1
                retry
            else
                actual_mime_type = interpolated_mime_type
            end
        end

        return actual_mime_type
    end
end

Paperclip.class_eval { extend VerifyMimeType }

```

Then in any model that is susceptible to this problem:
```before_validation -> { self.image_content_type = Paperclip.verify_mime_type(self, 'image') }, if: Proc.new { |post| post.image_content_type == 'application/octet-stream' }```

Feedback always welcomed!
