### ISSUE TITLE
Paper clip copying image from directory 

### ISSUE THREAD

**Issue by aliabbas-2012** [thoughtbot/paperclip#2410]
Hello I am using following code, but its is giving me following error

irb(main):021:0* image1.image = image
Command :: PATH=/usr/bin:$PATH; file -b --mime '/home/test/a.jpg'
[paperclip] Error while determining content type: Cocaine::CommandNotFoundError

My paper clip version is : 4.2.4
and Rails version is 4.2 
`  image1 = Image.new  `

`  a = "/home/test/a.jpg"  `
`  image = File.new(a)  `

` image1.image = image  `
` image1.save  `
` image.close  `

**Comment by georgebrock** [comment]
It looks like you don't have the `file` command on your path.

A few questions:

- what operating system are you seeing this error on?
- what do you see when you run the command `type file`, and the command `which -a file` from a a terminal?

**Comment by alishahpakneeds** [comment]
I am working on centos 6, above commands are not working , Paper clip works
for  browser upload
but not sure why is not working for url parsing

Thanks

**Comment by georgebrock** [comment]
When you say “above commands are not working”, can you be more specific? Is there any output at all, e.g. an error message?

**Comment by alishahpakneeds** [comment]
I run this command

*type 10.jpg *
-bash: type: 10.jpg: not found

*which -a 10.jpg*

/usr/bin/which: no 10.jpg in
(/home/ali/.rbenv/plugins/ruby-build/bin:/home/ali/.rbenv/plugins/ruby-build/bin:/home/ali/.rbenv/shims:/home/ali/.rbenv/bin:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/sbin:/home/ali/bin)




*Ali Abbas*
*Senior Software Engineer ( Php , Python , Ror)*
*skype : ali.abbas2012*

**Comment by georgebrock** [comment]
Sorry, I wasn't clear. The error seems to be a problem with finding the [`file(1)`](https://linux.die.net/man/1/file) command, so I was asking you to run the exact commands `type file` and `which -a file`, not `type 10.jpg` etc.

**Comment by alishahpakneeds** [comment]
```
[ali@vps Henry Cavill]$ ls -lah
total 4.2M
drwxrwxrwx   2 root root 4.0K Feb 15 10:24 .
drwxrwxrwx 211 root root  12K Feb 15 10:25 ..
-rwxrwxrwx   1 root root  71K Nov  7 03:42 10.jpg
-rwxrwxrwx   1 root root 224K Nov  7 03:35 1.jpg
-rwxrwxrwx   1 root root  90K Nov  7 03:35 2.jpg
-rwxrwxrwx   1 root root 352K Nov  7 03:35 3.jpg
-rwxrwxrwx   1 root root 447K Nov  7 03:35 4.jpg
-rwxrwxrwx   1 root root 1.6M Nov  7 03:36 5.jpg
-rwxrwxrwx   1 root root 116K Nov  7 03:36 6.jpg
-rwxrwxrwx   1 root root 639K Nov  7 03:36 7.jpg
-rwxrwxrwx   1 root root 188K Dec 14 07:33 8.jpg
-rwxrwxrwx   1 root root 454K Nov  7 03:36 9.jpg
-rwxrwxrwx   1 root root  83K Dec 14 07:31 Thumbs.db

```

I have run the following command on my centos ,after I run this command 

```
 which -a file
/usr/bin/which: no file in (/home/ali/.rbenv/plugins/ruby-build/bin:/home/ali/.rbenv/plugins/ruby-build/bin:/home/ali/.rbenv/shims:/home/ali/.rbenv/bin:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/sbin:/home/ali/bin)
```

**Comment by mike-burns** [comment]
You need to install the `file` command.
