### ISSUE TITLE
file_name is not available when setting s3_headers

### ISSUE THREAD

**Issue by cgreening** [thoughtbot/paperclip#2412]
Hi All,

I'm trying to set the content disposition header of an attachment stored on S3

```rb
  has_attached_file :attachment, :storage => :s3, :s3_protocol => 'https', ...
                    :s3_headers => lambda { |asset|
                      { "Content-Disposition" => "attachment; filename=\"#{asset.attachment_file_name}\"" }
                    }
```

Unfortunately attachment_file_name doesn't seem to to be set when the lambda is called so I end up with `attachment; filename=""` in the header.

Is there any way to get the original filename in the s3_headers lambda?

Thanks

**Comment by simonfranzen** [comment]
I am having the same problem. I need to set here csv or xlsx format.

Saving CSV to S3 without explicitly setting Content-Type and Content-Disposition will save the file in wrong content type. I also tried it to merge the extras in a post_process callback, but this also had no effect.

**Comment by mike-burns** [comment]
Thank you for the feature request. Unfortunately we will be deprecating Paperclip and therefore will no longer be accepting new features.

**Comment by zainzafar** [comment]
@simonfranzen what solution did you end up with?
