### ISSUE TITLE
Problem handling filename*= in content-disposition header

### ISSUE THREAD

**Issue by pepawel** [thoughtbot/paperclip#2419]
Hi,

When I do this:

`MyModel.new.attachment = URI.parse 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/84/Example.svg/600px-Example.svg.png'
`

I get exception in #filename_from_content_disposition. It happens because regexp tries to retrieve filename and fails when it is specified in different encoding using "filename*=" instead of "filename=".

The problematic header in server response:

`content-disposition:inline;filename*=UTF-8''Example.svg.png`

Some definitions from https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Disposition

> **filename**
> Is followed by a string containing the original name of the file transmitted. The filename is always optional and must not be used blindly by the application: path information should be striped, and conversion to the server file system rules should be done. This parameter provides mostly indicative information. When used in combination with Content-Disposition: attachment, it is used as the default filename for an eventual 'Save As" dialog presented to the user.
> 
> **filename***
> The parameters "filename" and "filename*" differ only in that "filename*" uses the encoding defined in RFC 5987. When both "filename" and "filename*" are present in a single header field value, "filename*" is preferred over "filename" when both are present and understood.

**Comment by Rajan4436** [comment]
similar problem here...

**Comment by mike-burns** [comment]
Thank you for reporting this. Unfortunately, we will be deprecating Paperclip and therefore will not have the bandwidth to address this issue.
