### ISSUE TITLE
5.1.0 won't upload to S3

### ISSUE THREAD

**Issue by Ravenstine** [thoughtbot/paperclip#2420]
I've followed several different instructions on how to configure Paperclip to upload to S3.  Nothing will work with 5.1.0 and it will simply write to disk with no errors.  Just changing to version 5.0.0 allows for successful uploads to S3.

Essentially, I followed these instructions:
https://devcenter.heroku.com/articles/paperclip-s3

**Comment by hahmed** [comment]
@Ravenstine I was having an issue with this too, I have logged an issue on rails. Wonder if that is a similar issue?

https://github.com/rails/rails/issues/28618

**Comment by mike-burns** [comment]
Thank you for reporting this. Unfortunately, we will be deprecating Paperclip and therefore will not have the bandwidth to address this issue.
