### ISSUE TITLE
Allow to choose frame (page) from a PDF file

### ISSUE THREAD

**Issue by adaRn** [thoughtbot/paperclip#2422]
This was already reported in #2155 and almost fixed.
Probably due to an oversight `lib/paperclip/thumbnail.rb` is still missing `.pdf` in `MULTI_FRAME_FORMATS` array. 

Another problem that arises is that if no frame (page) is chosen, current implementation falls back on `[0]` frame. But there are cases when frame mustn't be declared explicitly. For example no frame declaration in conjunction with `-append` parameter will make `convert` yield one image in which the pages are stacked vertically.

**Comment by adaRn** [comment]
I made a PR addressing the first part of the issue. I have no idea how to come at the second problem. I've tried setting `frame_index` to `''` or `*`, meaning `convert` would get `[]` or `[*]`, but none of them work.

**Comment by mike-burns** [comment]
Thank you for the feature request. Unfortunately we will be deprecating Paperclip and therefore will no longer be accepting new features.
