### ISSUE TITLE
Uppercase entries in content_type_mappings ignored

### ISSUE THREAD

**Issue by nbdavies** [thoughtbot/paperclip#2425]
A particular attachment can have files with an arbitrary file extension ("filename.ARBITRARY"), where the contents should be plain text. 

In the model, I have:
```
validates_attachment_content_type :file, content_type: ['text/plain', 'text/csv']
```

In the paperclip initializer, I have:
```
Paperclip.options[:content_type_mappings] = {
  ARBITRARY: 'text/plain'
}
```

I had to mess with the syntax quite a while, look at a lot of examples, and dig into the source code before realizing that the file extension is downcased before it's looked for in content_type_mappings:

```
def filename_extension
  File.extname(@name.to_s.downcase).sub(/^\./, '').to_sym
end
```

I guess downcasing can be convenient for not requiring people to list a bunch of variants for common extensions that are seen in upper or lower case. But if you're dealing with a custom file extension that you only ever expect to be in uppercase, this is unintuitive. 

While someone like me may be working with a file extension that they only ever see in uppercase, I don't think we need to worry about people needing different content_type_mappings for the same file extension in upper vs. lower case. The file system itself would make no such distinction. So my suggestion would be to automatically lowercase the content_type_mappings hash keys. Something like this:

```
def mapped_content_type
  mappings = Paperclip.options[:content_type_mappings].map{|extension, _| extension.downcase}.to_h
  mappings[filename_extension]
end
```

**Comment by mike-burns** [comment]
Thank you for the feature request. Unfortunately we will be deprecating Paperclip and therefore will no longer be accepting new features.
