### ISSUE TITLE
Compressing text attachments

### ISSUE THREAD

**Issue by cheerfulstoic** [thoughtbot/paperclip#2427]
I've been searching for a bit and I can't find an answer to the problem that I'm trying to solve.

We're attaching text files to our models and because there is a lot of text we'd like to have the text be stored in gzip format on S3.  How could I create a plugin which transparently compresses files before storing them on S3 and then uncompresses them automatically when they are asked for?

I see the "processors" functionality, but as far as I can tell that's just one way (saving to the file store).  Is there something with hooks going both ways?  It would be particularly good to have it be under the covers (rather than on the model) because if I try to save the compressed data paperclip will complain that the file type is wrong

**Comment by mike-burns** [comment]
Nothing built-in for unprocessing, sorry.
