### ISSUE TITLE
ruby 2.4

### ISSUE THREAD

**Issue by lws68825** [thoughtbot/paperclip#2428]
Hi, does paperclip 5.1.0 work with ruby 2.4.1?

**Comment by leder11011** [comment]
I do not think so: i tried rails 5.0.1 with AWS S3 and did not go further
than this
http://stackoverflow.com/questions/42087502/how-to-configure-rails-5-paperclip-5-aws-sdk-2-on-heroku-properly

BR
Gerrit

Am 13.04.2017 04:23 schrieb "lws68825" <notifications@github.com>:

**Comment by morgoth** [comment]
yes, it works - we're using 2.4.1 with paperclip ;-) - @lws68825 can you close the issue?
