### ISSUE TITLE
NotImplementedError: #exists? is not implemented for Aws::S3::Object

### ISSUE THREAD

**Issue by janvarljen** [thoughtbot/paperclip#2430]
I'm updating from paperclip 4.3.6 -> 5.1.0

I also updated aws-sdk from 1.67.0 -> 2.0.34 and added the configuration s3_region param...

Everything seems to be working fine on create but I keep getting this error when I try to change/remove the file:

``` ruby 
attachment.file = nil
```

**NotImplementedError: #exists? is not implemented for Aws::S3::Object**
/Users/jan/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/aws-sdk-resources-2.0.34/lib/aws-sdk-resources/resource.rb:47:in `rescue in exists?'

**Comment by janvarljen** [comment]
another way to reproduce the error is to just call:

```ruby
attachment.file.exists?
```

**Comment by kitop** [comment]
@janvarljen according to gemspec and as noted in the [README](https://github.com/thoughtbot/paperclip#understanding-storage), it requires aws-sdk ~> 2.3.0.
Have you tried upgrading your aws-sdk version?

**Comment by janvarljen** [comment]
@kitop I'm using the paperclip 5.1.0 version and if you read the [README](https://github.com/thoughtbot/paperclip/tree/v5.1.0#understanding-storage) of that exact version it states aws-sdk '>= 2.0.34'

you referenced the README of the "master" version which is not released to rubygems yet

but I also tried the 2.3.22 and the newest 2.9.7 version and they all had the exact same issue

**Comment by kitop** [comment]
@janvarljen you're right, my bad, sorry!

**Comment by janvarljen** [comment]
I fixed the issue.

It was related to something completely different (misconfiguration of Aws::Credentials) and the error was happening deep inside the aws-sdk gem but because the exists? method rescues from NoMethodError:

https://github.com/aws/aws-sdk-ruby/blob/v2.6.10/aws-sdk-resources/lib/aws-sdk-resources/resource.rb#L137

it was being reported as #exists? is not implemented for Aws::S3::Object...

I'm closing this
