### ISSUE TITLE
"no implicit conversion of nil into String" - While Saving Pdf

### ISSUE THREAD

**Issue by credi-himanshu** [thoughtbot/paperclip#2432]
a= Asset.new
 a.object = URI.parse("http://rgi.edu.in/rgi_pdf/Paulo_Coelho_-_The_Alchemist(1).pdf")
a.save

This happens only in the case of documents and not with images.

TypeError: no implicit conversion of nil into String
	from /home/karan/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/fileutils.rb:1583:in `path'
	from /home/karan/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/fileutils.rb:1583:in `fu_each_src_dest0'
	from /home/karan/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/fileutils.rb:1569:in `fu_each_src_dest'
	from /home/karan/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/fileutils.rb:402:in `cp'
	from /home/karan/.rvm/gems/ruby-2.3.1/gems/paperclip-4.2.4/lib/paperclip/io_adapters/attachment_adapter.rb:25:in `copy_to_tempfile'
	from /home/karan/.rvm/gems/ruby-2.3.1/gems/paperclip-4.2.4/lib/paperclip/io_adapters/attachment_adapter.rb:19:in `cache_current_values'
	from /home/karan/.rvm/gems/ruby-2.3.1/gems/paperclip-4.2.4/lib/paperclip/io_adapters/attachment_adapter.rb:11:in `initialize'
	from /home/karan/.rvm/gems/ruby-2.3.1/gems/paperclip-4.2.4/lib/paperclip/io_adapters/registry.rb:29:in `new'
	from /home/karan/.rvm/gems/ruby-2.3.1/gems/paperclip-4.2.4/lib/paperclip/io_adapters/registry.rb:29:in `for'
	from /home/karan/.rvm/gems/ruby-2.3.1/gems/paperclip-4.2.4/lib/paperclip/validators/media_type_spoof_detection_validator.rb:7:in `validate_each'
	from /home/karan/.rvm/gems/ruby-2.3.1/gems/activemodel-4.2.6/lib/active_model/validator.rb:151:in `block in validate'
	from /home/karan/.rvm/gems/ruby-2.3.1/gems/activemodel-4.2.6/lib/active_model/validator.rb:148:in `each'
	from /home/karan/.rvm/gems/ruby-2.3.1/gems/activemodel-4.2.6/lib/active_model/validator.rb:148:in `validate'
	from /home/karan/.rvm/gems/ruby-2.3.1/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:455:in `public_send'
	from /home/karan/.rvm/gems/ruby-2.3.1/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:455:in `block in make_lambda'
	from /home/karan/.rvm/gems/ruby-2.3.1/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:182:in `block in conditional'
... 30 levels...
	from /home/karan/.rvm/gems/ruby-2.3.1/gems/railties-4.2.6/lib/rails/commands/console.rb:9:in `start'
	from /home/karan/.rvm/gems/ruby-2.3.1/gems/railties-4.2.6/lib/rails/commands/commands_tasks.rb:68:in `console'
	from /home/karan/.rvm/gems/ruby-2.3.1/gems/railties-4.2.6/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /home/karan/.rvm/gems/ruby-2.3.1/gems/railties-4.2.6/lib/rails/commands.rb:17:in `<top (required)>'
	from /home/karan/.rvm/gems/ruby-2.3.1/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
	from /home/karan/.rvm/gems/ruby-2.3.1/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `block in require'
	from /home/karan/.rvm/gems/ruby-2.3.1/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /home/karan/.rvm/gems/ruby-2.3.1/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
	from /home/karan/Projects/credi_health/bin/rails:9:in `<top (required)>'
	from /home/karan/.rvm/gems/ruby-2.3.1/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:268:in `load'
	from /home/karan/.rvm/gems/ruby-2.3.1/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:268:in `block in load'
	from /home/karan/.rvm/gems/ruby-2.3.1/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /home/karan/.rvm/gems/ruby-2.3.1/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:268:in `load'
	from /home/karan/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /home/karan/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'

**Comment by mike-burns** [comment]
Thank you for reporting this. Unfortunately, we will be deprecating Paperclip and therefore will not have the bandwidth to address this issue.
