### ISSUE TITLE
Geometry detection needs to be more robust

### ISSUE THREAD

**Issue by JanneMantyharju** [thoughtbot/paperclip#2440]
I have a customer regularly sending broken PDFs. Paperclip uses identify command and trusts it either returns the geometry or nothing at all. The problem is that for these files identify returns error message in stdout and the proper geometry after that. I think the underlying problem is in ghostscript which identify uses that it writes that one particular error to stdout instead of stderr where it would get ignored properly.

I did an ugly fix to geometry_parser_factory.rb by checking if the string contains newline and if so discarding anything before that. This is not proper solution, I'd recommend fixing the regexp to ignore everything before matching the geometry AND checking that we got proper geometry before returning it to avoid crashing.

**Comment by mike-burns** [comment]
Thank you for reporting this. Unfortunately, we will be deprecating Paperclip and therefore will not have the bandwidth to address this issue.
