### ISSUE TITLE
Cannot attach XLS (But DOC works)

### ISSUE THREAD

**Issue by starrychloe** [thoughtbot/paperclip#2445]
http://stackoverflow.com/questions/43927006/paperclip-cannot-attach-xls-but-doc-works

I cannot attach a XLS file, but DOC works:

>Attachments file content type is invalid<br>
>Attachments file is invalid

Here is the log:

    Parameters: ... "files"=>[#<ActionDispatch::Http::UploadedFile:0x0000000daf7730 @tempfile=#<Tempfile:C:/Users/Chloe/AppData/Local/Temp/RackMultipart20170511-47156-ym774u.xls>, @original_filename="Chocolate_Store1.xls", @content_type="application/vnd.ms-excel", @headers="Content-Disposition: form-data; name=\"deal[files][]\"; filename=\"Chocolate_Store1.xls\"\r\nContent-Type: application/vnd.ms-excel\r\n">],
    ...
    Command :: file -b --mime "C:/Users/Chloe/AppData/Local/Temp/1f1fb4d71efc0bd245abd7b5b9aa661220170511-47156-1rqzd0q.xls"
       (1.0ms)  ROLLBACK
      Rendering deals/edit.html.erb within layouts/application

When I test the type:

    >file -b --mime "C:/Users/Chloe/AppData/Local/Temp/1f1fb4d71efc0bd245abd7b5b9aa661220170511-47156-1rqzd0q.xls"
    application/vnd.ms-office; charset=binary

I have this type in my accept list:

    class Attachment < ApplicationRecord
      has_attached_file :file
      validates_attachment_content_type :file, content_type: [
        "application/pdf", "application/msword", 
        "application/vnd.openxmlformats-officedocument.wordprocessingml.document", 
        "application/vnd.oasis.opendocument.text",
        "application/vnd.ms-excel",
        "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
        "application/vnd.oasis.opendocument.spreadsheet"
       ]
    
    end

Rails 5.0.2, Paperclip 5.1.0, File 5.04 (DevKit)

**Comment by wrkrb33** [comment]
@starrychloe did you find a fix for this?  I am experiencing the same problem.
