### ISSUE TITLE
Saving resource with attached image by setting schameless url

### ISSUE THREAD

**Issue by 1a2b** [thoughtbot/paperclip#2446]
Hi!

I parse some page and take images, that represents like protocol relative urls, and after assign for my resource this image I have exception
```
class ResourceClass < ApplicationRecord
...
has_attached_file(
      :image,
      styles: {
        original: {geometry: '100%', format: :jpg, storage_type: OBJ_STORAGE_NORMAL},
        thumb: {geometry: '200>', format: :jpg, storage_type: OBJ_STORAGE_THUMB},
        thumb_small: {geometry: 'x100>', format: :jpg, storage_type: OBJ_STORAGE_THUMB_SMALL}
      },
      storage_id: OBJ_STORAGE_ID
    )
...
```
`some_resource.image = '//url_for_image.jpg'`
`Paperclip::AdapterRegistry::NoHandlerError`

here is reason of this exception
[https://github.com/thoughtbot/paperclip/blob/master/lib/paperclip/io_adapters/http_url_proxy_adapter.rb#L4](https://github.com/thoughtbot/paperclip/blob/master/lib/paperclip/io_adapters/http_url_proxy_adapter.rb#L4)

url like http(s)://www.images/image.jpg is valid, but protocol relative urls are not.

Should I create pull request and correcting regex pattern? Or it is only my problem and I have to check ulrs that already parsed and insert  protocol http: before assign to resource?

**Comment by sidraval** [comment]
Thank you for reporting this. Unfortunately, we will be deprecating Paperclip and therefore will not have the bandwidth to address this issue.
