### ISSUE TITLE
stubbing s3 upload in rspec with factory girl

### ISSUE THREAD

**Issue by aandis** [thoughtbot/paperclip#2452]
The `shoulda_macros` have a method called [`paperclip_fixture`](https://github.com/thoughtbot/paperclip/blob/093b4da18444d883de826f58628089c2f480d461/shoulda_macros/paperclip.rb#L97) for stubbing s3 uploads in specs. Came across this [post](https://robots.thoughtbot.com/testing-paperclip-s3) which described how to use them. But the post is outdated and doesn't work anymore. So what's the recommended way to go about this? I tried

```
FactoryGirl.define do
  factory :user do
    avatar { paperclip_fixture("user", "thumb", "png") }
  end
end
```

but I get
```
undefined method `paperclip_fixture' for #<FactoryGirl::SyntaxRunner:0x007f4acdd6fc80>
```

**Comment by laclance** [comment]
https://stackoverflow.com/questions/31650949/rails-4-paperclip-factorygirl-file-uploading
