### ISSUE TITLE
Paperclip throws a Validation Error with png and jpeg images

### ISSUE THREAD

**Issue by NordGus** [thoughtbot/paperclip#2453]
This doesn't make sense. On Friday I change PCs and my project stopped working.
Now every time I try to upload an image i got this error:
`ActiveRecord::RecordInvalid: Validation failed: Cover has contents that are not what they are reported to be`

The bizarre, the project still works on my old PC, but in the new one it doesn't.

Please help me make sense of this. (I work on Windows)

**Comment by mk-nyein** [comment]
See the stackoverflow link also.

**Comment by chunkingz** [comment]
if you are working on windows, make sure you have "file" installed, please read the documentation of paperclip you'll see how to install.
