### ISSUE TITLE
'User update' fails

### ISSUE THREAD

**Issue by mk-nyein** [thoughtbot/paperclip#2454]
When update user information, click 'Update User' fails to redirect 'users/:id' and the following error encounters.
<strong>No route matches [PATCH] "/users"</strong>

This is happening because in users/_form.html.erb, we changed

<%= form_for @user, html: { :class => 'form-horizontal' } do |form| %> to 
<%= form_for @user, url: users_path, html: { multipart: true } do |form| %>

as suggested in the documentation.
In documentation, 
<h4>Edit and New Views</h4>

<%= form_for @user, url: users_path, html: { multipart: true } do |form| %>
  <%= form.file_field :avatar %>
<% end %>
<h4>Edit and New Views with Simple Form</h4>

<%= simple_form_for @user, url: users_path do |form| %>
  <%= form.input :avatar, as: :file %>
<% end %>

-------------------------------------
The problem lies in <i>form_for @user <strong>, url: users_path </strong>, html: { multipart: true } do |form| </i>.
url: users_path leads only to '/users/' whether post, put/patch.
But the actual user update route (default by ruby on rails/ RESTful), is /'users/:id' with put/patch.

Please change <%= form_for @user, url: users_path, html: { multipart: true } do |form| %>
to <%= form_for @user, html: { multipart: true } do |form| %> in <strong> Edit and New Views </strong>.

**Comment by sidraval** [comment]
Thank you for reporting this. Unfortunately, we will be deprecating Paperclip and therefore will not have the bandwidth to address this issue.
