### ISSUE TITLE
ImageMagick Upgrade Removes Convert/Identify

### ISSUE THREAD

**Issue by bradlis7** [thoughtbot/paperclip#2455]
The latest versions of ImageMagick no longer includes `convert` or `identify`. Paperclip does not seem to be compatible with the updates.

**Comment by janko-m** [comment]
Looking at the bottom of http://imagemagick.org/script/command-line-tools.php, it seems that the solution for this would be just prepending `magick` to the ImageMagick 6 commands, like `magick convert` and `magick identify`.

**Comment by TheMasterGabriel** [comment]
#2316 #2332 - I believe you can download the dynamic version with the "legacy" option checked and it will install the commands as separate executables.

**Comment by josephpage** [comment]
Paperclip is only tested with Imagemagick 6.7.7 which is the latest version today for Debian users : [packages.ubuntu.com](https://packages.ubuntu.com/trusty/imagemagick)
PR accepted to support 7.x version !

**Comment by sidraval** [comment]
Thank you for reporting this. Unfortunately, we will be deprecating Paperclip and therefore will not have the bandwidth to address this issue.
