### ISSUE TITLE
Parallel conversion and uploading of the styles

### ISSUE THREAD

**Issue by dmitry** [thoughtbot/paperclip#2457]
Is there are an easy way to implement parallel conversion and uploading of a styles?

Lets say attachment has 10 styles. When doing parallel conversion and uploading in threads then speedup could be gained for almost 10x times, so instead of 30s, everything could take up to 5s.

**Comment by sidraval** [comment]
Thank you for reporting this. Unfortunately, we will be deprecating Paperclip and therefore will not have the bandwidth to address this issue.
