### ISSUE TITLE
HttpUrlProxyAdapter chokes on square brackets

### ISSUE THREAD

**Issue by kevsherman** [thoughtbot/paperclip#2459]
When passing a url with a square bracket, it chokes here in the initializer: 
```ruby
module Paperclip
  class HttpUrlProxyAdapter < UriAdapter

    REGEXP = /\Ahttps?:\/\//

    def initialize(target)
      super(URI(URI.escape(target)))
    end

  end
end
```

Since `URI.escape(target)` doesn't escape the square brackets, the attempt to create a `URI` object throws a `URI::InvalidURIError: bad URI(is not URI?)` error.

eg: 

```ruby
target = "http://example.com[xyz]"
URI.escape(target)
#=> "http://example.com[xyz]"
URI(URI.escape(target))
#=> URI::InvalidURIError: bad URI(is not URI?): http://example.com[1]
```

As [issue 2253](https://github.com/thoughtbot/paperclip/issues/2253) points out, passing in an already escaped url causes this same method to choke, thanks to it getting escaped twice.

Attempting to only escape the square brackets still results in a double escaping:

```ruby
bracket_escaped_target = "http://example.com%5Bxyz%5D"
URI.escape(bracket_escaped_target)
#=> "http://example.com%255Bxyz%255D"
URI(URI.escape(bracket_escaped_target))
#=> <URI::HTTP http://example.com%255Bxyz%255D>
```

The resulting generates a valid URI object, but its no longer points where it needs to.  

This underlying issue with `URI` is nicely stated here [https://bugs.ruby-lang.org/issues/12235](https://bugs.ruby-lang.org/issues/12235)

Perhaps using `CGI.escape` or `URI.encode_www_form_component` would better serve the purpose.

**Comment by andresbravog** [comment]
what about

```ruby
[20] pry(main)> bracket_escaped_target = "http://example.com%5Bxyz%5D"
=> "http://example.com%5Bxyz%5D"
[21] pry(main)> CGI.escape(CGI.unescape(bracket_escaped_target))
=> "http%3A%2F%2Fexample.com%5Bxyz%5D"
[22] pry(main)> target = "http://example.com[xyz]"
=> "http://example.com[xyz]"
[23] pry(main)> CGI.escape(CGI.unescape(bracket_escaped_target))
=> "http%3A%2F%2Fexample.com%5Bxyz%5D"
```

**Comment by sidraval** [comment]
Thank you for reporting this. Unfortunately, we will be deprecating Paperclip and therefore will not have the bandwidth to address this issue.
