### ISSUE TITLE
Can't upload apple certificate 

### ISSUE THREAD

**Issue by vikasvr** [thoughtbot/paperclip#2460]
Whenever i try to upload apple certificate (.p12 extension file) it returns content_type  "application/octet-stream" and "text/plain" content-type for json files . Mimemagic method can't read these files appropriately , thus return nil value and then file command returns content-types mentioned above.

What's the solution to get appropriate content-type for both apple certificate and JSON extension files. Also for csv, js and css files.

**Comment by sidraval** [comment]
Thank you for reporting this. Unfortunately, we will be deprecating Paperclip and therefore will not have the bandwidth to address this issue.
