### ISSUE TITLE
validates_attachment_file_name not behaving as expected

### ISSUE THREAD

**Issue by bitops** [thoughtbot/paperclip#2461]
Hi all! I am trying to implement a validation that ensures that only filenames containing lowercase alphanumeric characters (numbers included) and underscores are allowed through. I.e., no special characters, no uppercase, etc.

This is my validation:

```ruby
validates_attachment_file_name :audio_file, matches: [/^[a-z0-9_]+\.mp3$/]
```

I tested out the regex on [Rubular](http://rubular.com/) and I believe I have written it correctly. However, Paperclip is allowing filenames containing spaces and special characters like `%`. 

For what it's worth, I'm using S3 as my upload store.

Am I using it incorrectly? Or do I have the wrong expectation here? Thanks so much.

**Comment by sidraval** [comment]
Thank you for reporting this. Unfortunately, we will be deprecating Paperclip and therefore will not have the bandwidth to address this issue.
