### ISSUE TITLE
Directly inheriting from ActiveRecord::Migration is not supported

### ISSUE THREAD

**Issue by acandael** [thoughtbot/paperclip#2465]
this error is given when trying to run a migration generated with the paperclip generator:

    rails g paperclip absence document

the error is:

    Directly inheriting from ActiveRecord::Migration is not supported. Please specify
     the Rails release the migration was written for:

the Rails version I use is 5.1.2

I fixed the issue by putting
    [5.1] 
at the end of ActiveRecord::Migration:

    class AddAttachmentDocumentToAbsences < ActiveRecord::Migration[5.1]

**Comment by jackellenberger** [comment]
Same issue, same solution. 
```
diff --git a/db/migrate/20170718022803_add_attachment_image_to_posts.rb b/db/migrate/20170718022803_add_attachment_image_to_posts.rb
index accf44e..93f1785 100644
--- a/db/migrate/20170718022803_add_attachment_image_to_posts.rb
+++ b/db/migrate/20170718022803_add_attachment_image_to_posts.rb
@@ -1,4 +1,4 @@
-class AddAttachmentImageToPosts < ActiveRecord::Migration
+class AddAttachmentImageToPosts < ActiveRecord::Migration[5.1]
   def self.up
     change_table :posts do |t|
       t.attachment :image
```

**Comment by stinnett-casey** [comment]
Same issue, same work around. I think a better solution would be to have Paperclip get the current Rails version and add that automatically. Unless I am missing something?
