### ISSUE TITLE
[QUESTION] Did not report that I did not have the imagemagick

### ISSUE THREAD

**Issue by YuriFontella** [thoughtbot/paperclip#2466]
Good evening, I have the following configuration on paperclip: `:styles => { :thumb => "100x100>" }`. After some uploads I realized that I was not generating the thumb folder, just the original one. I had not installed the imagemagick on the server.

What is the possibility, that I generate the thumb folder for those images that have already been uploaded?

**Comment by sidraval** [comment]
Thank you for reporting this. Unfortunately, we will be deprecating Paperclip and therefore will not have the bandwidth to address this issue.
