### ISSUE TITLE
Make -layers "optimize" optional for animated gifs

### ISSUE THREAD

**Issue by markdavies** [thoughtbot/paperclip#2467]
#1588 brings up an issue with the layers "optimize" default causing quality issues. I also found that my animated gifs were leaving artefacts between frames when this was turned on too. See below for example output:

![testgif_resize](https://user-images.githubusercontent.com/320683/28092043-68f8101e-66d5-11e7-8ef3-54c369642f1a.gif)

Versus without:

![testgif_resize](https://user-images.githubusercontent.com/320683/28092090-869edc4c-66d5-11e7-95a3-7895a35c090a.gif)

Can we make this command optional?

**Comment by andrewhood125** [comment]
@markdavies I ran into this issue with non-animated gifs. We were getting a large amount of artifacts. 

I was able to fix the issue by changing the order of flags in the optimize command for gifs. 
Check this out: https://github.com/ImageMagick/ImageMagick/issues/57

**Comment by sidraval** [comment]
Looks like there's a workaround, closing.
