### ISSUE TITLE
Interpolation skipped if interpolated variable name starts with ':clean'

### ISSUE THREAD

**Issue by AvaelKross** [thoughtbot/paperclip#2468]
Version: 5.1.0

Example code:

```
has_attached_file :my_pdf, { styles: {}, path: ':cleanpath/pdfs/:id/:basename.:extension'}
```

```
Paperclip.interpolates :clean_path do |_attachment, _style|
  if Paperclip::Attachment.default_options[:storage] == :filesystem
    ":rails_root/public/system"
  else
    'system'
  end
end
```

This code in development env creates a folder named ':rails_root' in .. rails root folder. Same with any other interpolations inside `:cleanpath`. If I rename my custom interpolation, everything works. I tried:

:clean_path - doesn't work
:cleanpath - doesn't work
:any_other_path - works
:anyotherpath - works

So I guess the problem is somehow related to 'clean' part at the start.. Just ridiculous :) I'll try to investigate later if nobody else wants to

**Comment by sidraval** [comment]
Thank you for reporting this. Unfortunately, we will be deprecating Paperclip and therefore will not have the bandwidth to address this issue.
