### ISSUE TITLE
Skip original file upload via Paperclip

### ISSUE THREAD

**Issue by asad-nga** [thoughtbot/paperclip#2469]
Is there a way to skip original file from being uploaded. I just want the style on the basis of the parameter which will be a url.

video --> "S3_URL"

has_attached_file :video, styles: {
    small: ['640x', :jpeg],
    medium: ['750x', :jpeg],
    large: ['1242x', :jpeg]
  }

I just want the images but by default the original file as a video is being uploaded. Any way to restrict it.

**Comment by sidraval** [comment]
Thank you for reporting this. Unfortunately, we will be deprecating Paperclip and therefore will not have the bandwidth to address this issue.
