### ISSUE TITLE
how to display an encrypted file from S3

### ISSUE THREAD

**Issue by natron19** [thoughtbot/paperclip#2473]
I have set up an app that successfully uploads encrypted files on S3 using the settings below:

```ruby
has_attached_file :file, s3_permissions: :private,
                         s3_server_side_encryption: "AES256"
```
Now I cannot access the image using the S3 URL and I'm not sure how to display that file in my application. Not sure if I am supposed to be decrypting the file as I am not specifying an encryption key using the paperclip setup. Am I missing something?

**Comment by nikhgupta** [comment]
I am having the same issue. Not sure how to display the file. Any pointers here will help :)

**Comment by sidraval** [comment]
Thank you for reporting this. Unfortunately, we will be deprecating Paperclip and therefore will not have the bandwidth to address this issue.
