### ISSUE TITLE
Styles are not being saved to S3

### ISSUE THREAD

**Issue by heroic** [thoughtbot/paperclip#2474]
I run this command:  RAILS_ENV=production rake paperclip:refresh CLASS=Offer

Here's my /environments/production.rb

```
  config.paperclip_defaults = {
    storage: :s3,
    bucket: 'test',
    s3_region: 'us-east-1',
    s3_host_name: 's3-us-east-1.amazonaws.com',
    s3_protocol: 'https',
    s3_credentials: {
      access_key_id: ENV['S3_AWS_ID'],
      secret_access_key: ENV['S3_AWS_KEY']
    }
  }
```

Expected

`Styles to be uploaded to S3.`

Output

```
I, [2017-07-28T21:59:06.703509 #390]  INFO -- : [paperclip] saving /offers/pictures/000/000/010/original/5.png
I, [2017-07-28T21:59:06.753502 #390]  INFO -- : [paperclip] saving /offers/pictures/000/000/010/320/5.webp
I, [2017-07-28T21:59:06.793001 #390]  INFO -- : [paperclip] saving /offers/pictures/000/000/010/480/5.webp
I, [2017-07-28T21:59:06.834175 #390]  INFO -- : [paperclip] saving /offers/pictures/000/000/010/640/5.webp
I, [2017-07-28T21:59:06.885716 #390]  INFO -- : [paperclip] saving /offers/pictures/000/000/010/1280/5.webp
I, [2017-07-28T21:59:06.909021 #390]  INFO -- : [paperclip] saving /offers/pictures/000/000/010/1920/5.webp
D, [2017-07-28T21:59:06.938724 #390] DEBUG -- :    (0.7ms)  BEGIN
D, [2017-07-28T21:59:06.941056 #390] DEBUG -- :   SQL (0.8ms)  UPDATE "offers" SET "picture_file_name" = $1, "picture_updated_at" = $2, "updated_at" = $3 WHERE "offers"."id" = $4  [["picture_file_name", "5.png"], ["picture_updated_at", "2017-07-28 21:59:05.443568"], ["updated_at", "2017-07-28 21:59:06.939161"], ["id", 10]]
D, [2017-07-28T21:59:06.943180 #390] DEBUG -- :    (1.7ms)  COMMIT
```

**Comment by stavskiys** [comment]
+1, only original photo present on s3 after processing

I am using paperclip (5.1.0): 
`config.paperclip_defaults = {
        storage: :s3,
        s3_credentials: {
          bucket: ENV['AWS_BUCKET'],
          s3_region: ENV['AWS_REGION'],
          access_key_id: ENV['AWS_ACCESS_KEY_ID'],
          secret_access_key: ENV['AWS_SECRET_ACCESS_KEY']
        },
        s3_protocol: 'https',
        path: ':class/:id_partition/:basename_:style.:extension',
        url: ':s3_eu_url'
      }`

**Comment by Yanchek99** [comment]
+1, only seeing one style on s3 with no original
I am using paperclip (5.1.0):

```
config.paperclip_defaults = {
    storage: :fog,
    fog_credentials: {
      aws_access_key_id: ENV['AWS_ACCESS_KEY_ID'],
      aws_secret_access_key: ENV['AWS_SECRET_ACCESS_KEY'],
      provider: 'AWS',
      region: 'us-west-2',
      scheme: 'https'
    },
    fog_directory: ENV['S3_BUCKET_NAME']
  }
```

**Comment by stavskiys** [comment]
I found a time for looking on it more detail. I resolved the issue. In my case it was spoofing error which blocked a styles processing. It because  original image which requested from s3 return a wrong content type. It can be specified during upload but not in my case... In any case the issue not actual any more for me.

**Comment by sidraval** [comment]
Thank you for reporting this. Unfortunately, we will be deprecating Paperclip and therefore will not have the bandwidth to address this issue.
