### ISSUE TITLE
Setting s3_headers after post_process does not work

### ISSUE THREAD

**Issue by paulmwatson** [thoughtbot/paperclip#2475]
I am trying to set the `Content-Disposition` of an attachment uploaded to S3. This is to better handle DOCX, PPTX, and XLSX files which go through as `application/zip`.

I have tried the `:s3_headers` attachment option with a `proc` and using `before` and `after` `post_process` but the metadata does not persist to S3

```
after_document_post_process :set_s3_headers

def set_s3_headers
  self.document.options.merge({:s3_headers => {"Content-Disposition" => "attachment; filename=" + self.document_file_name}})
end
```

If I use the options directly;
```
has_attached_file :document, 
    :s3_headers => proc { |attachment|
        Rails.logger.debug(attachment.to_json)
        { "Content-Disposition" => "attachment; filename=\"#{attachment.document_file_name}\"" }
    }
```

It seems to happen before I have any file information;
```
{"id":null,"document_file_name":null,"document_content_type":null,"document_file_size":null,"document_updated_at":null,"solution_id":null,"user_id":null,"created_at":null,"updated_at":null}
```

The documentation and source code seems to say this should work as do several StackOverflow questions and answers.

Paperclip 5.1.0

Any help appreciated, thank you.

**Comment by sidraval** [comment]
Thank you for reporting this. Unfortunately, we will be deprecating Paperclip and therefore will not have the bandwidth to address this issue.

**Comment by sharmin10seu** [comment]
In my case, it works like this:

```
  has_attached_file :csv,
                    :storage => :s3,
                    :s3_credentials => "#{Rails.root}/config/s3.yml",
                    :s3_headers => proc { |attachment|
                      file_name = attachment.generate_credential_report_url? ? "credential_report.csv" : "credential_matrix_report.csv"
                      {
                        'Content-Type' => 'text/csv',
                        "Content-Disposition" => "attachment; filename=\"#{file_name}\""
                      }
                    }```
