### ISSUE TITLE
Error creating a migration

### ISSUE THREAD

**Issue by Hamdan85** [thoughtbot/paperclip#2480]
Error on migration. Paperclip creates a migration without the version argument.

StandardError: Directly inheriting from ActiveRecord::Migration is not supported. Please specify the Rails release the migration was written for:

  class AddAttachmentFileToAttachments < ActiveRecord::Migration[4.2]

**Comment by crm114** [comment]
@Hamdan85 type this in your rails console

[`"[#{Rails::VERSION::MAJOR}.#{Rails::VERSION::MINOR}]"`]

Copy the output and append it to this line in your migration:
`class YourAttachment < ActiveRecord::Migration[Append Here]`

**Comment by Hamdan85** [comment]
It should be automatic right?

Anyway, thanks in advance.
