### ISSUE TITLE
Paperclip::DataUriAdapter - Unpermitted parameter for (base64 file)

### ISSUE THREAD

**Issue by owen2345** [thoughtbot/paperclip#2482]
Hi guys, I found a problem for this situation:
- Receive a file param in base64 format
- In accepted params convert it into Paperclip file
- ERROR: The param always is marked as "Unpermitted parameter :image". But it works well if it is an attachment file (not a base64 format)
```
def create
  Gallery.create(accepted_params)
end

def accepted_params
  params[:image] = Paperclip.io_adapters.for(params[:image]) # converting base64 into paperclip file
  params.permit(:image)
end
```

**Comment by drwl** [comment]
Seems like a rails issue and not something with paperclip. I imagine it has to do with `accepted_params`. Can you post the form you are posting with?
