### ISSUE TITLE
S3

### ISSUE THREAD

**Issue by jasonivers** [thoughtbot/paperclip#2483]
Amazon has recently updated their SDK gems to version 3.  This appears to have broken Paperclip's support of S3, as files are now being uploaded empty (0 bytes).

I don't have the time to dig through the gem to figure out where the issue is, exactly, at the moment, as I'm down 2 developers, but I would highly appreciate some help, or if there is a newer, more actively maintained repo (last real update was December of last year) that someone could point me at...

**Comment by jaybloke** [comment]
Also experiencing similar problems with this too. Upgrade AWS SDK 3.0.1 and now receive this message:

NameError: uninitialized constant Aws::VERSION
/home/deploy/production/shared/bundle/ruby/2.3.0/gems/paperclip-5.1.0/lib/paperclip/storage/s3.rb:125:in `extended'

**Comment by morgoth** [comment]
@jasonivers This should fix it https://github.com/thoughtbot/paperclip/pull/2481 - I guess for now you can freeze `aws-sdk` to `~> 2.0`

**Comment by jasonivers** [comment]
That's what I've done... Hopefully someone will merge that PR soon

**Comment by aghamdi** [comment]
Paperclip uses the Aws::VERSION to check features and compatibility of certin versions like 2, 2.0.33 and above 2.3.0. For now you can the missing method VERSION in your paperclip initializer or any file that get loaded like the following:

module Aws
  VERSION = "3.0.0"
end

It worked for me but use it with caution and test to ensure that nothing breaks in your code.

**Comment by mike-burns** [comment]
We have migrated to awk-sdk-s3.
