### ISSUE TITLE
aws-sdk gem 3.0.1+ raises `uninitialized constant Aws::VERSION`

### ISSUE THREAD

**Issue by easybills-admin** [thoughtbot/paperclip#2484]
I think this is happening because `aws-sdk` gem [has removed the constant `Aws::VERSION`](https://github.com/aws/aws-sdk-ruby/pull/1595/files), which is used by **Paperclip** [here](https://github.com/thoughtbot/paperclip/blob/b01f47407a03feabd41ac8786b577310e3be87b6/lib/paperclip/storage/s3.rb#L130-L131) and [here](https://github.com/thoughtbot/paperclip/blob/7edb35a2a9a80c9598dfde235c7e593c023fc914/spec/support/conditional_filter_helper.rb#L3).

**Comment by tsujigiri** [comment]
`aws-sdk` also got split up into different gems for the different services. I assume, only `aws-sdk-s3` would be needed.

**Comment by MSeneadza** [comment]
you'll get the same error with `aws-sdk-s3`

**Comment by rlugge** [comment]
So is there any fix for this?  A workaround?  Something?

**Comment by rlugge** [comment]
OK, I found a workaround.  Instead of simply specifying `gem 'aws-sdk'`, I'm using a specific version instead:  `gem 'aws-sdk', '2.10.45'`

Long-term this is NOT a good solution, but if you're like me and just trying to get off ground zero temporarily its 'a' solution while Paperclip gets updated.

**Comment by easybills-admin** [comment]
@rlugge you can specify it as `gem 'aws-sdk', '< 3.0'` so you'll get the latest `2.x` version :)

**Comment by RohitRox** [comment]
A workaround to keep using ''>= 2.0''
I did this (for rails)

``` ruby
# config/initializers/aws.rb
Aws::VERSION =  Gem.loaded_specs["aws-sdk"].version
```

**Comment by tomrossi7** [comment]
[Is there a way](https://stackoverflow.com/questions/47639286/which-aws-gems-are-really-necessary-for-paperclip) to not include the whole `aws-sdk` gem? So many dependencies!

**Comment by martinemde** [comment]
@tomrossi7 There's a PR working on this: #2481

**Comment by vidurpunj** [comment]
gem "paperclip", "~> 6.1.0"
gem 'aws-sdk', '~> 3.0', '>= 3.0.1'
