### ISSUE TITLE
undefined method `bucket' for #<String:0x007fa595a2c0c8>

### ISSUE THREAD

**Issue by haroldthompson** [thoughtbot/paperclip#2516]
Hello,

We see this error rarely while reading or creating images using paperclip + s3
Tried everything to find the issue but no luck. 

Is there anyone familiar with this issue?

Thanks,
Cheers!

```
undefined method `bucket' for #<String:0x007fa595a2c0c8>
[GEM_ROOT]/bundler/gems/paperclip-093b4da18444/lib/paperclip/storage/s3.rb:273
```

Please see [https://github.com/thoughtbot/paperclip/blob/master/lib/paperclip/storage/s3.rb#L273](https://github.com/thoughtbot/paperclip/blob/master/lib/paperclip/storage/s3.rb#L273)

This is our paperclip configuration

```
Paperclip.options[:content_type_mappings] = { 
    svg: %w(image/svg+xml text/html),
    xlsx: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' 
}

Paperclip::Attachment.default_options.update({
  path: '/images/:class/:attachment/:id_partition/:style/:filename',
  url: ':s3_domain_url',
  storage: :s3,
  s3_protocol: :https,
  s3_region: ENV['AWS_S3_REGION'],
  s3_credentials: {
    bucket: ENV['AWS_S3_BUCKET'],
    access_key_id: ENV['AWS_ACCESS_KEY_ID'],
    secret_access_key: ENV['AWS_SECRET_ACCESS_KEY']
  }
})
```

Backtrace: 
`[GEM_ROOT]/bundler/gems/paperclip-093b4da18444/lib/paperclip/storage/s3.rb:273 in s3_bucket
[GEM_ROOT]/bundler/gems/paperclip-093b4da18444/lib/paperclip/storage/s3.rb:281 in s3_object
[GEM_ROOT]/bundler/gems/paperclip-093b4da18444/lib/paperclip/storage/s3.rb:387 in block in flush_writes
[GEM_ROOT]/bundler/gems/paperclip-093b4da18444/lib/paperclip/storage/s3.rb:360 in each
[GEM_ROOT]/bundler/gems/paperclip-093b4da18444/lib/paperclip/storage/s3.rb:360 in flush_writes
[GEM_ROOT]/bundler/gems/paperclip-093b4da18444/lib/paperclip/attachment.rb:247 in save
[GEM_ROOT]/bundler/gems/paperclip-093b4da18444/lib/paperclip/has_attached_file.rb:92 in block in add_active_record_callbacks
/gems/activesupport-5.0.4/lib/active_support/callbacks.rb:396 in instance_exec
/gems/activesupport-5.0.4/lib/active_support/callbacks.rb:396 in block in make_lambda
/gems/activesupport-5.0.4/lib/active_support/callbacks.rb:207 in block in halting_and_conditional
/gems/activesupport-5.0.4/lib/active_support/callbacks.rb:456 in block in call
/gems/activesupport-5.0.4/lib/active_support/callbacks.rb:456 in each
/gems/activesupport-5.0.4/lib/active_support/callbacks.rb:456 in call
/gems/activesupport-5.0.4/lib/active_support/callbacks.rb:101 in __run_callbacks__
/gems/activesupport-5.0.4/lib/active_support/callbacks.rb:750 in _run_save_callbacks
/gems/activerecord-5.0.4/lib/active_record/callbacks.rb:298 in create_or_update
/gems/activerecord-5.0.4/lib/active_record/persistence.rb:129 in save
/gems/activerecord-5.0.4/lib/active_record/validations.rb:44 in save
/gems/activerecord-5.0.4/lib/active_record/attribute_methods/dirty.rb:22 in save
/gems/activerecord-5.0.4/lib/active_record/transactions.rb:319 in block (2 levels) in save
/gems/activerecord-5.0.4/lib/active_record/transactions.rb:395 in block in with_transaction_returning_status
/gems/activerecord-5.0.4/lib/active_record/connection_adapters/abstract/database_statements.rb:232 in block in transaction
/gems/activerecord-5.0.4/lib/active_record/connection_adapters/abstract/transaction.rb:189 in within_new_transaction
/gems/activerecord-5.0.4/lib/active_record/connection_adapters/abstract/database_statements.rb:232 in transaction
(eval):61 in block in transaction
(eval):15 in _makara_hijack
(eval):57 in transaction
/gems/makara-0.3.7/lib/makara/connection_wrapper.rb:99 in public_send
/gems/makara-0.3.7/lib/makara/connection_wrapper.rb:99 in method_missing
/gems/makara-0.3.7/lib/makara/proxy.rb:28 in block (3 levels) in hijack_method
/gems/makara-0.3.7/lib/active_record/connection_adapters/makara_abstract_adapter.rb:160 in block in appropriate_connection
/gems/makara-0.3.7/lib/makara/proxy.rb:165 in block (3 levels) in appropriate_connection
/gems/makara-0.3.7/lib/makara/proxy.rb:238 in hijacked
/gems/makara-0.3.7/lib/makara/proxy.rb:164 in block (2 levels) in appropriate_connection
/gems/makara-0.3.7/lib/makara/pool.rb:105 in block in provide
/gems/makara-0.3.7/lib/active_record/connection_adapters/makara_abstract_adapter.rb:37 in handle
/gems/makara-0.3.7/lib/makara/pool.rb:104 in provide
/gems/makara-0.3.7/lib/makara/proxy.rb:163 in block in appropriate_connection
/gems/makara-0.3.7/lib/makara/proxy.rb:178 in appropriate_pool
/gems/makara-0.3.7/lib/makara/proxy.rb:162 in appropriate_connection
/gems/makara-0.3.7/lib/active_record/connection_adapters/makara_abstract_adapter.rb:159 in appropriate_connection
/gems/makara-0.3.7/lib/makara/proxy.rb:27 in block (2 levels) in hijack_method
/gems/activerecord-5.0.4/lib/active_record/transactions.rb:211 in transaction
/gems/activerecord-5.0.4/lib/active_record/transactions.rb:392 in with_transaction_returning_status
/gems/activerecord-5.0.4/lib/active_record/transactions.rb:319 in block in save
/gems/activerecord-5.0.4/lib/active_record/transactions.rb:334 in rollback_active_record_state!
/gems/activerecord-5.0.4/lib/active_record/transactions.rb:318 in save
/gems/activerecord-5.0.4/lib/active_record/suppressor.rb:41 in save
app/controllers/files_controller.rb:26 in upload
/gems/actionpack-5.0.4/lib/action_controller/metal/basic_implicit_render.rb:4 in send_action
/gems/actionpack-5.0.4/lib/abstract_controller/base.rb:188 in process_action
/gems/actionpack-5.0.4/lib/action_controller/metal/rendering.rb:30 in process_action
/gems/actionpack-5.0.4/lib/abstract_controller/callbacks.rb:20 in block in process_action
/gems/activesupport-5.0.4/lib/active_support/callbacks.rb:126 in call
/gems/activesupport-5.0.4/lib/active_support/callbacks.rb:506 in block (2 levels) in compile
/gems/activesupport-5.0.4/lib/active_support/callbacks.rb:455 in call
/gems/activesupport-5.0.4/lib/active_support/callbacks.rb:448 in block (2 levels) in around
/gems/activesupport-5.0.4/lib/active_support/callbacks.rb:267 in block (2 levels) in halting_and_conditional
app/controllers/application_controller.rb:57 in set_current_admin
/gems/activesupport-5.0.4/lib/active_support/callbacks.rb:382 in block in make_lambda
/gems/activesupport-5.0.4/lib/active_support/callbacks.rb:266 in block in halting_and_conditional
/gems/activesupport-5.0.4/lib/active_support/callbacks.rb:447 in block in around
/gems/activesupport-5.0.4/lib/active_support/callbacks.rb:455 in call
/gems/activesupport-5.0.4/lib/active_support/callbacks.rb:448 in block (2 levels) in around
/gems/activesupport-5.0.4/lib/active_support/callbacks.rb:286 in block (2 levels) in halting
/gems/audited-4.4.1/lib/audited/sweeper.rb:14 in around
/gems/activesupport-5.0.4/lib/active_support/callbacks.rb:405 in public_send
/gems/activesupport-5.0.4/lib/active_support/callbacks.rb:405 in block in make_lambda
/gems/activesupport-5.0.4/lib/active_support/callbacks.rb:285 in block in halting
/gems/activesupport-5.0.4/lib/active_support/callbacks.rb:447 in block in around
/gems/activesupport-5.0.4/lib/active_support/callbacks.rb:455 in call
/gems/activesupport-5.0.4/lib/active_support/callbacks.rb:448 in block (2 levels) in around
/gems/activesupport-5.0.4/lib/active_support/callbacks.rb:286 in block (2 levels) in halting
/gems/audited-4.4.1/lib/audited/sweeper.rb:14 in around
/gems/activesupport-5.0.4/lib/active_support/callbacks.rb:405 in public_send
/gems/activesupport-5.0.4/lib/active_support/callbacks.rb:405 in block in make_lambda
/gems/activesupport-5.0.4/lib/active_support/callbacks.rb:285 in block in halting
/gems/activesupport-5.0.4/lib/active_support/callbacks.rb:447 in block in around
/gems/activesupport-5.0.4/lib/active_support/callbacks.rb:455 in call
/gems/activesupport-5.0.4/lib/active_support/callbacks.rb:101 in __run_callbacks__
/gems/activesupport-5.0.4/lib/active_support/callbacks.rb:750 in _run_process_action_callbacks
/gems/activesupport-5.0.4/lib/active_support/callbacks.rb:90 in run_callbacks
/gems/actionpack-5.0.4/lib/abstract_controller/callbacks.rb:19 in process_action
/gems/actionpack-5.0.4/lib/action_controller/metal/rescue.rb:20 in process_action
/gems/actionpack-5.0.4/lib/action_controller/metal/instrumentation.rb:32 in block in process_action
/gems/activesupport-5.0.4/lib/active_support/notifications.rb:164 in block in instrument
/gems/activesupport-5.0.4/lib/active_support/notifications/instrumenter.rb:21 in instrument
/gems/activesupport-5.0.4/lib/active_support/notifications.rb:164 in instrument
/gems/actionpack-5.0.4/lib/action_controller/metal/instrumentation.rb:30 in process_action
/gems/actionpack-5.0.4/lib/action_controller/metal/params_wrapper.rb:248 in process_action
/gems/activerecord-5.0.4/lib/active_record/railties/controller_runtime.rb:18 in process_action
/gems/actionpack-5.0.4/lib/abstract_controller/base.rb:126 in process
/gems/actionview-5.0.4/lib/action_view/rendering.rb:30 in process
/gems/actionpack-5.0.4/lib/action_controller/metal.rb:190 in dispatch
/gems/actionpack-5.0.4/lib/action_controller/metal.rb:262 in dispatch
/gems/actionpack-5.0.4/lib/action_dispatch/routing/route_set.rb:50 in dispatch
/gems/actionpack-5.0.4/lib/action_dispatch/routing/route_set.rb:32 in serve
/gems/actionpack-5.0.4/lib/action_dispatch/journey/router.rb:39 in block in serve
/gems/actionpack-5.0.4/lib/action_dispatch/journey/router.rb:26 in each
/gems/actionpack-5.0.4/lib/action_dispatch/journey/router.rb:26 in serve
/gems/actionpack-5.0.4/lib/action_dispatch/routing/route_set.rb:725 in call
/gems/makara-0.3.7/lib/makara/middleware.rb:26 in call
[GEM_ROOT]/bundler/gems/remotipart-d9109eb032b9/lib/remotipart/middleware.rb:32 in call
/gems/warden-1.2.7/lib/warden/manager.rb:36 in block in call
/gems/warden-1.2.7/lib/warden/manager.rb:35 in catch
/gems/warden-1.2.7/lib/warden/manager.rb:35 in call
/gems/rack-2.0.3/lib/rack/etag.rb:25 in call
/gems/rack-2.0.3/lib/rack/conditional_get.rb:38 in call
/gems/rack-2.0.3/lib/rack/head.rb:12 in call
/gems/rack-2.0.3/lib/rack/session/abstract/id.rb:232 in context
/gems/rack-2.0.3/lib/rack/session/abstract/id.rb:226 in call
/gems/actionpack-5.0.4/lib/action_dispatch/middleware/cookies.rb:613 in call
/gems/actionpack-5.0.4/lib/action_dispatch/middleware/callbacks.rb:38 in block in call
/gems/activesupport-5.0.4/lib/active_support/callbacks.rb:97 in __run_callbacks__
/gems/activesupport-5.0.4/lib/active_support/callbacks.rb:750 in _run_call_callbacks
/gems/activesupport-5.0.4/lib/active_support/callbacks.rb:90 in run_callbacks
/gems/actionpack-5.0.4/lib/action_dispatch/middleware/callbacks.rb:36 in call
/gems/actionpack-5.0.4/lib/action_dispatch/middleware/remote_ip.rb:79 in call
/gems/airbrake-6.1.0/lib/airbrake/rack/middleware.rb:52 in call
/gems/actionpack-5.0.4/lib/action_dispatch/middleware/debug_exceptions.rb:49 in call
/gems/actionpack-5.0.4/lib/action_dispatch/middleware/show_exceptions.rb:31 in call
/gems/railties-5.0.4/lib/rails/rack/logger.rb:36 in call_app
/gems/railties-5.0.4/lib/rails/rack/logger.rb:24 in block in call
/gems/activesupport-5.0.4/lib/active_support/tagged_logging.rb:69 in block in tagged
/gems/activesupport-5.0.4/lib/active_support/tagged_logging.rb:26 in tagged
/gems/activesupport-5.0.4/lib/active_support/tagged_logging.rb:69 in tagged
/gems/railties-5.0.4/lib/rails/rack/logger.rb:24 in call
/gems/request_store-1.3.2/lib/request_store/middleware.rb:9 in call
/gems/actionpack-5.0.4/lib/action_dispatch/middleware/request_id.rb:24 in call
/gems/rack-2.0.3/lib/rack/method_override.rb:22 in call
/gems/rack-2.0.3/lib/rack/runtime.rb:22 in call
/gems/activesupport-5.0.4/lib/active_support/cache/strategy/local_cache_middleware.rb:28 in call
/gems/actionpack-5.0.4/lib/action_dispatch/middleware/executor.rb:12 in call
/gems/rack-2.0.3/lib/rack/sendfile.rb:111 in call
/gems/actionpack-5.0.4/lib/action_dispatch/middleware/ssl.rb:84 in call
/gems/railties-5.0.4/lib/rails/engine.rb:522 in call
/gems/puma-3.9.1/lib/puma/configuration.rb:224 in call
/gems/puma-3.9.1/lib/puma/server.rb:602 in handle_request
/gems/puma-3.9.1/lib/puma/server.rb:435 in process_client
/gems/puma-3.9.1/lib/puma/server.rb:299 in block in run
/gems/puma-3.9.1/lib/puma/thread_pool.rb:120 in block in spawn_thread`

**Comment by haroldthompson** [comment]
Months passed but i still havent been able to find the source of this issue

**Comment by mike-burns** [comment]
Thank you for reporting this. Unfortunately, we will be deprecating Paperclip and therefore will not have the bandwidth to address this issue.
