### ISSUE TITLE
Upload using formData

### ISSUE THREAD

**Issue by cstenico** [thoughtbot/paperclip#2519]
Hello,

I've been trying to upload a picture on a React client application, but when I receive the formData on rails server, paperclip cannot understand the formData object, throwing the following mistake:

Paperclip::AdapterRegistry::NoHandlerError (No handler found for "[object File]"):

What can I do to complete this upload?

**Comment by mike-burns** [comment]
This is a JavaScript error, unrelated to Paperclip. Closing.
