### ISSUE TITLE
Doc: Clarify threat models covered by Security Validations

### ISSUE THREAD

**Issue by yozlet** [thoughtbot/paperclip#2520]
The README currently says:

> Thanks to a report from Egor Homakov we have taken steps to prevent people from spoofing Content-Types and getting data you weren't expecting onto your server.

This raises and doesn't answer these questions:

 * What does "data you weren't expecting" mean? There's bad stuff here, right?
 * What are the dangers of unexpected data types on my server?
 * Are these dangers still present if I'm using external storage (e.g. S3)?

@stvnrlly and I, working on a Federal Government app, were trying to work out whether these Security Validations are sufficient to cover our regulations; it took us quite a bit of reading around the links, code and issues before we had some understanding.

(And while you're updating the docs, if #1713 isn't fixed yet, this would be a good thing to call out.)

**Comment by mike-burns** [comment]
Thank you for the feature request. Unfortunately we will be deprecating Paperclip and therefore will no longer be accepting new features.
