### ISSUE TITLE
Tests failing at head

### ISSUE THREAD

**Issue by alenzamanyan** [thoughtbot/paperclip#2523]
I'm following the instructions in [CONTRIBUTING.md](https://github.com/thoughtbot/paperclip/blob/master/CONTRIBUTING.md) and I noticed that the tests appear to be broken at head. Perhaps there is something missing in my setup. Can anyone else reproduce this?

**Comment by mike-burns** [comment]
CI is passing. Can you provide more information?

**Comment by alenzamanyan** [comment]
I cloned the repo and installed ghostscript and imagemagick using:
sudo apt-get install imagemagick ghostscript -y

I then ran:
bundle && bundle exec rake

Here's a gist with the output:
https://gist.github.com/alenzamanyan/8a670027f26f697227ad3d2eca967269

**Comment by mike-burns** [comment]
Thank you for trying to contribute to Paperclip. Unfortunately we will be deprecating Paperclip and therefore will no longer be accepting new features.
