### ISSUE TITLE
s3_protocol parameter. Using with API

### ISSUE THREAD

**Issue by denis-mironov** [thoughtbot/paperclip#2524]
Hi, guys!

I'm working with API and using paperclip for uploading images. After updating from v4.3.6 to v5.1.0 all images stopped displaying on IOS and Android apps. I spent some time trying to understand and fix it. Problem was in setting s3_protocol as empty string in v5.1.0 (https://github.com/thoughtbot/paperclip/issues/2038).  
By default my API was returning images urls without specifying the protocol. Such behavior is more sensitive for WEB, but our mobile apps are using libraries to work with images and can not identify image url without protocol.
It was necessary to add `s3_protocol: :http` to `config.paperclip_defaults` to fix issue. But this solution is not obvious for everyone and there is no any documentation for such case.

**I think it will be good if you add this case explanation to paperclip documentation**

**Comment by mike-burns** [comment]
Thank you for the feature request. Unfortunately we will be deprecating Paperclip and therefore will no longer be accepting new features.
