### ISSUE TITLE
Update AWS subdomain

### ISSUE THREAD

**Issue by hirosmans** [thoughtbot/paperclip#2525]
Hi,

I'm using `Paperclip.io_adapters.for(logo)` to upload base64 png. I try with versions 5.0, 5.1 and link assing init with:  http://s3.amazonaws.com/ 
but in my aws bucket init with:  https://s3-us-west-2.amazonaws.com

`@company.logo.url(:thumb)`

**Comment by mike-burns** [comment]
Thank you for the feature request. Unfortunately we will be deprecating Paperclip and therefore will no longer be accepting new features.
