### ISSUE TITLE
Styles does not work when i save file manually

### ISSUE THREAD

**Issue by oguzcicek** [thoughtbot/paperclip#2529]
i upload images from public folder manually  ( not from a form ). 
But i can't create styles like `:medium` or `:thumb`. i can only create `:original` version of photos.
Model : 

```
has_attached_file :photo,
                    styles: { medium: "500x500" , thumb: "85x83"  } ,
                    :url => "/companyImg/:style/:basename.:extension",
                    :path => ":rails_root/public/companyImg/:style/:basename.:extension"
  validates_attachment_content_type :photo, content_type: /\Aimage\/.*\z/

```
Controller : 

```
 def create
    @company = Company.create company_params    

    @company.photo = open("public/example.jpg")
    File.delete("public/example.jpg")

    if @company.save...
       ...
  end
```

i can upload file manually but can't apply styles. `has_attached_file` does not work. It uploads file to `:original` folder. `:medium` and `:thumb` folders are empty.

**Comment by sidraval** [comment]
Thank you for reporting this. Unfortunately, we will be deprecating Paperclip and therefore will not have the bandwidth to address this issue.
