### ISSUE TITLE
upgraded to 5.2 - Errno::EEXIST (File exists @ syserr_fail2_in

### ISSUE THREAD

**Issue by ubswrk** [thoughtbot/paperclip#2533]
Windows 10
Ruby 2.3.1
Rails 5.1.2
Hi,
After upgrading to paperclip 5.2 (due to recent vulnerability problem), when trying to attach the file to a document (mongoid), I'm getting the following error:

File exists @ syserr_fail2_in - C:/.../AppData/Local/Temp/ee26908bf9629eeb4b37dac350f4754a20180125-21364-1l0ujqp excluded from capture: Not configured to send/capture in environment 'development'
FATAL -- : Errno::EEXIST (File exists @ syserr_fail2_in - C:/.../AppData/Local/Temp/ee26908bf9629eeb4b37dac350f4754a20180125-21364-1l0ujqp):

Everything works ok when I rollback to use paperclip 5.1.
What am I missing?

**Comment by geoffharcourt** [comment]
@ubswrk I'm not an expert on Paperclip, but could you try loading each of these three adapters alone in `config/initializers/paperclip.rb` here and see if Mongoid might depend on one of them?

- Paperclip::UriAdapter - which accepts a URI instance.
- Paperclip::HttpUrlProxyAdapter - which accepts a http string.
- Paperclip::DataUriAdapter - which accepts a Base64-encoded data: string.

Docs are here: https://github.com/thoughtbot/paperclip#io-adapters

**Comment by mike-burns** [comment]
I hope this is not related to #2290. We had not QAed it on Windows.

If you're able to reproduce this locally, you could try reverting 4debddb80ff7ea5da7145aa116eb909247380a3a in a local Paperclip to see if that fixes it.

Here's a sketch of how I'd do it using the tools I know:

```
git clone git@github.com:thoughtbot/paperclip.git
cd paperclip
git revert --no-edit 4debddb80ff7ea5da7145aa116eb909247380a3a
cd ../your-app
[ --- edit Gemfile such that gem paperclip uses local: gem 'paperclip', path: '../paperclip' --- ]
bundle
```

If that fixes it, then that commit was definitely the issue.

But like Geoff says above, we're not sure what the issue is. Is it possible to get a longer backtrace?

**Comment by mike-burns** [comment]
Aha, it's fixed it #2532!

**Comment by mike-burns** [comment]
Paperclip 5.2.1 should fix this. Thank you for reporting this, and thank you again to @hron for the fix.

**Comment by ubswrk** [comment]
Thanks, this solved the issue.
