### ISSUE TITLE
<Paperclip::Errors::NotIdentifiedByImageMagickError: Paperclip::Errors::NotIdentifiedByImageMagickError>

### ISSUE THREAD

**Issue by vaidehitikd** [thoughtbot/paperclip#2538]
log/development.log <==
[paperclip] An error was received while processing: #<Paperclip::Errors::NotIdentifiedByImageMagickError: Paperclip::Errors::NotIdentifiedByImageMagickError>
   (1.8ms)  BEGIN
   (1.4ms)  ROLLBACK
   (2.8ms)  BEGIN
Command :: PATH=/usr/local/bin/identify:$PATH; identify -format '%wx%h,%[exif:orientation]' '/tmp/8d777f385d3dfec8815d20f7496026dc20180130-15863-8e9egh[0]' 2>/dev/null
Command :: PATH=/usr/local/bin/identify:$PATH; identify -format '%wx%h,%[exif:orientation]' '/tmp/8d777f385d3dfec8815d20f7496026dc20180130-15863-110veqh[0]' 2>/dev/null
[paperclip] An error was received while processing: #<Paperclip::Errors::NotIdentifiedByImageMagickError: Paperclip::Errors::NotIdentifiedByImageMagickError>
   (1.7ms)  ROLLBACK
[paperclip] An error was received while processing: #<Paperclip::Errors::NotIdentifiedByImageMagickError: Paperclip::Errors::NotIdentifiedByImageMagickError>
   (1.6ms)  ROLLBACK

**Comment by ayrat555** [comment]
@vaidehitikd can you give more information about your problem? image example and imagemagick version would be helpful.

I have the same issue

**Comment by rocket-turtle** [comment]
We had the same error once because Paperclip called identify on a `.pdf `File and ghostscript was not installed.

But I can't see any Filename in the Error so it could be something totally different :)

**Comment by ScottBishop** [comment]
I am getting the same error using PNGs. Doesn't happen every time but enough that it is a problem.

**Comment by sidraval** [comment]
Thank you for reporting this. Unfortunately, we will be deprecating Paperclip and therefore will not have the bandwidth to address this issue.

**Comment by danielpuglisi** [comment]
Had the same issue with processing pdfs. Upgrading ghostscript solved it.

**Comment by phansch** [comment]
If you hit this error since October 2018 on Ubuntu, have a look at https://github.com/thoughtbot/paperclip/issues/2223#issuecomment-428862815 for a possible fix.

**Comment by pierre-alain-b** [comment]
I hit this problem in Debian Stretch starting around early Dec 2018. I fixed it temporarily by reverting to an older version of ghostscript.
```apt-get install libgs9=9.20~dfsg-3.2+deb9u5 ghostscript=9.20~dfsg-3.2+deb9u5 libgs9-common=9.20~dfsg-3.2+deb9u5```

My explanation, not yet confirmed, is that the recent update to Ghostscript 9.26 in Debian Stretch Security caused the issue to pop up. Further investigation to do...

**Comment by pierre-alain-b** [comment]
Being treated here as a bug of ghostscript: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=915832 and https://bugs.launchpad.net/ubuntu/+source/ghostscript/+bug/1806517

**Comment by pierre-alain-b** [comment]
I hit this problem (again ?!) in Debian Buster starting around mid August 2020. In this version of the issue, the "convert" command was returning this error:

```
convert 20F0001.pdf test.png
convert-im6.q16: attempt to perform an operation not allowed by the security policy `PDF' @ error/constitute.c/IsCoderAuthorized/408.
convert-im6.q16: no images defined `test.png' @ error/convert.c/ConvertImageCommand/3258.
zsh: exit 1     convert 20F0001.pdf test.png
```

To fix it, I had to comment this line in /etc/ImageMagick-6/policy.xml :
`<policy domain="coder" rights="none" pattern="PDF" />`
