### ISSUE TITLE
Required content_type validation not working correctly for multiple attachments

### ISSUE THREAD

**Issue by chanko** [thoughtbot/paperclip#2541]
When having multiple attachments in a single model, it seems the content_type validation requirement is only checking for a single instance of it, regardless of which attachment it's for.

```
class SomeClass
  has_attached_file :first
  has_attached_file :second

  validates_attachment_content_type :first, :content_type: 'application/pdf'
end
``` 

This code does not throw an error even though the `:second` attachment does not include a validation for its content type.

Or am I missing something? The documentation states that every attachment requires its content_type validated.

**Comment by sidraval** [comment]
Thank you for reporting this. Unfortunately, we will be deprecating Paperclip and therefore will not have the bandwidth to address this issue.
