### ISSUE TITLE
Destroying attachment doesn't delete file from S3

### ISSUE THREAD

**Issue by toobulkeh** [thoughtbot/paperclip#2542]
We have some information from uploads we'd like to store on S3 temporarily while the files can be parsed. Once the parsing fails or succeeds, we'd like the file to be deleted. We don't really care about the reference to the file being deleted, but that's fine if it does.

I found that the following deletes the reference from the model, but not the actual file:
```ruby
u.file.destroy
```

Where
```ruby
class Upload < ActiveRecord::Base
  has_attached_file :file
  ...
end
```

Note that we're not doing file type or media type validation, as this is a protected and trusted interface (not sure if this impacts anything).

Here is our S3 ACL that the system is using:
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "2",
            "Effect": "Allow",
            "Action": "s3:*",
            "Resource": [
                "arn:aws:s3:::bucket-production/*",
                "arn:aws:s3:::bucket-production"
            ]
        }
    ]
}
```

Also note that we're using Paperclip 5.1.0 and ruby 2.3.0p0 and rails 4.2.7.1.

I found some old issues related to this topic, but they seemed abandoned:

https://github.com/thoughtbot/paperclip/issues/1239
https://github.com/thoughtbot/paperclip/issues/1717
https://github.com/thoughtbot/paperclip/issues/1704 https://github.com/thoughtbot/paperclip/issues/1326

https://stackoverflow.com/questions/4435826/rails-paperclip-how-to-delete-attachment

**Comment by toobulkeh** [comment]
Ah, so I believe this stems from the `preserve_files: true` config option we were using in our paperclip initializer. I was under the impression that this only preserved files when the model was deleted, not the attachment on the model was directly deleted.

In my example above, `u.destroy` vs. `u.file.destroy`. Also, `u.destroy!` or `u.file.destroy!` would be good methods to skip the `preserve_files: true` config?

Either way, I can get rid of that config in our use case, so this is now a feature request.

**Comment by sidraval** [comment]
Thank you for reporting this. Unfortunately, we will be deprecating Paperclip and therefore will not have the bandwidth to address this issue.

**Comment by joshuapinter** [comment]
I know `paperclip` is deprecated but for those of us still using it, here's what we did to optionally delete the files on S3: 

1. Keep `preserve_files: true`.
   This ensures that the default remains for the files to be persisted on S3 in case the records are restored or just as a good backup. (I recommend this where ever possible.)

2. Create a method that _really_ deletes the files on S3: 

    ```ruby
    # Our paperclip configuration is such that we have `preserve_files: true`, which ensures that the actual files are not deleted when a record is (soft) deleted.
    # This is helpful as a backup and when a deleted record gets restored.
    # However, for some items, such as demo files or large archives, we actually want to delete the files off of S3, as they cost us money and take up space.
    # This iterates over each style and deletes the file from S3, skipping styles that do not exist.
    # NOTE: The bang was appended to the method name to indicate a destructive function, as opposed to the soft deletes we usually use.
    #
    def delete_files!
      self.file.styles.keys.push( nil ).each do |style| # NOTE: Add `nil` for the original file size.
        begin
          self.s3_object( style ).delete

        rescue Aws::S3::Errors::NoSuchKey # If a style doesn't exist, skip it and go to the next.
          next
        end
      end

      true
    end
    ```

    Notice the usage of a bang suffix to the method name to indicate a non-default destructive behaviour.

3. Either call `delete_files!` directly whenever needed, or setup an `after_destroy` callback that calls it based on some condition: 

    ```ruby
    after_destroy :delete_files!, if: :archive?
    ```

Hope that helps.

**Comment by ajnetterfield** [comment]
I also came across this situation where I needed to set `preserve_files: true` to prevent files from being deleted automatically on soft-deletes, but still allow files to be manually deleted where necessary.

In `lib/paperclip/attachment.rb` I noticed that `@options[:preserve_files]` is only being checked when deleting all file styles via the method `queue_all_for_delete` but not via the method `queue_some_for_delete`.

It's possible to write your own method almost identical to the official `destroy` method in `lib/paperclip/attachment.rb`, only with a slight change in that you have to pass in all styles that you want to delete, e.g.

```
class Attachment < ActiveRecord::Base
  has_attached_file :file, preserve_files: true

  def destroy_file
    file.clear(:original, *file.styles.keys)
    file.save
  end
end
```
