### ISSUE TITLE
how to use to IBM bluemix

### ISSUE THREAD

**Issue by kattak2k** [thoughtbot/paperclip#2548]
Hi Team, c
Can we implement paperclip for IBM object storage which is like AWS S3. If yes, how to achieve it?

**Comment by tbleich** [comment]
I had to use fog to get it working with IBM cloud object storage S3 API. Here are the settings from my environments/production.rb:
```
config.paperclip_defaults = {
    storage: :fog,
    fog_credentials: {
      provider: 'AWS',
      path: '<your bucket name>',
      aws_access_key_id: ENV['ibm_cloud_storage_s3_key'],
      aws_secret_access_key: ENV['ibm_cloud_storage_s3_secret'],
      endpoint: 'https://s3.eu-geo.objectstorage.service.networklayer.com' # thats the IBM COS internal uri
    },
    fog_directory: '<your bucket name>',
    fog_host: 'https://s3.eu-geo.objectstorage.softlayer.net/<your bucket name>' # external uri
  }
```

Not entirely sure if setting `fog_directory` is necessary, I started with this config and it just worked so I did not try other permutations.

**Comment by sidraval** [comment]
Looks like you've found a workaround, closing.
