### ISSUE TITLE
HEIC images

### ISSUE THREAD

**Issue by rogsmith** [thoughtbot/paperclip#2551]
Has anyone successfully gotten paperclip working with HEIC images? I was able to compile in heic.c into ImageMagick and can 'convert' on the command line, but when I upload an HEIC image to my rails app it does not work. Any thoughts?

**Comment by sidraval** [comment]
Thank you for reporting this. Unfortunately, we will be deprecating Paperclip and therefore will not have the bandwidth to address this issue.

**Comment by garyfoster** [comment]
There does not appear to be a reliable way to validate content type of uploaded files in Active Storage given the fact that the file and metadata are stored prior to running validations. We've tried a few examples we've seen in various articles that do not work, and now sure how it will even be accomplished without some lower level changes to active storage. In the meantime, any photo created by an iPhone fails to work with Paperclip/S3. Wondering if anyone has either found a solution to HEIC files on paperclip, or figured out how to properly validate content in active storage so we can move away from the deprecated Paperclip gem.

**Comment by aivils** [comment]
If anyone else is interested
https://github.com/sharetribe/sharetribe/pull/3966
