### ISSUE TITLE
aws-sdk

### ISSUE THREAD

**Issue by braindeaf** [thoughtbot/paperclip#2554]
Since aws-sdk is split into multiple gems now is it really necessary to require 'awd-sdk' in s3.rb? Wouldn't 'awd-sdk-s3' suffice?

**Comment by morgoth** [comment]
@braindeaf There is a pending PR for this https://github.com/thoughtbot/paperclip/pull/2481

**Comment by braindeaf** [comment]
Excellent, thank you :)
