### ISSUE TITLE
File content type is not valid, File is not valid with mime-type "text/comma-separated-values"

### ISSUE THREAD

**Issue by akkee** [thoughtbot/paperclip#2556]
I have a model which has a csv attachment, `:csv`. I have the following block in my model:

```
if Rails.env.development? || Rails.env.test?
    has_attached_file :csv,
      :storage => :filesystem,
      :path => ":rails_root/public/assets/tmp/#{name.underscore}/:id/:style.:extension",
      :url => "/assets/tmp/#{name.underscore}/:id/:style.:extension"
  else
    has_attached_file :csv, :storage => :s3, :s3_credentials => "#{Rails.root}/config/amazon_s3.yml",
      :s3_permissions => "public-read", :s3_protocol => 'https', :s3_headers => {'Content-Disposition' => 'attachment', 'Content-Type' => 'text/csv'}, :url => ":s3_ap_se_url",
      :path => ":attachment/:id/Pilot Comment Report.csv", :bucket => S3_SETTINGS['buckets']['reports'].to_environment_bucket,s3_region: APP_CONFIG[:s3_region]
  end
  validates_attachment_content_type :csv, :content_type => ["text/plain", "text/csv", "application/csv", "application/vnd.ms-excel", "application/msword", "application/vnd.ms-office", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "application/zip", "application/xls", "application/octet-stream", "application/CDFV2-unknown; charset=binary","application/x-ole-storage", "text/comma-separated-values"]
```

Off late I have been getting errors in `:validates_attachment_content_type` when I do a `self.csv = File.new('somefile.csv', 'r')` and then a `self.save!`. The error shows up like ` Validation failed: Csv content type is not valid, Csv is not valid`

When I do a `MIME::Types.type_for(self.csv_file_name).first.to_s` before saving it gives me `text/comma-separated-values`. I, very clearly have mentioned `text/comma-separated-values` in the content_type array as I have mentioned above.

Just for following what other links on the issue say, I have added this clause before saving too, but with no avail:

```
unless Rails.env.development? || Rails.env.test?
      mime_type = MIME::Types.type_for(self.csv_file_name).first.to_s
      self.csv.send :initialize_storage
      self.csv.options[:s3_headers]['Content-Type'] = mime_type
      self.csv.send :initialize_storage
end
```
Do I have to follow a lambda route to specify content type in `s3_headers` ? Is there a recommended way to do that?
(This is not happening for all my attachments, only in few cases)

*Rails*: 4.2.10
*Ruby*: 2.3.0
*Paperclip*: 5+ (I've tried both 5.0 and 5.2.1)

**Comment by sidraval** [comment]
Thank you for reporting this. Unfortunately, we will be deprecating Paperclip and therefore will not have the bandwidth to address this issue.
