### ISSUE TITLE
Content Type Spoof error with Paperclip::UriAdapter with files without extensions

### ISSUE THREAD

**Issue by mabdelfattah** [thoughtbot/paperclip#2561]
I'm having a problem with uploading files from URLs (without extensions), although everything works fine when I upload files locally.

Versions:
rails: 5.1.4
paperclip: 5.2.1

model
```
has_attached_file :logo,
                    styles: {
                      medium: "200x200>",
                      thumb:  "100x100>"
                    },
                    default_url: "/images/:style/logo_missing.png",
                    url: "/:class/:attachment/:style/:id.:extension",
                    path: ":rails_root/public/assets/images/:class/:attachment/:style/:id.:extension"
validates_attachment_content_type :logo,
                                  content_type: /\Aimage\/.*\z/

```

Error:
```
[paperclip] Trying to link /tmp/f777d8ae005f6e876395e03c629cb82720180226-5420-1b52tto.OLj3YedBuMmdXbDd1bcbsiR7HHY to /tmp/f777d8ae005f6e876395e03c629cb82720180226-5420-26q6cu.OLj3YedBuMmdXbDd1bcbsiR7HHY
Command :: PATH=/usr/bin:$PATH; file -b --mime '/tmp/f777d8ae005f6e876395e03c629cb82720180226-5420-26q6cu.OLj3YedBuMmdXbDd1bcbsiR7HHY'
[paperclip] Content Type Spoof: Filename ImNhcmVlbS9jYkxvZ28ucG5nIg.OLj3YedBuMmdXbDd1bcbsiR7HHY (image/png from Headers, [] from Extension), content type discovered from file command: image/png. See documentation to allow this combination.
```

**Comment by mabdelfattah** [comment]
I got it working using the following famous monkey patch :)
```
require 'paperclip/media_type_spoof_detector'
module Paperclip
  class MediaTypeSpoofDetector
    def spoofed?
      false
    end
  end
end
```

**Comment by atreat** [comment]
The above monkey patch completely disables the media type spoof detector. You should be very careful and cognizant of the ramifications of this.

I've found the following monkey patch works for me what I came across this same issue:

```ruby
require 'paperclip/io_adapters/uri_adapter'
module Paperclip
  class UriAdapter < AbstractAdapter

    def content_type_from_content
      content_type = @content.meta["content-type"]
      return nil if content_type.blank?

      content_type.split(/[:;\s]+/).first
    end

  end
end
```

I found that the "content-type" value started to contain the charset definition(e.g. `text/plain; charset=us-ascii`), somewhere along the way this seems to be causing problems.


Hope this helps, I plan to put a PR up for the URI Adapter to get more feedback on this solution.

**Comment by euqueme** [comment]
> The above monkey patch completely disables the media type spoof detector. You should be very careful and cognizant of the ramifications of this.
> 
> I've found the following monkey patch works for me what I came across this same issue:
> 
> ```ruby
> require 'paperclip/io_adapters/uri_adapter'
> module Paperclip
>   class UriAdapter < AbstractAdapter
> 
>     def content_type_from_content
>       content_type = @content.meta["content-type"]
>       return nil if content_type.blank?
> 
>       content_type.split(/[:;\s]+/).first
>     end
> 
>   end
> end
> ```
> 
> I found that the "content-type" value started to contain the charset definition(e.g. `text/plain; charset=us-ascii`), somewhere along the way this seems to be causing problems.
> 
> Hope this helps, I plan to put a PR up for the URI Adapter to get more feedback on this solution.

Where did you create this class? class UriAdapter < AbstractAdapter
