### ISSUE TITLE
Unable to upload .docx format file downloaded via google drive.

### ISSUE THREAD

**Issue by rakesh-050791** [thoughtbot/paperclip#2562]
Unable to upload .docx format file (downloaded via google drive) but it's working when .docx file generated via "Microsoft Word".

using MimeType for .docx is `"application/vnd.openxmlformats-officedocument.wordprocessingml.document"`

*note : attaching both files.

MS word File :   [file-from-ms-word.docx](https://github.com/thoughtbot/paperclip/files/1761325/file-from-ms-word.docx)
Google Drive File :   [file-from-google-drive.docx](https://github.com/thoughtbot/paperclip/files/1761323/file-from-google-drive.docx)

**Comment by sidraval** [comment]
Thank you for reporting this. Unfortunately, we will be deprecating Paperclip and therefore will not have the bandwidth to address this issue.
