### ISSUE TITLE
IO adapters can't handle Content-Disposition with filename=""

### ISSUE THREAD

**Issue by stretchkennedy** [thoughtbot/paperclip#2563]
If you feed paperclip a URI and the remote server sets the header `Content-Disposition: inline;filename=""` then paperclip will proceed with an empty filename, eventually causing an Erno::EISDIR.

This is a problem when trying to use OmniAuth with omniauth-google-oauth2, because Google sets that header.

I've solved the problem for myself by doing
```ruby
class UriAdapterWithoutContentDisposition < Paperclip::UriAdapter
  def filename_from_content_disposition
    nil
  end
end

UriAdapterWithoutContentDisposition.register
```
but it would be nice if the UriAdapter could fall back to other methods when it finds a blank string.

**Comment by stretchkennedy** [comment]
Also see https://github.com/thoughtbot/paperclip/pull/2437

**Comment by sidraval** [comment]
Thank you for reporting this. Unfortunately, we will be deprecating Paperclip and therefore will not have the bandwidth to address this issue.
