### ISSUE TITLE
resize full image inside frame without loosing ratio

### ISSUE THREAD

**Issue by tuxtux59** [thoughtbot/paperclip#2565]
Hi,

I use paperclip for a while but not really focusing on ratio and sizing.
But today I need to build a copy of a picture attachment into a 320x480 image without any crop of the original picture. The goal is to always see the entire image inside this frame on center with a fill of empty pace with white or transparent color.

Here is my current code

`has_attached_file :picture, processors: [:watermark], styles: {`
`thumb: '100x100#',`
`small: '150x150>',`
`medium: '200x200',`
`preview: '400x400',`
`sharing: { geometry: '320x480^', watermark_path: "watermark.png", gravity: 'Center', background: 'white'}`
  `}, default_url: ':placeholder'`

I talk about my sharing style (I use watermark over this style and tried to set gravitiy and background for the wanted result)

I tried `#`,`^`,`>`,`<`,`'` and no added param to geometry value during my tests.

I read bunch of ImageMagick pages in aim to find a solution but never worked !

When the frame is ok, the image is cropped or ratio not respected and when the ratio is ok the frame match the original image sizes.

If you have the magic geometry parameter to set (without watermark config) I guess I could apply after the watermark ;).

Thanks !

**Comment by sidraval** [comment]
Thank you for reporting this. Unfortunately, we will be deprecating Paperclip and therefore will not have the bandwidth to address this issue.
