### ISSUE TITLE
include rmagick processor from previous style

### ISSUE THREAD

**Issue by tuxtux59** [thoughtbot/paperclip#2570]
Hi,

I want to create a combination of a styled attachment and an overlay image.

For the moment here is my code:

`has_attached_file :picture,`
`styles: {sharing: '320x480>'},`
`convert_options: {sharing: '-gravity center -background white -extent 320x480' },`
`
default_url: ':placeholder'`
`after_picture_post_process :social_img`

`def social_img`
`src = picture.url(:sharing)`
`begin`
`first_image  = MiniMagick::Image.open(src)`
`second_image = MiniMagick::Image.open("path_to_overlay.png")`
`result = first_image.composite(second_image) do |c|`
`c.compose "Over"`
`end`
`name = "#{id}-name.jpg"`
`temp = Tempfile.new(name)`
`result.write(temp.path)`
`# upload to storage and return object`
`rescue => e`
`puts e.message`
`end`
`end`

What are my concerns : 

- when `social_img`is called by `after_picture_post_process` `:sharing`is not yet ready
- Everytime I call `social_img`a new copy of the wanted image is store on my storage

I 'm wondering if I can create a custom processor To include my Magick code in paperclip directly but I guess I cannot access `:sharing`style !?

Anyone knows if I can do sharing process and my social_img process inside one processor ?

Thanks !

**Comment by sidraval** [comment]
Thank you for reporting this. Unfortunately, we will be deprecating Paperclip and therefore will not have the bandwidth to address this issue.
