### ISSUE TITLE
Error: `No handler found` with Base64 for Paperclip 5.2

### ISSUE THREAD

**Issue by mosinski** [thoughtbot/paperclip#2575]
Hi,
I'm facing with problem to upload images as base64.
Everything works fine with paperclip version **5.1.0 or lower**

My model:
```
  ...
  do_not_validate_attachment_file_type :image

  has_attached_file :image
  ...
```
My controller action:
```
  ...
  def update
    current_appointment.update(update_params)

    redirect_to check_in_flow.next_step_path
  end

  private

  def update_params
    params.require(:appointment).permit(:image)
  end
  ...
```
My params:
```
<ActionController::Parameters {"appointment"=>{"image"=>"data:image/png;base64, iVBORw0KGgo..."}, "controller"=>"my_controller", "action"=>"update"} permitted: false>
```

After upgrading version I'm always getting:
```
     Paperclip::AdapterRegistry::NoHandlerError:
       No handler found for "data:image/png;base64, iVBORw0KGgo..."
```

I was looking for a solution but without success, maybe new version not support base64 anymore ?

Paperclip version: **5.2.0 or newest**
Rails version: **5.1.4**
Ruby version: **2.3.4p301**

**Comment by mosinski** [comment]
Ok I found solution, need add the following to `config/initializers/paperclip.rb`:
```
Paperclip::DataUriAdapter.register
```

**Comment by arjunINaccolite** [comment]
I am using the above fix for the same issue but it is not working with paperclip 6.0 version. Is there any issue with newer version? Do i need to downgrade compulsorily ?

**Comment by tina-tran** [comment]
Hi @arjunINaccolite, 

Did you find a solution other than downgrade paperclip gem?
I'm having the same issue with paperclip 6.1.0. (Rails 4.2.10 and ruby 2.3.1). And I want to upload images converted from html canvas to base64.
Here is the line that throws the error:
`image_file = Paperclip.io_adapters.for(base64_image)`

Thank you in advanced for any help that you can provide.

Cheers,
Tina.

**Comment by arjunINaccolite** [comment]
@tina-tran , nope, i moved to active storage as paperclip was deprecated.

**Comment by tina-tran** [comment]
I forgot to mention that I use mongoid.
After adding `Paperclip::DataUriAdapter.register` to the `config/initializers/paperclip.rb`, I got another error: `Key not found: hash_digest`

I found this issue on: https://github.com/mrrooijen/mongoid-paperclip/issues/76.
So finally, the solution is using `Paperclip.io_adapters.for(params[:img], { hash_digest: Digest::MD5 })` after adding the adapter.
So, everything works now for me.

Cheers,
Tina.

**Comment by vedmant** [comment]
I added `Paperclip::DataUriAdapter.register` to initializer but still have an error: `No handler found for "https....."` (paperclip (5.2.1))

**Comment by akhildave** [comment]
Solution from docs

**Comment by akhildave** [comment]
Found from the docsPaperclip::UriAdapter - which accepts a URI instance.
Paperclip::HttpUrlProxyAdapter - which accepts a http string.
Paperclip::DataUriAdapter - which accepts a Base64-encoded data: string.
