### ISSUE TITLE
[paperclip] Trying to link (v5.2.1)

### ISSUE THREAD

**Issue by prodigerati** [thoughtbot/paperclip#2576]
I have a problem with the below error showing up when trying to upload a file using any paperclip version after 4.3.1...

`[paperclip] Trying to link /var/folders/cc/83f4xv2s6t92kvtppj3_78_80000gn/T/RackMultipart20180309-59843-1t9sg6r.xls to /var/folders/cc/83f4xv2s6t92kvtppj3_78_80000gn/T/d2c1003b7f8f349073e1cd091f5951d120180309-59843-1uxl0c5.xls
[paperclip] Trying to link /var/folders/cc/83f4xv2s6t92kvtppj3_78_80000gn/T/d2c1003b7f8f349073e1cd091f5951d120180309-59843-1uxl0c5.xls to /var/folders/cc/83f4xv2s6t92kvtppj3_78_80000gn/T/d2c1003b7f8f349073e1cd091f5951d120180309-59843-bkator.xls
Command :: file -b --mime '/var/folders/cc/83f4xv2s6t92kvtppj3_78_80000gn/T/d2c1003b7f8f349073e1cd091f5951d120180309-59843-bkator.xls'
   (0.5ms)  BEGIN
[paperclip] Trying to link /var/folders/cc/83f4xv2s6t92kvtppj3_78_80000gn/T/d2c1003b7f8f349073e1cd091f5951d120180309-59843-1uxl0c5.xls to /var/folders/cc/83f4xv2s6t92kvtppj3_78_80000gn/T/d2c1003b7f8f349073e1cd091f5951d120180309-59843-1vzui8x.xls
Command :: file -b --mime '/var/folders/cc/83f4xv2s6t92kvtppj3_78_80000gn/T/d2c1003b7f8f349073e1cd091f5951d120180309-59843-1vzui8x.xls'
   (0.3ms)  ROLLBACK`

My model:

      has_attached_file :attachment, :path => (Rails.root + "path/:id").to_s,
                                 :url => "/path/:id"

      validates_attachment_content_type :attachment,
                                    content_type: ["image/png",
                                                   "application/msword",
                                                   "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
                                                   "text/plain",
                                                   "application/vnd.ms-excel",
                                                   "application/x-msexcel",
                                                   "application/ms-excel",
                                                   "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", 
                                                   "application/vnd.ms-excel.sheet.binary.macroEnabled.12",
                                                   "application/octet-stream",
                                                   "application/x-apple-msg-attachment"],
                                    message: "file must be plain text, MS Word or MS Excel format."

      validates_attachment_presence :attachment

**Comment by kdironside** [comment]
You might need to set the path in your development environment so it can find ImageMagick.

e.g., in config/environments/development.rb:
  Paperclip.options[:command_path] = "/usr/local/bin/"

**Comment by sidraval** [comment]
Thank you for reporting this. Unfortunately, we will be deprecating Paperclip and therefore will not have the bandwidth to address this issue.
