### ISSUE TITLE
Paperclip changing .xlsm file mimetype to 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'

### ISSUE THREAD

**Issue by bevinh** [thoughtbot/paperclip#2577]
I'm uploading to s3 and when I upload an .xlsm file with the mimetype of 'application/vnd.ms-excel.sheet.macroEnabled.12' it is  'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' upon arrival at s3. 

I can't send specific content headers for just that upload, since there may be a variety of file types coming through the same upload.

I isolated it to Paperclip after making a new app with carrierwave and fog, and it does not change the file mime-type. 

So, I either need to migrate away from Paperclip entirely, or get a fix here. Thanks!

**Comment by sidraval** [comment]
Thank you for reporting this. Unfortunately, we will be deprecating Paperclip and therefore will not have the bandwidth to address this issue.

**Comment by micahlisonbee** [comment]
I solved this by manually overriding the content_type in a `before_post_process` like this:

Note: `file_name` is passed in from the client as we're using base64 data streams. However you can get the filename on non base64 Paperclip files the standard way `file.original_filename`.

```
before_file_attachment_post_process :modify_content_type

def modify_content_type
    return unless file_name
    extension = File.extname(file_name)
    # Paperclip is inferring macro enabled xlsm docs as the wrong content type, so we're overriding it
    if extension == '.xlsm'
      file_attachment.instance_write(:content_type, 'application/vnd.ms-excel.sheet.macroEnabled.12')
    end
  end
```
