### ISSUE TITLE
Using a Remote Imagemagick service

### ISSUE THREAD

**Issue by dracorna** [thoughtbot/paperclip#2581]
I am trying to figure out if there is a way to interface paperclip with a remote imagemagick microservice such as [flyimg](https://github.com/flyimg/flyimg). So far I have not come across any configurations that are obviously what I need to implement to accomplish this. 

This is for a mature app with plenty of preexisting media and that currently uses paperclip. We will be transitioning to gcloud and would like to avoid having to use the more expensive flex engines just to have something like imagemagick available.

**Comment by sidraval** [comment]
Thank you for reporting this. Unfortunately, we will be deprecating Paperclip and therefore will not have the bandwidth to address this issue.
