### ISSUE TITLE
`Paperclip::Geometry.from_file(file)` returns incorrect width & height when file is a specific animated gif.

### ISSUE THREAD

**Issue by YuheiNakasaka** [thoughtbot/paperclip#2582]
`Paperclip::Geometry.from_file(file)` returns incorrect dimensions when `file` is an animated gif.
https://github.com/thoughtbot/paperclip/blob/master/lib/paperclip/geometry_detector_factory.rb#L19

This method uses first frame as a file to generate dimension, so it returns incorrect width&height when each frames are different size like this input.gif.

```
$ identify  -format '%wx%h, ' input.gif
93x152, 110x107, 144x112, 103x141, 84x106, 81x121, 74x136, 104x127, 117x98, 140x99, 143x85, 98x91, 92x113, 88x109, 105x170, 105x168, 100x125, 84x171, 150x196, 136x108, 93x104, 138x91, 204x96, 201x95, 147x145, 97x150, 61x220, 129x151, 62x172, 62x172, 62x113

$ file input.gif
input.gif: GIF image data, version 89a, 290 x 241
```

To fix this behavior easily, I'll recommend to use `%Wx%H` instead of `%wx%h`.

Example

```ruby
    def geometry_string
      begin
        orientation = Paperclip.options[:use_exif_orientation] ?
          "%[exif:orientation]" : "1"
        Paperclip.run(
          "identify",
          "-format '%Wx%H,#{orientation}' :file", { # Replaced %wx%h to %Wx%H.
            :file => "#{path}[0]"
          }, {
            :swallow_stderr => true
          }
        )
      rescue Terrapin::ExitStatusError
        ""
      rescue Terrapin::CommandNotFoundError => e
        raise_because_imagemagick_missing
      end
    end
```

This may not be considered a bug, but I'd be happy to return logical screen size.

**Comment by sidraval** [comment]
Thank you for reporting this. Unfortunately, we will be deprecating Paperclip and therefore will not have the bandwidth to address this issue.
