### ISSUE TITLE
v5.2.0 and later break paperclip processors that relied on earlier copying behavior

### ISSUE THREAD

**Issue by gsar** [thoughtbot/paperclip#2583]
If you have a paperclip processor that writes to the same destination file when it gets called to process more than one style in an attachment, it now fails with a log message like this when attempting to upload processed files to S3:

```
excon.error.response 
Mar 23 07:08:08 yourapp app/worker.5:    :body          => "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>IncompleteBody</Code><Message>You did not provide the number of bytes specified by the Content-Length HTTP header</Message><NumberBytesExpected>30575</NumberBytesExpected><NumberBytesProvided>29856</NumberBytesProvided><RequestId>2E4D133F1AA09F00</RequestId><HostId>IWyangP2nj6Fy8J3a5N6Qcd0ko7Uz6rOw5owvcQLbP2eElkkW1QgkTg1uof9N4aSoBQoC7ocBxk=</HostId></Error>"
```

We have determined this is a side effect of the hardlinking optimization introduced in #2120. Since the file is no longer copied, a subsequent call to the processor to generate the second style will overwrite the hardlinked file. This corrupts the file that was earlier queued for sending to S3 and produces errors like the above.

The fix is to make sure your processors create unique files when they are called, perhaps by including the style name in the file or its path.

This incompatibility should be better documented.

**Comment by sidraval** [comment]
Thank you for reporting this. Unfortunately, we will be deprecating Paperclip and therefore will not have the bandwidth to address this issue.
