### ISSUE TITLE
Paperclip “Data content type is not valid” after trying upload image in rails

### ISSUE THREAD

**Issue by elisbresciani** [thoughtbot/paperclip#2585]
This is what appear in my log:

```
Parameters: {"upload"=>#<ActionDispatch::Http::UploadedFile:0x7e20e68
@tempfile=#<Tempfile:C:/Users/bi/AppData/Local/Temp/2/RackMultipart20180116-3004-iw0tdo.jpg>,
@original_filename="Inkedmdb atualizado_LI.jpg", @content_type="image/jpeg", 
@headers="Content-Disposition: form-data; name=\"upload\"; 
filename=\"Inkedmdb atualizado_LI.jpg\"\r\nContent-Type: image/jpeg\r\n">,
"ckCsrfToken"=>"AR65EsJdr219Nu21oN1Vlw8fc8XAJTc5ZTIQ1lg9", "CKEditor"=>"pop_objective", 
"CKEditorFuncNum"=>"1", "langCode"=>"pt-br"}

Command :: file -b --mime "C:/Users/bi/AppData/Local/Temp/2/43a60d0ece9425495f704619dc133c4f20180116-3004-bkzljx.jpg"

Command :: identify -format '%wx%h,%[exif:orientation]' "C:/Users/bi/AppData/Local/Temp/2/242e48571825b96df1752e5c3933b2fd20180116-3004-1n87xt.jpg[0]" 2>NUL
```
I searched on internet end they suggested me to create a new file in the initializer to overwrite the method spoof or something like that, I created, and now the error changed, but still there.

Data content type is not valid

Does someone have any ideas, why that happening?

**Comment by drwl** [comment]
Can you also post your model validations?

**Comment by elisbresciani** [comment]
has_attached_file :image,
    :styles => {
      :thumb => '32x32#',
      :medium => '64x64#',
      :large => '256x256#'
    }, :default_url => "/images/default.png"

**Comment by elisbresciani** [comment]
Someone has any idea why that happening?

**Comment by elisbresciani** [comment]
@drwl some idea why this is happening?

**Comment by sidraval** [comment]
Thank you for reporting this. Unfortunately, we will be deprecating Paperclip and therefore will not have the bandwidth to address this issue.
