### ISSUE TITLE
Paperclip::UriAdapter doesn't handle getting the filename from content-disposition properly

### ISSUE THREAD

**Issue by Korkey128k** [thoughtbot/paperclip#2590]
https://github.com/thoughtbot/paperclip/blob/4c0eacdb585d017d53b202ad67631fbde13d2dbd/lib/paperclip/io_adapters/uri_adapter.rb#L38

Quick fix is to modify the regex, making the quotes optional (probably isn't the best solution)
`matches = @content.meta["content-disposition"].match(/filename="?([^"]*)"?/) `

I glanced at [the RFC](https://www.ietf.org/rfc/rfc2183.txt) and didn't see where the filename needs to be quoted, but the regex requires it.
Thoughts?

**Comment by sidraval** [comment]
Thank you for reporting this. Unfortunately, we will be deprecating Paperclip and therefore will not have the bandwidth to address this issue.
