### ISSUE TITLE
Set default filename if filename_from_content_disposition fails

### ISSUE THREAD

**Issue by tuxtux59** [thoughtbot/paperclip#2591]
Hi,

I'm currently trying to save attachments from URLs but major of these hasn't neither a filename neither a type on URL. But there is a content and a content-type in the headers.

I'm facing an error from `uri_adapter.rb:34` : `filename_from_content_disposition` using a set using url

My question is : Is there a way to force set of filename at same time of setting content from url?

Thanks

**Comment by sidraval** [comment]
Thank you for reporting this. Unfortunately, we will be deprecating Paperclip and therefore will not have the bandwidth to address this issue.
