### ISSUE TITLE
Any way to mock/fake paperclip attributes to speed up test cases?

### ISSUE THREAD

**Issue by mridulap2003** [thoughtbot/paperclip#2593]
I am using Paperclip in my `Rails 5` application and it works fine. The issue however is that my test cases run a little slow. Let me explain:

I use `Rspec` to write specs. I have an `Event` model which has many attachments in it, and all these attachments are compulsory (about 15 of them).

I need an object of the `Event` model in almost every test case. So all these 15 attachments are processed and created for each test case - which makes the test suite run a bit slow.

One option to make it faster is to keep ONE event object, which is created before the suite runs using the `before(:all)` hook. But the problem is that, if I make any changes to the object, it will be carried forward to the next test case, which I want to avoid.

Is there anyway that when I create the Event object in the test environment, the attachments are faked so as to speed up the test suite?

**Comment by sidraval** [comment]
Thank you for reporting this. Unfortunately, we will be deprecating Paperclip and therefore will not have the bandwidth to address this issue.
