### ISSUE TITLE
NotIdentifiedByImageMagickError on Ubuntu 16.04 (12/05/2018)

### ISSUE THREAD

**Issue by Skulli** [thoughtbot/paperclip#2626]
The problem described in #2223 is not the cause of the error. That setting was already set a month ago.
Recently there was another security update, probably for the ghostscript package (9.26).

Following command gives trouble: 

`identify -format '%wx%h,%[exif:orientation]' 'test.pdf[0]'
`

which results in

> identify: FailedToExecuteCommand `"gs" -q -dQUIET -dSAFER -dBATCH -dNOPAUSE -dNOPROMPT  .....

`identify -format '%wx%h,%[exif:orientation]' 'test.pdf'
`

and

`identify 'test.pdf[0]'
`

are working but not the combination of both.

**Comment by Skulli** [comment]
Just did a ghostscript downgrade to 9.18 and now erverything works (version before 27 Sep 2018)

**Comment by Skulli** [comment]
shame on me, server restart was enough. Since there was an upgrade from 9.18 to 9.26, there was a change in the path and imagemagick did not get that.

**Comment by pierre-alain-b** [comment]
I hit this problem in Debian Stretch starting around early Dec 2018. I fixed it temporarily by reverting to an older version of ghostscript.
apt-get install libgs9=9.20~dfsg-3.2+deb9u5 ghostscript=9.20~dfsg-3.2+deb9u5 libgs9-common=9.20~dfsg-3.2+deb9u5

My explanation, not yet confirmed, is that the recent update to Ghostscript 9.26 in Debian Stretch Security caused the issue to pop up. Further investigation to do...

**Comment by Skulli** [comment]
see https://bugs.launchpad.net/ubuntu/+source/ghostscript/+bug/1806517

in Ubuntu it should be fixed by now

**Comment by pierre-alain-b** [comment]
Thank you for pointing this out, I will make sure this bug is similarly reported in Debian and treated diligently
