### ISSUE TITLE
Permission denied @ dir_s_mkdir - /photos

### ISSUE THREAD

**Issue by FacelessMonster** [thoughtbot/paperclip#2641]
In development mode, when I try to upload a photo, I get an error:
![Снимок экрана 2019-05-16 в 13 32 07](https://user-images.githubusercontent.com/45975483/57847417-15488f80-77df-11e9-8c60-0b774ab65e04.png)

But it works when I try to do it on heroku+aws s3

**Comment by rahulpattanshetty** [comment]
@FacelessMonster getting the same error in development mode. How u resolved this?
