### ISSUE TITLE
validates_attachment_size :less_than => 5.megabytes - not working?

### ISSUE THREAD

**Issue by adamthedeveloper** [thoughtbot/paperclip#284]
<pre>
class ReviewImage < ActiveRecord::Base
  belongs_to :review

  options = Modcloth::Images::S3.new.configuration
  has_attached_file :data, options.merge!(:styles => {:thumb => "71x106#", :zoom => "320x320>", :original => "500x500>"})

  validates_attachment_presence :data
  validates_attachment_size :less_than => 5.megabytes
  validates_attachment_content_type :data, :content_type => ['image/jpeg', 'image/png', 'image/gif']
end
</pre>

But when I run this, I get the following in the logs:

<pre>
NoMethodError (undefined method `less_than5242880_file_size' for #<ReviewImage:0xcab1d08>):
  app/controllers/storefront/reviews_controller.rb:13:in `create'
  haml (3.0.18) rails/./lib/sass/plugin/rack.rb:41:in `call'
  haml (3.0.18) rails/./lib/sass/plugin/rack.rb:41:in `call'
  app/middleware/flash_session_cookie_middleware.rb:14:in `call'
</pre>

Any ideas?  Thanks,

Adam

**Comment by pmaojo** [comment]
Yes but without the comma after validates_attachment_size
Like this:
validates_attachment_size :data, :less_than => 5.megabytes
