### ISSUE TITLE
Paperclip::InfiniteInterpolationError (Paperclip::InfiniteInterpolationError):

### ISSUE THREAD

**Issue by ypadlyak** [thoughtbot/paperclip#516]
How can I debug this kind of error?

Thank you in advance!

Paperclip::InfiniteInterpolationError (Paperclip::InfiniteInterpolationError):
  paperclip (2.3.3) lib/paperclip/interpolations.rb:45:in `url'
  paperclip (2.3.3) lib/paperclip/interpolations.rb:31:in`send'
  paperclip (2.3.3) lib/paperclip/interpolations.rb:31:in `interpolate'
  paperclip (2.3.3) lib/paperclip/interpolations.rb:30:in`gsub'
  paperclip (2.3.3) lib/paperclip/interpolations.rb:30:in `interpolate'
  paperclip (2.3.3) lib/paperclip/interpolations.rb:29:in`each'
  paperclip (2.3.3) lib/paperclip/interpolations.rb:29:in `inject'
  paperclip (2.3.3) lib/paperclip/interpolations.rb:29:in`interpolate'
  paperclip (2.3.3) lib/paperclip/attachment.rb:305:in `interpolate'
  paperclip (2.3.3) lib/paperclip/attachment.rb:122:in`path'
  paperclip (2.3.3) lib/paperclip/storage.rb:40:in `flush_writes'
  paperclip (2.3.3) lib/paperclip/storage.rb:38:in`each'
  paperclip (2.3.3) lib/paperclip/storage.rb:38:in `flush_writes'
  paperclip (2.3.3) lib/paperclip/attachment.rb:144:in`save'
  paperclip (2.3.3) lib/paperclip.rb:384:in `send'
  paperclip (2.3.3) lib/paperclip.rb:384:in`save_attached_files'
  paperclip (2.3.3) lib/paperclip.rb:377:in `each_attachment'
  paperclip (2.3.3) lib/paperclip.rb:376:in`each'
  paperclip (2.3.3) lib/paperclip.rb:376:in `each_attachment'
  paperclip (2.3.3) lib/paperclip.rb:383:in`save_attached_files'

**Comment by shqear93** [comment]
I have the same issue, this is my configurations

`
Paperclip::Attachment.default_options.merge!(
  s3_headers:     { cache_control: 'public, max-age=31536000', expires: 10.years.from_now.httpdate },
  s3_protocol:    'https',
  storage:        :s3,
  s3_region:      Rails.application.secrets[:s3_region],
  #s3_host_name:    's3.eu-central-1.amazonaws.com'  ,
  s3_endpoint:    's3.eu-central-1.amazonaws.com'  ,
  url:            ':s3_domain_url',
  s3_credentials: {
    bucket:            Rails.application.secrets[:s3_bucket],
    access_key_id:     Rails.application.secrets[:s3_access_key_id],
    secret_access_key: Rails.application.secrets[:s3_secret_access_key]
  },
  s3_permissions: :private,
  default_url:    "#{Rails.application.secrets[:zenhr_url]}/images/missing.png",
  s3_options:     s3_options
)`
