### ISSUE TITLE
Support for S3 versioning

### ISSUE THREAD

**Issue by JDutil** [thoughtbot/paperclip#541]
I'm implementing the PaperTrail gem into one of my applications, and am not sure how I can version PaperClip assets stored to S3.  After looking through the PaperClip code I don't see any references to being able to get the S3 objects version id or to retrieve objects from S3 using a version id.  It looks like PaperClip only cares about the most recent version.  It would be nice to add support for getting the S3 objects version id and/or to be able to retrieve assets using a version id.

I'm not sure if this is possible with PaperClip or within it's scope, but would love to hear thoughts on how this could be accomplished.

**Comment by xtagon** [comment]
@JDutil and @sikachu I appologize for  bringing up an old issue, but I was wondering if anyone moved forward with a solution for this since then on their own? I have the same use case and wanted to see if there's an existing solution that may have come up since.

**Comment by JDutil** [comment]
@xtagon I did not follow through with an implementation as it was removed from the scope of the project I was working on at the time.

**Comment by xtagon** [comment]
@JDutil That's too bad, but thank you for letting me know and responding so quickly :-)
