### ISSUE TITLE
Rails 3.1, RSpec Controllers & Paperclip Mass Assignment (bug?)

### ISSUE THREAD

**Issue by thebaggage** [thoughtbot/paperclip#571]
This may be a bug, or it may be me missing something, but in rails 3.1.0.rc6/rspec2.6.0/paperclip2.3.15 I'm trying to run the following code:

```
describe "POST create" do
  describe "with valid params" do
    it "creates a new Banner" do
      attribs = {
        :name => 'Test Name',
        :bannerimage => File.open(File.join(Rails.root, "spec", "samples", "laptop1.jpg"))
      }

      expect {
        post :create, :banner => attribs
      }.to change(Banner, :count).by(1)
    end
  end
end
```

The test fails with a 'count not changed' error, but passes if I replace the post :create, :banner => attribs call with 

```
b = Banner.new(attribs)
b.save
```

which is what's happening in the controller.

It also passes if I take out the validates_attachment_presence call in the banners model. The functionality works if performed manually through the browser.

Inspecting through the debugger, i'm getting the good ol' "missing.png" for :bannerimage, and a "bannerimage file name must be set" for banner.errors.full_messages. The action is a dead simple restful create:

```
def create
  @banner = Banner.new(params[:banner])

  if @banner.save
    redirect_to admin_banner_url(@banner), notice: 'Banner was successfully created.'
  else
    render action: "new"
  end
end
```

I've tried taking out attr_accessible - no joy. I've injected puts messages into the controller action to ensure it's calling the correct action (it is). Any idea what might be causing this?

**Comment by niltonvasques** [comment]
I got this error again in paperclip 5.0.0: 
```ruby
     Paperclip::AdapterRegistry::NoHandlerError:
       No handler found for "#<Rack::Test::UploadedFile:0x00000005359698>"
```
