### ISSUE TITLE
absolute url

### ISSUE THREAD

**Issue by ghost** [thoughtbot/paperclip#584]
This ticket is a feature request for a method to get the absolute url to the image instead of a relative url.

The `Attachment#url` method is misleading since it returns a relative path (like the Routes _path methods) not a full url (like the Routes _url methods).  Googling turns up several "answers", but they are all hacks.

**Comment by faizalluthfi** [comment]
When the absolute url is needed for image, image_path(u.photo.url) works for me..

image_tag(u.photo.url) works for me too to insert image in html template..

See image_tag code in Ruby on Rails API documentation for detail..

**Comment by snowmoonsoftware** [comment]
My use case is a bit different. I need to generate a full url from a paperclip-enabled model, from a service object to use in an SVG file. I could really use this feature.

**Comment by brendon** [comment]
You can use `asset_url(file.url(:thumb))`. You can pass the `:host` into the `asset_url` method directly, or set it globally:

```ruby
asset_url(file.url(:thumb), :host => "//www.myassets.com")
```

or

```ruby
config.action_controller.asset_host = "//www.myassets.com"
config.action_mailer.asset_host = "//www.myassets.com"
```
