### ISSUE TITLE
showing up sideways

### ISSUE THREAD

**Issue by jaehyunkim** [thoughtbot/paperclip#591]
[My environements]

Rails 3.1, Paperclip 2.4.0

code block:

  has_attached_file :image, :styles => { :small => "100x75#", :xsmall => "80x60#", :small_square => '104x104#' },
  :convert_options => { :all => '-auto-orient' }

As a result, 75x100 and 60x80 images were generated.

I want to orient first, and then resize image. but, paperclip work to resize first, and then orient.

How can I get auto-oriented 100x75 and 80x60 size images?

**Comment by xiaopow** [comment]
I am currently having the same issue 

has_attached_file :picture, source_file_options: { all: '-auto-orient' }, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "http://placehold.it/400x400"

this does not auto rotate the image when it gets stored.

**Comment by forrestgrant** [comment]
+1

**Comment by gosukiwi** [comment]
@xiaopow try adding a `:original` style, maybe it's only applying it to the thumbs?

**Comment by kreeger** [comment]
For what it's worth, adding an original style works like this quite nicely for me.

```ruby
# -auto-orient here makes sure photo rotation data is flattened first, and
#   the empty original style is so that the -auto-orient flag is also applied
#   to the original file
has_attached_file :file,
  source_file_options: { all: '-auto-orient' },
  styles: { original: "", thumb: "200x200#" }
```

**Comment by bradbumbalough** [comment]
Thanks @kreeger! I ended up writing all this hack code to determine if the image rotated and how to property crop it... come to find this thread and the `-auto-orient` prop which as solved everything. I did have to create an empty `original` style too.

**Comment by dougc84** [comment]
@kreeger - had this same issue in a recent project where photos looked fine uploaded, but running them through a JS image cropper rotated images sideways.

The `styles: { original: "" }` seems to be the fix, with `convert_options: { original: "-strip" }` to remove metatags on the original (and should be done on all images and styles for security purposes alone).

It seems `source_file_options` doesn't actually do anything.  There's no reference to it in Paperclip's documentation, and adding or removing it didn't make any change.

**Comment by starspace1** [comment]
@kreeger Thank you so much! I had -auto-orient but was missing the empty original style (```original: ""```) which I would never have thought of. Much appreciated!

**Comment by oBuiDucThinh** [comment]
@kreeger thank you, your solution works great
