### ISSUE TITLE
Spaces in filename are URL encoded when saved to filesystem

### ISSUE THREAD

**Issue by brighton-agency** [thoughtbot/paperclip#608]
When attaching a file with spaces i.e "spaced file.png" the file is saved to the filesystem with the filename "spaced%20file.png"

**Comment by phbernard** [comment]
I got the same kind of issue when assigning a URI to an attribute declared with `has_attached_file`. Not sure what I'm doing wrong.

I worked around the issue by using a custom `filename_cleaner`:

    class CustomCleaner
      def initialize
        @filename_cleaner = Paperclip::FilenameCleaner.new(Paperclip::Attachment.default_options[:restricted_characters])
      end

      def call(name)
        @filename_cleaner.call URI.unescape(name)
      end
    end

Then, in the attribute declaration:

    has_attached_file :some_attribute,
      filename_cleaner: CustomCleaner.new,
      ...
