### ISSUE TITLE
Which callback gets called when the attachment is uploaded to S3?

### ISSUE THREAD

**Issue by guiocavalcanti** [thoughtbot/paperclip#816]
Hello, I'm wondering if there is any paperclip callback fired _after_ the file gets uploaded to S3. I did some research on this topic and got inconclusive answers.

My case is: after the file is uploaded I want to send its S3 URL to another service which is going to process the file. So it's important that the file is already accessible by this URL, ie uploaded.

Thanks for the support!

**Comment by marcpt** [comment]
I defined the `after_flush_writes` method inside the model that has an attachment and It did not work.
Where should I define the method?

```
class ExcelFile < ActiveRecord::Base
  belongs_to :insertion #, required: true
  has_attached_file :excel
  validates_attachment_content_type :excel, content_type: [ "application/vnd.ms-excel",
                    "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
                    "application/msword",
                    "application/vnd.openxmlformats-officedocument.wordprocessingml.document"]


  def after_flush_writes
    super
    byebug
    file = Roo::Excelx.new(self.excel.url(:original, timestamp: false))
    input_from_generals self.id, file
    input_from_financials self.id, file
  end
```
