### ISSUE TITLE
Animated GIF support?

### ISSUE THREAD

**Issue by evie404** [thoughtbot/paperclip#851]
I know this question has already been asked too many times. I digged through the wiki with no luck. But the source code there is an option `:animated` in /lib/paperclip/style.rb

so I implemented the attachment with the animated options:

`has_attached_file :banner, :styles => { :cover_200x40 => {:geometry =>'200x40#',:animated => true}}`

but the files i uploaded are still not animated. changed the file format to GIF:

`has_attached_file :banner, :styles => { :cover_200x40 => {:geometry =>'200x40#',:animated => true, :format => 'GIF'}}`

and still not animated.

Is this option actually valid?

the line I am using to output the image file is:

`<img src="<%=event.banner.url(:cover_200x40)%>"/>`

thanks in advance.

**Comment by seanfcarroll** [comment]
+1

**Comment by sambecker** [comment]
I seem to be having a related issue. When I upload a GIF w/ or w/out `animated: true` it stops looping the way the original file did. Is this a problem w/ Paperclip or possibly ImageMagick?
