### ISSUE TITLE
Passing Access-Control-Allow-Origin to Rackspace using Fog Storage

### ISSUE THREAD

**Issue by johnkelly** [thoughtbot/paperclip#852]
Due to some HTML5 canvas security issues, I am looking to pass the header "Access-Control-Allow-Origin" => "*" with my image when I do an upload with paperclip.

I am trying
```ruby
  has_attached_file :image,
                    PAPERCLIP_OPTIONS.merge(
                        :path => ":filename",
                        :storage => :fog,
                        :fog_file => {
                            'Access-Control-Allow-Origin' => '*'
                        },
...
```
The upload is successful but when I view the image I do not see the Access-Control-Allow-Origin header in the image get request.  In Rackspace's cloudfiles gem I can simply do

```ruby
   ...
    headers = {
        'Access-Control-Allow-Origin' => '*',
    }
    object.write file, headers
```
to save the file with the correct header and I can then view the header on the image get request.  Any ideas why this is not working with paperclip?  Shouldn't :fog_files save the file with the header?

**Comment by maclover7** [comment]
Hi @johnkelly ! Is this still an issue for you in Paperclip; I know this issue is from approximately 3 years ago. If it is still an issue, can you please provide the code that's causing you the error? Thanks!

**Comment by johnkelly** [comment]
@maclover7 The company with this issue no longer uses rackspace and I don't use paperclip so I think I can close.
