### ISSUE TITLE
Too many open files

### ISSUE THREAD

**Issue by amolpujari** [thoughtbot/paperclip#862]
*\* Execute articles_download_images_from_url

"Downloading images in batches"
"This may take few minutes/hours"
rake aborted!
Too many open files - /tmp/stream20120507-32724-271eno.jpg
/usr/local/lib/ruby/1.9.1/tempfile.rb:147:in `initialize'
/usr/local/lib/ruby/1.9.1/tempfile.rb:147:in`open'
/usr/local/lib/ruby/1.9.1/tempfile.rb:147:in `block in initialize'
/usr/local/lib/ruby/1.9.1/tmpdir.rb:132:in`create'
/usr/local/lib/ruby/1.9.1/tempfile.rb:134:in `initialize'
/home/amol/my_project/releases/20120503120644/vendor/plugins/paperclip/lib/paperclip/iostream.rb:8:in`new'
/home/amol/my_project/releases/20120503120644/vendor/plugins/paperclip/lib/paperclip/iostream.rb:8:in `to_tempfile'
/home/amol/my_project/releases/20120503120644/vendor/plugins/paperclip/lib/paperclip/attachment.rb:92:in`assign'
/home/amol/my_project/releases/20120503120644/vendor/plugins/paperclip/lib/paperclip.rb:252:in `block in has_attached_file'
/usr/local/lib/ruby/gems/1.9.1/gems/activerecord-3.0.5/lib/active_record/base.rb:1558:in`block in attributes='
/usr/local/lib/ruby/gems/1.9.1/gems/activerecord-3.0.5/lib/active_record/base.rb:1554:in `each'
/usr/local/lib/ruby/gems/1.9.1/gems/activerecord-3.0.5/lib/active_record/base.rb:1554:in`attributes='
/usr/local/lib/ruby/gems/1.9.1/gems/activerecord-3.0.5/lib/active_record/base.rb:1406:in `initialize'
/usr/local/lib/ruby/gems/1.9.1/gems/activerecord-3.0.5/lib/active_record/reflection.rb:173:in`new'
/usr/local/lib/ruby/gems/1.9.1/gems/activerecord-3.0.5/lib/active_record/reflection.rb:173:in `build_association'
/usr/local/lib/ruby/gems/1.9.1/gems/activerecord-3.0.5/lib/active_record/associations/association_collection.rb:511:in`build_record'
/usr/local/lib/ruby/gems/1.9.1/gems/activerecord-3.0.5/lib/active_record/associations/association_collection.rb:119:in `build'
/home/amol/my_project/releases/20120503120644/lib/attachment_module.rb:43:in`block in save_attachments'
/home/amol/my_project/releases/20120503120644/lib/attachment_module.rb:42:in `each'
/home/amol/my_project/releases/20120503120644/lib/attachment_module.rb:42:in`save_attachments'
/home/amol/my_project/releases/20120503120644/app/models/article.rb:485:in `block (2 levels) in download_images_from_url'
/home/amol/my_project/releases/20120503120644/app/models/article.rb:477:in`each'
/home/amol/my_project/releases/20120503120644/app/models/article.rb:477:in `block in download_images_from_url'
/usr/local/lib/ruby/gems/1.9.1/gems/activerecord-3.0.5/lib/active_record/relation/batches.rb:71:in`find_in_batches'
/usr/local/lib/ruby/gems/1.9.1/gems/activerecord-3.0.5/lib/active_record/base.rb:440:in `find_in_batches'
/home/amol/my_project/releases/20120503120644/app/models/article.rb:475:in`download_images_from_url'
/home/amol/my_project/releases/20120503120644/lib/tasks/articles.rake:72:in `block (2 levels) in <top (required)>'
/usr/local/lib/ruby/gems/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:205:in`call'
/usr/local/lib/ruby/gems/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:205:in `block in execute'
/usr/local/lib/ruby/gems/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:200:in`each'
/usr/local/lib/ruby/gems/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:200:in `execute'
/usr/local/lib/ruby/gems/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:158:in`block in invoke_with_call_chain'
/usr/local/lib/ruby/1.9.1/monitor.rb:201:in `mon_synchronize'
/usr/local/lib/ruby/gems/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:151:in`invoke_with_call_chain'
/usr/local/lib/ruby/gems/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:144:in `invoke'
/usr/local/lib/ruby/gems/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:116:in`invoke_task'
/usr/local/lib/ruby/gems/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:94:in `block (2 levels) in top_level'
/usr/local/lib/ruby/gems/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:94:in`each'
/usr/local/lib/ruby/gems/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:94:in `block in top_level'
/usr/local/lib/ruby/gems/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:133:in`standard_exception_handling'
/usr/local/lib/ruby/gems/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:88:in `top_level'
/usr/local/lib/ruby/gems/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:66:in`block in run'
/usr/local/lib/ruby/gems/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:133:in `standard_exception_handling'
/usr/local/lib/ruby/gems/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:63:in`run'
/usr/local/lib/ruby/gems/1.9.1/gems/rake-0.9.2.2/bin/rake:33:in `<top (required)>'
/usr/local/bin/rake:19:in`load'
/usr/local/bin/rake:19:in `<main>'
Tasks: TOP => articles_download_images_from_url

**Comment by slavajacobson** [comment]
Is there a way to make paperclip close files after creating a new database entry? After running the following code couple of hundred times, I am getting an error too.

```ruby
Frame::Page.create!({background_image: 'db/files/file.jpg'})
```

Errno::EMFILE: Too many open files - file -b --mime '/tmp/f90a3056404d0e51d76583c0c692bfe620150306-20951-18eyd9820150306-20951-vpjz97.jpg'
