### ISSUE TITLE
Paperclip loops hundreds of times and times out

### ISSUE THREAD

**Issue by johnroa** [thoughtbot/paperclip#866]
SE thread: http://stackoverflow.com/questions/10142159/paperclip-s3-paperclip-saving-attachments-times-out

Rails 3.1.1
Heroku

When I access one particular model of my app in everything from updating attributes to creating to deleting, the logs show:

   [paperclip] Saving attachments
   [paperclip] Saving attachments
   [paperclip] Saving attachments
   [paperclip] Saving attachments
   [paperclip] Saving attachments
   [paperclip] Saving attachments

about 200 times, and then the app times out. It only happens on one particular model.

The paperclip config in the model is:

```
# File upload
has_attached_file :questimage, 
    :styles => {
        :original => {
            :geometry => "2048",
            :quality => 70
        },
        :full   =>  "933",
        :thumb => "300x200#",
        :small => "85x85#"
    },
    :convert_options => { :all => '-auto-orient' },
    :storage => :s3,
:s3_credentials => YAML.load_file('config/s3.yml'),
:path => ":attachment/:id_:style.:extension"
```

One in about five attempts everything works fine. The other four, the app times out and dies.

Here is the strange parts: 

a) this only happens in production. In staging, which has the _exact_ same environment config file, it works perfectly. It also works perfectly in development (all of which use s3).

b) this happens even when a file is not being manipulated, such as changing an attribute on the record from true to false.

The log do not reveal anything except the hundreds of "[paperclip] Saving attachments." before timing out. 

Completely stuck on this. Guessing I've found an odd bug but am having a hard time tracing it.

Thank you!

**Comment by osifoanosike** [comment]
@jgarber you the best man! ur comment still very relevant!
