### ISSUE TITLE
s3_headers doesn't work correctly

### ISSUE THREAD

**Issue by k4roshi** [thoughtbot/paperclip#895]
Adding :s3_headers  => {:content_md5 => encoded_md5} to has_attached_file always produces an "Invalid Digest" error from S3. This in spite of using the correct md5 fingerprint, encoded in base64. I also tried adding or removing a trailing '=' to the string, to no result. 
On a related note, using a lambda to calculate at runtime the correct value for :content_md5 doesn't seem to produce the desired results, as it gets called too early, when the md5 has yet to be calculated.

**Comment by maclover7** [comment]
Hi @k4roshi ! Is this still an issue for you in Paperclip; I know this issue is from approximately 3 years ago. If it is still an issue, can you please provide the code that's causing you the error? Thanks!

**Comment by k4roshi** [comment]
I'm sorry, that code has been removed from production a long time ago. AFAIK, it was never solved though. We skipped the integrated md5 check entirely to get around the issue.

**Comment by maclover7** [comment]
@jferris @jyurek Please close issue, problem appears to be solved.

**Comment by tute** [comment]
Thanks for your work on paperclip issues, @maclover7!
