### ISSUE TITLE
Copying s3-based attachments

### ISSUE THREAD

**Issue by qrush** [thoughtbot/paperclip#9]
Reported by Dylan Markow

Using S3, it doesn't seem that copying attachments from one record to another works. The comments in attachment.rb state that "In addition to form uploads, you can also assign another Paperclip attachment: new_user.avatar = old_user.avatar", but when I try this, the second record's attachment remains empty and nothing gets uploaded to amazon's servers.

<pre>
a = Post.find(1)
b = Post.find(2)
a.attachment_file_name
# => "Attachment.pdf"
b.attachment_file_name
# => nil
b.attachment = a.attachment
b.save
b.attachment_file_name
# => nil
</pre>

**Comment by michaelcavallaro03** [comment]
I realize this thread is from literally a decade ago. If anyone is still using paperclip/can't migrate off of it and are having problems when duplicating an attachment, after trying everything I could find/think of, such as doing `.image = nil`. `.image = copy_of_file` or `.image.destroy`, etc. etc., what eventually worked was the following:

The following snippet assumes you are duplicating an ActiveRecord model with a Paperclip attachment attribute that is uploaded to AmazonS3.

```
# ModelA.image - the paperclip attachment attribute

modelB = modelA.dup

# commit this to the Database to get the ID on the model
modelB.save!

# Before this point, modelB still had the reference to modelA's instance
# so we need to reset this instance manually to the new model, otherwise
# `modelB` would still be tied to/affected by changes on `modelA`
modelB.image.instance_variable_set("@instance", modelB)

# Download the file from the url on the image, ie. `modelA.image.url`
new_file = <enter your own file URL fetching logic>

# Finally assign the new file to the attachment to allow paperclip to reupload
# Note: `modelB.image = new_file` would likely work.
modelB.image.assign(new_file)
``` 

This very well could've been a product of a specific use case/misunderstanding of how the library works/bug in paperclip. Regardless of all that, this worked for me and there's no way I dig deeper mainly out of fear.

Hope this helps someone!
