### ISSUE TITLE
Paperclip with ActionDispatch::Http::UploadedFile handler

### ISSUE THREAD

**Issue by chenillen** [thoughtbot/paperclip#907]
I am using paperclip with uploadify as multiple files uploading front-end, so paperclip with handle the file from  ActionDispatch::Http::UploadedFile. The problem is when uploading, the original file name has been covert to Rack tmp file name.
# File:/var/folders/_t/46v44dfs51s20fjrkfnrhd3h0000gn/T/RackMultipart20120606-4904-14xpwrz>

```
Track.create!(:media => params[:file].tempfile)
```

Any way to get the original file name? I tried give the params[:file] object to media, but didn't upload successfully.

**Comment by JagannathMP** [comment]
Uploading same attachment twice fails, until i refresh the page after first upload.
