### ISSUE TITLE
Slow generation of url

### ISSUE THREAD

**Issue by DriesS** [thoughtbot/paperclip#909]
We are trying to optimize our views and on a page where 40 pictures are loaded with the following code :

```
= image_tag(product.pictures.first.data.url(:gallery))
```

We have a load time of 840ms, if we change it to the following code :

```
= image_tag("http://bucketname.s3.amazonaws.com/products/#{product.pictures.first.id}/gallery.jpg?1325844462"
```

We become a load time of 220ms.

It means the interpolation of s3_path_url is very slow. Somebody else is expecting the same problems? For the moment I created a helper that generates my urls :

```
def picture_url(picture, style)
  "http://bucketname.s3.amazonaws.com/products/#{picture.id}/#{style}.jpg"
end
```

Only problem I have here is that the cache key is not there and also the extension not.

**Comment by deanputney** [comment]
This problem still seems to be an issue. +1 for reopening.

**Comment by lucianosousa** [comment]
I remember that when I had this problem, I just migrate from fog to aws-s3 and had a better performance, but, it's incomparable with carrierwave or any other solution I used.

Looks like when I paperclip request for a image they authenticate all the time on AWS, and other solutions store a login in cache... looks like this way the problem.
