### ISSUE TITLE
AccessDenied XML document on S3 when trying to access an uploaded photo

### ISSUE THREAD

**Issue by rahilsondhi** [thoughtbot/paperclip#949]
Here is my bucket policy on S3:

```
{
    "Version": "2008-10-17",
    "Statement": [
        {
            "Sid": "AllowPublicRead",
            "Effect": "Allow",
            "Principal": {
                "AWS": "*"
            },
            "Action": "s3:GetObject",
            "Resource": "arn:aws:s3:::BUCKET_NAME/avatars/*"
        }
    ]
}
```

Here is the code in my `Profile` model to initialize Paperclip:

``` ruby
has_mongoid_attached_file :avatar,
    :styles => { :square => ['50x50#', :jpg], :large => ['225x150#', :jpg] },
    :storage => :"#{Settings.paperclip.storage}",
    :hash_secret => "#{Settings.paperclip.app_secret}",
    :path => ":attachment/:style/:hash.:extension",
    :fog_credentials => {
      :aws_access_key_id => Settings.aws.s3_key,
      :aws_secret_access_key => Settings.aws.s3_secret,
      :provider => 'AWS'
    },
    :fog_directory => Settings.aws.s3_bucket,
    :processors => [:cropper]
```

If I go into S3, right click on my bucket folder and click `Make public`, I can access all the uploaded files publically. But if I upload a new file and try to access it via the S3 url, my browser gives me an AccessDenied XML document.

``` xml
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>4B8296F8F77491F5</RequestId>
<HostId>
CG96q+LGWcvsIK2YkuaE2wExL8/YTqH1PmjOSFGAqcgaKaTYnOet1QoItGJhW1Oj
</HostId>
</Error>
```

**Comment by TijenderSingh** [comment]
Make a public uploaded picture .
Woking fine .

**Comment by rathod4rathod** [comment]
$response = $this->s3->putObject(
                    [
                        'Bucket' => $bucketName,
                        'Key' => $keyname,
                        'SourceFile' => $tempFilePath,
                        'ContentType' => 'image/png',
                        'ACL' => 'public-read',
                        'StorageClass' => 'REDUCED_REDUNDANCY'
                    ]
            );



   'ACL' => 'public-read',

**Comment by JEET0291** [comment]
'ACL': 'public-read',

**Comment by Bob4F** [comment]
How fix，Bro

**Comment by Vernes4322** [comment]
'ACL' => 'public-read',
add this
