### ISSUE TITLE
can't add a new key into hash during iteration

### ISSUE THREAD

**Issue by pointblack** [thoughtbot/paperclip#985]
With Rails 3.1.7+ and master from the main paperclip repository =>
when trying to call the styles method on the attachment. It throws following exception:

RuntimeError: can't add a new key into hash during iteration
    gems/paperclip-70f0f1fea030/lib/paperclip/attachment.rb:171:in `[]='
    gems/paperclip-70f0f1fea030/lib/paperclip/attachment.rb:171:in`block in styles'
    gems/paperclip-70f0f1fea030/lib/paperclip/attachment.rb:170:in `each_pair'
    gems/paperclip-70f0f1fea030/lib/paperclip/attachment.rb:170:in`styles'

**Comment by voltechs** [comment]
Seems to be back. I'm on rails 4.2.4 and paperclip 4.3.1

**Comment by abepetrillo** [comment]
Can confirm I suffered from this on Rails 3.2 and paperclip 4.3.7. Somehow the `Attachment#path` method is causing it.
