### ISSUE TITLE
io_adapters.for(object.attachment).path failing randomly

### ISSUE THREAD

**Issue by brownjohnf** [thoughtbot/paperclip#986]
I've been using Paperclip for a while, but just recently updated to 3.1.4, and am now having problems creating zip archives. I've messed with all my code, checked the individual files, etc., and I think it's a Paperclip issue. I'm using s3 storage, with the `aws-sdk` gem, `:s3` settings, but have no problems with any other parts of the app but this one.

When iterating over a set of Documents which belong in a Library to grab their file attachments, I get seemingly random `Errno::ENOENT: No such file or directory` errors. They happen on different files each time I run the code, and happen in all environments. I'm running a simplified version of my app code in the console trying to sort this out. I had essentially the exact same piece of code in production for months with no problems on an old version of Paperclip.

```ruby
Library.order('id ASC').each do |lib|
  bundle_filename = "/tmp/#{lib.name.parameterize}-#{rand(100)}.zip"

  Zip::ZipFile.open(bundle_filename, Zip::ZipFile::CREATE) do |zipfile|
    lib.documents.each do |document|
      zipfile.add( document.canonical_title.parameterize, File.open(Paperclip.io_adapters.for(document.file).path) )
    end
  end

  lib.zip = File.open(bundle_filename)
  lib.save!

end
```
Thoughts? I hope this isn't just me being stupid. I've checked all the models and data involved, and it's all fine. Sometimes it'll get through 25+ libraries, sometimes 9, sometimes 2, but NEVER all of them.

**Comment by maclover7** [comment]
Hi @brownjohnf ! Is this still an issue for you in Paperclip; I know this issue is from approximately 3 years ago. If it is still an issue, can you please provide the code that's causing you the error? Thanks!

**Comment by brownjohnf** [comment]
Honestly, I'm not even sure! I'm pretty sure that code is long
out-of-production. Thanks for the follow-up, though.

Jack

-- 
Jack Brown
jack@brownjohnf.com

**Comment by maclover7** [comment]
@jferris @jyurek Please close issue, problem appears to be solved.

**Comment by tute** [comment]
Thank you for your help on this, @maclover7! :heart:
