### ISSUE TITLE
paperclip + fog doesn't pass through s3_headers 

### ISSUE THREAD

**Issue by cannikin** [thoughtbot/paperclip#987]
When using fog with paperclip it looks like any additional headers set through the `:s3_headers` option are *not* given to fog to send through. Am I missing a hidden `:fog_*` option maybe? Or was this omission on purpose? Thanks!

**Comment by JuanitoFatas** [comment]
Hi @cannikin, I think if you use fog as storage, you can pass extra headers via `fog_file`, e.g.:

```
fog_file: { 'Cache-Control' => 'max-age=1209600', 'Expires' => 14.days.from_now.httpdate }
```

:blush:

**Comment by maclover7** [comment]
Hi @cannikin ! Is this still an issue for you in Paperclip; I know this issue is from approximately 3 years ago. If it is still an issue, can you please provide the code that's causing you the error? Thanks!

**Comment by cannikin** [comment]
Oh geez, it's been years! I probably switched over to aws-sdk at the time. I don't even remember which project this was for, sorry! Feel free to close. :)

**Comment by maclover7** [comment]
@jferris @jyurek Close issue; issue appears to be resolved.

**Comment by tute** [comment]
Thanks for your help, @maclover7!
