### ISSUE TITLE
reprocess! doesn't update the DB after moving a file on S3

### ISSUE THREAD

**Issue by sidonath** [thoughtbot/paperclip#996]
We have been using Paperclip for a while now and we have files on our S3 with spaces in the names. It seems that in the recent versions this is not possible anymore since Paperclip replaces spaces with underscores.

However, we had a recent style change on a model and needed to reprocess the attachments. However, some originals started missing after the process!

After some exploration it seems that the missing attachments were not deleted, but renamed on S3 without updating the database.

Eg. we had `Image id:1337 attachment_file_name: 'Foo Bar.jpg'`. Reprocess moved the image from `1337/original/Foo Bar.jpg` to `1337/original/Foo_Bar.jpg`, but the actual model wasn't updated, so the image was still pointing to the old original which didn't exist anymore.

Looks like a workaround for now is to run reprocess and then manually update the records in the database.

**Comment by maclover7** [comment]
Hi @sidonath and @bjensen ! Is this still an issue for you in Paperclip; I know this issue is from approximately 3 years ago. If it is still an issue, can you please provide the code that's causing you the error? Thanks!

**Comment by bjensen** [comment]
Nope.not for me. Thanks for checking up :-)



Brian JensenNordplaner ApS

www.nordplaner.dk

+45 607 12000

**Comment by maclover7** [comment]
@jferris @jyurek Please close issue, problem appears to be solved.

**Comment by tute** [comment]
Thank you! :)
