### ISSUE TITLE
Paperclip interpolation bug

### ISSUE THREAD

**Issue by kshnurov** [thoughtbot/paperclip#998]
I have a model with interpolation:

    has_attached_file :img, :url => "/img/:parent_type/:parent_id/:id_partition/:fname.:extension"

    Paperclip.interpolates :fname do |attachment, style|
      Digest::MD5.hexdigest(attachment.instance.id.to_s+style.to_s)
    end

On development (Mac OS X) everything works great. On production (Debian + Passenger) I get the same :fname for all styles (probably style returns nil). How can I fix this?

P.S. Rails 3.2.8, Paperclip 3.1.4

**Comment by maclover7** [comment]
Hi @kshnurov! Is this still an issue for you in Paperclip; I know this issue is from approximately 3 years ago. If it is still an issue, can you please provide the code that's causing you the error? Thanks!

**Comment by kshnurov** [comment]
No, it's fine.
